import type { PuzzleRaw } from "../puzzleData";

/**
 * Batch 4 — 200 new puzzles (IDs p631–p830).
 *  • p631–p670: 40 easy
 *  • p671–p730: 60 medium
 *  • p731–p790: 60 hard
 *  • p791–p830: 40 expert
 */
export const BATCH4: PuzzleRaw[] = [
  // -------------------- EASY (40) --------------------
  {
    id: "p631",
    quote: "Bad news travels fast.",
    attribution: "Proverb",
    theme: "Communication",
    difficulty: "easy",
    clueWords: [
      { hint: "Of poor quality", word: "BAD" },
      { hint: "Reports of events", word: "NEWS" },
      { hint: "Moves, journeys", word: "TRAVELS" },
      { hint: "Quickly", word: "FAST" },
    ],
  },
  {
    id: "p632",
    quote: "A chain is only as strong as its weakest link.",
    attribution: "Proverb",
    theme: "Teamwork",
    difficulty: "easy",
    clueWords: [
      { hint: "Linked metal rings", word: "CHAIN" },
      { hint: "Solely", word: "ONLY" },
      { hint: "Powerful, firm", word: "STRONG" },
      { hint: "Most feeble", word: "WEAKEST" },
      { hint: "A connection", word: "LINK" },
    ],
  },
  {
    id: "p633",
    quote: "Two wrongs do not make a right.",
    attribution: "Proverb",
    theme: "Ethics",
    difficulty: "easy",
    clueWords: [
      { hint: "A pair", word: "TWO" },
      { hint: "Errors, harms", word: "WRONGS" },
      { hint: "Cause to be", word: "MAKE" },
      { hint: "Correct, just", word: "RIGHT" },
    ],
  },
  {
    id: "p634",
    quote: "A rolling stone gathers no moss.",
    attribution: "Proverb",
    theme: "Change",
    difficulty: "easy",
    clueWords: [
      { hint: "Turning over and over", word: "ROLLING" },
      { hint: "A piece of rock", word: "STONE" },
      { hint: "Collects, accumulates", word: "GATHERS" },
      { hint: "Green plant on rocks", word: "MOSS" },
    ],
  },
  {
    id: "p635",
    quote: "All work and no play makes Jack a dull boy.",
    attribution: "Proverb",
    theme: "Balance",
    difficulty: "easy",
    clueWords: [
      { hint: "Effort, labor", word: "WORK" },
      { hint: "Recreation, fun", word: "PLAY" },
      { hint: "Causes to be", word: "MAKES" },
      { hint: "Boring, lifeless", word: "DULL" },
      { hint: "A young male", word: "BOY" },
    ],
  },
  {
    id: "p636",
    quote: "Behind every great man is a great woman.",
    attribution: "Proverb",
    theme: "Partnership",
    difficulty: "easy",
    clueWords: [
      { hint: "In the rear of", word: "BEHIND" },
      { hint: "Each one", word: "EVERY" },
      { hint: "Outstanding", word: "GREAT" },
      { hint: "Adult human male", word: "MAN" },
      { hint: "Adult human female", word: "WOMAN" },
    ],
  },
  {
    id: "p637",
    quote: "Boys will be boys.",
    attribution: "Proverb",
    theme: "Acceptance",
    difficulty: "easy",
    clueWords: [
      { hint: "Young males", word: "BOYS" },
      { hint: "Future tense helper", word: "WILL" },
      { hint: "Exist as", word: "BE" },
    ],
  },
  {
    id: "p638",
    quote: "Distance lends enchantment to the view.",
    attribution: "Proverb",
    theme: "Perspective",
    difficulty: "easy",
    clueWords: [
      { hint: "Far apart in space", word: "DISTANCE" },
      { hint: "Gives, provides", word: "LENDS" },
      { hint: "Magical charm", word: "ENCHANTMENT" },
      { hint: "What you see", word: "VIEW" },
    ],
  },
  {
    id: "p639",
    quote: "Do not bite off more than you can chew.",
    attribution: "Proverb",
    theme: "Prudence",
    difficulty: "easy",
    clueWords: [
      { hint: "Use teeth on", word: "BITE" },
      { hint: "To a greater amount", word: "MORE" },
      { hint: "Are able to", word: "CAN" },
      { hint: "Grind with teeth", word: "CHEW" },
    ],
  },
  {
    id: "p640",
    quote: "Do not look a gift horse in the mouth.",
    attribution: "Proverb",
    theme: "Gratitude",
    difficulty: "easy",
    clueWords: [
      { hint: "Use the eyes", word: "LOOK" },
      { hint: "A present", word: "GIFT" },
      { hint: "A riding animal", word: "HORSE" },
      { hint: "Speaking opening", word: "MOUTH" },
    ],
  },
  {
    id: "p641",
    quote: "Do not put off until tomorrow what you can do today.",
    attribution: "Benjamin Franklin",
    theme: "Initiative",
    difficulty: "easy",
    clueWords: [
      { hint: "Delay, postpone", word: "PUT" },
      { hint: "Up to that point", word: "UNTIL" },
      { hint: "The day after today", word: "TOMORROW" },
      { hint: "Are able to", word: "CAN" },
      { hint: "Perform", word: "DO" },
      { hint: "The current day", word: "TODAY" },
    ],
  },
  {
    id: "p642",
    quote: "Do not put the cart before the horse.",
    attribution: "Proverb",
    theme: "Order",
    difficulty: "easy",
    clueWords: [
      { hint: "Place, set", word: "PUT" },
      { hint: "Wheeled wagon", word: "CART" },
      { hint: "Earlier than", word: "BEFORE" },
      { hint: "A pulling animal", word: "HORSE" },
    ],
  },
  {
    id: "p643",
    quote: "Early to bed, early to rise.",
    attribution: "Benjamin Franklin",
    theme: "Discipline",
    difficulty: "easy",
    clueWords: [
      { hint: "Before usual hour", word: "EARLY" },
      { hint: "Place to sleep", word: "BED" },
      { hint: "Get up", word: "RISE" },
    ],
  },
  {
    id: "p644",
    quote: "Forewarned is forearmed.",
    attribution: "Proverb",
    theme: "Preparation",
    difficulty: "easy",
    clueWords: [
      { hint: "Warned in advance", word: "FOREWARNED" },
      { hint: "Prepared in advance", word: "FOREARMED" },
    ],
  },
  {
    id: "p645",
    quote: "Forgive and forget.",
    attribution: "Proverb",
    theme: "Forgiveness",
    difficulty: "easy",
    clueWords: [
      { hint: "Pardon", word: "FORGIVE" },
      { hint: "Lose memory of", word: "FORGET" },
    ],
  },
  {
    id: "p646",
    quote: "Fortune knocks but once.",
    attribution: "Proverb",
    theme: "Opportunity",
    difficulty: "easy",
    clueWords: [
      { hint: "Luck, prosperity", word: "FORTUNE" },
      { hint: "Raps on a door", word: "KNOCKS" },
      { hint: "A single occasion", word: "ONCE" },
    ],
  },
  {
    id: "p647",
    quote: "Half a loaf is better than none.",
    attribution: "Proverb",
    theme: "Pragmatism",
    difficulty: "easy",
    clueWords: [
      { hint: "Fifty percent", word: "HALF" },
      { hint: "A baked bread piece", word: "LOAF" },
      { hint: "Preferable", word: "BETTER" },
      { hint: "Not any", word: "NONE" },
    ],
  },
  {
    id: "p648",
    quote: "Haste is the enemy of perfection.",
    attribution: "Proverb",
    theme: "Patience",
    difficulty: "easy",
    clueWords: [
      { hint: "Rushing", word: "HASTE" },
      { hint: "An adversary", word: "ENEMY" },
      { hint: "Without flaw", word: "PERFECTION" },
    ],
  },
  {
    id: "p649",
    quote: "He laughs best who laughs last.",
    attribution: "Proverb",
    theme: "Patience",
    difficulty: "easy",
    clueWords: [
      { hint: "Expresses amusement", word: "LAUGHS" },
      { hint: "Most well", word: "BEST" },
      { hint: "Final, ultimate", word: "LAST" },
    ],
  },
  {
    id: "p650",
    quote: "Hindsight is twenty-twenty.",
    attribution: "Proverb",
    theme: "Reflection",
    difficulty: "easy",
    clueWords: [
      { hint: "Looking back at past", word: "HINDSIGHT" },
      { hint: "Two times ten", word: "TWENTY" },
    ],
  },
  {
    id: "p651",
    quote: "If wishes were horses, beggars would ride.",
    attribution: "Proverb",
    theme: "Pragmatism",
    difficulty: "easy",
    clueWords: [
      { hint: "Hopes, desires", word: "WISHES" },
      { hint: "Riding animals", word: "HORSES" },
      { hint: "Those asking for help", word: "BEGGARS" },
      { hint: "Travel atop", word: "RIDE" },
    ],
  },
  {
    id: "p652",
    quote: "It takes a village to raise a child.",
    attribution: "African Proverb",
    theme: "Community",
    difficulty: "easy",
    clueWords: [
      { hint: "Requires", word: "TAKES" },
      { hint: "A small community", word: "VILLAGE" },
      { hint: "Bring up, rear", word: "RAISE" },
      { hint: "A young person", word: "CHILD" },
    ],
  },
  {
    id: "p653",
    quote: "Lend a hand to those in need.",
    attribution: "Proverb",
    theme: "Service",
    difficulty: "easy",
    clueWords: [
      { hint: "Offer, give temporarily", word: "LEND" },
      { hint: "Body part with fingers", word: "HAND" },
      { hint: "Particular ones", word: "THOSE" },
      { hint: "Requirement, want", word: "NEED" },
    ],
  },
  {
    id: "p654",
    quote: "Let bygones be bygones.",
    attribution: "Proverb",
    theme: "Forgiveness",
    difficulty: "easy",
    clueWords: [
      { hint: "Allow", word: "LET" },
      { hint: "Past matters", word: "BYGONES" },
      { hint: "Exist as", word: "BE" },
    ],
  },
  {
    id: "p655",
    quote: "Like father, like son.",
    attribution: "Proverb",
    theme: "Family",
    difficulty: "easy",
    clueWords: [
      { hint: "Similar to", word: "LIKE" },
      { hint: "Male parent", word: "FATHER" },
      { hint: "Male child", word: "SON" },
    ],
  },
  {
    id: "p656",
    quote: "Look on the bright side.",
    attribution: "Proverb",
    theme: "Optimism",
    difficulty: "easy",
    clueWords: [
      { hint: "Use the eyes", word: "LOOK" },
      { hint: "Cheerful, sunny", word: "BRIGHT" },
      { hint: "An edge or face", word: "SIDE" },
    ],
  },
  {
    id: "p657",
    quote: "Mind over matter.",
    attribution: "Proverb",
    theme: "Mindset",
    difficulty: "easy",
    clueWords: [
      { hint: "Thinking faculty", word: "MIND" },
      { hint: "Above, prevailing", word: "OVER" },
      { hint: "Physical substance", word: "MATTER" },
    ],
  },
  {
    id: "p658",
    quote: "More haste, less speed.",
    attribution: "Proverb",
    theme: "Patience",
    difficulty: "easy",
    clueWords: [
      { hint: "To a greater extent", word: "MORE" },
      { hint: "Hurried action", word: "HASTE" },
      { hint: "To a smaller extent", word: "LESS" },
      { hint: "Velocity, pace", word: "SPEED" },
    ],
  },
  {
    id: "p659",
    quote: "Music has charms to soothe the savage breast.",
    attribution: "William Congreve",
    theme: "Joy",
    difficulty: "easy",
    clueWords: [
      { hint: "Organized sound", word: "MUSIC" },
      { hint: "Possesses", word: "HAS" },
      { hint: "Magical appeal", word: "CHARMS" },
      { hint: "Calm, ease", word: "SOOTHE" },
      { hint: "Wild, untamed", word: "SAVAGE" },
    ],
  },
  {
    id: "p660",
    quote: "Never trouble trouble until trouble troubles you.",
    attribution: "Proverb",
    theme: "Mindfulness",
    difficulty: "easy",
    clueWords: [
      { hint: "At no time", word: "NEVER" },
      { hint: "Difficulty, distress", word: "TROUBLE" },
      { hint: "Up to that point", word: "UNTIL" },
      { hint: "Bothers you", word: "TROUBLES" },
    ],
  },
  {
    id: "p661",
    quote: "No news is good news.",
    attribution: "Proverb",
    theme: "Optimism",
    difficulty: "easy",
    clueWords: [
      { hint: "Negation", word: "NO" },
      { hint: "Reports of events", word: "NEWS" },
      { hint: "Worthy, fine", word: "GOOD" },
    ],
  },
  {
    id: "p662",
    quote: "Nothing succeeds like success.",
    attribution: "Proverb",
    theme: "Momentum",
    difficulty: "easy",
    clueWords: [
      { hint: "Not anything", word: "NOTHING" },
      { hint: "Achieves a goal", word: "SUCCEEDS" },
      { hint: "Similar to", word: "LIKE" },
      { hint: "Achievement", word: "SUCCESS" },
    ],
  },
  {
    id: "p663",
    quote: "Patience pays off in the end.",
    attribution: "Proverb",
    theme: "Patience",
    difficulty: "easy",
    clueWords: [
      { hint: "Calm endurance", word: "PATIENCE" },
      { hint: "Provides reward", word: "PAYS" },
      { hint: "Final point", word: "END" },
    ],
  },
  {
    id: "p664",
    quote: "Save for a rainy day.",
    attribution: "Proverb",
    theme: "Thrift",
    difficulty: "easy",
    clueWords: [
      { hint: "Set aside, conserve", word: "SAVE" },
      { hint: "Wet weather", word: "RAINY" },
      { hint: "A 24-hour period", word: "DAY" },
    ],
  },
  {
    id: "p665",
    quote: "Slow but sure wins the race.",
    attribution: "Proverb",
    theme: "Persistence",
    difficulty: "easy",
    clueWords: [
      { hint: "Not fast", word: "SLOW" },
      { hint: "Certain, confident", word: "SURE" },
      { hint: "Comes first", word: "WINS" },
      { hint: "A speed contest", word: "RACE" },
    ],
  },
  {
    id: "p666",
    quote: "Still waters run deep.",
    attribution: "Proverb",
    theme: "Wisdom",
    difficulty: "easy",
    clueWords: [
      { hint: "Calm, motionless", word: "STILL" },
      { hint: "Bodies of liquid", word: "WATERS" },
      { hint: "Move quickly", word: "RUN" },
      { hint: "Far below the surface", word: "DEEP" },
    ],
  },
  {
    id: "p667",
    quote: "Take it with a grain of salt.",
    attribution: "Proverb",
    theme: "Skepticism",
    difficulty: "easy",
    clueWords: [
      { hint: "Receive, accept", word: "TAKE" },
      { hint: "A small particle", word: "GRAIN" },
      { hint: "Common seasoning", word: "SALT" },
    ],
  },
  {
    id: "p668",
    quote: "The proof is in the pudding.",
    attribution: "Proverb",
    theme: "Evidence",
    difficulty: "easy",
    clueWords: [
      { hint: "Evidence", word: "PROOF" },
      { hint: "Soft sweet dish", word: "PUDDING" },
    ],
  },
  {
    id: "p669",
    quote: "The squeaky wheel gets the grease.",
    attribution: "Proverb",
    theme: "Initiative",
    difficulty: "easy",
    clueWords: [
      { hint: "Making high-pitched noise", word: "SQUEAKY" },
      { hint: "Round rolling part", word: "WHEEL" },
      { hint: "Receives", word: "GETS" },
      { hint: "Lubricating fat", word: "GREASE" },
    ],
  },
  {
    id: "p670",
    quote: "Two is company, three is a crowd.",
    attribution: "Proverb",
    theme: "Friendship",
    difficulty: "easy",
    clueWords: [
      { hint: "A pair", word: "TWO" },
      { hint: "Companionship", word: "COMPANY" },
      { hint: "A trio", word: "THREE" },
      { hint: "A large group", word: "CROWD" },
    ],
  },

  // -------------------- MEDIUM (60) --------------------
  {
    id: "p671",
    quote: "An obstacle is often a stepping stone.",
    attribution: "William Prescott",
    theme: "Adversity",
    difficulty: "medium",
    clueWords: [
      { hint: "A barrier", word: "OBSTACLE" },
      { hint: "Many times", word: "OFTEN" },
      { hint: "Used to step on", word: "STEPPING" },
      { hint: "A piece of rock", word: "STONE" },
    ],
  },
  {
    id: "p672",
    quote: "Never let the future disturb you.",
    attribution: "Marcus Aurelius",
    theme: "Mindfulness",
    difficulty: "medium",
    clueWords: [
      { hint: "At no time", word: "NEVER" },
      { hint: "Allow", word: "LET" },
      { hint: "Time yet to come", word: "FUTURE" },
      { hint: "Trouble, agitate", word: "DISTURB" },
    ],
  },
  {
    id: "p673",
    quote: "Look within. Within is the fountain of good.",
    attribution: "Marcus Aurelius",
    theme: "Self-Knowledge",
    difficulty: "medium",
    clueWords: [
      { hint: "Use the eyes", word: "LOOK" },
      { hint: "Inside", word: "WITHIN" },
      { hint: "A flowing source", word: "FOUNTAIN" },
      { hint: "Worthy, fine", word: "GOOD" },
    ],
  },
  {
    id: "p674",
    quote: "The best revenge is not to be like that which has wronged you.",
    attribution: "Marcus Aurelius",
    theme: "Forgiveness",
    difficulty: "medium",
    clueWords: [
      { hint: "Top quality", word: "BEST" },
      { hint: "Retaliation", word: "REVENGE" },
      { hint: "Similar to", word: "LIKE" },
      { hint: "Treated unfairly", word: "WRONGED" },
    ],
  },
  {
    id: "p675",
    quote: "Dwell on the beauty of life. Watch the stars and see yourself running with them.",
    attribution: "Marcus Aurelius",
    theme: "Wonder",
    difficulty: "medium",
    clueWords: [
      { hint: "Linger upon", word: "DWELL" },
      { hint: "Loveliness", word: "BEAUTY" },
      { hint: "Existence", word: "LIFE" },
      { hint: "Observe", word: "WATCH" },
      { hint: "Celestial bodies", word: "STARS" },
      { hint: "Moving quickly on foot", word: "RUNNING" },
    ],
  },
  {
    id: "p676",
    quote: "If anyone can show me that I am making a mistake, I will gladly change.",
    attribution: "Marcus Aurelius",
    theme: "Open Mind",
    difficulty: "medium",
    clueWords: [
      { hint: "Any individual", word: "ANYONE" },
      { hint: "Display, demonstrate", word: "SHOW" },
      { hint: "Causing, doing", word: "MAKING" },
      { hint: "An error", word: "MISTAKE" },
      { hint: "Happily", word: "GLADLY" },
      { hint: "Alter, modify", word: "CHANGE" },
    ],
  },
  {
    id: "p677",
    quote: "He who lives in harmony with himself lives in harmony with the universe.",
    attribution: "Marcus Aurelius",
    theme: "Inner Peace",
    difficulty: "medium",
    clueWords: [
      { hint: "Is alive", word: "LIVES" },
      { hint: "Pleasant agreement", word: "HARMONY" },
      { hint: "He himself", word: "HIMSELF" },
      { hint: "All of existence", word: "UNIVERSE" },
    ],
  },
  {
    id: "p678",
    quote: "The first rule is to keep an untroubled spirit. The second is to look things in the face.",
    attribution: "Marcus Aurelius",
    theme: "Stoicism",
    difficulty: "medium",
    clueWords: [
      { hint: "Initial", word: "FIRST" },
      { hint: "A guideline", word: "RULE" },
      { hint: "Maintain", word: "KEEP" },
      { hint: "Inner essence", word: "SPIRIT" },
      { hint: "Number after first", word: "SECOND" },
      { hint: "Front of the head", word: "FACE" },
    ],
  },
  {
    id: "p679",
    quote: "Receive without conceit, release without struggle.",
    attribution: "Marcus Aurelius",
    theme: "Acceptance",
    difficulty: "medium",
    clueWords: [
      { hint: "Take, accept", word: "RECEIVE" },
      { hint: "Without", word: "WITHOUT" },
      { hint: "Excessive pride", word: "CONCEIT" },
      { hint: "Let go of", word: "RELEASE" },
      { hint: "Hard fight", word: "STRUGGLE" },
    ],
  },
  {
    id: "p680",
    quote: "It is not events that disturb us, but our judgments concerning them.",
    attribution: "Epictetus",
    theme: "Mindset",
    difficulty: "medium",
    clueWords: [
      { hint: "Occurrences", word: "EVENTS" },
      { hint: "Trouble, agitate", word: "DISTURB" },
      { hint: "Belonging to us", word: "OUR" },
      { hint: "Opinions, assessments", word: "JUDGMENTS" },
      { hint: "About, regarding", word: "CONCERNING" },
    ],
  },
  {
    id: "p681",
    quote: "Make the best use of what is in your power and take the rest as it happens.",
    attribution: "Epictetus",
    theme: "Acceptance",
    difficulty: "medium",
    clueWords: [
      { hint: "Top quality", word: "BEST" },
      { hint: "Apply, employ", word: "USE" },
      { hint: "Authority, ability", word: "POWER" },
      { hint: "Remaining portion", word: "REST" },
      { hint: "Take place", word: "HAPPENS" },
    ],
  },
  {
    id: "p682",
    quote: "Do not seek to have events happen as you wish, but wish them to happen as they do.",
    attribution: "Epictetus",
    theme: "Acceptance",
    difficulty: "medium",
    clueWords: [
      { hint: "Search for", word: "SEEK" },
      { hint: "Occurrences", word: "EVENTS" },
      { hint: "Take place", word: "HAPPEN" },
      { hint: "Desire, hope", word: "WISH" },
    ],
  },
  {
    id: "p683",
    quote: "He is a wise man who does not grieve for the things he has not.",
    attribution: "Epictetus",
    theme: "Contentment",
    difficulty: "medium",
    clueWords: [
      { hint: "Sage, learned", word: "WISE" },
      { hint: "Adult human male", word: "MAN" },
      { hint: "Mourn deeply", word: "GRIEVE" },
      { hint: "Items, matters", word: "THINGS" },
      { hint: "Possesses", word: "HAS" },
    ],
  },
  {
    id: "p684",
    quote: "If you wish to be a writer, write.",
    attribution: "Epictetus",
    theme: "Action",
    difficulty: "medium",
    clueWords: [
      { hint: "Desire", word: "WISH" },
      { hint: "One who composes text", word: "WRITER" },
      { hint: "Compose text", word: "WRITE" },
    ],
  },
  {
    id: "p685",
    quote: "First learn the meaning of what you say, and then speak.",
    attribution: "Epictetus",
    theme: "Wisdom",
    difficulty: "medium",
    clueWords: [
      { hint: "Initially", word: "FIRST" },
      { hint: "Acquire knowledge", word: "LEARN" },
      { hint: "Significance", word: "MEANING" },
      { hint: "Express verbally", word: "SAY" },
      { hint: "Utter aloud", word: "SPEAK" },
    ],
  },
  {
    id: "p686",
    quote: "Only the educated are free.",
    attribution: "Epictetus",
    theme: "Liberty",
    difficulty: "medium",
    clueWords: [
      { hint: "Sole, single", word: "ONLY" },
      { hint: "Schooled, taught", word: "EDUCATED" },
      { hint: "Not bound", word: "FREE" },
    ],
  },
  {
    id: "p687",
    quote: "Wherever you go, there you are.",
    attribution: "Jon Kabat-Zinn",
    theme: "Mindfulness",
    difficulty: "medium",
    clueWords: [
      { hint: "In any place that", word: "WHEREVER" },
      { hint: "Travel", word: "GO" },
      { hint: "At that place", word: "THERE" },
    ],
  },
  {
    id: "p688",
    quote: "Empty your mind. Be formless, shapeless, like water.",
    attribution: "Bruce Lee",
    theme: "Adaptability",
    difficulty: "medium",
    clueWords: [
      { hint: "Containing nothing", word: "EMPTY" },
      { hint: "Thinking faculty", word: "MIND" },
      { hint: "Without form", word: "FORMLESS" },
      { hint: "Without shape", word: "SHAPELESS" },
      { hint: "The clear liquid", word: "WATER" },
    ],
  },
  {
    id: "p689",
    quote: "If you spend too much time thinking about a thing, you will never get it done.",
    attribution: "Bruce Lee",
    theme: "Action",
    difficulty: "medium",
    clueWords: [
      { hint: "Use up time", word: "SPEND" },
      { hint: "Excessively", word: "TOO" },
      { hint: "A great amount", word: "MUCH" },
      { hint: "Pondering", word: "THINKING" },
      { hint: "An item or matter", word: "THING" },
      { hint: "Completed", word: "DONE" },
    ],
  },
  {
    id: "p690",
    quote: "I fear not the man who has practiced ten thousand kicks once, but ten thousand times.",
    attribution: "Bruce Lee",
    theme: "Mastery",
    difficulty: "medium",
    clueWords: [
      { hint: "Be afraid of", word: "FEAR" },
      { hint: "Adult human male", word: "MAN" },
      { hint: "Repeated training", word: "PRACTICED" },
      { hint: "Striking with foot", word: "KICKS" },
      { hint: "A single occasion", word: "ONCE" },
      { hint: "Ten times one thousand", word: "THOUSAND" },
    ],
  },
  {
    id: "p691",
    quote: "Showing off is the fool's idea of glory.",
    attribution: "Bruce Lee",
    theme: "Humility",
    difficulty: "medium",
    clueWords: [
      { hint: "Boasting display", word: "SHOWING" },
      { hint: "Foolish person", word: "FOOL" },
      { hint: "A concept", word: "IDEA" },
      { hint: "Honor, fame", word: "GLORY" },
    ],
  },
  {
    id: "p692",
    quote: "Mistakes are always forgivable, if one has the courage to admit them.",
    attribution: "Bruce Lee",
    theme: "Honesty",
    difficulty: "medium",
    clueWords: [
      { hint: "Errors", word: "MISTAKES" },
      { hint: "All the time", word: "ALWAYS" },
      { hint: "Able to be pardoned", word: "FORGIVABLE" },
      { hint: "Bravery", word: "COURAGE" },
      { hint: "Confess, acknowledge", word: "ADMIT" },
    ],
  },
  {
    id: "p693",
    quote: "Be water, my friend.",
    attribution: "Bruce Lee",
    theme: "Adaptability",
    difficulty: "medium",
    clueWords: [
      { hint: "The clear liquid", word: "WATER" },
      { hint: "A close companion", word: "FRIEND" },
      { hint: "Belonging to me", word: "MY" },
    ],
  },
  {
    id: "p694",
    quote: "Walk as if you are kissing the earth with your feet.",
    attribution: "Thich Nhat Hanh",
    theme: "Mindfulness",
    difficulty: "medium",
    clueWords: [
      { hint: "Move on foot", word: "WALK" },
      { hint: "Touching with lips", word: "KISSING" },
      { hint: "Our planet", word: "EARTH" },
      { hint: "Lower limb ends", word: "FEET" },
    ],
  },
  {
    id: "p695",
    quote: "The present moment is filled with joy. If you are attentive, you will see it.",
    attribution: "Thich Nhat Hanh",
    theme: "Mindfulness",
    difficulty: "medium",
    clueWords: [
      { hint: "Current time", word: "PRESENT" },
      { hint: "An instant", word: "MOMENT" },
      { hint: "Made full", word: "FILLED" },
      { hint: "Happiness", word: "JOY" },
      { hint: "Paying attention", word: "ATTENTIVE" },
      { hint: "Perceive with eyes", word: "SEE" },
    ],
  },
  {
    id: "p696",
    quote: "There is no way to happiness; happiness is the way.",
    attribution: "Thich Nhat Hanh",
    theme: "Joy",
    difficulty: "medium",
    clueWords: [
      { hint: "A path", word: "WAY" },
      { hint: "Joyful state", word: "HAPPINESS" },
      { hint: "Negation", word: "NO" },
    ],
  },
  {
    id: "p697",
    quote: "Sometimes your smile can be the source of your joy.",
    attribution: "Thich Nhat Hanh",
    theme: "Joy",
    difficulty: "medium",
    clueWords: [
      { hint: "On occasion", word: "SOMETIMES" },
      { hint: "Pleasant facial expression", word: "SMILE" },
      { hint: "An origin", word: "SOURCE" },
      { hint: "Happiness", word: "JOY" },
    ],
  },
  {
    id: "p698",
    quote: "Drink your tea slowly and reverently.",
    attribution: "Thich Nhat Hanh",
    theme: "Mindfulness",
    difficulty: "medium",
    clueWords: [
      { hint: "Consume liquid", word: "DRINK" },
      { hint: "Hot beverage", word: "TEA" },
      { hint: "Without haste", word: "SLOWLY" },
      { hint: "With respect", word: "REVERENTLY" },
    ],
  },
  {
    id: "p699",
    quote: "Around us, life bursts with miracles.",
    attribution: "Thich Nhat Hanh",
    theme: "Wonder",
    difficulty: "medium",
    clueWords: [
      { hint: "Surrounding", word: "AROUND" },
      { hint: "Existence", word: "LIFE" },
      { hint: "Erupts forth", word: "BURSTS" },
      { hint: "Wondrous occurrences", word: "MIRACLES" },
    ],
  },
  {
    id: "p700",
    quote: "Hope is important because it can make the present moment less difficult to bear.",
    attribution: "Thich Nhat Hanh",
    theme: "Hope",
    difficulty: "medium",
    clueWords: [
      { hint: "Optimistic feeling", word: "HOPE" },
      { hint: "Significant", word: "IMPORTANT" },
      { hint: "Cause to be", word: "MAKE" },
      { hint: "Current time", word: "PRESENT" },
      { hint: "An instant", word: "MOMENT" },
      { hint: "Endure, carry", word: "BEAR" },
    ],
  },
  {
    id: "p701",
    quote: "When you love someone, the best thing you can offer is your presence.",
    attribution: "Thich Nhat Hanh",
    theme: "Love",
    difficulty: "medium",
    clueWords: [
      { hint: "Cherish deeply", word: "LOVE" },
      { hint: "An individual", word: "SOMEONE" },
      { hint: "Top quality", word: "BEST" },
      { hint: "Give, present", word: "OFFER" },
      { hint: "Being there", word: "PRESENCE" },
    ],
  },
  {
    id: "p702",
    quote: "Many people are alive but do not touch the miracle of being alive.",
    attribution: "Thich Nhat Hanh",
    theme: "Mindfulness",
    difficulty: "medium",
    clueWords: [
      { hint: "A great number", word: "MANY" },
      { hint: "Human beings", word: "PEOPLE" },
      { hint: "Living", word: "ALIVE" },
      { hint: "Make contact with", word: "TOUCH" },
      { hint: "A wondrous event", word: "MIRACLE" },
    ],
  },
  {
    id: "p703",
    quote: "You yourself deserve your love and affection as much as anybody.",
    attribution: "Buddha",
    theme: "Self-Love",
    difficulty: "medium",
    clueWords: [
      { hint: "Your own person", word: "YOURSELF" },
      { hint: "Are worthy of", word: "DESERVE" },
      { hint: "Deep affection", word: "LOVE" },
      { hint: "Fondness, care", word: "AFFECTION" },
      { hint: "Any person", word: "ANYBODY" },
    ],
  },
  {
    id: "p704",
    quote: "Holding on to anger is like grasping a hot coal.",
    attribution: "Buddha",
    theme: "Forgiveness",
    difficulty: "medium",
    clueWords: [
      { hint: "Keeping a grip", word: "HOLDING" },
      { hint: "Strong displeasure", word: "ANGER" },
      { hint: "Seizing firmly", word: "GRASPING" },
      { hint: "High temperature", word: "HOT" },
      { hint: "Burning ember", word: "COAL" },
    ],
  },
  {
    id: "p705",
    quote: "Do not dwell in the past, do not dream of the future, concentrate on the present.",
    attribution: "Buddha",
    theme: "Mindfulness",
    difficulty: "medium",
    clueWords: [
      { hint: "Linger upon", word: "DWELL" },
      { hint: "Earlier time", word: "PAST" },
      { hint: "Imagine, hope for", word: "DREAM" },
      { hint: "Time yet to come", word: "FUTURE" },
      { hint: "Focus closely", word: "CONCENTRATE" },
      { hint: "Current time", word: "PRESENT" },
    ],
  },
  {
    id: "p706",
    quote: "When you realize how perfect everything is, you will tilt your head back and laugh at the sky.",
    attribution: "Buddha",
    theme: "Wonder",
    difficulty: "medium",
    clueWords: [
      { hint: "Become aware", word: "REALIZE" },
      { hint: "Without flaw", word: "PERFECT" },
      { hint: "All things", word: "EVERYTHING" },
      { hint: "Tip or angle", word: "TILT" },
      { hint: "Express joyfully", word: "LAUGH" },
      { hint: "The heavens above", word: "SKY" },
    ],
  },
  {
    id: "p707",
    quote: "It is better to travel well than to arrive.",
    attribution: "Buddha",
    theme: "Mindfulness",
    difficulty: "medium",
    clueWords: [
      { hint: "Preferable", word: "BETTER" },
      { hint: "Journey", word: "TRAVEL" },
      { hint: "Properly, finely", word: "WELL" },
      { hint: "Reach a destination", word: "ARRIVE" },
    ],
  },
  {
    id: "p708",
    quote: "An idea put into action is more important than an idea that exists only as an idea.",
    attribution: "Buddha",
    theme: "Action",
    difficulty: "medium",
    clueWords: [
      { hint: "A thought, concept", word: "IDEA" },
      { hint: "A deed", word: "ACTION" },
      { hint: "Significant", word: "IMPORTANT" },
      { hint: "Be present", word: "EXISTS" },
      { hint: "Solely", word: "ONLY" },
      { hint: "To a greater degree", word: "MORE" },
    ],
  },
  {
    id: "p709",
    quote: "Be where your feet are.",
    attribution: "Anonymous",
    theme: "Mindfulness",
    difficulty: "medium",
    clueWords: [
      { hint: "Exist", word: "BE" },
      { hint: "At which place", word: "WHERE" },
      { hint: "Lower limb ends", word: "FEET" },
      { hint: "Belonging to you", word: "YOUR" },
    ],
  },
  {
    id: "p710",
    quote: "Throw kindness around like confetti.",
    attribution: "Anonymous",
    theme: "Kindness",
    difficulty: "medium",
    clueWords: [
      { hint: "Cast forth", word: "THROW" },
      { hint: "Considerate behavior", word: "KINDNESS" },
      { hint: "Surrounding", word: "AROUND" },
      { hint: "Similar to", word: "LIKE" },
      { hint: "Tiny celebration paper", word: "CONFETTI" },
    ],
  },
  {
    id: "p711",
    quote: "We acquire the strength we have overcome.",
    attribution: "Ralph Waldo Emerson",
    theme: "Resilience",
    difficulty: "medium",
    clueWords: [
      { hint: "Obtain", word: "ACQUIRE" },
      { hint: "Power, fortitude", word: "STRENGTH" },
      { hint: "Conquered, beaten", word: "OVERCOME" },
      { hint: "Possess", word: "HAVE" },
    ],
  },
  {
    id: "p712",
    quote: "Do not be too timid and squeamish about your actions. All life is an experiment.",
    attribution: "Ralph Waldo Emerson",
    theme: "Adventure",
    difficulty: "medium",
    clueWords: [
      { hint: "Excessively", word: "TOO" },
      { hint: "Shy, fearful", word: "TIMID" },
      { hint: "Easily disgusted", word: "SQUEAMISH" },
      { hint: "Deeds", word: "ACTIONS" },
      { hint: "Existence", word: "LIFE" },
      { hint: "A test, trial", word: "EXPERIMENT" },
    ],
  },
  {
    id: "p713",
    quote: "Self-trust is the first secret of success.",
    attribution: "Ralph Waldo Emerson",
    theme: "Confidence",
    difficulty: "medium",
    clueWords: [
      { hint: "Belief in oneself", word: "TRUST" },
      { hint: "Initial", word: "FIRST" },
      { hint: "Hidden knowledge", word: "SECRET" },
      { hint: "Achievement", word: "SUCCESS" },
    ],
  },
  {
    id: "p714",
    quote: "Adopt the pace of nature: her secret is patience.",
    attribution: "Ralph Waldo Emerson",
    theme: "Patience",
    difficulty: "medium",
    clueWords: [
      { hint: "Take on, embrace", word: "ADOPT" },
      { hint: "Speed, rate", word: "PACE" },
      { hint: "The natural world", word: "NATURE" },
      { hint: "Hidden truth", word: "SECRET" },
      { hint: "Calm endurance", word: "PATIENCE" },
    ],
  },
  {
    id: "p715",
    quote: "The first wealth is health.",
    attribution: "Ralph Waldo Emerson",
    theme: "Health",
    difficulty: "medium",
    clueWords: [
      { hint: "Initial", word: "FIRST" },
      { hint: "Riches", word: "WEALTH" },
      { hint: "Physical well-being", word: "HEALTH" },
    ],
  },
  {
    id: "p716",
    quote: "Finish each day and be done with it. You have done what you could.",
    attribution: "Ralph Waldo Emerson",
    theme: "Acceptance",
    difficulty: "medium",
    clueWords: [
      { hint: "Complete", word: "FINISH" },
      { hint: "Every", word: "EACH" },
      { hint: "A 24-hour period", word: "DAY" },
      { hint: "Completed", word: "DONE" },
      { hint: "Were able to", word: "COULD" },
    ],
  },
  {
    id: "p717",
    quote: "We must be our own before we can be another's.",
    attribution: "Ralph Waldo Emerson",
    theme: "Self-Knowledge",
    difficulty: "medium",
    clueWords: [
      { hint: "Belonging to us", word: "OUR" },
      { hint: "Belonging to oneself", word: "OWN" },
      { hint: "Earlier than", word: "BEFORE" },
      { hint: "Are able to", word: "CAN" },
      { hint: "A different person", word: "ANOTHER" },
    ],
  },
  {
    id: "p718",
    quote: "Make the most of yourself by fanning the inner sparks of possibility.",
    attribution: "Ralph Waldo Emerson",
    theme: "Potential",
    difficulty: "medium",
    clueWords: [
      { hint: "The greatest amount", word: "MOST" },
      { hint: "Your own person", word: "YOURSELF" },
      { hint: "Stirring up flames", word: "FANNING" },
      { hint: "Tiny burning particles", word: "SPARKS" },
      { hint: "Capability", word: "POSSIBILITY" },
      { hint: "Internal", word: "INNER" },
    ],
  },
  {
    id: "p719",
    quote: "Lives of great people remind us we can make our lives sublime.",
    attribution: "Henry Wadsworth Longfellow",
    theme: "Legacy",
    difficulty: "medium",
    clueWords: [
      { hint: "Existences", word: "LIVES" },
      { hint: "Outstanding", word: "GREAT" },
      { hint: "Human beings", word: "PEOPLE" },
      { hint: "Cause to recall", word: "REMIND" },
      { hint: "Are able to", word: "CAN" },
      { hint: "Lofty, exalted", word: "SUBLIME" },
    ],
  },
  {
    id: "p720",
    quote: "Pretty much all the honest truth-telling there is in the world is done by children.",
    attribution: "Oliver Wendell Holmes",
    theme: "Honesty",
    difficulty: "medium",
    clueWords: [
      { hint: "Truthful", word: "HONEST" },
      { hint: "Honest reality", word: "TRUTH" },
      { hint: "Stating, narrating", word: "TELLING" },
      { hint: "The earth", word: "WORLD" },
      { hint: "Performed", word: "DONE" },
      { hint: "Young people", word: "CHILDREN" },
    ],
  },
  {
    id: "p721",
    quote: "Many of life's failures are people who did not realize how close they were to success.",
    attribution: "Thomas Edison",
    theme: "Persistence",
    difficulty: "medium",
    clueWords: [
      { hint: "A great number", word: "MANY" },
      { hint: "Existence", word: "LIFE" },
      { hint: "Lack of success", word: "FAILURES" },
      { hint: "Human beings", word: "PEOPLE" },
      { hint: "Become aware of", word: "REALIZE" },
      { hint: "Achievement", word: "SUCCESS" },
    ],
  },
  {
    id: "p722",
    quote: "Sometimes you face difficulties because you are doing something right.",
    attribution: "Joel Osteen",
    theme: "Adversity",
    difficulty: "medium",
    clueWords: [
      { hint: "On occasion", word: "SOMETIMES" },
      { hint: "Confront", word: "FACE" },
      { hint: "Hardships", word: "DIFFICULTIES" },
      { hint: "Performing", word: "DOING" },
      { hint: "An item", word: "SOMETHING" },
      { hint: "Correct", word: "RIGHT" },
    ],
  },
  {
    id: "p723",
    quote: "When there is no enemy within, the enemies outside cannot hurt you.",
    attribution: "African Proverb",
    theme: "Inner Peace",
    difficulty: "medium",
    clueWords: [
      { hint: "An adversary", word: "ENEMY" },
      { hint: "Inside", word: "WITHIN" },
      { hint: "Adversaries", word: "ENEMIES" },
      { hint: "Beyond", word: "OUTSIDE" },
      { hint: "Cause harm", word: "HURT" },
    ],
  },
  {
    id: "p724",
    quote: "However big the elephant is, the eye can take it all in.",
    attribution: "African Proverb",
    theme: "Perspective",
    difficulty: "medium",
    clueWords: [
      { hint: "No matter how", word: "HOWEVER" },
      { hint: "Of large size", word: "BIG" },
      { hint: "Largest land animal", word: "ELEPHANT" },
      { hint: "Sight organ", word: "EYE" },
      { hint: "Take, accept", word: "TAKE" },
    ],
  },
  {
    id: "p725",
    quote: "If you want to know the road ahead, ask those coming back.",
    attribution: "Chinese Proverb",
    theme: "Wisdom",
    difficulty: "medium",
    clueWords: [
      { hint: "Desire", word: "WANT" },
      { hint: "Be aware of", word: "KNOW" },
      { hint: "A travel route", word: "ROAD" },
      { hint: "In front", word: "AHEAD" },
      { hint: "Inquire", word: "ASK" },
      { hint: "Returning", word: "COMING" },
    ],
  },
  {
    id: "p726",
    quote: "Even a fish would not get into trouble if it kept its mouth shut.",
    attribution: "Korean Proverb",
    theme: "Speech",
    difficulty: "medium",
    clueWords: [
      { hint: "Water creature", word: "FISH" },
      { hint: "Difficulty", word: "TROUBLE" },
      { hint: "Maintained", word: "KEPT" },
      { hint: "Speaking opening", word: "MOUTH" },
      { hint: "Closed", word: "SHUT" },
    ],
  },
  {
    id: "p727",
    quote: "Even monkeys fall from trees.",
    attribution: "Japanese Proverb",
    theme: "Humility",
    difficulty: "medium",
    clueWords: [
      { hint: "Furthermore", word: "EVEN" },
      { hint: "Tree-dwelling primates", word: "MONKEYS" },
      { hint: "Drop down", word: "FALL" },
      { hint: "Tall woody plants", word: "TREES" },
    ],
  },
  {
    id: "p728",
    quote: "Vision is the art of seeing what is invisible to others.",
    attribution: "Jonathan Swift",
    theme: "Imagination",
    difficulty: "medium",
    clueWords: [
      { hint: "Mental sight", word: "VISION" },
      { hint: "Skill, craft", word: "ART" },
      { hint: "Perceiving", word: "SEEING" },
      { hint: "Cannot be seen", word: "INVISIBLE" },
      { hint: "Other people", word: "OTHERS" },
    ],
  },
  {
    id: "p729",
    quote: "May you live every day of your life.",
    attribution: "Jonathan Swift",
    theme: "Mindfulness",
    difficulty: "medium",
    clueWords: [
      { hint: "Possibly will", word: "MAY" },
      { hint: "Be alive", word: "LIVE" },
      { hint: "Each one", word: "EVERY" },
      { hint: "A 24-hour period", word: "DAY" },
      { hint: "Existence", word: "LIFE" },
    ],
  },
  {
    id: "p730",
    quote: "Falsehood flies and the truth comes limping after it.",
    attribution: "Jonathan Swift",
    theme: "Truth",
    difficulty: "medium",
    clueWords: [
      { hint: "A lie", word: "FALSEHOOD" },
      { hint: "Travels through air", word: "FLIES" },
      { hint: "Honest reality", word: "TRUTH" },
      { hint: "Arrives", word: "COMES" },
      { hint: "Walking with difficulty", word: "LIMPING" },
    ],
  },

  // -------------------- HARD (60) --------------------
  {
    id: "p731",
    quote: "Knowledge has a beginning but no end.",
    attribution: "Anonymous",
    theme: "Learning",
    difficulty: "hard",
    clueWords: [
      { hint: "Information mastered", word: "KNOWLEDGE" },
      { hint: "Possesses", word: "HAS" },
      { hint: "The starting point", word: "BEGINNING" },
      { hint: "The final point", word: "END" },
    ],
  },
  {
    id: "p732",
    quote: "The greatest weapon against stress is our ability to choose one thought over another.",
    attribution: "William James",
    theme: "Mindset",
    difficulty: "hard",
    clueWords: [
      { hint: "Largest, finest", word: "GREATEST" },
      { hint: "Instrument of war", word: "WEAPON" },
      { hint: "Mental strain", word: "STRESS" },
      { hint: "Capability", word: "ABILITY" },
      { hint: "Make a selection", word: "CHOOSE" },
      { hint: "A mental idea", word: "THOUGHT" },
    ],
  },
  {
    id: "p733",
    quote: "Act as if what you do makes a difference. It does.",
    attribution: "William James",
    theme: "Action",
    difficulty: "hard",
    clueWords: [
      { hint: "Behave, perform", word: "ACT" },
      { hint: "Perform", word: "DO" },
      { hint: "Causes", word: "MAKES" },
      { hint: "Distinction, change", word: "DIFFERENCE" },
    ],
  },
  {
    id: "p734",
    quote: "Human beings can alter their lives by altering their attitudes.",
    attribution: "William James",
    theme: "Mindset",
    difficulty: "hard",
    clueWords: [
      { hint: "Of people", word: "HUMAN" },
      { hint: "Living entities", word: "BEINGS" },
      { hint: "Change, modify", word: "ALTER" },
      { hint: "Existences", word: "LIVES" },
      { hint: "Mental dispositions", word: "ATTITUDES" },
      { hint: "Belonging to them", word: "THEIR" },
    ],
  },
  {
    id: "p735",
    quote: "An attitude of positive expectation is the mark of the superior personality.",
    attribution: "Brian Tracy",
    theme: "Mindset",
    difficulty: "hard",
    clueWords: [
      { hint: "Mental disposition", word: "ATTITUDE" },
      { hint: "Constructive, optimistic", word: "POSITIVE" },
      { hint: "Anticipation", word: "EXPECTATION" },
      { hint: "Indicator, sign", word: "MARK" },
      { hint: "Better, higher", word: "SUPERIOR" },
      { hint: "Distinct character", word: "PERSONALITY" },
    ],
  },
  {
    id: "p736",
    quote: "Successful people are always looking for opportunities to help others.",
    attribution: "Brian Tracy",
    theme: "Service",
    difficulty: "hard",
    clueWords: [
      { hint: "Achieving goals", word: "SUCCESSFUL" },
      { hint: "Human beings", word: "PEOPLE" },
      { hint: "All the time", word: "ALWAYS" },
      { hint: "Searching", word: "LOOKING" },
      { hint: "Favorable chances", word: "OPPORTUNITIES" },
      { hint: "Aid, assist", word: "HELP" },
    ],
  },
  {
    id: "p737",
    quote: "The key to success is to focus our conscious mind on things we desire.",
    attribution: "Brian Tracy",
    theme: "Focus",
    difficulty: "hard",
    clueWords: [
      { hint: "An opener", word: "KEY" },
      { hint: "Achievement", word: "SUCCESS" },
      { hint: "Concentrate", word: "FOCUS" },
      { hint: "Aware", word: "CONSCIOUS" },
      { hint: "Thinking faculty", word: "MIND" },
      { hint: "Strongly want", word: "DESIRE" },
    ],
  },
  {
    id: "p738",
    quote: "If you wish your merit to be known, acknowledge that of other people.",
    attribution: "Asian Proverb",
    theme: "Humility",
    difficulty: "hard",
    clueWords: [
      { hint: "Desire", word: "WISH" },
      { hint: "Worth, value", word: "MERIT" },
      { hint: "Recognized, familiar", word: "KNOWN" },
      { hint: "Recognize", word: "ACKNOWLEDGE" },
      { hint: "Different", word: "OTHER" },
      { hint: "Human beings", word: "PEOPLE" },
    ],
  },
  {
    id: "p739",
    quote: "He who has imagination without learning has wings but no feet.",
    attribution: "Joseph Joubert",
    theme: "Wisdom",
    difficulty: "hard",
    clueWords: [
      { hint: "Mental creativity", word: "IMAGINATION" },
      { hint: "Lacking", word: "WITHOUT" },
      { hint: "Acquiring knowledge", word: "LEARNING" },
      { hint: "Bird flying parts", word: "WINGS" },
      { hint: "Lower limb ends", word: "FEET" },
    ],
  },
  {
    id: "p740",
    quote: "We are never as bad off or as happy as we say we are.",
    attribution: "Honore de Balzac",
    theme: "Perspective",
    difficulty: "hard",
    clueWords: [
      { hint: "At no time", word: "NEVER" },
      { hint: "Of poor quality", word: "BAD" },
      { hint: "Joyful", word: "HAPPY" },
      { hint: "Express verbally", word: "SAY" },
      { hint: "First-person plural", word: "WE" },
    ],
  },
  {
    id: "p741",
    quote: "I have never met a man so ignorant that I could not learn something from him.",
    attribution: "Galileo Galilei",
    theme: "Learning",
    difficulty: "hard",
    clueWords: [
      { hint: "At no time", word: "NEVER" },
      { hint: "Encountered", word: "MET" },
      { hint: "Adult human male", word: "MAN" },
      { hint: "Lacking knowledge", word: "IGNORANT" },
      { hint: "Acquire knowledge", word: "LEARN" },
      { hint: "An item or matter", word: "SOMETHING" },
    ],
  },
  {
    id: "p742",
    quote: "All truths are easy to understand once they are discovered; the point is to discover them.",
    attribution: "Galileo Galilei",
    theme: "Discovery",
    difficulty: "hard",
    clueWords: [
      { hint: "Honest realities", word: "TRUTHS" },
      { hint: "Without difficulty", word: "EASY" },
      { hint: "Comprehend", word: "UNDERSTAND" },
      { hint: "A single occasion", word: "ONCE" },
      { hint: "Found out", word: "DISCOVERED" },
      { hint: "An aim or message", word: "POINT" },
    ],
  },
  {
    id: "p743",
    quote: "You cannot teach a man anything; you can only help him discover it within himself.",
    attribution: "Galileo Galilei",
    theme: "Teaching",
    difficulty: "hard",
    clueWords: [
      { hint: "Are not able to", word: "CANNOT" },
      { hint: "Instruct", word: "TEACH" },
      { hint: "Adult human male", word: "MAN" },
      { hint: "Aid, assist", word: "HELP" },
      { hint: "Find", word: "DISCOVER" },
      { hint: "He himself", word: "HIMSELF" },
    ],
  },
  {
    id: "p744",
    quote: "Doubt is the father of invention.",
    attribution: "Galileo Galilei",
    theme: "Curiosity",
    difficulty: "hard",
    clueWords: [
      { hint: "Lack of certainty", word: "DOUBT" },
      { hint: "Male parent, originator", word: "FATHER" },
      { hint: "A new creation", word: "INVENTION" },
    ],
  },
  {
    id: "p745",
    quote: "Mathematics is the language of nature.",
    attribution: "Galileo Galilei",
    theme: "Wonder",
    difficulty: "hard",
    clueWords: [
      { hint: "Study of numbers", word: "MATHEMATICS" },
      { hint: "System of communication", word: "LANGUAGE" },
      { hint: "The natural world", word: "NATURE" },
    ],
  },
  {
    id: "p746",
    quote: "Life is a play, not a competition.",
    attribution: "Anonymous",
    theme: "Joy",
    difficulty: "hard",
    clueWords: [
      { hint: "Existence", word: "LIFE" },
      { hint: "Recreation, fun", word: "PLAY" },
      { hint: "A contest", word: "COMPETITION" },
    ],
  },
  {
    id: "p747",
    quote: "All limitations are self-imposed.",
    attribution: "Oliver Wendell Holmes",
    theme: "Self-Determination",
    difficulty: "hard",
    clueWords: [
      { hint: "Each, every", word: "ALL" },
      { hint: "Restrictions", word: "LIMITATIONS" },
      { hint: "One's own person", word: "SELF" },
      { hint: "Placed upon", word: "IMPOSED" },
    ],
  },
  {
    id: "p748",
    quote: "We do not stop playing because we grow old; we grow old because we stop playing.",
    attribution: "George Bernard Shaw",
    theme: "Joy",
    difficulty: "hard",
    clueWords: [
      { hint: "Cease", word: "STOP" },
      { hint: "Engaging in fun", word: "PLAYING" },
      { hint: "For what reason", word: "BECAUSE" },
      { hint: "Mature, age", word: "GROW" },
      { hint: "Aged, longstanding", word: "OLD" },
    ],
  },
  {
    id: "p749",
    quote: "Life is not about finding yourself. Life is about creating yourself.",
    attribution: "George Bernard Shaw",
    theme: "Identity",
    difficulty: "hard",
    clueWords: [
      { hint: "Existence", word: "LIFE" },
      { hint: "Discovering", word: "FINDING" },
      { hint: "Your own person", word: "YOURSELF" },
      { hint: "Bringing into being", word: "CREATING" },
      { hint: "Concerning", word: "ABOUT" },
    ],
  },
  {
    id: "p750",
    quote: "Progress is impossible without change.",
    attribution: "George Bernard Shaw",
    theme: "Change",
    difficulty: "hard",
    clueWords: [
      { hint: "Forward motion", word: "PROGRESS" },
      { hint: "Cannot be done", word: "IMPOSSIBLE" },
      { hint: "Lacking", word: "WITHOUT" },
      { hint: "Alteration", word: "CHANGE" },
    ],
  },
  {
    id: "p751",
    quote: "There are two tragedies in life: one is to lose your heart's desire; the other is to gain it.",
    attribution: "George Bernard Shaw",
    theme: "Reflection",
    difficulty: "hard",
    clueWords: [
      { hint: "A pair", word: "TWO" },
      { hint: "Catastrophes", word: "TRAGEDIES" },
      { hint: "Existence", word: "LIFE" },
      { hint: "Forfeit", word: "LOSE" },
      { hint: "Strong wish", word: "DESIRE" },
      { hint: "Acquire, obtain", word: "GAIN" },
    ],
  },
  {
    id: "p752",
    quote: "We are made wise not by recollection of our past, but by responsibility for our future.",
    attribution: "George Bernard Shaw",
    theme: "Wisdom",
    difficulty: "hard",
    clueWords: [
      { hint: "Sage, learned", word: "WISE" },
      { hint: "Memory of past", word: "RECOLLECTION" },
      { hint: "Earlier time", word: "PAST" },
      { hint: "Accountability", word: "RESPONSIBILITY" },
      { hint: "Time yet to come", word: "FUTURE" },
    ],
  },
  {
    id: "p753",
    quote: "Success consists in never making the same mistake a second time.",
    attribution: "George Bernard Shaw",
    theme: "Learning",
    difficulty: "hard",
    clueWords: [
      { hint: "Achievement", word: "SUCCESS" },
      { hint: "Is composed of", word: "CONSISTS" },
      { hint: "At no time", word: "NEVER" },
      { hint: "Doing", word: "MAKING" },
      { hint: "Identical", word: "SAME" },
      { hint: "An error", word: "MISTAKE" },
    ],
  },
  {
    id: "p754",
    quote: "Beware of false knowledge; it is more dangerous than ignorance.",
    attribution: "George Bernard Shaw",
    theme: "Wisdom",
    difficulty: "hard",
    clueWords: [
      { hint: "Be cautious of", word: "BEWARE" },
      { hint: "Untrue, fake", word: "FALSE" },
      { hint: "Information mastered", word: "KNOWLEDGE" },
      { hint: "Risky, harmful", word: "DANGEROUS" },
      { hint: "Lack of knowledge", word: "IGNORANCE" },
    ],
  },
  {
    id: "p755",
    quote: "All great truths begin as blasphemies.",
    attribution: "George Bernard Shaw",
    theme: "Originality",
    difficulty: "hard",
    clueWords: [
      { hint: "Outstanding", word: "GREAT" },
      { hint: "Honest realities", word: "TRUTHS" },
      { hint: "Start", word: "BEGIN" },
      { hint: "Heretical statements", word: "BLASPHEMIES" },
    ],
  },
  {
    id: "p756",
    quote: "Patience is the ability to keep a good attitude while waiting.",
    attribution: "Joyce Meyer",
    theme: "Patience",
    difficulty: "hard",
    clueWords: [
      { hint: "Calm endurance", word: "PATIENCE" },
      { hint: "Capability", word: "ABILITY" },
      { hint: "Maintain", word: "KEEP" },
      { hint: "Worthy", word: "GOOD" },
      { hint: "Mental disposition", word: "ATTITUDE" },
      { hint: "Pausing in expectation", word: "WAITING" },
    ],
  },
  {
    id: "p757",
    quote: "The greatest happiness of life is the conviction that we are loved.",
    attribution: "Victor Hugo",
    theme: "Love",
    difficulty: "hard",
    clueWords: [
      { hint: "Largest, finest", word: "GREATEST" },
      { hint: "Joyful state", word: "HAPPINESS" },
      { hint: "Existence", word: "LIFE" },
      { hint: "Strong belief", word: "CONVICTION" },
      { hint: "Cherished", word: "LOVED" },
    ],
  },
  {
    id: "p758",
    quote: "Music expresses what cannot be said and on which it is impossible to be silent.",
    attribution: "Victor Hugo",
    theme: "Wonder",
    difficulty: "hard",
    clueWords: [
      { hint: "Organized sound", word: "MUSIC" },
      { hint: "Communicates", word: "EXPRESSES" },
      { hint: "Are not able to", word: "CANNOT" },
      { hint: "Stated, expressed", word: "SAID" },
      { hint: "Cannot be done", word: "IMPOSSIBLE" },
      { hint: "Without sound", word: "SILENT" },
    ],
  },
  {
    id: "p759",
    quote: "Even the darkest night will end and the sun will rise.",
    attribution: "Victor Hugo",
    theme: "Hope",
    difficulty: "hard",
    clueWords: [
      { hint: "Most without illumination", word: "DARKEST" },
      { hint: "Period of darkness", word: "NIGHT" },
      { hint: "Conclude", word: "END" },
      { hint: "Star at center of solar system", word: "SUN" },
      { hint: "Get up", word: "RISE" },
    ],
  },
  {
    id: "p760",
    quote: "Life is the flower for which love is the honey.",
    attribution: "Victor Hugo",
    theme: "Love",
    difficulty: "hard",
    clueWords: [
      { hint: "Existence", word: "LIFE" },
      { hint: "Plant blossom", word: "FLOWER" },
      { hint: "Deep affection", word: "LOVE" },
      { hint: "Sweet bee product", word: "HONEY" },
    ],
  },
  {
    id: "p761",
    quote: "Strong and bitter words indicate a weak cause.",
    attribution: "Victor Hugo",
    theme: "Communication",
    difficulty: "hard",
    clueWords: [
      { hint: "Powerful, firm", word: "STRONG" },
      { hint: "Sharp, harsh", word: "BITTER" },
      { hint: "Spoken units", word: "WORDS" },
      { hint: "Suggest, signal", word: "INDICATE" },
      { hint: "Lacking strength", word: "WEAK" },
      { hint: "A reason", word: "CAUSE" },
    ],
  },
  {
    id: "p762",
    quote: "There is nothing like a dream to create the future.",
    attribution: "Victor Hugo",
    theme: "Aspiration",
    difficulty: "hard",
    clueWords: [
      { hint: "Not anything", word: "NOTHING" },
      { hint: "Similar to", word: "LIKE" },
      { hint: "An aspiration", word: "DREAM" },
      { hint: "Bring into existence", word: "CREATE" },
      { hint: "Time yet to come", word: "FUTURE" },
    ],
  },
  {
    id: "p763",
    quote: "When the heart is afire, some sparks will fly out at the mouth.",
    attribution: "Thomas Fuller",
    theme: "Passion",
    difficulty: "hard",
    clueWords: [
      { hint: "Pumping organ", word: "HEART" },
      { hint: "On fire", word: "AFIRE" },
      { hint: "Tiny burning particles", word: "SPARKS" },
      { hint: "Travel through air", word: "FLY" },
      { hint: "Speaking opening", word: "MOUTH" },
    ],
  },
  {
    id: "p764",
    quote: "Trust everybody, but cut the cards.",
    attribution: "Finley Peter Dunne",
    theme: "Caution",
    difficulty: "hard",
    clueWords: [
      { hint: "Have faith in", word: "TRUST" },
      { hint: "Each person", word: "EVERYBODY" },
      { hint: "Slice, divide", word: "CUT" },
      { hint: "Playing pieces", word: "CARDS" },
    ],
  },
  {
    id: "p765",
    quote: "Without faith, nothing is possible. With it, nothing is impossible.",
    attribution: "Mary McLeod Bethune",
    theme: "Faith",
    difficulty: "hard",
    clueWords: [
      { hint: "Lacking", word: "WITHOUT" },
      { hint: "Trust, belief", word: "FAITH" },
      { hint: "Not anything", word: "NOTHING" },
      { hint: "Capable", word: "POSSIBLE" },
      { hint: "Cannot be done", word: "IMPOSSIBLE" },
    ],
  },
  {
    id: "p766",
    quote: "The deepest waters make the least noise.",
    attribution: "Italian Proverb",
    theme: "Wisdom",
    difficulty: "hard",
    clueWords: [
      { hint: "Most profound", word: "DEEPEST" },
      { hint: "Bodies of liquid", word: "WATERS" },
      { hint: "Cause, produce", word: "MAKE" },
      { hint: "Smallest amount", word: "LEAST" },
      { hint: "Loud sound", word: "NOISE" },
    ],
  },
  {
    id: "p767",
    quote: "Better to light a candle than to curse the darkness.",
    attribution: "Chinese Proverb",
    theme: "Action",
    difficulty: "hard",
    clueWords: [
      { hint: "Preferable", word: "BETTER" },
      { hint: "Set ablaze", word: "LIGHT" },
      { hint: "A wax light source", word: "CANDLE" },
      { hint: "Speak ill of", word: "CURSE" },
      { hint: "Absence of light", word: "DARKNESS" },
    ],
  },
  {
    id: "p768",
    quote: "If your heart is right, then the world is right.",
    attribution: "Chinese Proverb",
    theme: "Inner Peace",
    difficulty: "hard",
    clueWords: [
      { hint: "Pumping organ", word: "HEART" },
      { hint: "Correct, just", word: "RIGHT" },
      { hint: "After that", word: "THEN" },
      { hint: "The earth", word: "WORLD" },
    ],
  },
  {
    id: "p769",
    quote: "A book is a garden carried in the pocket.",
    attribution: "Chinese Proverb",
    theme: "Learning",
    difficulty: "hard",
    clueWords: [
      { hint: "Bound reading material", word: "BOOK" },
      { hint: "Cultivated plot of plants", word: "GARDEN" },
      { hint: "Conveyed, carried", word: "CARRIED" },
      { hint: "A clothing pouch", word: "POCKET" },
    ],
  },
  {
    id: "p770",
    quote: "Teachers open the door; you enter by yourself.",
    attribution: "Chinese Proverb",
    theme: "Learning",
    difficulty: "hard",
    clueWords: [
      { hint: "Instructors", word: "TEACHERS" },
      { hint: "Begin, unbar", word: "OPEN" },
      { hint: "Entryway", word: "DOOR" },
      { hint: "Go in", word: "ENTER" },
      { hint: "Your own person", word: "YOURSELF" },
    ],
  },
  {
    id: "p771",
    quote: "He who returns from a journey is not the same as he who left.",
    attribution: "Chinese Proverb",
    theme: "Growth",
    difficulty: "hard",
    clueWords: [
      { hint: "Comes back", word: "RETURNS" },
      { hint: "A long trip", word: "JOURNEY" },
      { hint: "Identical", word: "SAME" },
      { hint: "Departed", word: "LEFT" },
    ],
  },
  {
    id: "p772",
    quote: "A bird does not sing because it has an answer; it sings because it has a song.",
    attribution: "Maya Angelou",
    theme: "Joy",
    difficulty: "hard",
    clueWords: [
      { hint: "Feathered creature", word: "BIRD" },
      { hint: "Vocalize melodically", word: "SING" },
      { hint: "Vocalizes melodically", word: "SINGS" },
      { hint: "A reply", word: "ANSWER" },
      { hint: "Possesses", word: "HAS" },
      { hint: "Musical piece", word: "SONG" },
    ],
  },
  {
    id: "p773",
    quote: "Making a living is not the same as making a life.",
    attribution: "Maya Angelou",
    theme: "Purpose",
    difficulty: "hard",
    clueWords: [
      { hint: "Earning, creating", word: "MAKING" },
      { hint: "Earning income", word: "LIVING" },
      { hint: "Identical", word: "SAME" },
      { hint: "Existence", word: "LIFE" },
    ],
  },
  {
    id: "p774",
    quote: "If you find it in your heart to care for somebody else, you will have succeeded.",
    attribution: "Maya Angelou",
    theme: "Service",
    difficulty: "hard",
    clueWords: [
      { hint: "Discover", word: "FIND" },
      { hint: "Pumping organ", word: "HEART" },
      { hint: "Show concern for", word: "CARE" },
      { hint: "Some person", word: "SOMEBODY" },
      { hint: "Apart from, other", word: "ELSE" },
      { hint: "Achieved success", word: "SUCCEEDED" },
    ],
  },
  {
    id: "p775",
    quote: "When you know better, do better.",
    attribution: "Maya Angelou",
    theme: "Growth",
    difficulty: "hard",
    clueWords: [
      { hint: "Be aware of", word: "KNOW" },
      { hint: "Improved", word: "BETTER" },
      { hint: "Perform", word: "DO" },
    ],
  },
  {
    id: "p776",
    quote: "We delight in the beauty of the butterfly, but rarely admit the changes it has gone through.",
    attribution: "Maya Angelou",
    theme: "Growth",
    difficulty: "hard",
    clueWords: [
      { hint: "Take pleasure", word: "DELIGHT" },
      { hint: "Loveliness", word: "BEAUTY" },
      { hint: "A winged insect", word: "BUTTERFLY" },
      { hint: "Seldom", word: "RARELY" },
      { hint: "Concede", word: "ADMIT" },
      { hint: "Alterations", word: "CHANGES" },
    ],
  },
  {
    id: "p777",
    quote: "Have enough courage to trust love one more time and always one more time.",
    attribution: "Maya Angelou",
    theme: "Love",
    difficulty: "hard",
    clueWords: [
      { hint: "Sufficient", word: "ENOUGH" },
      { hint: "Bravery", word: "COURAGE" },
      { hint: "Have faith in", word: "TRUST" },
      { hint: "Deep affection", word: "LOVE" },
      { hint: "An occasion", word: "TIME" },
      { hint: "All the time", word: "ALWAYS" },
    ],
  },
  {
    id: "p778",
    quote: "Asking the right questions takes as much skill as giving the right answers.",
    attribution: "Robert Half",
    theme: "Wisdom",
    difficulty: "hard",
    clueWords: [
      { hint: "Inquiring", word: "ASKING" },
      { hint: "Correct", word: "RIGHT" },
      { hint: "Inquiries", word: "QUESTIONS" },
      { hint: "Trained ability", word: "SKILL" },
      { hint: "Providing", word: "GIVING" },
      { hint: "Replies", word: "ANSWERS" },
    ],
  },
  {
    id: "p779",
    quote: "If something is wrong, fix it now. But train yourself not to worry.",
    attribution: "Mary Hemingway",
    theme: "Action",
    difficulty: "hard",
    clueWords: [
      { hint: "An item", word: "SOMETHING" },
      { hint: "Incorrect, harmful", word: "WRONG" },
      { hint: "Repair, mend", word: "FIX" },
      { hint: "At this moment", word: "NOW" },
      { hint: "Discipline, condition", word: "TRAIN" },
      { hint: "Anxious thought", word: "WORRY" },
    ],
  },
  {
    id: "p780",
    quote: "All progress takes place outside the comfort zone.",
    attribution: "Michael John Bobak",
    theme: "Growth",
    difficulty: "hard",
    clueWords: [
      { hint: "Each, every", word: "ALL" },
      { hint: "Forward motion", word: "PROGRESS" },
      { hint: "Occurs", word: "TAKES" },
      { hint: "A location", word: "PLACE" },
      { hint: "Beyond", word: "OUTSIDE" },
      { hint: "Ease, security", word: "COMFORT" },
    ],
  },
  {
    id: "p781",
    quote: "Sometimes life knocks you down. Get up and keep moving forward.",
    attribution: "Anonymous",
    theme: "Resilience",
    difficulty: "hard",
    clueWords: [
      { hint: "On occasion", word: "SOMETIMES" },
      { hint: "Existence", word: "LIFE" },
      { hint: "Strikes", word: "KNOCKS" },
      { hint: "Maintain", word: "KEEP" },
      { hint: "In motion", word: "MOVING" },
      { hint: "Toward the front", word: "FORWARD" },
    ],
  },
  {
    id: "p782",
    quote: "The greatest part of our happiness depends on our dispositions, not on our circumstances.",
    attribution: "Martha Washington",
    theme: "Happiness",
    difficulty: "hard",
    clueWords: [
      { hint: "Largest portion", word: "GREATEST" },
      { hint: "Joyful state", word: "HAPPINESS" },
      { hint: "Relies upon", word: "DEPENDS" },
      { hint: "Mental temperaments", word: "DISPOSITIONS" },
      { hint: "Conditions, situations", word: "CIRCUMSTANCES" },
    ],
  },
  {
    id: "p783",
    quote: "Education is what survives when what has been learned has been forgotten.",
    attribution: "B.F. Skinner",
    theme: "Learning",
    difficulty: "hard",
    clueWords: [
      { hint: "Schooling, instruction", word: "EDUCATION" },
      { hint: "Endures, outlasts", word: "SURVIVES" },
      { hint: "Acquired knowledge", word: "LEARNED" },
      { hint: "Lost from memory", word: "FORGOTTEN" },
    ],
  },
  {
    id: "p784",
    quote: "The whole purpose of education is to turn mirrors into windows.",
    attribution: "Sydney J. Harris",
    theme: "Learning",
    difficulty: "hard",
    clueWords: [
      { hint: "Entire", word: "WHOLE" },
      { hint: "Aim, intention", word: "PURPOSE" },
      { hint: "Schooling, instruction", word: "EDUCATION" },
      { hint: "Reflective surfaces", word: "MIRRORS" },
      { hint: "Glass openings", word: "WINDOWS" },
    ],
  },
  {
    id: "p785",
    quote: "Wisdom begins in wonder.",
    attribution: "Socrates",
    theme: "Wonder",
    difficulty: "hard",
    clueWords: [
      { hint: "Deep insight", word: "WISDOM" },
      { hint: "Starts", word: "BEGINS" },
      { hint: "Awe, amazement", word: "WONDER" },
    ],
  },
  {
    id: "p786",
    quote: "Do not say a little in many words but a great deal in a few.",
    attribution: "Pythagoras",
    theme: "Communication",
    difficulty: "hard",
    clueWords: [
      { hint: "Express verbally", word: "SAY" },
      { hint: "A small amount", word: "LITTLE" },
      { hint: "A great number", word: "MANY" },
      { hint: "Spoken units", word: "WORDS" },
      { hint: "Outstanding", word: "GREAT" },
      { hint: "Small number", word: "FEW" },
    ],
  },
  {
    id: "p787",
    quote: "No man steps in the same river twice.",
    attribution: "Heraclitus",
    theme: "Change",
    difficulty: "hard",
    clueWords: [
      { hint: "Adult human male", word: "MAN" },
      { hint: "Paces forward", word: "STEPS" },
      { hint: "Identical", word: "SAME" },
      { hint: "Flowing waterway", word: "RIVER" },
      { hint: "Two times", word: "TWICE" },
    ],
  },
  {
    id: "p788",
    quote: "Character is destiny.",
    attribution: "Heraclitus",
    theme: "Character",
    difficulty: "hard",
    clueWords: [
      { hint: "Moral nature", word: "CHARACTER" },
      { hint: "Predetermined fate", word: "DESTINY" },
    ],
  },
  {
    id: "p789",
    quote: "There is nothing permanent except change.",
    attribution: "Heraclitus",
    theme: "Change",
    difficulty: "hard",
    clueWords: [
      { hint: "Not anything", word: "NOTHING" },
      { hint: "Lasting forever", word: "PERMANENT" },
      { hint: "Apart from", word: "EXCEPT" },
      { hint: "Alteration", word: "CHANGE" },
    ],
  },
  {
    id: "p790",
    quote: "Big results require big ambitions.",
    attribution: "Heraclitus",
    theme: "Ambition",
    difficulty: "hard",
    clueWords: [
      { hint: "Of large size", word: "BIG" },
      { hint: "Outcomes", word: "RESULTS" },
      { hint: "Demand, need", word: "REQUIRE" },
      { hint: "Strong desires for success", word: "AMBITIONS" },
    ],
  },

  // -------------------- EXPERT (40) --------------------
  {
    id: "p791",
    quote: "Of all the wonders that I have heard, it seems most strange that men should fear.",
    attribution: "William Shakespeare",
    theme: "Courage",
    difficulty: "expert",
    clueWords: [
      { hint: "Marvels", word: "WONDERS" },
      { hint: "Perceived by ear", word: "HEARD" },
      { hint: "Appears to be", word: "SEEMS" },
      { hint: "Greatest", word: "MOST" },
      { hint: "Unusual, foreign", word: "STRANGE" },
      { hint: "Be afraid of", word: "FEAR" },
    ],
  },
  {
    id: "p792",
    quote: "Words without thoughts never to heaven go.",
    attribution: "William Shakespeare",
    theme: "Sincerity",
    difficulty: "expert",
    clueWords: [
      { hint: "Spoken units", word: "WORDS" },
      { hint: "Without", word: "WITHOUT" },
      { hint: "Mental ideas", word: "THOUGHTS" },
      { hint: "At no time", word: "NEVER" },
      { hint: "The skies, paradise", word: "HEAVEN" },
      { hint: "Travel", word: "GO" },
    ],
  },
  {
    id: "p793",
    quote: "Sweet are the uses of adversity.",
    attribution: "William Shakespeare",
    theme: "Adversity",
    difficulty: "expert",
    clueWords: [
      { hint: "Pleasant, sugary", word: "SWEET" },
      { hint: "Applications", word: "USES" },
      { hint: "Hardship", word: "ADVERSITY" },
    ],
  },
  {
    id: "p794",
    quote: "I dream my painting and I paint my dream.",
    attribution: "Vincent van Gogh",
    theme: "Creativity",
    difficulty: "expert",
    clueWords: [
      { hint: "Imagine in sleep", word: "DREAM" },
      { hint: "An artwork on canvas", word: "PAINTING" },
      { hint: "Apply pigment", word: "PAINT" },
      { hint: "Belonging to me", word: "MY" },
    ],
  },
  {
    id: "p795",
    quote: "If you hear a voice within you say you cannot paint, by all means paint, and that voice will be silenced.",
    attribution: "Vincent van Gogh",
    theme: "Creativity",
    difficulty: "expert",
    clueWords: [
      { hint: "Receive sound", word: "HEAR" },
      { hint: "Sound from one's throat", word: "VOICE" },
      { hint: "Inside", word: "WITHIN" },
      { hint: "Are not able to", word: "CANNOT" },
      { hint: "Apply pigment", word: "PAINT" },
      { hint: "Made quiet", word: "SILENCED" },
    ],
  },
  {
    id: "p796",
    quote: "Great things are not done by impulse, but by a series of small things brought together.",
    attribution: "Vincent van Gogh",
    theme: "Effort",
    difficulty: "expert",
    clueWords: [
      { hint: "Outstanding", word: "GREAT" },
      { hint: "Items, matters", word: "THINGS" },
      { hint: "Done", word: "DONE" },
      { hint: "Sudden urge", word: "IMPULSE" },
      { hint: "A sequence", word: "SERIES" },
      { hint: "Little, slight", word: "SMALL" },
    ],
  },
  {
    id: "p797",
    quote: "What would life be if we had no courage to attempt anything?",
    attribution: "Vincent van Gogh",
    theme: "Courage",
    difficulty: "expert",
    clueWords: [
      { hint: "Existence", word: "LIFE" },
      { hint: "Possessed", word: "HAD" },
      { hint: "Bravery", word: "COURAGE" },
      { hint: "Try to do", word: "ATTEMPT" },
      { hint: "Any item", word: "ANYTHING" },
    ],
  },
  {
    id: "p798",
    quote: "Normality is a paved road: it is comfortable to walk, but no flowers grow on it.",
    attribution: "Vincent van Gogh",
    theme: "Originality",
    difficulty: "expert",
    clueWords: [
      { hint: "The usual state", word: "NORMALITY" },
      { hint: "Surfaced with stones", word: "PAVED" },
      { hint: "A travel route", word: "ROAD" },
      { hint: "At ease", word: "COMFORTABLE" },
      { hint: "Move on foot", word: "WALK" },
      { hint: "Plant blossoms", word: "FLOWERS" },
    ],
  },
  {
    id: "p799",
    quote: "There is nothing impossible to him who will try.",
    attribution: "Alexander the Great",
    theme: "Determination",
    difficulty: "expert",
    clueWords: [
      { hint: "Not anything", word: "NOTHING" },
      { hint: "Cannot be done", word: "IMPOSSIBLE" },
      { hint: "Make an attempt", word: "TRY" },
    ],
  },
  {
    id: "p800",
    quote: "I am indebted to my father for living, but to my teacher for living well.",
    attribution: "Alexander the Great",
    theme: "Gratitude",
    difficulty: "expert",
    clueWords: [
      { hint: "Owing thanks", word: "INDEBTED" },
      { hint: "Male parent", word: "FATHER" },
      { hint: "Existing", word: "LIVING" },
      { hint: "An instructor", word: "TEACHER" },
      { hint: "Properly, finely", word: "WELL" },
    ],
  },
  {
    id: "p801",
    quote: "These are the times that try men's souls.",
    attribution: "Thomas Paine",
    theme: "Adversity",
    difficulty: "expert",
    clueWords: [
      { hint: "Periods, occasions", word: "TIMES" },
      { hint: "Test, challenge", word: "TRY" },
      { hint: "Adult human males", word: "MEN" },
      { hint: "Inner essences", word: "SOULS" },
    ],
  },
  {
    id: "p802",
    quote: "He who dares not offend cannot be honest.",
    attribution: "Thomas Paine",
    theme: "Integrity",
    difficulty: "expert",
    clueWords: [
      { hint: "Has the courage", word: "DARES" },
      { hint: "Cause displeasure to", word: "OFFEND" },
      { hint: "Are not able to", word: "CANNOT" },
      { hint: "Truthful", word: "HONEST" },
    ],
  },
  {
    id: "p803",
    quote: "The mind once enlightened cannot again become dark.",
    attribution: "Thomas Paine",
    theme: "Learning",
    difficulty: "expert",
    clueWords: [
      { hint: "Thinking faculty", word: "MIND" },
      { hint: "A single occasion", word: "ONCE" },
      { hint: "Awakened, illuminated", word: "ENLIGHTENED" },
      { hint: "Are not able to", word: "CANNOT" },
      { hint: "Once more", word: "AGAIN" },
      { hint: "Without illumination", word: "DARK" },
    ],
  },
  {
    id: "p804",
    quote: "If everyone is thinking alike, then somebody is not thinking.",
    attribution: "George Patton",
    theme: "Independence",
    difficulty: "expert",
    clueWords: [
      { hint: "Each person", word: "EVERYONE" },
      { hint: "Pondering", word: "THINKING" },
      { hint: "Similarly", word: "ALIKE" },
      { hint: "Some person", word: "SOMEBODY" },
      { hint: "After that", word: "THEN" },
    ],
  },
  {
    id: "p805",
    quote: "Some people see things as they are and ask why; others dream of things that never were and ask why not.",
    attribution: "George Bernard Shaw",
    theme: "Imagination",
    difficulty: "expert",
    clueWords: [
      { hint: "A few", word: "SOME" },
      { hint: "Human beings", word: "PEOPLE" },
      { hint: "Items, matters", word: "THINGS" },
      { hint: "Inquire", word: "ASK" },
      { hint: "Different ones", word: "OTHERS" },
      { hint: "At no time", word: "NEVER" },
    ],
  },
  {
    id: "p806",
    quote: "Liberty means responsibility. That is why most men dread it.",
    attribution: "George Bernard Shaw",
    theme: "Liberty",
    difficulty: "expert",
    clueWords: [
      { hint: "Freedom", word: "LIBERTY" },
      { hint: "Signifies", word: "MEANS" },
      { hint: "Accountability", word: "RESPONSIBILITY" },
      { hint: "The greatest amount", word: "MOST" },
      { hint: "Adult human males", word: "MEN" },
      { hint: "Greatly fear", word: "DREAD" },
    ],
  },
  {
    id: "p807",
    quote: "Imagination is the eye of the soul.",
    attribution: "Joseph Joubert",
    theme: "Wonder",
    difficulty: "expert",
    clueWords: [
      { hint: "Mental creativity", word: "IMAGINATION" },
      { hint: "Sight organ", word: "EYE" },
      { hint: "Inner essence", word: "SOUL" },
    ],
  },
  {
    id: "p808",
    quote: "Tenderness and kindness are not signs of weakness, but manifestations of strength.",
    attribution: "Kahlil Gibran",
    theme: "Kindness",
    difficulty: "expert",
    clueWords: [
      { hint: "Gentle care", word: "TENDERNESS" },
      { hint: "Considerate behavior", word: "KINDNESS" },
      { hint: "Indicators", word: "SIGNS" },
      { hint: "Lack of strength", word: "WEAKNESS" },
      { hint: "Visible expressions", word: "MANIFESTATIONS" },
      { hint: "Power, fortitude", word: "STRENGTH" },
    ],
  },
  {
    id: "p809",
    quote: "Out of suffering have emerged the strongest souls.",
    attribution: "Kahlil Gibran",
    theme: "Resilience",
    difficulty: "expert",
    clueWords: [
      { hint: "Hardship, anguish", word: "SUFFERING" },
      { hint: "Come forth", word: "EMERGED" },
      { hint: "Most powerful", word: "STRONGEST" },
      { hint: "Inner essences", word: "SOULS" },
    ],
  },
  {
    id: "p810",
    quote: "The deeper that sorrow carves into your being, the more joy you can contain.",
    attribution: "Kahlil Gibran",
    theme: "Healing",
    difficulty: "expert",
    clueWords: [
      { hint: "More profoundly", word: "DEEPER" },
      { hint: "Sadness", word: "SORROW" },
      { hint: "Cuts, etches", word: "CARVES" },
      { hint: "Existence", word: "BEING" },
      { hint: "Happiness", word: "JOY" },
      { hint: "Hold, include", word: "CONTAIN" },
    ],
  },
  {
    id: "p811",
    quote: "Beauty is eternity gazing at itself in a mirror.",
    attribution: "Kahlil Gibran",
    theme: "Wonder",
    difficulty: "expert",
    clueWords: [
      { hint: "Loveliness", word: "BEAUTY" },
      { hint: "Endless time", word: "ETERNITY" },
      { hint: "Looking intently", word: "GAZING" },
      { hint: "On its own", word: "ITSELF" },
      { hint: "A reflective surface", word: "MIRROR" },
    ],
  },
  {
    id: "p812",
    quote: "Trees are poems that the earth writes upon the sky.",
    attribution: "Kahlil Gibran",
    theme: "Nature",
    difficulty: "expert",
    clueWords: [
      { hint: "Tall woody plants", word: "TREES" },
      { hint: "Verses of art", word: "POEMS" },
      { hint: "Our planet", word: "EARTH" },
      { hint: "Composes", word: "WRITES" },
      { hint: "Onto, on top of", word: "UPON" },
      { hint: "The heavens above", word: "SKY" },
    ],
  },
  {
    id: "p813",
    quote: "If you love somebody, let them go. For if they return, they were always yours.",
    attribution: "Kahlil Gibran",
    theme: "Love",
    difficulty: "expert",
    clueWords: [
      { hint: "Cherish deeply", word: "LOVE" },
      { hint: "Some person", word: "SOMEBODY" },
      { hint: "Allow", word: "LET" },
      { hint: "Come back", word: "RETURN" },
      { hint: "All the time", word: "ALWAYS" },
      { hint: "Belonging to you", word: "YOURS" },
    ],
  },
  {
    id: "p814",
    quote: "Yesterday is but today's memory, and tomorrow is today's dream.",
    attribution: "Kahlil Gibran",
    theme: "Time",
    difficulty: "expert",
    clueWords: [
      { hint: "The day before", word: "YESTERDAY" },
      { hint: "The current day", word: "TODAY" },
      { hint: "Recollection", word: "MEMORY" },
      { hint: "The day after today", word: "TOMORROW" },
      { hint: "An aspiration", word: "DREAM" },
    ],
  },
  {
    id: "p815",
    quote: "Faith is an oasis in the heart which will never be reached by the caravan of thinking.",
    attribution: "Kahlil Gibran",
    theme: "Faith",
    difficulty: "expert",
    clueWords: [
      { hint: "Trust, belief", word: "FAITH" },
      { hint: "Desert haven", word: "OASIS" },
      { hint: "Pumping organ", word: "HEART" },
      { hint: "At no time", word: "NEVER" },
      { hint: "Group of travelers", word: "CARAVAN" },
      { hint: "Pondering", word: "THINKING" },
    ],
  },
  {
    id: "p816",
    quote: "And forget not that the earth delights to feel your bare feet.",
    attribution: "Kahlil Gibran",
    theme: "Nature",
    difficulty: "expert",
    clueWords: [
      { hint: "Lose memory of", word: "FORGET" },
      { hint: "Our planet", word: "EARTH" },
      { hint: "Takes pleasure", word: "DELIGHTS" },
      { hint: "Sense, perceive", word: "FEEL" },
      { hint: "Uncovered, naked", word: "BARE" },
      { hint: "Lower limb ends", word: "FEET" },
    ],
  },
  {
    id: "p817",
    quote: "The wound is the place where the light enters you.",
    attribution: "Rumi",
    theme: "Healing",
    difficulty: "expert",
    clueWords: [
      { hint: "An injury", word: "WOUND" },
      { hint: "A location", word: "PLACE" },
      { hint: "Illumination", word: "LIGHT" },
      { hint: "Goes into", word: "ENTERS" },
      { hint: "At which point", word: "WHERE" },
    ],
  },
  {
    id: "p818",
    quote: "Be silent, only sometimes the song of silence is heard.",
    attribution: "Anonymous",
    theme: "Mindfulness",
    difficulty: "expert",
    clueWords: [
      { hint: "Without sound", word: "SILENT" },
      { hint: "On occasion", word: "SOMETIMES" },
      { hint: "Solely", word: "ONLY" },
      { hint: "Musical piece", word: "SONG" },
      { hint: "Absence of sound", word: "SILENCE" },
      { hint: "Perceived by ear", word: "HEARD" },
    ],
  },
  {
    id: "p819",
    quote: "Hard times will always reveal true friends.",
    attribution: "Anonymous",
    theme: "Friendship",
    difficulty: "expert",
    clueWords: [
      { hint: "Difficult", word: "HARD" },
      { hint: "Periods, occasions", word: "TIMES" },
      { hint: "All the time", word: "ALWAYS" },
      { hint: "Uncover, expose", word: "REVEAL" },
      { hint: "Genuine", word: "TRUE" },
      { hint: "Companions", word: "FRIENDS" },
    ],
  },
  {
    id: "p820",
    quote: "We must not allow other people's limited perceptions to define us.",
    attribution: "Virginia Satir",
    theme: "Authenticity",
    difficulty: "expert",
    clueWords: [
      { hint: "Allow, permit", word: "ALLOW" },
      { hint: "Different", word: "OTHER" },
      { hint: "Human beings", word: "PEOPLE" },
      { hint: "Restricted, narrow", word: "LIMITED" },
      { hint: "Awarenesses", word: "PERCEPTIONS" },
      { hint: "Determine, characterize", word: "DEFINE" },
    ],
  },
  {
    id: "p821",
    quote: "Do not waste a minute, not a single moment of life on someone's prejudice.",
    attribution: "Maya Angelou",
    theme: "Self-Worth",
    difficulty: "expert",
    clueWords: [
      { hint: "Squander", word: "WASTE" },
      { hint: "Sixty seconds", word: "MINUTE" },
      { hint: "One alone", word: "SINGLE" },
      { hint: "An instant", word: "MOMENT" },
      { hint: "Existence", word: "LIFE" },
      { hint: "An unfair bias", word: "PREJUDICE" },
    ],
  },
  {
    id: "p822",
    quote: "If you must look back, do so forgivingly. If you must look forward, do so prayerfully.",
    attribution: "Maya Angelou",
    theme: "Mindfulness",
    difficulty: "expert",
    clueWords: [
      { hint: "Use the eyes", word: "LOOK" },
      { hint: "Toward the rear", word: "BACK" },
      { hint: "With pardon", word: "FORGIVINGLY" },
      { hint: "Toward the future", word: "FORWARD" },
      { hint: "With prayer", word: "PRAYERFULLY" },
    ],
  },
  {
    id: "p823",
    quote: "If you are going to live, leave a legacy.",
    attribution: "Maya Angelou",
    theme: "Legacy",
    difficulty: "expert",
    clueWords: [
      { hint: "Travel", word: "GOING" },
      { hint: "Be alive", word: "LIVE" },
      { hint: "Depart, abandon", word: "LEAVE" },
      { hint: "Inheritance, mark", word: "LEGACY" },
    ],
  },
  {
    id: "p824",
    quote: "Each man takes care that his neighbor shall not cheat him; one day he finds that he has cheated himself.",
    attribution: "Ralph Waldo Emerson",
    theme: "Integrity",
    difficulty: "expert",
    clueWords: [
      { hint: "Every", word: "EACH" },
      { hint: "Adult human male", word: "MAN" },
      { hint: "A close-by person", word: "NEIGHBOR" },
      { hint: "Deceive", word: "CHEAT" },
      { hint: "Discovers", word: "FINDS" },
      { hint: "He himself", word: "HIMSELF" },
    ],
  },
  {
    id: "p825",
    quote: "What you are will show in what you do.",
    attribution: "Thomas Edison",
    theme: "Character",
    difficulty: "expert",
    clueWords: [
      { hint: "Display, reveal", word: "SHOW" },
      { hint: "Perform", word: "DO" },
      { hint: "Anything that", word: "WHAT" },
    ],
  },
  {
    id: "p826",
    quote: "There is far more opportunity than there is ability.",
    attribution: "Thomas Edison",
    theme: "Opportunity",
    difficulty: "expert",
    clueWords: [
      { hint: "By a great distance", word: "FAR" },
      { hint: "To a greater extent", word: "MORE" },
      { hint: "A favorable chance", word: "OPPORTUNITY" },
      { hint: "Capability", word: "ABILITY" },
    ],
  },
  {
    id: "p827",
    quote: "The first requisite for success is the ability to apply your physical and mental energies to one problem.",
    attribution: "Thomas Edison",
    theme: "Focus",
    difficulty: "expert",
    clueWords: [
      { hint: "Initial", word: "FIRST" },
      { hint: "A requirement", word: "REQUISITE" },
      { hint: "Achievement", word: "SUCCESS" },
      { hint: "Capability", word: "ABILITY" },
      { hint: "Bodily", word: "PHYSICAL" },
      { hint: "Of the mind", word: "MENTAL" },
    ],
  },
  {
    id: "p828",
    quote: "Show me a thoroughly satisfied person and I will show you a failure.",
    attribution: "Thomas Edison",
    theme: "Growth",
    difficulty: "expert",
    clueWords: [
      { hint: "Display", word: "SHOW" },
      { hint: "Completely, fully", word: "THOROUGHLY" },
      { hint: "Content, pleased", word: "SATISFIED" },
      { hint: "An individual", word: "PERSON" },
      { hint: "Lack of success", word: "FAILURE" },
    ],
  },
  {
    id: "p829",
    quote: "Restlessness is discontent and discontent is the first necessity of progress.",
    attribution: "Thomas Edison",
    theme: "Progress",
    difficulty: "expert",
    clueWords: [
      { hint: "Lack of calm", word: "RESTLESSNESS" },
      { hint: "Dissatisfaction", word: "DISCONTENT" },
      { hint: "Initial", word: "FIRST" },
      { hint: "An essential need", word: "NECESSITY" },
      { hint: "Forward motion", word: "PROGRESS" },
    ],
  },
  {
    id: "p830",
    quote: "When you have exhausted all possibilities, remember this: you have not.",
    attribution: "Thomas Edison",
    theme: "Persistence",
    difficulty: "expert",
    clueWords: [
      { hint: "Used up entirely", word: "EXHAUSTED" },
      { hint: "Each, every", word: "ALL" },
      { hint: "Capable possibilities", word: "POSSIBILITIES" },
      { hint: "Recall to mind", word: "REMEMBER" },
      { hint: "Possess", word: "HAVE" },
    ],
  },
];
