import type { PuzzleRaw } from "../puzzleData";

/**
 * Batch 1 — 200 new puzzles (IDs p031–p230).
 *  • p031–p070: 40 easy
 *  • p071–p130: 60 medium
 *  • p131–p190: 60 hard
 *  • p191–p230: 40 expert
 *
 * Sources lean on proverbs / public-domain wisdom, with a smattering of
 * well-attributed famous quotes. Each clue word is a token that actually
 * appears in its quote (after uppercasing).
 */
export const BATCH1: PuzzleRaw[] = [
  // -------------------- EASY (40) --------------------
  {
    id: "p031",
    quote: "Actions speak louder than words.",
    attribution: "Proverb",
    theme: "Action",
    difficulty: "easy",
    clueWords: [
      { hint: "Deeds and behaviors", word: "ACTIONS" },
      { hint: "Talk or utter", word: "SPEAK" },
      { hint: "Greater in volume", word: "LOUDER" },
      { hint: "Spoken units of language", word: "WORDS" },
    ],
  },
  {
    id: "p032",
    quote: "A penny saved is a penny earned.",
    attribution: "Benjamin Franklin",
    theme: "Thrift",
    difficulty: "easy",
    clueWords: [
      { hint: "A small unit of money", word: "PENNY" },
      { hint: "Set aside for later", word: "SAVED" },
      { hint: "Acquired through work", word: "EARNED" },
    ],
  },
  {
    id: "p033",
    quote: "Slow and steady wins the race.",
    attribution: "Aesop",
    theme: "Persistence",
    difficulty: "easy",
    clueWords: [
      { hint: "Not fast", word: "SLOW" },
      { hint: "Constant and even", word: "STEADY" },
      { hint: "Comes first in", word: "WINS" },
      { hint: "A speed contest", word: "RACE" },
    ],
  },
  {
    id: "p034",
    quote: "Time is money.",
    attribution: "Benjamin Franklin",
    theme: "Time",
    difficulty: "easy",
    clueWords: [
      { hint: "Hours and minutes", word: "TIME" },
      { hint: "Currency or wealth", word: "MONEY" },
    ],
  },
  {
    id: "p035",
    quote: "Better late than never.",
    attribution: "Proverb",
    theme: "Timing",
    difficulty: "easy",
    clueWords: [
      { hint: "Improved or preferable", word: "BETTER" },
      { hint: "Behind schedule", word: "LATE" },
      { hint: "At no time", word: "NEVER" },
    ],
  },
  {
    id: "p036",
    quote: "Where there is a will there is a way.",
    attribution: "Proverb",
    theme: "Determination",
    difficulty: "easy",
    clueWords: [
      { hint: "Strong intent or resolve", word: "WILL" },
      { hint: "A path or method", word: "WAY" },
      { hint: "At what location", word: "WHERE" },
    ],
  },
  {
    id: "p037",
    quote: "Practice makes perfect.",
    attribution: "Proverb",
    theme: "Mastery",
    difficulty: "easy",
    clueWords: [
      { hint: "Repeated training", word: "PRACTICE" },
      { hint: "Causes or produces", word: "MAKES" },
      { hint: "Without flaw", word: "PERFECT" },
    ],
  },
  {
    id: "p038",
    quote: "Knowledge is power.",
    attribution: "Francis Bacon",
    theme: "Wisdom",
    difficulty: "easy",
    clueWords: [
      { hint: "Information you know", word: "KNOWLEDGE" },
      { hint: "Strength or authority", word: "POWER" },
    ],
  },
  {
    id: "p039",
    quote: "Honesty is the best policy.",
    attribution: "Benjamin Franklin",
    theme: "Honesty",
    difficulty: "easy",
    clueWords: [
      { hint: "Truthfulness", word: "HONESTY" },
      { hint: "Top quality", word: "BEST" },
      { hint: "A guiding rule", word: "POLICY" },
    ],
  },
  {
    id: "p040",
    quote: "All that glitters is not gold.",
    attribution: "Proverb",
    theme: "Caution",
    difficulty: "easy",
    clueWords: [
      { hint: "Sparkles brightly", word: "GLITTERS" },
      { hint: "Precious yellow metal", word: "GOLD" },
      { hint: "Each and every", word: "ALL" },
    ],
  },
  {
    id: "p041",
    quote: "Birds of a feather flock together.",
    attribution: "Proverb",
    theme: "Friendship",
    difficulty: "easy",
    clueWords: [
      { hint: "Flying creatures", word: "BIRDS" },
      { hint: "A bird's plumage", word: "FEATHER" },
      { hint: "Group or gather as a herd", word: "FLOCK" },
      { hint: "Joined as one", word: "TOGETHER" },
    ],
  },
  {
    id: "p042",
    quote: "A friend in need is a friend indeed.",
    attribution: "Proverb",
    theme: "Friendship",
    difficulty: "easy",
    clueWords: [
      { hint: "A close companion", word: "FRIEND" },
      { hint: "Requires help", word: "NEED" },
      { hint: "Truly or in fact", word: "INDEED" },
    ],
  },
  {
    id: "p043",
    quote: "Look before you leap.",
    attribution: "Proverb",
    theme: "Prudence",
    difficulty: "easy",
    clueWords: [
      { hint: "Use your eyes", word: "LOOK" },
      { hint: "Earlier than", word: "BEFORE" },
      { hint: "Jump forward", word: "LEAP" },
    ],
  },
  {
    id: "p044",
    quote: "Beauty is in the eye of the beholder.",
    attribution: "Margaret Wolfe Hungerford",
    theme: "Perception",
    difficulty: "easy",
    clueWords: [
      { hint: "Aesthetic loveliness", word: "BEAUTY" },
      { hint: "Organ of sight", word: "EYE" },
      { hint: "One who looks", word: "BEHOLDER" },
    ],
  },
  {
    id: "p045",
    quote: "Every cloud has a silver lining.",
    attribution: "Proverb",
    theme: "Optimism",
    difficulty: "easy",
    clueWords: [
      { hint: "Each one without exception", word: "EVERY" },
      { hint: "Visible mass of vapor", word: "CLOUD" },
      { hint: "Bright greyish metal", word: "SILVER" },
      { hint: "Inner edge or layer", word: "LINING" },
    ],
  },
  {
    id: "p046",
    quote: "An apple a day keeps the doctor away.",
    attribution: "Proverb",
    theme: "Health",
    difficulty: "easy",
    clueWords: [
      { hint: "Round red or green fruit", word: "APPLE" },
      { hint: "Twenty-four hours", word: "DAY" },
      { hint: "Medical professional", word: "DOCTOR" },
      { hint: "At a distance", word: "AWAY" },
    ],
  },
  {
    id: "p047",
    quote: "Curiosity killed the cat.",
    attribution: "Proverb",
    theme: "Caution",
    difficulty: "easy",
    clueWords: [
      { hint: "Eagerness to know", word: "CURIOSITY" },
      { hint: "Caused the death of", word: "KILLED" },
      { hint: "Whiskered house pet", word: "CAT" },
    ],
  },
  {
    id: "p048",
    quote: "Easy come, easy go.",
    attribution: "Proverb",
    theme: "Acceptance",
    difficulty: "easy",
    clueWords: [
      { hint: "Without effort", word: "EASY" },
      { hint: "Arrive", word: "COME" },
      { hint: "Depart", word: "GO" },
    ],
  },
  {
    id: "p049",
    quote: "Haste makes waste.",
    attribution: "Proverb",
    theme: "Patience",
    difficulty: "easy",
    clueWords: [
      { hint: "Excessive hurry", word: "HASTE" },
      { hint: "Causes or creates", word: "MAKES" },
      { hint: "Squandered effort", word: "WASTE" },
    ],
  },
  {
    id: "p050",
    quote: "Out of sight, out of mind.",
    attribution: "Proverb",
    theme: "Memory",
    difficulty: "easy",
    clueWords: [
      { hint: "Power to see", word: "SIGHT" },
      { hint: "The thinking faculty", word: "MIND" },
      { hint: "Outside or away from", word: "OUT" },
    ],
  },
  {
    id: "p051",
    quote: "When in Rome, do as the Romans do.",
    attribution: "Saint Ambrose",
    theme: "Adaptability",
    difficulty: "easy",
    clueWords: [
      { hint: "Italian capital city", word: "ROME" },
      { hint: "Citizens of that city", word: "ROMANS" },
      { hint: "Perform an action", word: "DO" },
      { hint: "In the same manner", word: "AS" },
    ],
  },
  {
    id: "p052",
    quote: "Hope for the best, prepare for the worst.",
    attribution: "Proverb",
    theme: "Preparedness",
    difficulty: "easy",
    clueWords: [
      { hint: "Wish or expect", word: "HOPE" },
      { hint: "Top outcome", word: "BEST" },
      { hint: "Get ready", word: "PREPARE" },
      { hint: "The poorest outcome", word: "WORST" },
    ],
  },
  {
    id: "p053",
    quote: "A bird in the hand is worth two in the bush.",
    attribution: "Proverb",
    theme: "Pragmatism",
    difficulty: "easy",
    clueWords: [
      { hint: "Feathered creature", word: "BIRD" },
      { hint: "Body part with fingers", word: "HAND" },
      { hint: "A leafy shrub", word: "BUSH" },
      { hint: "One plus one", word: "TWO" },
      { hint: "Has the value of", word: "WORTH" },
    ],
  },
  {
    id: "p054",
    quote: "Do not judge a book by its cover.",
    attribution: "Proverb",
    theme: "Perception",
    difficulty: "easy",
    clueWords: [
      { hint: "Form an opinion of", word: "JUDGE" },
      { hint: "Bound pages to read", word: "BOOK" },
      { hint: "An outer wrap", word: "COVER" },
    ],
  },
  {
    id: "p055",
    quote: "Two heads are better than one.",
    attribution: "Proverb",
    theme: "Teamwork",
    difficulty: "easy",
    clueWords: [
      { hint: "A pair", word: "TWO" },
      { hint: "Body parts that think", word: "HEADS" },
      { hint: "More desirable", word: "BETTER" },
      { hint: "A single unit", word: "ONE" },
    ],
  },
  {
    id: "p056",
    quote: "Strike while the iron is hot.",
    attribution: "Proverb",
    theme: "Timing",
    difficulty: "easy",
    clueWords: [
      { hint: "Hit firmly", word: "STRIKE" },
      { hint: "A heated metal", word: "IRON" },
      { hint: "High temperature", word: "HOT" },
    ],
  },
  {
    id: "p057",
    quote: "Rome was not built in a day.",
    attribution: "Proverb",
    theme: "Patience",
    difficulty: "easy",
    clueWords: [
      { hint: "Italian capital city", word: "ROME" },
      { hint: "Constructed", word: "BUILT" },
      { hint: "A 24-hour period", word: "DAY" },
    ],
  },
  {
    id: "p058",
    quote: "The pen is mightier than the sword.",
    attribution: "Edward Bulwer-Lytton",
    theme: "Communication",
    difficulty: "easy",
    clueWords: [
      { hint: "Writing tool with ink", word: "PEN" },
      { hint: "Greater in power", word: "MIGHTIER" },
      { hint: "Bladed weapon", word: "SWORD" },
    ],
  },
  {
    id: "p059",
    quote: "A picture is worth a thousand words.",
    attribution: "Proverb",
    theme: "Communication",
    difficulty: "easy",
    clueWords: [
      { hint: "Visual image or photo", word: "PICTURE" },
      { hint: "Has the value of", word: "WORTH" },
      { hint: "Ten hundred", word: "THOUSAND" },
      { hint: "Spoken units", word: "WORDS" },
    ],
  },
  {
    id: "p060",
    quote: "Necessity is the mother of invention.",
    attribution: "Proverb",
    theme: "Creativity",
    difficulty: "easy",
    clueWords: [
      { hint: "An essential requirement", word: "NECESSITY" },
      { hint: "Female parent", word: "MOTHER" },
      { hint: "A new creation", word: "INVENTION" },
    ],
  },
  {
    id: "p061",
    quote: "Money does not grow on trees.",
    attribution: "Proverb",
    theme: "Thrift",
    difficulty: "easy",
    clueWords: [
      { hint: "Currency or wealth", word: "MONEY" },
      { hint: "Increase in size", word: "GROW" },
      { hint: "Tall woody plants", word: "TREES" },
    ],
  },
  {
    id: "p062",
    quote: "A watched pot never boils.",
    attribution: "Proverb",
    theme: "Patience",
    difficulty: "easy",
    clueWords: [
      { hint: "Closely observed", word: "WATCHED" },
      { hint: "Cooking vessel", word: "POT" },
      { hint: "At no time", word: "NEVER" },
      { hint: "Reaches a bubble", word: "BOILS" },
    ],
  },
  {
    id: "p063",
    quote: "Fortune favors the bold.",
    attribution: "Latin Proverb",
    theme: "Courage",
    difficulty: "easy",
    clueWords: [
      { hint: "Luck or destiny", word: "FORTUNE" },
      { hint: "Treats kindly", word: "FAVORS" },
      { hint: "Daring or brave", word: "BOLD" },
    ],
  },
  {
    id: "p064",
    quote: "Patience is a virtue.",
    attribution: "Proverb",
    theme: "Patience",
    difficulty: "easy",
    clueWords: [
      { hint: "Calm endurance", word: "PATIENCE" },
      { hint: "A moral excellence", word: "VIRTUE" },
    ],
  },
  {
    id: "p065",
    quote: "Silence is golden.",
    attribution: "Proverb",
    theme: "Mindfulness",
    difficulty: "easy",
    clueWords: [
      { hint: "Absence of sound", word: "SILENCE" },
      { hint: "Like precious metal", word: "GOLDEN" },
    ],
  },
  {
    id: "p066",
    quote: "Do not cry over spilt milk.",
    attribution: "Proverb",
    theme: "Acceptance",
    difficulty: "easy",
    clueWords: [
      { hint: "Shed tears", word: "CRY" },
      { hint: "Accidentally tipped over", word: "SPILT" },
      { hint: "White dairy drink", word: "MILK" },
    ],
  },
  {
    id: "p067",
    quote: "The early bird catches the worm.",
    attribution: "Proverb",
    theme: "Initiative",
    difficulty: "easy",
    clueWords: [
      { hint: "Before the usual hour", word: "EARLY" },
      { hint: "Feathered creature", word: "BIRD" },
      { hint: "Grabs hold of", word: "CATCHES" },
      { hint: "Soft soil dweller", word: "WORM" },
    ],
  },
  {
    id: "p068",
    quote: "Where there is smoke there is fire.",
    attribution: "Proverb",
    theme: "Suspicion",
    difficulty: "easy",
    clueWords: [
      { hint: "Hazy combustion vapor", word: "SMOKE" },
      { hint: "Burning flame", word: "FIRE" },
      { hint: "At which location", word: "WHERE" },
    ],
  },
  {
    id: "p069",
    quote: "Many hands make light work.",
    attribution: "Proverb",
    theme: "Teamwork",
    difficulty: "easy",
    clueWords: [
      { hint: "A great number", word: "MANY" },
      { hint: "Body parts with fingers", word: "HANDS" },
      { hint: "Easy or not heavy", word: "LIGHT" },
      { hint: "Effort or labor", word: "WORK" },
    ],
  },
  {
    id: "p070",
    quote: "A leopard cannot change its spots.",
    attribution: "Proverb",
    theme: "Identity",
    difficulty: "easy",
    clueWords: [
      { hint: "Spotted big cat", word: "LEOPARD" },
      { hint: "Make different", word: "CHANGE" },
      { hint: "Round dark marks", word: "SPOTS" },
    ],
  },

  // -------------------- MEDIUM (60) --------------------
  {
    id: "p071",
    quote: "An eye for an eye makes the whole world blind.",
    attribution: "Mahatma Gandhi",
    theme: "Justice",
    difficulty: "medium",
    clueWords: [
      { hint: "Organ of sight", word: "EYE" },
      { hint: "Causes or produces", word: "MAKES" },
      { hint: "Entire or complete", word: "WHOLE" },
      { hint: "The earth and its peoples", word: "WORLD" },
      { hint: "Without vision", word: "BLIND" },
    ],
  },
  {
    id: "p072",
    quote: "Be the change that you wish to see in the world.",
    attribution: "Mahatma Gandhi",
    theme: "Action",
    difficulty: "medium",
    clueWords: [
      { hint: "Transformation", word: "CHANGE" },
      { hint: "Want or desire", word: "WISH" },
      { hint: "Observe with the eyes", word: "SEE" },
      { hint: "Planet earth", word: "WORLD" },
    ],
  },
  {
    id: "p073",
    quote: "If you want to go fast, go alone. If you want to go far, go together.",
    attribution: "African Proverb",
    theme: "Teamwork",
    difficulty: "medium",
    clueWords: [
      { hint: "Quickly", word: "FAST" },
      { hint: "By oneself", word: "ALONE" },
      { hint: "A long distance", word: "FAR" },
      { hint: "With others", word: "TOGETHER" },
      { hint: "Desire or wish", word: "WANT" },
    ],
  },
  {
    id: "p074",
    quote: "He who has a why to live can bear almost any how.",
    attribution: "Friedrich Nietzsche",
    theme: "Purpose",
    difficulty: "medium",
    clueWords: [
      { hint: "Reason or cause", word: "WHY" },
      { hint: "To exist", word: "LIVE" },
      { hint: "Endure or carry", word: "BEAR" },
      { hint: "Nearly", word: "ALMOST" },
      { hint: "In what manner", word: "HOW" },
    ],
  },
  {
    id: "p075",
    quote: "Whatever you are, be a good one.",
    attribution: "Abraham Lincoln",
    theme: "Excellence",
    difficulty: "medium",
    clueWords: [
      { hint: "Anything that", word: "WHATEVER" },
      { hint: "High quality or kind", word: "GOOD" },
      { hint: "A single unit", word: "ONE" },
      { hint: "Exist or take form", word: "BE" },
    ],
  },
  {
    id: "p076",
    quote: "Do unto others as you would have them do unto you.",
    attribution: "The Golden Rule",
    theme: "Ethics",
    difficulty: "medium",
    clueWords: [
      { hint: "Other people", word: "OTHERS" },
      { hint: "Act or perform", word: "DO" },
      { hint: "Toward (archaic)", word: "UNTO" },
      { hint: "Them, those", word: "THEM" },
    ],
  },
  {
    id: "p077",
    quote: "We are what we repeatedly do.",
    attribution: "Will Durant",
    theme: "Habit",
    difficulty: "medium",
    clueWords: [
      { hint: "Again and again", word: "REPEATEDLY" },
      { hint: "Perform or act", word: "DO" },
      { hint: "First-person plural", word: "WE" },
      { hint: "Ourselves, multiple", word: "ARE" },
    ],
  },
  {
    id: "p078",
    quote: "Knowing yourself is the beginning of all wisdom.",
    attribution: "Aristotle",
    theme: "Self-Knowledge",
    difficulty: "medium",
    clueWords: [
      { hint: "Awareness of facts", word: "KNOWING" },
      { hint: "Your own person", word: "YOURSELF" },
      { hint: "The start", word: "BEGINNING" },
      { hint: "Deep understanding", word: "WISDOM" },
    ],
  },
  {
    id: "p079",
    quote: "Whether you think you can or think you cannot, you are right.",
    attribution: "Henry Ford",
    theme: "Mindset",
    difficulty: "medium",
    clueWords: [
      { hint: "Use the mind", word: "THINK" },
      { hint: "Are able to", word: "CAN" },
      { hint: "Are not able", word: "CANNOT" },
      { hint: "Correct, accurate", word: "RIGHT" },
    ],
  },
  {
    id: "p080",
    quote: "Tough times never last, but tough people do.",
    attribution: "Robert Schuller",
    theme: "Resilience",
    difficulty: "medium",
    clueWords: [
      { hint: "Hard or difficult", word: "TOUGH" },
      { hint: "Periods or moments", word: "TIMES" },
      { hint: "At no time", word: "NEVER" },
      { hint: "Continue, endure", word: "LAST" },
      { hint: "Human beings", word: "PEOPLE" },
    ],
  },
  {
    id: "p081",
    quote: "Some people want it to happen, some wish it would happen, others make it happen.",
    attribution: "Michael Jordan",
    theme: "Initiative",
    difficulty: "medium",
    clueWords: [
      { hint: "A few", word: "SOME" },
      { hint: "Take place", word: "HAPPEN" },
      { hint: "Want longingly", word: "WISH" },
      { hint: "Different ones", word: "OTHERS" },
      { hint: "Cause to occur", word: "MAKE" },
    ],
  },
  {
    id: "p082",
    quote: "Try to be a rainbow in someone's cloud.",
    attribution: "Maya Angelou",
    theme: "Kindness",
    difficulty: "medium",
    clueWords: [
      { hint: "Attempt", word: "TRY" },
      { hint: "Arc of colors after rain", word: "RAINBOW" },
      { hint: "A gloomy gathering of vapor", word: "CLOUD" },
      { hint: "An unspecified person", word: "SOMEONE" },
    ],
  },
  {
    id: "p083",
    quote: "It is during our darkest moments that we must focus to see the light.",
    attribution: "Aristotle Onassis",
    theme: "Optimism",
    difficulty: "medium",
    clueWords: [
      { hint: "Most without illumination", word: "DARKEST" },
      { hint: "Brief instants", word: "MOMENTS" },
      { hint: "Concentrate attention", word: "FOCUS" },
      { hint: "Illumination", word: "LIGHT" },
      { hint: "Perceive with the eyes", word: "SEE" },
    ],
  },
  {
    id: "p084",
    quote: "It is never too late to be what you might have been.",
    attribution: "George Eliot",
    theme: "Possibility",
    difficulty: "medium",
    clueWords: [
      { hint: "At no time", word: "NEVER" },
      { hint: "After the proper time", word: "LATE" },
      { hint: "In the past", word: "BEEN" },
      { hint: "Excessively", word: "TOO" },
    ],
  },
  {
    id: "p085",
    quote: "Quality is not an act, it is a habit.",
    attribution: "Will Durant",
    theme: "Excellence",
    difficulty: "medium",
    clueWords: [
      { hint: "Standard of excellence", word: "QUALITY" },
      { hint: "A deed or performance", word: "ACT" },
      { hint: "A repeated behavior", word: "HABIT" },
    ],
  },
  {
    id: "p086",
    quote: "The way to get started is to quit talking and begin doing.",
    attribution: "Walt Disney",
    theme: "Action",
    difficulty: "medium",
    clueWords: [
      { hint: "A path or method", word: "WAY" },
      { hint: "Initiate", word: "STARTED" },
      { hint: "Stop or leave", word: "QUIT" },
      { hint: "Speaking", word: "TALKING" },
      { hint: "Start", word: "BEGIN" },
      { hint: "Performing", word: "DOING" },
    ],
  },
  {
    id: "p087",
    quote: "Whatever the mind can conceive and believe, it can achieve.",
    attribution: "Napoleon Hill",
    theme: "Mindset",
    difficulty: "medium",
    clueWords: [
      { hint: "The thinking faculty", word: "MIND" },
      { hint: "Form an idea of", word: "CONCEIVE" },
      { hint: "Have faith in", word: "BELIEVE" },
      { hint: "Successfully complete", word: "ACHIEVE" },
    ],
  },
  {
    id: "p088",
    quote: "Do what you can, with what you have, where you are.",
    attribution: "Theodore Roosevelt",
    theme: "Resourcefulness",
    difficulty: "medium",
    clueWords: [
      { hint: "Are able to", word: "CAN" },
      { hint: "Possess", word: "HAVE" },
      { hint: "At which place", word: "WHERE" },
      { hint: "Perform", word: "DO" },
    ],
  },
  {
    id: "p089",
    quote: "The best way to predict the future is to create it.",
    attribution: "Peter Drucker",
    theme: "Action",
    difficulty: "medium",
    clueWords: [
      { hint: "Top in quality", word: "BEST" },
      { hint: "Foretell", word: "PREDICT" },
      { hint: "Time yet to come", word: "FUTURE" },
      { hint: "Bring into existence", word: "CREATE" },
    ],
  },
  {
    id: "p090",
    quote: "Difficult roads often lead to beautiful destinations.",
    attribution: "Anonymous",
    theme: "Hope",
    difficulty: "medium",
    clueWords: [
      { hint: "Hard or challenging", word: "DIFFICULT" },
      { hint: "Paved paths", word: "ROADS" },
      { hint: "Many times", word: "OFTEN" },
      { hint: "Aesthetically pleasing", word: "BEAUTIFUL" },
      { hint: "Travel endpoints", word: "DESTINATIONS" },
    ],
  },
  {
    id: "p091",
    quote: "Do not let yesterday take up too much of today.",
    attribution: "Will Rogers",
    theme: "Mindfulness",
    difficulty: "medium",
    clueWords: [
      { hint: "The day before", word: "YESTERDAY" },
      { hint: "The current day", word: "TODAY" },
      { hint: "Permit or allow", word: "LET" },
      { hint: "Excessively much", word: "TOO" },
    ],
  },
  {
    id: "p092",
    quote: "Action is the foundational key to all success.",
    attribution: "Pablo Picasso",
    theme: "Action",
    difficulty: "medium",
    clueWords: [
      { hint: "An act or deed", word: "ACTION" },
      { hint: "Base or core", word: "FOUNDATIONAL" },
      { hint: "An opener", word: "KEY" },
      { hint: "Achievement", word: "SUCCESS" },
    ],
  },
  {
    id: "p093",
    quote: "Do not watch the clock; do what it does. Keep going.",
    attribution: "Sam Levenson",
    theme: "Persistence",
    difficulty: "medium",
    clueWords: [
      { hint: "Observe carefully", word: "WATCH" },
      { hint: "Time-keeping device", word: "CLOCK" },
      { hint: "Continue without stopping", word: "KEEP" },
      { hint: "Moving forward", word: "GOING" },
    ],
  },
  {
    id: "p094",
    quote: "Either I will find a way, or I will make one.",
    attribution: "Hannibal",
    theme: "Determination",
    difficulty: "medium",
    clueWords: [
      { hint: "Discover or locate", word: "FIND" },
      { hint: "A path or method", word: "WAY" },
      { hint: "Construct or create", word: "MAKE" },
      { hint: "One or the other", word: "EITHER" },
    ],
  },
  {
    id: "p095",
    quote: "Kindness is a language which the deaf can hear and the blind can see.",
    attribution: "Mark Twain",
    theme: "Kindness",
    difficulty: "medium",
    clueWords: [
      { hint: "Quality of being kind", word: "KINDNESS" },
      { hint: "System of communication", word: "LANGUAGE" },
      { hint: "Cannot hear", word: "DEAF" },
      { hint: "Cannot see", word: "BLIND" },
      { hint: "Receive sound", word: "HEAR" },
    ],
  },
  {
    id: "p096",
    quote: "Doubt kills more dreams than failure ever will.",
    attribution: "Suzy Kassem",
    theme: "Confidence",
    difficulty: "medium",
    clueWords: [
      { hint: "Lack of certainty", word: "DOUBT" },
      { hint: "Ends the life of", word: "KILLS" },
      { hint: "Hopes or aspirations", word: "DREAMS" },
      { hint: "Lack of success", word: "FAILURE" },
      { hint: "At any time", word: "EVER" },
    ],
  },
  {
    id: "p097",
    quote: "Happiness depends upon ourselves.",
    attribution: "Aristotle",
    theme: "Happiness",
    difficulty: "medium",
    clueWords: [
      { hint: "Joyful well-being", word: "HAPPINESS" },
      { hint: "Relies on", word: "DEPENDS" },
      { hint: "Our own selves", word: "OURSELVES" },
      { hint: "On top of", word: "UPON" },
    ],
  },
  {
    id: "p098",
    quote: "Stay hungry, stay foolish.",
    attribution: "Steve Jobs",
    theme: "Curiosity",
    difficulty: "medium",
    clueWords: [
      { hint: "Remain", word: "STAY" },
      { hint: "Wanting food", word: "HUNGRY" },
      { hint: "Lacking sense", word: "FOOLISH" },
    ],
  },
  {
    id: "p099",
    quote: "Live as if you were to die tomorrow. Learn as if you were to live forever.",
    attribution: "Mahatma Gandhi",
    theme: "Wisdom",
    difficulty: "medium",
    clueWords: [
      { hint: "Be alive", word: "LIVE" },
      { hint: "Acquire knowledge", word: "LEARN" },
      { hint: "Cease living", word: "DIE" },
      { hint: "The day after today", word: "TOMORROW" },
      { hint: "Eternally", word: "FOREVER" },
    ],
  },
  {
    id: "p100",
    quote: "Do not be afraid to give up the good to go for the great.",
    attribution: "John D. Rockefeller",
    theme: "Ambition",
    difficulty: "medium",
    clueWords: [
      { hint: "Fearful", word: "AFRAID" },
      { hint: "Surrender or hand over", word: "GIVE" },
      { hint: "Acceptable, fine", word: "GOOD" },
      { hint: "Outstanding, superior", word: "GREAT" },
      { hint: "Move toward", word: "GO" },
    ],
  },
  {
    id: "p101",
    quote: "Life is really simple, but we insist on making it complicated.",
    attribution: "Confucius",
    theme: "Simplicity",
    difficulty: "medium",
    clueWords: [
      { hint: "Existence", word: "LIFE" },
      { hint: "Truly, in fact", word: "REALLY" },
      { hint: "Easy, uncomplicated", word: "SIMPLE" },
      { hint: "Demand persistently", word: "INSIST" },
      { hint: "Made complex", word: "COMPLICATED" },
    ],
  },
  {
    id: "p102",
    quote: "Time you enjoy wasting is not wasted time.",
    attribution: "Marthe Troly-Curtin",
    theme: "Joy",
    difficulty: "medium",
    clueWords: [
      { hint: "Hours and minutes", word: "TIME" },
      { hint: "Take pleasure in", word: "ENJOY" },
      { hint: "Squandering", word: "WASTING" },
      { hint: "Squandered", word: "WASTED" },
    ],
  },
  {
    id: "p103",
    quote: "The only impossible journey is the one you never begin.",
    attribution: "Tony Robbins",
    theme: "Initiative",
    difficulty: "medium",
    clueWords: [
      { hint: "Cannot be done", word: "IMPOSSIBLE" },
      { hint: "A long trip", word: "JOURNEY" },
      { hint: "Start", word: "BEGIN" },
      { hint: "Sole, single", word: "ONLY" },
      { hint: "At no time", word: "NEVER" },
    ],
  },
  {
    id: "p104",
    quote: "Try to leave this world a little better than you found it.",
    attribution: "Robert Baden-Powell",
    theme: "Legacy",
    difficulty: "medium",
    clueWords: [
      { hint: "Make an attempt", word: "TRY" },
      { hint: "Depart from", word: "LEAVE" },
      { hint: "Planet earth", word: "WORLD" },
      { hint: "Improved", word: "BETTER" },
      { hint: "Discovered", word: "FOUND" },
    ],
  },
  {
    id: "p105",
    quote: "Reading is to the mind what exercise is to the body.",
    attribution: "Joseph Addison",
    theme: "Learning",
    difficulty: "medium",
    clueWords: [
      { hint: "Going through written words", word: "READING" },
      { hint: "Thinking faculty", word: "MIND" },
      { hint: "Physical activity", word: "EXERCISE" },
      { hint: "The physical form", word: "BODY" },
    ],
  },
  {
    id: "p106",
    quote: "We do not see things as they are, we see them as we are.",
    attribution: "Anais Nin",
    theme: "Perception",
    difficulty: "medium",
    clueWords: [
      { hint: "Perceive with the eyes", word: "SEE" },
      { hint: "Objects or matters", word: "THINGS" },
      { hint: "They, multiple", word: "THEM" },
      { hint: "First-person plural", word: "WE" },
    ],
  },
  {
    id: "p107",
    quote: "Talk is cheap. Show me the code.",
    attribution: "Linus Torvalds",
    theme: "Action",
    difficulty: "medium",
    clueWords: [
      { hint: "Speech or words", word: "TALK" },
      { hint: "Inexpensive", word: "CHEAP" },
      { hint: "Display or reveal", word: "SHOW" },
      { hint: "Programming text", word: "CODE" },
    ],
  },
  {
    id: "p108",
    quote: "When you reach the end of your rope, tie a knot and hang on.",
    attribution: "Franklin D. Roosevelt",
    theme: "Resilience",
    difficulty: "medium",
    clueWords: [
      { hint: "Get to", word: "REACH" },
      { hint: "The final point", word: "END" },
      { hint: "A length of cord", word: "ROPE" },
      { hint: "Form a knot", word: "TIE" },
      { hint: "Hold tight", word: "HANG" },
    ],
  },
  {
    id: "p109",
    quote: "Fall seven times, stand up eight.",
    attribution: "Japanese Proverb",
    theme: "Resilience",
    difficulty: "medium",
    clueWords: [
      { hint: "Drop down", word: "FALL" },
      { hint: "One more than six", word: "SEVEN" },
      { hint: "Get on your feet", word: "STAND" },
      { hint: "One more than seven", word: "EIGHT" },
    ],
  },
  {
    id: "p110",
    quote: "If you cannot fly, then run. If you cannot run, then walk.",
    attribution: "Martin Luther King Jr.",
    theme: "Persistence",
    difficulty: "medium",
    clueWords: [
      { hint: "Move through air", word: "FLY" },
      { hint: "Move on foot quickly", word: "RUN" },
      { hint: "Move on foot slowly", word: "WALK" },
      { hint: "After that", word: "THEN" },
    ],
  },
  {
    id: "p111",
    quote: "Smile, breathe, and go slowly.",
    attribution: "Thich Nhat Hanh",
    theme: "Mindfulness",
    difficulty: "medium",
    clueWords: [
      { hint: "Show a happy face", word: "SMILE" },
      { hint: "Inhale and exhale", word: "BREATHE" },
      { hint: "Move along", word: "GO" },
      { hint: "Without haste", word: "SLOWLY" },
    ],
  },
  {
    id: "p112",
    quote: "Yesterday is history, tomorrow is a mystery, today is a gift.",
    attribution: "Eleanor Roosevelt",
    theme: "Mindfulness",
    difficulty: "medium",
    clueWords: [
      { hint: "The day before", word: "YESTERDAY" },
      { hint: "The day after today", word: "TOMORROW" },
      { hint: "The current day", word: "TODAY" },
      { hint: "An unknown thing", word: "MYSTERY" },
      { hint: "A present", word: "GIFT" },
    ],
  },
  {
    id: "p113",
    quote: "Adventure is worthwhile in itself.",
    attribution: "Amelia Earhart",
    theme: "Adventure",
    difficulty: "medium",
    clueWords: [
      { hint: "An exciting experience", word: "ADVENTURE" },
      { hint: "Worth the effort", word: "WORTHWHILE" },
      { hint: "Itself, on its own", word: "ITSELF" },
    ],
  },
  {
    id: "p114",
    quote: "What we think we become.",
    attribution: "Buddha",
    theme: "Mindset",
    difficulty: "medium",
    clueWords: [
      { hint: "Use the mind", word: "THINK" },
      { hint: "Turn into", word: "BECOME" },
      { hint: "First-person plural", word: "WE" },
    ],
  },
  {
    id: "p115",
    quote: "Believe in yourself and all that you are.",
    attribution: "Christian D. Larson",
    theme: "Confidence",
    difficulty: "medium",
    clueWords: [
      { hint: "Have faith in", word: "BELIEVE" },
      { hint: "Your own person", word: "YOURSELF" },
      { hint: "Each thing", word: "ALL" },
    ],
  },
  {
    id: "p116",
    quote: "Wisdom comes from experience.",
    attribution: "Proverb",
    theme: "Wisdom",
    difficulty: "medium",
    clueWords: [
      { hint: "Deep insight", word: "WISDOM" },
      { hint: "Arrives or originates", word: "COMES" },
      { hint: "Lived or observed events", word: "EXPERIENCE" },
    ],
  },
  {
    id: "p117",
    quote: "Hardships often prepare ordinary people for an extraordinary destiny.",
    attribution: "C.S. Lewis",
    theme: "Adversity",
    difficulty: "medium",
    clueWords: [
      { hint: "Difficulties or struggles", word: "HARDSHIPS" },
      { hint: "Many times", word: "OFTEN" },
      { hint: "Make ready", word: "PREPARE" },
      { hint: "Common, normal", word: "ORDINARY" },
      { hint: "Beyond ordinary", word: "EXTRAORDINARY" },
      { hint: "Predetermined fate", word: "DESTINY" },
    ],
  },
  {
    id: "p118",
    quote: "When everything seems against you, remember that the airplane takes off against the wind.",
    attribution: "Henry Ford",
    theme: "Resilience",
    difficulty: "medium",
    clueWords: [
      { hint: "Looks like", word: "SEEMS" },
      { hint: "Recall to mind", word: "REMEMBER" },
      { hint: "Flying machine", word: "AIRPLANE" },
      { hint: "Moving air", word: "WIND" },
      { hint: "In opposition to", word: "AGAINST" },
    ],
  },
  {
    id: "p119",
    quote: "Always remember that you are absolutely unique. Just like everyone else.",
    attribution: "Margaret Mead",
    theme: "Identity",
    difficulty: "medium",
    clueWords: [
      { hint: "Recall to mind", word: "REMEMBER" },
      { hint: "Wholly, entirely", word: "ABSOLUTELY" },
      { hint: "One of a kind", word: "UNIQUE" },
      { hint: "Each person", word: "EVERYONE" },
      { hint: "At all times", word: "ALWAYS" },
    ],
  },
  {
    id: "p120",
    quote: "Do not pray for an easy life, pray for the strength to endure a difficult one.",
    attribution: "Bruce Lee",
    theme: "Strength",
    difficulty: "medium",
    clueWords: [
      { hint: "Speak to a higher power", word: "PRAY" },
      { hint: "Without difficulty", word: "EASY" },
      { hint: "Existence", word: "LIFE" },
      { hint: "Power or fortitude", word: "STRENGTH" },
      { hint: "Persist through", word: "ENDURE" },
      { hint: "Hard or challenging", word: "DIFFICULT" },
    ],
  },
  {
    id: "p121",
    quote: "Do not count the days, make the days count.",
    attribution: "Muhammad Ali",
    theme: "Mindfulness",
    difficulty: "medium",
    clueWords: [
      { hint: "Tally up", word: "COUNT" },
      { hint: "24-hour periods", word: "DAYS" },
      { hint: "Cause to matter", word: "MAKE" },
    ],
  },
  {
    id: "p122",
    quote: "The man who does not read has no advantage over the man who cannot read.",
    attribution: "Mark Twain",
    theme: "Learning",
    difficulty: "medium",
    clueWords: [
      { hint: "Adult human", word: "MAN" },
      { hint: "Go through written text", word: "READ" },
      { hint: "Beneficial edge", word: "ADVANTAGE" },
      { hint: "Above or beyond", word: "OVER" },
      { hint: "Is not able", word: "CANNOT" },
    ],
  },
  {
    id: "p123",
    quote: "Change your thoughts and you change your world.",
    attribution: "Norman Vincent Peale",
    theme: "Mindset",
    difficulty: "medium",
    clueWords: [
      { hint: "Alter or modify", word: "CHANGE" },
      { hint: "Mental ideas", word: "THOUGHTS" },
      { hint: "Your reality", word: "WORLD" },
      { hint: "Belonging to you", word: "YOUR" },
    ],
  },
  {
    id: "p124",
    quote: "Without music, life would be a mistake.",
    attribution: "Friedrich Nietzsche",
    theme: "Joy",
    difficulty: "medium",
    clueWords: [
      { hint: "Lacking, devoid of", word: "WITHOUT" },
      { hint: "Organized sound", word: "MUSIC" },
      { hint: "Existence", word: "LIFE" },
      { hint: "An error", word: "MISTAKE" },
    ],
  },
  {
    id: "p125",
    quote: "Be yourself; everyone else is taken.",
    attribution: "Oscar Wilde",
    theme: "Identity",
    difficulty: "medium",
    clueWords: [
      { hint: "Your own person", word: "YOURSELF" },
      { hint: "Each person", word: "EVERYONE" },
      { hint: "Other than", word: "ELSE" },
      { hint: "Already claimed", word: "TAKEN" },
    ],
  },
  {
    id: "p126",
    quote: "Whatever good things we build end up building us.",
    attribution: "Jim Rohn",
    theme: "Growth",
    difficulty: "medium",
    clueWords: [
      { hint: "Anything that", word: "WHATEVER" },
      { hint: "Construct", word: "BUILD" },
      { hint: "Constructing", word: "BUILDING" },
      { hint: "Beneficial, fine", word: "GOOD" },
      { hint: "Items or matters", word: "THINGS" },
    ],
  },
  {
    id: "p127",
    quote: "The only person you should try to be better than is the person you were yesterday.",
    attribution: "Anonymous",
    theme: "Growth",
    difficulty: "medium",
    clueWords: [
      { hint: "An individual", word: "PERSON" },
      { hint: "Make an attempt", word: "TRY" },
      { hint: "Improved upon", word: "BETTER" },
      { hint: "The day before", word: "YESTERDAY" },
      { hint: "Sole, single", word: "ONLY" },
    ],
  },
  {
    id: "p128",
    quote: "Doubt is the origin of wisdom.",
    attribution: "Rene Descartes",
    theme: "Wisdom",
    difficulty: "medium",
    clueWords: [
      { hint: "Lack of certainty", word: "DOUBT" },
      { hint: "Source or beginning", word: "ORIGIN" },
      { hint: "Deep insight", word: "WISDOM" },
    ],
  },
  {
    id: "p129",
    quote: "Knowledge speaks, but wisdom listens.",
    attribution: "Jimi Hendrix",
    theme: "Wisdom",
    difficulty: "medium",
    clueWords: [
      { hint: "What you know", word: "KNOWLEDGE" },
      { hint: "Talks", word: "SPEAKS" },
      { hint: "Deep insight", word: "WISDOM" },
      { hint: "Pays attention", word: "LISTENS" },
    ],
  },
  {
    id: "p130",
    quote: "The journey of a thousand miles begins beneath your feet.",
    attribution: "Lao Tzu",
    theme: "Beginnings",
    difficulty: "medium",
    clueWords: [
      { hint: "A long voyage", word: "JOURNEY" },
      { hint: "Ten hundreds", word: "THOUSAND" },
      { hint: "Distance units", word: "MILES" },
      { hint: "Starts", word: "BEGINS" },
      { hint: "Body parts you stand on", word: "FEET" },
      { hint: "Underneath", word: "BENEATH" },
    ],
  },

  // -------------------- HARD (60) --------------------
  {
    id: "p131",
    quote: "We must accept finite disappointment, but never lose infinite hope.",
    attribution: "Martin Luther King Jr.",
    theme: "Hope",
    difficulty: "hard",
    clueWords: [
      { hint: "Receive willingly", word: "ACCEPT" },
      { hint: "Limited or bounded", word: "FINITE" },
      { hint: "Frustration of expectations", word: "DISAPPOINTMENT" },
      { hint: "Boundless or endless", word: "INFINITE" },
      { hint: "Wish, expect", word: "HOPE" },
    ],
  },
  {
    id: "p132",
    quote: "Darkness cannot drive out darkness; only light can do that.",
    attribution: "Martin Luther King Jr.",
    theme: "Compassion",
    difficulty: "hard",
    clueWords: [
      { hint: "Absence of light", word: "DARKNESS" },
      { hint: "Push or steer", word: "DRIVE" },
      { hint: "Illumination", word: "LIGHT" },
      { hint: "Sole, exclusive", word: "ONLY" },
    ],
  },
  {
    id: "p133",
    quote: "The supreme art of war is to subdue the enemy without fighting.",
    attribution: "Sun Tzu",
    theme: "Strategy",
    difficulty: "hard",
    clueWords: [
      { hint: "Highest, ultimate", word: "SUPREME" },
      { hint: "Skill or craft", word: "ART" },
      { hint: "Armed conflict", word: "WAR" },
      { hint: "Bring under control", word: "SUBDUE" },
      { hint: "An adversary", word: "ENEMY" },
      { hint: "Combating", word: "FIGHTING" },
    ],
  },
  {
    id: "p134",
    quote: "If you know the enemy and know yourself, you need not fear the result of a hundred battles.",
    attribution: "Sun Tzu",
    theme: "Strategy",
    difficulty: "hard",
    clueWords: [
      { hint: "Be aware of", word: "KNOW" },
      { hint: "An adversary", word: "ENEMY" },
      { hint: "Be afraid of", word: "FEAR" },
      { hint: "Outcome", word: "RESULT" },
      { hint: "Ten times ten", word: "HUNDRED" },
      { hint: "Combats or fights", word: "BATTLES" },
    ],
  },
  {
    id: "p135",
    quote: "All warfare is based on deception.",
    attribution: "Sun Tzu",
    theme: "Strategy",
    difficulty: "hard",
    clueWords: [
      { hint: "Each, every", word: "ALL" },
      { hint: "Conduct of war", word: "WARFARE" },
      { hint: "Founded upon", word: "BASED" },
      { hint: "Misleading trickery", word: "DECEPTION" },
    ],
  },
  {
    id: "p136",
    quote: "Opportunities multiply as they are seized.",
    attribution: "Sun Tzu",
    theme: "Initiative",
    difficulty: "hard",
    clueWords: [
      { hint: "Chances or openings", word: "OPPORTUNITIES" },
      { hint: "Increase in number", word: "MULTIPLY" },
      { hint: "Grabbed and acted upon", word: "SEIZED" },
    ],
  },
  {
    id: "p137",
    quote: "Knowing others is intelligence; knowing yourself is true wisdom.",
    attribution: "Lao Tzu",
    theme: "Self-Knowledge",
    difficulty: "hard",
    clueWords: [
      { hint: "Being aware of", word: "KNOWING" },
      { hint: "Other people", word: "OTHERS" },
      { hint: "Mental capability", word: "INTELLIGENCE" },
      { hint: "Your own person", word: "YOURSELF" },
      { hint: "Real, genuine", word: "TRUE" },
      { hint: "Deep insight", word: "WISDOM" },
    ],
  },
  {
    id: "p138",
    quote: "When you are content to be simply yourself, everybody will respect you.",
    attribution: "Lao Tzu",
    theme: "Authenticity",
    difficulty: "hard",
    clueWords: [
      { hint: "Satisfied", word: "CONTENT" },
      { hint: "Plainly, just", word: "SIMPLY" },
      { hint: "Your own person", word: "YOURSELF" },
      { hint: "Each person", word: "EVERYBODY" },
      { hint: "Hold in esteem", word: "RESPECT" },
    ],
  },
  {
    id: "p139",
    quote: "He who knows others is wise; he who knows himself is enlightened.",
    attribution: "Lao Tzu",
    theme: "Self-Knowledge",
    difficulty: "hard",
    clueWords: [
      { hint: "Is aware of", word: "KNOWS" },
      { hint: "Other people", word: "OTHERS" },
      { hint: "Sage or learned", word: "WISE" },
      { hint: "He as object", word: "HIMSELF" },
      { hint: "Spiritually awakened", word: "ENLIGHTENED" },
    ],
  },
  {
    id: "p140",
    quote: "We suffer more often in imagination than in reality.",
    attribution: "Seneca",
    theme: "Mindset",
    difficulty: "hard",
    clueWords: [
      { hint: "Endure pain", word: "SUFFER" },
      { hint: "Frequently", word: "OFTEN" },
      { hint: "Mental imagery", word: "IMAGINATION" },
      { hint: "What is real", word: "REALITY" },
    ],
  },
  {
    id: "p141",
    quote: "It is not the man who has too little, but the man who craves more, that is poor.",
    attribution: "Seneca",
    theme: "Contentment",
    difficulty: "hard",
    clueWords: [
      { hint: "Adult male", word: "MAN" },
      { hint: "Possesses", word: "HAS" },
      { hint: "Excessively", word: "TOO" },
      { hint: "A small amount", word: "LITTLE" },
      { hint: "Strongly desires", word: "CRAVES" },
      { hint: "Lacking wealth", word: "POOR" },
    ],
  },
  {
    id: "p142",
    quote: "While we wait for life, life passes.",
    attribution: "Seneca",
    theme: "Mindfulness",
    difficulty: "hard",
    clueWords: [
      { hint: "During the time that", word: "WHILE" },
      { hint: "Stay in expectation", word: "WAIT" },
      { hint: "Existence", word: "LIFE" },
      { hint: "Goes by", word: "PASSES" },
    ],
  },
  {
    id: "p143",
    quote: "Waste no more time arguing about what a good man should be. Be one.",
    attribution: "Marcus Aurelius",
    theme: "Action",
    difficulty: "hard",
    clueWords: [
      { hint: "Squander", word: "WASTE" },
      { hint: "Quarreling verbally", word: "ARGUING" },
      { hint: "Fine in quality", word: "GOOD" },
      { hint: "Adult male", word: "MAN" },
      { hint: "Single unit", word: "ONE" },
    ],
  },
  {
    id: "p144",
    quote: "The happiness of your life depends upon the quality of your thoughts.",
    attribution: "Marcus Aurelius",
    theme: "Mindset",
    difficulty: "hard",
    clueWords: [
      { hint: "Joyful state", word: "HAPPINESS" },
      { hint: "Existence", word: "LIFE" },
      { hint: "Relies on", word: "DEPENDS" },
      { hint: "Standard of excellence", word: "QUALITY" },
      { hint: "Mental ideas", word: "THOUGHTS" },
    ],
  },
  {
    id: "p145",
    quote: "You have power over your mind, not outside events.",
    attribution: "Marcus Aurelius",
    theme: "Self-Control",
    difficulty: "hard",
    clueWords: [
      { hint: "Possess", word: "HAVE" },
      { hint: "Control or might", word: "POWER" },
      { hint: "Thinking faculty", word: "MIND" },
      { hint: "Beyond, external", word: "OUTSIDE" },
      { hint: "Occurrences", word: "EVENTS" },
    ],
  },
  {
    id: "p146",
    quote: "When you arise in the morning, think of what a precious privilege it is to be alive.",
    attribution: "Marcus Aurelius",
    theme: "Gratitude",
    difficulty: "hard",
    clueWords: [
      { hint: "Get up", word: "ARISE" },
      { hint: "Early part of the day", word: "MORNING" },
      { hint: "Reflect on", word: "THINK" },
      { hint: "Greatly valued", word: "PRECIOUS" },
      { hint: "Special advantage", word: "PRIVILEGE" },
      { hint: "Living, not dead", word: "ALIVE" },
    ],
  },
  {
    id: "p147",
    quote: "An unexamined life is not worth living.",
    attribution: "Socrates",
    theme: "Reflection",
    difficulty: "hard",
    clueWords: [
      { hint: "Not inspected", word: "UNEXAMINED" },
      { hint: "Existence", word: "LIFE" },
      { hint: "Of value", word: "WORTH" },
      { hint: "Being alive", word: "LIVING" },
    ],
  },
  {
    id: "p148",
    quote: "I cannot teach anybody anything. I can only make them think.",
    attribution: "Socrates",
    theme: "Teaching",
    difficulty: "hard",
    clueWords: [
      { hint: "Instruct", word: "TEACH" },
      { hint: "Any person", word: "ANYBODY" },
      { hint: "Cause or compel", word: "MAKE" },
      { hint: "Use the mind", word: "THINK" },
      { hint: "Solely", word: "ONLY" },
    ],
  },
  {
    id: "p149",
    quote: "There is only one good, knowledge, and one evil, ignorance.",
    attribution: "Socrates",
    theme: "Wisdom",
    difficulty: "hard",
    clueWords: [
      { hint: "Sole, single", word: "ONLY" },
      { hint: "Worthy or fine", word: "GOOD" },
      { hint: "What you know", word: "KNOWLEDGE" },
      { hint: "Wickedness", word: "EVIL" },
      { hint: "Lack of knowledge", word: "IGNORANCE" },
    ],
  },
  {
    id: "p150",
    quote: "Education is the kindling of a flame, not the filling of a vessel.",
    attribution: "Socrates",
    theme: "Learning",
    difficulty: "hard",
    clueWords: [
      { hint: "Schooling, instruction", word: "EDUCATION" },
      { hint: "Igniting", word: "KINDLING" },
      { hint: "A small fire", word: "FLAME" },
      { hint: "Pouring into", word: "FILLING" },
      { hint: "Container", word: "VESSEL" },
    ],
  },
  {
    id: "p151",
    quote: "Tell me and I forget. Teach me and I may remember. Involve me and I learn.",
    attribution: "Benjamin Franklin",
    theme: "Learning",
    difficulty: "hard",
    clueWords: [
      { hint: "State, inform", word: "TELL" },
      { hint: "Lose memory of", word: "FORGET" },
      { hint: "Instruct", word: "TEACH" },
      { hint: "Recall to mind", word: "REMEMBER" },
      { hint: "Engage actively", word: "INVOLVE" },
      { hint: "Acquire knowledge", word: "LEARN" },
    ],
  },
  {
    id: "p152",
    quote: "Either write something worth reading or do something worth writing.",
    attribution: "Benjamin Franklin",
    theme: "Legacy",
    difficulty: "hard",
    clueWords: [
      { hint: "Compose text", word: "WRITE" },
      { hint: "Going through text", word: "READING" },
      { hint: "Performing text", word: "WRITING" },
      { hint: "Of value", word: "WORTH" },
      { hint: "An item", word: "SOMETHING" },
    ],
  },
  {
    id: "p153",
    quote: "Energy and persistence conquer all things.",
    attribution: "Benjamin Franklin",
    theme: "Persistence",
    difficulty: "hard",
    clueWords: [
      { hint: "Vitality or vigor", word: "ENERGY" },
      { hint: "Steady persistence", word: "PERSISTENCE" },
      { hint: "Overcome by force", word: "CONQUER" },
      { hint: "Each, every", word: "ALL" },
      { hint: "Items or matters", word: "THINGS" },
    ],
  },
  {
    id: "p154",
    quote: "Lost time is never found again.",
    attribution: "Benjamin Franklin",
    theme: "Time",
    difficulty: "hard",
    clueWords: [
      { hint: "Misplaced", word: "LOST" },
      { hint: "Hours and minutes", word: "TIME" },
      { hint: "At no point", word: "NEVER" },
      { hint: "Recovered", word: "FOUND" },
      { hint: "Once more", word: "AGAIN" },
    ],
  },
  {
    id: "p155",
    quote: "Well done is better than well said.",
    attribution: "Benjamin Franklin",
    theme: "Action",
    difficulty: "hard",
    clueWords: [
      { hint: "In a good manner", word: "WELL" },
      { hint: "Performed, completed", word: "DONE" },
      { hint: "Spoken, expressed", word: "SAID" },
      { hint: "Preferable", word: "BETTER" },
    ],
  },
  {
    id: "p156",
    quote: "By failing to prepare, you are preparing to fail.",
    attribution: "Benjamin Franklin",
    theme: "Preparation",
    difficulty: "hard",
    clueWords: [
      { hint: "Not succeeding at", word: "FAILING" },
      { hint: "Get ready", word: "PREPARE" },
      { hint: "Getting ready", word: "PREPARING" },
      { hint: "Not succeed", word: "FAIL" },
    ],
  },
  {
    id: "p157",
    quote: "An investment in knowledge pays the best interest.",
    attribution: "Benjamin Franklin",
    theme: "Learning",
    difficulty: "hard",
    clueWords: [
      { hint: "Putting resources to use", word: "INVESTMENT" },
      { hint: "Information mastered", word: "KNOWLEDGE" },
      { hint: "Gives back, rewards", word: "PAYS" },
      { hint: "Top quality", word: "BEST" },
      { hint: "Return on capital", word: "INTEREST" },
    ],
  },
  {
    id: "p158",
    quote: "Three may keep a secret, if two of them are dead.",
    attribution: "Benjamin Franklin",
    theme: "Secrecy",
    difficulty: "hard",
    clueWords: [
      { hint: "Number after two", word: "THREE" },
      { hint: "Hold or guard", word: "KEEP" },
      { hint: "Hidden information", word: "SECRET" },
      { hint: "One pair", word: "TWO" },
      { hint: "Without life", word: "DEAD" },
    ],
  },
  {
    id: "p159",
    quote: "Genius is one percent inspiration and ninety-nine percent perspiration.",
    attribution: "Thomas Edison",
    theme: "Effort",
    difficulty: "hard",
    clueWords: [
      { hint: "Exceptional ability", word: "GENIUS" },
      { hint: "Single unit", word: "ONE" },
      { hint: "A part per hundred", word: "PERCENT" },
      { hint: "Creative spark", word: "INSPIRATION" },
      { hint: "Sweating from effort", word: "PERSPIRATION" },
    ],
  },
  {
    id: "p160",
    quote: "I have not failed. I have just found ten thousand ways that will not work.",
    attribution: "Thomas Edison",
    theme: "Persistence",
    difficulty: "hard",
    clueWords: [
      { hint: "Did not succeed", word: "FAILED" },
      { hint: "Discovered", word: "FOUND" },
      { hint: "10 times 1000", word: "THOUSAND" },
      { hint: "Methods", word: "WAYS" },
      { hint: "Function properly", word: "WORK" },
      { hint: "One more than nine", word: "TEN" },
    ],
  },
  {
    id: "p161",
    quote: "Our greatest weakness lies in giving up.",
    attribution: "Thomas Edison",
    theme: "Persistence",
    difficulty: "hard",
    clueWords: [
      { hint: "Most great", word: "GREATEST" },
      { hint: "Lack of strength", word: "WEAKNESS" },
      { hint: "Belongs to us", word: "OUR" },
      { hint: "Surrendering", word: "GIVING" },
      { hint: "Rests, exists", word: "LIES" },
    ],
  },
  {
    id: "p162",
    quote: "Imagination is more important than knowledge.",
    attribution: "Albert Einstein",
    theme: "Creativity",
    difficulty: "hard",
    clueWords: [
      { hint: "Mental creative power", word: "IMAGINATION" },
      { hint: "Of greater significance", word: "IMPORTANT" },
      { hint: "Information mastered", word: "KNOWLEDGE" },
      { hint: "To a greater degree", word: "MORE" },
    ],
  },
  {
    id: "p163",
    quote: "Try not to become a man of success, but rather try to become a man of value.",
    attribution: "Albert Einstein",
    theme: "Values",
    difficulty: "hard",
    clueWords: [
      { hint: "Make an attempt", word: "TRY" },
      { hint: "Turn into", word: "BECOME" },
      { hint: "Adult male", word: "MAN" },
      { hint: "Achievement", word: "SUCCESS" },
      { hint: "Worth or merit", word: "VALUE" },
    ],
  },
  {
    id: "p164",
    quote: "Logic will get you from A to B. Imagination will take you everywhere.",
    attribution: "Albert Einstein",
    theme: "Creativity",
    difficulty: "hard",
    clueWords: [
      { hint: "Reasoning", word: "LOGIC" },
      { hint: "Mental images", word: "IMAGINATION" },
      { hint: "Carry, transport", word: "TAKE" },
      { hint: "In every place", word: "EVERYWHERE" },
    ],
  },
  {
    id: "p165",
    quote: "A person who never made a mistake never tried anything new.",
    attribution: "Albert Einstein",
    theme: "Risk",
    difficulty: "hard",
    clueWords: [
      { hint: "Human individual", word: "PERSON" },
      { hint: "An error", word: "MISTAKE" },
      { hint: "Made an attempt at", word: "TRIED" },
      { hint: "Recently created", word: "NEW" },
      { hint: "At no time", word: "NEVER" },
    ],
  },
  {
    id: "p166",
    quote: "Once we accept our limits, we go beyond them.",
    attribution: "Albert Einstein",
    theme: "Growth",
    difficulty: "hard",
    clueWords: [
      { hint: "A single occasion", word: "ONCE" },
      { hint: "Receive willingly", word: "ACCEPT" },
      { hint: "Boundaries", word: "LIMITS" },
      { hint: "Past or further than", word: "BEYOND" },
      { hint: "Belonging to us", word: "OUR" },
    ],
  },
  {
    id: "p167",
    quote: "The true sign of intelligence is not knowledge but imagination.",
    attribution: "Albert Einstein",
    theme: "Creativity",
    difficulty: "hard",
    clueWords: [
      { hint: "Genuine, real", word: "TRUE" },
      { hint: "An indicator", word: "SIGN" },
      { hint: "Mental capability", word: "INTELLIGENCE" },
      { hint: "Information mastered", word: "KNOWLEDGE" },
      { hint: "Mental creativity", word: "IMAGINATION" },
    ],
  },
  {
    id: "p168",
    quote: "Strive not to be a success, but rather to be of value.",
    attribution: "Albert Einstein",
    theme: "Values",
    difficulty: "hard",
    clueWords: [
      { hint: "Make great effort", word: "STRIVE" },
      { hint: "Achievement", word: "SUCCESS" },
      { hint: "Worth, merit", word: "VALUE" },
      { hint: "Instead of", word: "RATHER" },
    ],
  },
  {
    id: "p169",
    quote: "He who is brave is free.",
    attribution: "Seneca",
    theme: "Courage",
    difficulty: "hard",
    clueWords: [
      { hint: "Courageous", word: "BRAVE" },
      { hint: "Not bound", word: "FREE" },
    ],
  },
  {
    id: "p170",
    quote: "Things do not change; we change.",
    attribution: "Henry David Thoreau",
    theme: "Growth",
    difficulty: "hard",
    clueWords: [
      { hint: "Items or matters", word: "THINGS" },
      { hint: "Become different", word: "CHANGE" },
      { hint: "First-person plural", word: "WE" },
    ],
  },
  {
    id: "p171",
    quote: "Go confidently in the direction of your dreams.",
    attribution: "Henry David Thoreau",
    theme: "Aspiration",
    difficulty: "hard",
    clueWords: [
      { hint: "Move forward", word: "GO" },
      { hint: "With self-assurance", word: "CONFIDENTLY" },
      { hint: "A heading or course", word: "DIRECTION" },
      { hint: "Aspirations", word: "DREAMS" },
    ],
  },
  {
    id: "p172",
    quote: "The mass of men lead lives of quiet desperation.",
    attribution: "Henry David Thoreau",
    theme: "Reflection",
    difficulty: "hard",
    clueWords: [
      { hint: "A large group", word: "MASS" },
      { hint: "Adult males", word: "MEN" },
      { hint: "Guide, direct", word: "LEAD" },
      { hint: "Calm or hushed", word: "QUIET" },
      { hint: "Hopelessness", word: "DESPERATION" },
      { hint: "Existences", word: "LIVES" },
    ],
  },
  {
    id: "p173",
    quote: "Insanity is doing the same thing over and over and expecting different results.",
    attribution: "Anonymous",
    theme: "Change",
    difficulty: "hard",
    clueWords: [
      { hint: "Madness", word: "INSANITY" },
      { hint: "Identical", word: "SAME" },
      { hint: "An item or matter", word: "THING" },
      { hint: "Anticipating", word: "EXPECTING" },
      { hint: "Outcomes", word: "RESULTS" },
      { hint: "Not the same", word: "DIFFERENT" },
    ],
  },
  {
    id: "p174",
    quote: "Whatever can happen at any time can happen today.",
    attribution: "Seneca",
    theme: "Mindfulness",
    difficulty: "hard",
    clueWords: [
      { hint: "Anything that", word: "WHATEVER" },
      { hint: "Take place", word: "HAPPEN" },
      { hint: "At a moment", word: "TIME" },
      { hint: "The current day", word: "TODAY" },
    ],
  },
  {
    id: "p175",
    quote: "It is not what happens to you, but how you react to it that matters.",
    attribution: "Epictetus",
    theme: "Mindset",
    difficulty: "hard",
    clueWords: [
      { hint: "Take place", word: "HAPPENS" },
      { hint: "Respond to", word: "REACT" },
      { hint: "Is significant", word: "MATTERS" },
      { hint: "In what manner", word: "HOW" },
    ],
  },
  {
    id: "p176",
    quote: "First, say to yourself what you would be; and then do what you have to do.",
    attribution: "Epictetus",
    theme: "Action",
    difficulty: "hard",
    clueWords: [
      { hint: "Before all others", word: "FIRST" },
      { hint: "Speak", word: "SAY" },
      { hint: "Your own person", word: "YOURSELF" },
      { hint: "After that", word: "THEN" },
      { hint: "Perform", word: "DO" },
    ],
  },
  {
    id: "p177",
    quote: "We have two ears and one mouth so that we can listen twice as much as we speak.",
    attribution: "Epictetus",
    theme: "Listening",
    difficulty: "hard",
    clueWords: [
      { hint: "Hearing organs", word: "EARS" },
      { hint: "Speaking organ", word: "MOUTH" },
      { hint: "A pair", word: "TWO" },
      { hint: "Pay attention to", word: "LISTEN" },
      { hint: "Talk, utter", word: "SPEAK" },
      { hint: "Two times", word: "TWICE" },
    ],
  },
  {
    id: "p178",
    quote: "Wealth consists not in having great possessions, but in having few wants.",
    attribution: "Epictetus",
    theme: "Contentment",
    difficulty: "hard",
    clueWords: [
      { hint: "Riches", word: "WEALTH" },
      { hint: "Is composed of", word: "CONSISTS" },
      { hint: "Owning", word: "HAVING" },
      { hint: "Things owned", word: "POSSESSIONS" },
      { hint: "Desires", word: "WANTS" },
      { hint: "A small number", word: "FEW" },
    ],
  },
  {
    id: "p179",
    quote: "If you want to improve, be content to be thought foolish and stupid.",
    attribution: "Epictetus",
    theme: "Humility",
    difficulty: "hard",
    clueWords: [
      { hint: "Make better", word: "IMPROVE" },
      { hint: "Satisfied", word: "CONTENT" },
      { hint: "Considered or believed", word: "THOUGHT" },
      { hint: "Lacking sense", word: "FOOLISH" },
      { hint: "Not smart", word: "STUPID" },
    ],
  },
  {
    id: "p180",
    quote: "No man is free who is not master of himself.",
    attribution: "Epictetus",
    theme: "Self-Control",
    difficulty: "hard",
    clueWords: [
      { hint: "Adult male", word: "MAN" },
      { hint: "Not bound", word: "FREE" },
      { hint: "Controller, expert", word: "MASTER" },
      { hint: "He himself", word: "HIMSELF" },
    ],
  },
  {
    id: "p181",
    quote: "The unexamined life is the life lived in chains.",
    attribution: "Anonymous",
    theme: "Reflection",
    difficulty: "hard",
    clueWords: [
      { hint: "Not inspected", word: "UNEXAMINED" },
      { hint: "Existence", word: "LIFE" },
      { hint: "Past tense of live", word: "LIVED" },
      { hint: "Linked iron rings", word: "CHAINS" },
    ],
  },
  {
    id: "p182",
    quote: "What you do speaks so loudly that I cannot hear what you say.",
    attribution: "Ralph Waldo Emerson",
    theme: "Action",
    difficulty: "hard",
    clueWords: [
      { hint: "Perform", word: "DO" },
      { hint: "Talks, utters", word: "SPEAKS" },
      { hint: "With loud volume", word: "LOUDLY" },
      { hint: "Receive sound", word: "HEAR" },
      { hint: "Express verbally", word: "SAY" },
    ],
  },
  {
    id: "p183",
    quote: "Without continual growth and progress, words like improvement and success have no meaning.",
    attribution: "Benjamin Franklin",
    theme: "Growth",
    difficulty: "hard",
    clueWords: [
      { hint: "Lacking", word: "WITHOUT" },
      { hint: "Ongoing", word: "CONTINUAL" },
      { hint: "Development", word: "GROWTH" },
      { hint: "Forward motion", word: "PROGRESS" },
      { hint: "Improvement", word: "IMPROVEMENT" },
      { hint: "Achievement", word: "SUCCESS" },
    ],
  },
  {
    id: "p184",
    quote: "Patience is bitter, but its fruit is sweet.",
    attribution: "Aristotle",
    theme: "Patience",
    difficulty: "hard",
    clueWords: [
      { hint: "Calm endurance", word: "PATIENCE" },
      { hint: "Sharp, harsh", word: "BITTER" },
      { hint: "Reward of plant", word: "FRUIT" },
      { hint: "Sugary, pleasant", word: "SWEET" },
    ],
  },
  {
    id: "p185",
    quote: "He who has overcome his fears will truly be free.",
    attribution: "Aristotle",
    theme: "Courage",
    difficulty: "hard",
    clueWords: [
      { hint: "Conquered", word: "OVERCOME" },
      { hint: "Worries, dreads", word: "FEARS" },
      { hint: "In a true way", word: "TRULY" },
      { hint: "Liberated, unbound", word: "FREE" },
    ],
  },
  {
    id: "p186",
    quote: "It is the mark of an educated mind to entertain a thought without accepting it.",
    attribution: "Aristotle",
    theme: "Open Mind",
    difficulty: "hard",
    clueWords: [
      { hint: "A sign or trait", word: "MARK" },
      { hint: "Schooled", word: "EDUCATED" },
      { hint: "Thinking faculty", word: "MIND" },
      { hint: "Consider, host", word: "ENTERTAIN" },
      { hint: "An idea", word: "THOUGHT" },
      { hint: "Receiving as true", word: "ACCEPTING" },
    ],
  },
  {
    id: "p187",
    quote: "Pleasure in the job puts perfection in the work.",
    attribution: "Aristotle",
    theme: "Work",
    difficulty: "hard",
    clueWords: [
      { hint: "Enjoyment", word: "PLEASURE" },
      { hint: "An occupation", word: "JOB" },
      { hint: "Without flaw", word: "PERFECTION" },
      { hint: "Effort, labor", word: "WORK" },
      { hint: "Places into", word: "PUTS" },
    ],
  },
  {
    id: "p188",
    quote: "We are what we repeatedly do. Excellence, then, is not an act but a habit.",
    attribution: "Will Durant",
    theme: "Habit",
    difficulty: "hard",
    clueWords: [
      { hint: "Time and again", word: "REPEATEDLY" },
      { hint: "Perform", word: "DO" },
      { hint: "Outstanding quality", word: "EXCELLENCE" },
      { hint: "A deed", word: "ACT" },
      { hint: "A repeated behavior", word: "HABIT" },
    ],
  },
  {
    id: "p189",
    quote: "Anything that excites me for any reason, I will photograph.",
    attribution: "Edward Weston",
    theme: "Curiosity",
    difficulty: "hard",
    clueWords: [
      { hint: "Any thing or matter", word: "ANYTHING" },
      { hint: "Stirs interest in", word: "EXCITES" },
      { hint: "A motive", word: "REASON" },
      { hint: "Capture in image", word: "PHOTOGRAPH" },
    ],
  },
  {
    id: "p190",
    quote: "First they ignore you, then they laugh at you, then they fight you, then you win.",
    attribution: "Anonymous",
    theme: "Persistence",
    difficulty: "hard",
    clueWords: [
      { hint: "Pay no attention to", word: "IGNORE" },
      { hint: "Express amusement at", word: "LAUGH" },
      { hint: "Battle, oppose", word: "FIGHT" },
      { hint: "Be victorious", word: "WIN" },
      { hint: "After that", word: "THEN" },
    ],
  },

  // -------------------- EXPERT (40) --------------------
  {
    id: "p191",
    quote: "Cowards die many times before their deaths; the valiant never taste of death but once.",
    attribution: "William Shakespeare",
    theme: "Courage",
    difficulty: "expert",
    clueWords: [
      { hint: "Those without courage", word: "COWARDS" },
      { hint: "Cease to live", word: "DIE" },
      { hint: "A great number", word: "MANY" },
      { hint: "Brave individuals", word: "VALIANT" },
      { hint: "Sample, experience", word: "TASTE" },
      { hint: "End of life", word: "DEATH" },
    ],
  },
  {
    id: "p192",
    quote: "All the world is a stage, and all the men and women merely players.",
    attribution: "William Shakespeare",
    theme: "Life",
    difficulty: "expert",
    clueWords: [
      { hint: "The earth", word: "WORLD" },
      { hint: "A theater platform", word: "STAGE" },
      { hint: "Adult males", word: "MEN" },
      { hint: "Adult females", word: "WOMEN" },
      { hint: "Performers", word: "PLAYERS" },
      { hint: "Only, simply", word: "MERELY" },
    ],
  },
  {
    id: "p193",
    quote: "To thine own self be true, and it must follow that thou canst not be false to any man.",
    attribution: "William Shakespeare",
    theme: "Authenticity",
    difficulty: "expert",
    clueWords: [
      { hint: "Your (archaic)", word: "THINE" },
      { hint: "Belonging to oneself", word: "OWN" },
      { hint: "Genuine, honest", word: "TRUE" },
      { hint: "Come after", word: "FOLLOW" },
      { hint: "Untruthful", word: "FALSE" },
      { hint: "Adult male", word: "MAN" },
    ],
  },
  {
    id: "p194",
    quote: "Brevity is the soul of wit.",
    attribution: "William Shakespeare",
    theme: "Communication",
    difficulty: "expert",
    clueWords: [
      { hint: "Concise quality", word: "BREVITY" },
      { hint: "Inner essence", word: "SOUL" },
      { hint: "Cleverness in speech", word: "WIT" },
    ],
  },
  {
    id: "p195",
    quote: "We know what we are, but know not what we may be.",
    attribution: "William Shakespeare",
    theme: "Possibility",
    difficulty: "expert",
    clueWords: [
      { hint: "Are aware of", word: "KNOW" },
      { hint: "First-person plural", word: "WE" },
      { hint: "Could possibly", word: "MAY" },
      { hint: "Exist as", word: "BE" },
    ],
  },
  {
    id: "p196",
    quote: "There is nothing either good or bad, but thinking makes it so.",
    attribution: "William Shakespeare",
    theme: "Mindset",
    difficulty: "expert",
    clueWords: [
      { hint: "Not anything", word: "NOTHING" },
      { hint: "One or the other", word: "EITHER" },
      { hint: "Fine in quality", word: "GOOD" },
      { hint: "Of poor quality", word: "BAD" },
      { hint: "Pondering", word: "THINKING" },
      { hint: "Causes", word: "MAKES" },
    ],
  },
  {
    id: "p197",
    quote: "The fool doth think he is wise, but the wise man knows himself to be a fool.",
    attribution: "William Shakespeare",
    theme: "Humility",
    difficulty: "expert",
    clueWords: [
      { hint: "Foolish person", word: "FOOL" },
      { hint: "Believes, ponders", word: "THINK" },
      { hint: "Sage, learned", word: "WISE" },
      { hint: "Adult male", word: "MAN" },
      { hint: "Is aware", word: "KNOWS" },
      { hint: "He himself", word: "HIMSELF" },
    ],
  },
  {
    id: "p198",
    quote: "Some are born great, some achieve greatness, and some have greatness thrust upon them.",
    attribution: "William Shakespeare",
    theme: "Greatness",
    difficulty: "expert",
    clueWords: [
      { hint: "Brought into life", word: "BORN" },
      { hint: "Outstanding", word: "GREAT" },
      { hint: "Earn or accomplish", word: "ACHIEVE" },
      { hint: "Quality of being great", word: "GREATNESS" },
      { hint: "Forced or pushed", word: "THRUST" },
      { hint: "Onto, on top of", word: "UPON" },
    ],
  },
  {
    id: "p199",
    quote: "When sorrows come, they come not single spies, but in battalions.",
    attribution: "William Shakespeare",
    theme: "Adversity",
    difficulty: "expert",
    clueWords: [
      { hint: "Griefs, sadnesses", word: "SORROWS" },
      { hint: "Arrive", word: "COME" },
      { hint: "One alone", word: "SINGLE" },
      { hint: "Secret observers", word: "SPIES" },
      { hint: "Large army units", word: "BATTALIONS" },
    ],
  },
  {
    id: "p200",
    quote: "Our doubts are traitors and make us lose the good we oft might win by fearing to attempt.",
    attribution: "William Shakespeare",
    theme: "Courage",
    difficulty: "expert",
    clueWords: [
      { hint: "Uncertainties", word: "DOUBTS" },
      { hint: "Disloyal betrayers", word: "TRAITORS" },
      { hint: "Forfeit", word: "LOSE" },
      { hint: "Worthy or fine", word: "GOOD" },
      { hint: "Often (poetic)", word: "OFT" },
      { hint: "Try to do", word: "ATTEMPT" },
    ],
  },
  {
    id: "p201",
    quote: "What is in a name? That which we call a rose by any other name would smell as sweet.",
    attribution: "William Shakespeare",
    theme: "Identity",
    difficulty: "expert",
    clueWords: [
      { hint: "Identifier of a thing", word: "NAME" },
      { hint: "Refer to as", word: "CALL" },
      { hint: "Thorny flower", word: "ROSE" },
      { hint: "Detect with the nose", word: "SMELL" },
      { hint: "Sugary, pleasant", word: "SWEET" },
    ],
  },
  {
    id: "p202",
    quote: "There is a tide in the affairs of men which, taken at the flood, leads on to fortune.",
    attribution: "William Shakespeare",
    theme: "Opportunity",
    difficulty: "expert",
    clueWords: [
      { hint: "Ocean rise and fall", word: "TIDE" },
      { hint: "Matters or business", word: "AFFAIRS" },
      { hint: "Adult males", word: "MEN" },
      { hint: "High water", word: "FLOOD" },
      { hint: "Guides, conducts", word: "LEADS" },
      { hint: "Luck, prosperity", word: "FORTUNE" },
    ],
  },
  {
    id: "p203",
    quote: "He who is not courageous enough to take risks will accomplish nothing in life.",
    attribution: "Muhammad Ali",
    theme: "Courage",
    difficulty: "expert",
    clueWords: [
      { hint: "Brave, bold", word: "COURAGEOUS" },
      { hint: "Sufficient", word: "ENOUGH" },
      { hint: "Hazards", word: "RISKS" },
      { hint: "Successfully complete", word: "ACCOMPLISH" },
      { hint: "Not anything", word: "NOTHING" },
      { hint: "Existence", word: "LIFE" },
    ],
  },
  {
    id: "p204",
    quote: "Float like a butterfly, sting like a bee.",
    attribution: "Muhammad Ali",
    theme: "Style",
    difficulty: "expert",
    clueWords: [
      { hint: "Drift on water or air", word: "FLOAT" },
      { hint: "A colorful winged insect", word: "BUTTERFLY" },
      { hint: "Pierce sharply", word: "STING" },
      { hint: "Buzzing flying insect", word: "BEE" },
      { hint: "Similar to", word: "LIKE" },
    ],
  },
  {
    id: "p205",
    quote: "Service to others is the rent you pay for your room here on earth.",
    attribution: "Muhammad Ali",
    theme: "Service",
    difficulty: "expert",
    clueWords: [
      { hint: "Helpful labor", word: "SERVICE" },
      { hint: "Other people", word: "OTHERS" },
      { hint: "Periodic payment for use", word: "RENT" },
      { hint: "Hand over money", word: "PAY" },
      { hint: "An interior space", word: "ROOM" },
      { hint: "Our planet", word: "EARTH" },
    ],
  },
  {
    id: "p206",
    quote: "How wonderful it is that nobody need wait a single moment before starting to improve the world.",
    attribution: "Anne Frank",
    theme: "Action",
    difficulty: "expert",
    clueWords: [
      { hint: "Marvelous, fantastic", word: "WONDERFUL" },
      { hint: "Not a person", word: "NOBODY" },
      { hint: "Stay, expect", word: "WAIT" },
      { hint: "An instant in time", word: "MOMENT" },
      { hint: "Make better", word: "IMPROVE" },
      { hint: "Earth", word: "WORLD" },
    ],
  },
  {
    id: "p207",
    quote: "I do not think of all the misery, but of the beauty that still remains.",
    attribution: "Anne Frank",
    theme: "Optimism",
    difficulty: "expert",
    clueWords: [
      { hint: "Reflect, ponder", word: "THINK" },
      { hint: "Great suffering", word: "MISERY" },
      { hint: "Loveliness", word: "BEAUTY" },
      { hint: "Yet, even now", word: "STILL" },
      { hint: "Stays behind", word: "REMAINS" },
    ],
  },
  {
    id: "p208",
    quote: "The final forming of a person's character lies in their own hands.",
    attribution: "Anne Frank",
    theme: "Self-Determination",
    difficulty: "expert",
    clueWords: [
      { hint: "Last, ultimate", word: "FINAL" },
      { hint: "Shaping or molding", word: "FORMING" },
      { hint: "An individual", word: "PERSON" },
      { hint: "Moral nature", word: "CHARACTER" },
      { hint: "Body parts with fingers", word: "HANDS" },
      { hint: "Belonging to them", word: "THEIR" },
    ],
  },
  {
    id: "p209",
    quote: "I have learned over the years that when one's mind is made up, this diminishes fear.",
    attribution: "Rosa Parks",
    theme: "Resolve",
    difficulty: "expert",
    clueWords: [
      { hint: "Acquired knowledge", word: "LEARNED" },
      { hint: "Calendar units", word: "YEARS" },
      { hint: "Thinking faculty", word: "MIND" },
      { hint: "Made firm", word: "MADE" },
      { hint: "Reduces, lessens", word: "DIMINISHES" },
      { hint: "Dread or terror", word: "FEAR" },
    ],
  },
  {
    id: "p210",
    quote: "Stand for something or you will fall for anything.",
    attribution: "Rosa Parks",
    theme: "Conviction",
    difficulty: "expert",
    clueWords: [
      { hint: "Take a position", word: "STAND" },
      { hint: "An item or cause", word: "SOMETHING" },
      { hint: "Drop, descend", word: "FALL" },
      { hint: "Any thing", word: "ANYTHING" },
    ],
  },
  {
    id: "p211",
    quote: "Memories of our lives, of our works and our deeds will continue in others.",
    attribution: "Rosa Parks",
    theme: "Legacy",
    difficulty: "expert",
    clueWords: [
      { hint: "Recollections", word: "MEMORIES" },
      { hint: "Existences", word: "LIVES" },
      { hint: "Created products", word: "WORKS" },
      { hint: "Actions performed", word: "DEEDS" },
      { hint: "Persist, go on", word: "CONTINUE" },
      { hint: "Other people", word: "OTHERS" },
    ],
  },
  {
    id: "p212",
    quote: "It is in moments of decision that your destiny is shaped.",
    attribution: "Tony Robbins",
    theme: "Decision",
    difficulty: "expert",
    clueWords: [
      { hint: "Brief instants", word: "MOMENTS" },
      { hint: "A choice or judgment", word: "DECISION" },
      { hint: "Pre-set fate", word: "DESTINY" },
      { hint: "Formed or molded", word: "SHAPED" },
    ],
  },
  {
    id: "p213",
    quote: "Setting goals is the first step in turning the invisible into the visible.",
    attribution: "Tony Robbins",
    theme: "Aspiration",
    difficulty: "expert",
    clueWords: [
      { hint: "Establishing", word: "SETTING" },
      { hint: "Targets to reach", word: "GOALS" },
      { hint: "Initial pace", word: "STEP" },
      { hint: "Cannot be seen", word: "INVISIBLE" },
      { hint: "Can be seen", word: "VISIBLE" },
      { hint: "Converting", word: "TURNING" },
    ],
  },
  {
    id: "p214",
    quote: "The quality of your life is the quality of your relationships.",
    attribution: "Tony Robbins",
    theme: "Connection",
    difficulty: "expert",
    clueWords: [
      { hint: "Standard of excellence", word: "QUALITY" },
      { hint: "Existence", word: "LIFE" },
      { hint: "Connections with others", word: "RELATIONSHIPS" },
      { hint: "Belonging to you", word: "YOUR" },
    ],
  },
  {
    id: "p215",
    quote: "Do not let what you cannot do interfere with what you can do.",
    attribution: "John Wooden",
    theme: "Focus",
    difficulty: "expert",
    clueWords: [
      { hint: "Permit", word: "LET" },
      { hint: "Are not able to", word: "CANNOT" },
      { hint: "Are able to", word: "CAN" },
      { hint: "Perform", word: "DO" },
      { hint: "Disrupt or hinder", word: "INTERFERE" },
    ],
  },
  {
    id: "p216",
    quote: "Be more concerned with your character than your reputation.",
    attribution: "John Wooden",
    theme: "Character",
    difficulty: "expert",
    clueWords: [
      { hint: "Worried, focused on", word: "CONCERNED" },
      { hint: "Moral nature", word: "CHARACTER" },
      { hint: "Public image", word: "REPUTATION" },
      { hint: "To a greater degree", word: "MORE" },
    ],
  },
  {
    id: "p217",
    quote: "The best preparation for tomorrow is doing your best today.",
    attribution: "H. Jackson Brown Jr.",
    theme: "Preparation",
    difficulty: "expert",
    clueWords: [
      { hint: "Top quality", word: "BEST" },
      { hint: "Getting ready", word: "PREPARATION" },
      { hint: "The day after today", word: "TOMORROW" },
      { hint: "Performing", word: "DOING" },
      { hint: "The current day", word: "TODAY" },
    ],
  },
  {
    id: "p218",
    quote: "It is better to fail in originality than to succeed in imitation.",
    attribution: "Herman Melville",
    theme: "Originality",
    difficulty: "expert",
    clueWords: [
      { hint: "Preferable", word: "BETTER" },
      { hint: "Not succeed", word: "FAIL" },
      { hint: "Quality of being unique", word: "ORIGINALITY" },
      { hint: "Achieve success", word: "SUCCEED" },
      { hint: "Copying others", word: "IMITATION" },
    ],
  },
  {
    id: "p219",
    quote: "I have not yet begun to fight.",
    attribution: "John Paul Jones",
    theme: "Resolve",
    difficulty: "expert",
    clueWords: [
      { hint: "Up to now", word: "YET" },
      { hint: "Started", word: "BEGUN" },
      { hint: "Engage in combat", word: "FIGHT" },
    ],
  },
  {
    id: "p220",
    quote: "I have a dream that one day this nation will rise up and live out the true meaning of its creed.",
    attribution: "Martin Luther King Jr.",
    theme: "Hope",
    difficulty: "expert",
    clueWords: [
      { hint: "An aspiration", word: "DREAM" },
      { hint: "A country", word: "NATION" },
      { hint: "Get up", word: "RISE" },
      { hint: "Genuine, real", word: "TRUE" },
      { hint: "Significance", word: "MEANING" },
      { hint: "Belief or doctrine", word: "CREED" },
    ],
  },
  {
    id: "p221",
    quote: "The arc of the moral universe is long, but it bends toward justice.",
    attribution: "Theodore Parker",
    theme: "Justice",
    difficulty: "expert",
    clueWords: [
      { hint: "Curved shape", word: "ARC" },
      { hint: "Ethical, virtuous", word: "MORAL" },
      { hint: "Cosmos, all of space", word: "UNIVERSE" },
      { hint: "Curves or flexes", word: "BENDS" },
      { hint: "Fairness, equity", word: "JUSTICE" },
    ],
  },
  {
    id: "p222",
    quote: "Injustice anywhere is a threat to justice everywhere.",
    attribution: "Martin Luther King Jr.",
    theme: "Justice",
    difficulty: "expert",
    clueWords: [
      { hint: "Lack of fairness", word: "INJUSTICE" },
      { hint: "In any place", word: "ANYWHERE" },
      { hint: "Possible danger", word: "THREAT" },
      { hint: "Fair treatment", word: "JUSTICE" },
      { hint: "In all places", word: "EVERYWHERE" },
    ],
  },
  {
    id: "p223",
    quote: "We may encounter many defeats, but we must not be defeated.",
    attribution: "Maya Angelou",
    theme: "Resilience",
    difficulty: "expert",
    clueWords: [
      { hint: "Possibly", word: "MAY" },
      { hint: "Run into, meet", word: "ENCOUNTER" },
      { hint: "Numerous", word: "MANY" },
      { hint: "Losses or failures", word: "DEFEATS" },
      { hint: "Beaten or overcome", word: "DEFEATED" },
    ],
  },
  {
    id: "p224",
    quote: "There is no greater agony than bearing an untold story inside you.",
    attribution: "Maya Angelou",
    theme: "Expression",
    difficulty: "expert",
    clueWords: [
      { hint: "Larger or more intense", word: "GREATER" },
      { hint: "Severe pain", word: "AGONY" },
      { hint: "Carrying", word: "BEARING" },
      { hint: "Not spoken aloud", word: "UNTOLD" },
      { hint: "A narrative or tale", word: "STORY" },
      { hint: "Within", word: "INSIDE" },
    ],
  },
  {
    id: "p225",
    quote: "If you do not like something, change it. If you cannot change it, change your attitude.",
    attribution: "Maya Angelou",
    theme: "Adaptability",
    difficulty: "expert",
    clueWords: [
      { hint: "Find pleasing", word: "LIKE" },
      { hint: "An item", word: "SOMETHING" },
      { hint: "Modify, alter", word: "CHANGE" },
      { hint: "Mental disposition", word: "ATTITUDE" },
      { hint: "Belonging to you", word: "YOUR" },
    ],
  },
  {
    id: "p226",
    quote: "Nothing will work unless you do.",
    attribution: "Maya Angelou",
    theme: "Effort",
    difficulty: "expert",
    clueWords: [
      { hint: "Not anything", word: "NOTHING" },
      { hint: "Function properly", word: "WORK" },
      { hint: "Except if", word: "UNLESS" },
      { hint: "Perform", word: "DO" },
    ],
  },
  {
    id: "p227",
    quote: "The unexamined life is the life lived in chains, said the philosopher long ago.",
    attribution: "Anonymous",
    theme: "Reflection",
    difficulty: "expert",
    clueWords: [
      { hint: "Not inspected", word: "UNEXAMINED" },
      { hint: "Existence", word: "LIFE" },
      { hint: "Being alive", word: "LIVED" },
      { hint: "Linked iron rings", word: "CHAINS" },
      { hint: "Lover of wisdom", word: "PHILOSOPHER" },
    ],
  },
  {
    id: "p228",
    quote: "If you light a lamp for somebody, it will also brighten your path.",
    attribution: "Buddha",
    theme: "Generosity",
    difficulty: "expert",
    clueWords: [
      { hint: "Set ablaze, kindle", word: "LIGHT" },
      { hint: "A small lighting device", word: "LAMP" },
      { hint: "Some person", word: "SOMEBODY" },
      { hint: "Make luminous", word: "BRIGHTEN" },
      { hint: "A walking route", word: "PATH" },
    ],
  },
  {
    id: "p229",
    quote: "Three things cannot be long hidden: the sun, the moon, and the truth.",
    attribution: "Buddha",
    theme: "Truth",
    difficulty: "expert",
    clueWords: [
      { hint: "Number after two", word: "THREE" },
      { hint: "Items or matters", word: "THINGS" },
      { hint: "Unable to", word: "CANNOT" },
      { hint: "Concealed", word: "HIDDEN" },
      { hint: "Star at center of solar system", word: "SUN" },
      { hint: "Earth's natural satellite", word: "MOON" },
      { hint: "Honesty, fact", word: "TRUTH" },
    ],
  },
  {
    id: "p230",
    quote: "Better than a thousand hollow words is one word that brings peace.",
    attribution: "Buddha",
    theme: "Peace",
    difficulty: "expert",
    clueWords: [
      { hint: "Preferable", word: "BETTER" },
      { hint: "10 hundreds", word: "THOUSAND" },
      { hint: "Empty, meaningless", word: "HOLLOW" },
      { hint: "Spoken units", word: "WORDS" },
      { hint: "Single", word: "ONE" },
      { hint: "Tranquility", word: "PEACE" },
    ],
  },
];
