import type { PuzzleRaw } from "../puzzleData";

/**
 * Batch 2 — 200 new puzzles (IDs p231–p430).
 *  • p231–p270: 40 easy
 *  • p271–p330: 60 medium
 *  • p331–p390: 60 hard
 *  • p391–p430: 40 expert
 */
export const BATCH2: PuzzleRaw[] = [
  // -------------------- EASY (40) --------------------
  {
    id: "p231",
    quote: "All good things must come to an end.",
    attribution: "Proverb",
    theme: "Acceptance",
    difficulty: "easy",
    clueWords: [
      { hint: "Each one", word: "ALL" },
      { hint: "Fine, worthy", word: "GOOD" },
      { hint: "Items or matters", word: "THINGS" },
      { hint: "The final point", word: "END" },
    ],
  },
  {
    id: "p232",
    quote: "Better safe than sorry.",
    attribution: "Proverb",
    theme: "Caution",
    difficulty: "easy",
    clueWords: [
      { hint: "Preferable", word: "BETTER" },
      { hint: "Out of harm's way", word: "SAFE" },
      { hint: "Regretful", word: "SORRY" },
    ],
  },
  {
    id: "p233",
    quote: "Beggars cannot be choosers.",
    attribution: "Proverb",
    theme: "Pragmatism",
    difficulty: "easy",
    clueWords: [
      { hint: "People asking for charity", word: "BEGGARS" },
      { hint: "Are not able to", word: "CANNOT" },
      { hint: "Those who select", word: "CHOOSERS" },
    ],
  },
  {
    id: "p234",
    quote: "Blood is thicker than water.",
    attribution: "Proverb",
    theme: "Family",
    difficulty: "easy",
    clueWords: [
      { hint: "Red bodily fluid", word: "BLOOD" },
      { hint: "More dense", word: "THICKER" },
      { hint: "Clear liquid we drink", word: "WATER" },
    ],
  },
  {
    id: "p235",
    quote: "Do not bite the hand that feeds you.",
    attribution: "Proverb",
    theme: "Gratitude",
    difficulty: "easy",
    clueWords: [
      { hint: "Use teeth on", word: "BITE" },
      { hint: "Body part with fingers", word: "HAND" },
      { hint: "Provides food to", word: "FEEDS" },
    ],
  },
  {
    id: "p236",
    quote: "Do not put all your eggs in one basket.",
    attribution: "Proverb",
    theme: "Caution",
    difficulty: "easy",
    clueWords: [
      { hint: "Place into", word: "PUT" },
      { hint: "Oval shells from hens", word: "EGGS" },
      { hint: "A woven container", word: "BASKET" },
      { hint: "Single", word: "ONE" },
    ],
  },
  {
    id: "p237",
    quote: "Familiarity breeds contempt.",
    attribution: "Proverb",
    theme: "Caution",
    difficulty: "easy",
    clueWords: [
      { hint: "Close acquaintance", word: "FAMILIARITY" },
      { hint: "Produces, generates", word: "BREEDS" },
      { hint: "Disdain or scorn", word: "CONTEMPT" },
    ],
  },
  {
    id: "p238",
    quote: "Give credit where credit is due.",
    attribution: "Proverb",
    theme: "Fairness",
    difficulty: "easy",
    clueWords: [
      { hint: "Hand over", word: "GIVE" },
      { hint: "Recognition or praise", word: "CREDIT" },
      { hint: "Owed or warranted", word: "DUE" },
      { hint: "At which place", word: "WHERE" },
    ],
  },
  {
    id: "p239",
    quote: "Good things come to those who wait.",
    attribution: "Proverb",
    theme: "Patience",
    difficulty: "easy",
    clueWords: [
      { hint: "Worthy or fine", word: "GOOD" },
      { hint: "Items", word: "THINGS" },
      { hint: "Arrive", word: "COME" },
      { hint: "Stay in expectation", word: "WAIT" },
      { hint: "Particular ones", word: "THOSE" },
    ],
  },
  {
    id: "p240",
    quote: "Great minds think alike.",
    attribution: "Proverb",
    theme: "Friendship",
    difficulty: "easy",
    clueWords: [
      { hint: "Outstanding", word: "GREAT" },
      { hint: "Thinking faculties", word: "MINDS" },
      { hint: "Use the brain", word: "THINK" },
      { hint: "Similarly", word: "ALIKE" },
    ],
  },
  {
    id: "p241",
    quote: "Home is where the heart is.",
    attribution: "Proverb",
    theme: "Belonging",
    difficulty: "easy",
    clueWords: [
      { hint: "Place of dwelling", word: "HOME" },
      { hint: "Pumping organ", word: "HEART" },
      { hint: "At which location", word: "WHERE" },
    ],
  },
  {
    id: "p242",
    quote: "If the shoe fits, wear it.",
    attribution: "Proverb",
    theme: "Acceptance",
    difficulty: "easy",
    clueWords: [
      { hint: "Foot covering", word: "SHOE" },
      { hint: "Is the right size", word: "FITS" },
      { hint: "Put on as clothing", word: "WEAR" },
      { hint: "On the condition that", word: "IF" },
    ],
  },
  {
    id: "p243",
    quote: "Ignorance is bliss.",
    attribution: "Thomas Gray",
    theme: "Mindset",
    difficulty: "easy",
    clueWords: [
      { hint: "Lack of knowledge", word: "IGNORANCE" },
      { hint: "Pure happiness", word: "BLISS" },
    ],
  },
  {
    id: "p244",
    quote: "It takes two to tango.",
    attribution: "Proverb",
    theme: "Cooperation",
    difficulty: "easy",
    clueWords: [
      { hint: "Requires", word: "TAKES" },
      { hint: "A pair", word: "TWO" },
      { hint: "A partner dance", word: "TANGO" },
    ],
  },
  {
    id: "p245",
    quote: "Laughter is the best medicine.",
    attribution: "Proverb",
    theme: "Joy",
    difficulty: "easy",
    clueWords: [
      { hint: "Sounds of joy", word: "LAUGHTER" },
      { hint: "Top quality", word: "BEST" },
      { hint: "A remedy or cure", word: "MEDICINE" },
    ],
  },
  {
    id: "p246",
    quote: "Make hay while the sun shines.",
    attribution: "Proverb",
    theme: "Timing",
    difficulty: "easy",
    clueWords: [
      { hint: "Produce", word: "MAKE" },
      { hint: "Dried grass for animals", word: "HAY" },
      { hint: "Star at center of solar system", word: "SUN" },
      { hint: "Glows brightly", word: "SHINES" },
    ],
  },
  {
    id: "p247",
    quote: "No man is an island.",
    attribution: "John Donne",
    theme: "Connection",
    difficulty: "easy",
    clueWords: [
      { hint: "Negation", word: "NO" },
      { hint: "Adult human male", word: "MAN" },
      { hint: "Land surrounded by water", word: "ISLAND" },
    ],
  },
  {
    id: "p248",
    quote: "No pain, no gain.",
    attribution: "Proverb",
    theme: "Effort",
    difficulty: "easy",
    clueWords: [
      { hint: "Negation", word: "NO" },
      { hint: "Suffering or hurt", word: "PAIN" },
      { hint: "Profit, increase", word: "GAIN" },
    ],
  },
  {
    id: "p249",
    quote: "Nothing ventured, nothing gained.",
    attribution: "Proverb",
    theme: "Risk",
    difficulty: "easy",
    clueWords: [
      { hint: "Not anything", word: "NOTHING" },
      { hint: "Risked, dared", word: "VENTURED" },
      { hint: "Earned, obtained", word: "GAINED" },
    ],
  },
  {
    id: "p250",
    quote: "Opposites attract.",
    attribution: "Proverb",
    theme: "Connection",
    difficulty: "easy",
    clueWords: [
      { hint: "Things that contrast", word: "OPPOSITES" },
      { hint: "Pull together", word: "ATTRACT" },
    ],
  },
  {
    id: "p251",
    quote: "Practice what you preach.",
    attribution: "Proverb",
    theme: "Integrity",
    difficulty: "easy",
    clueWords: [
      { hint: "Carry out repeatedly", word: "PRACTICE" },
      { hint: "Teach or advocate", word: "PREACH" },
    ],
  },
  {
    id: "p252",
    quote: "Pride comes before a fall.",
    attribution: "Proverb",
    theme: "Humility",
    difficulty: "easy",
    clueWords: [
      { hint: "Excessive self-esteem", word: "PRIDE" },
      { hint: "Arrives", word: "COMES" },
      { hint: "Earlier than", word: "BEFORE" },
      { hint: "A descent or downfall", word: "FALL" },
    ],
  },
  {
    id: "p253",
    quote: "Old habits die hard.",
    attribution: "Proverb",
    theme: "Habit",
    difficulty: "easy",
    clueWords: [
      { hint: "Aged or longstanding", word: "OLD" },
      { hint: "Repeated behaviors", word: "HABITS" },
      { hint: "Cease, perish", word: "DIE" },
      { hint: "Difficult, with effort", word: "HARD" },
    ],
  },
  {
    id: "p254",
    quote: "The grass is always greener on the other side.",
    attribution: "Proverb",
    theme: "Envy",
    difficulty: "easy",
    clueWords: [
      { hint: "Lawn plant", word: "GRASS" },
      { hint: "More verdant", word: "GREENER" },
      { hint: "At all times", word: "ALWAYS" },
      { hint: "Different", word: "OTHER" },
      { hint: "The far edge", word: "SIDE" },
    ],
  },
  {
    id: "p255",
    quote: "Time heals all wounds.",
    attribution: "Proverb",
    theme: "Healing",
    difficulty: "easy",
    clueWords: [
      { hint: "Hours and days", word: "TIME" },
      { hint: "Cures, mends", word: "HEALS" },
      { hint: "Each, every", word: "ALL" },
      { hint: "Injuries", word: "WOUNDS" },
    ],
  },
  {
    id: "p256",
    quote: "Too many cooks spoil the broth.",
    attribution: "Proverb",
    theme: "Teamwork",
    difficulty: "easy",
    clueWords: [
      { hint: "Excessively", word: "TOO" },
      { hint: "A great number", word: "MANY" },
      { hint: "Kitchen workers", word: "COOKS" },
      { hint: "Ruin or damage", word: "SPOIL" },
      { hint: "A clear soup", word: "BROTH" },
    ],
  },
  {
    id: "p257",
    quote: "Truth is stranger than fiction.",
    attribution: "Mark Twain",
    theme: "Truth",
    difficulty: "easy",
    clueWords: [
      { hint: "Honest reality", word: "TRUTH" },
      { hint: "More unusual", word: "STRANGER" },
      { hint: "Made-up stories", word: "FICTION" },
    ],
  },
  {
    id: "p258",
    quote: "Variety is the spice of life.",
    attribution: "William Cowper",
    theme: "Joy",
    difficulty: "easy",
    clueWords: [
      { hint: "Diversity, range", word: "VARIETY" },
      { hint: "A flavoring", word: "SPICE" },
      { hint: "Existence", word: "LIFE" },
    ],
  },
  {
    id: "p259",
    quote: "What goes around comes around.",
    attribution: "Proverb",
    theme: "Karma",
    difficulty: "easy",
    clueWords: [
      { hint: "Travels", word: "GOES" },
      { hint: "In a circle", word: "AROUND" },
      { hint: "Returns", word: "COMES" },
    ],
  },
  {
    id: "p260",
    quote: "When the going gets tough, the tough get going.",
    attribution: "Proverb",
    theme: "Resilience",
    difficulty: "easy",
    clueWords: [
      { hint: "Progress, journey", word: "GOING" },
      { hint: "Become", word: "GETS" },
      { hint: "Hard, demanding", word: "TOUGH" },
      { hint: "Become or acquire", word: "GET" },
    ],
  },
  {
    id: "p261",
    quote: "You reap what you sow.",
    attribution: "Proverb",
    theme: "Karma",
    difficulty: "easy",
    clueWords: [
      { hint: "Harvest, gather", word: "REAP" },
      { hint: "Plant seeds", word: "SOW" },
      { hint: "Anything that", word: "WHAT" },
    ],
  },
  {
    id: "p262",
    quote: "Absence makes the heart grow fonder.",
    attribution: "Proverb",
    theme: "Love",
    difficulty: "easy",
    clueWords: [
      { hint: "Being away", word: "ABSENCE" },
      { hint: "Causes, produces", word: "MAKES" },
      { hint: "The pumping organ", word: "HEART" },
      { hint: "Become", word: "GROW" },
      { hint: "More affectionate", word: "FONDER" },
    ],
  },
  {
    id: "p263",
    quote: "An ounce of prevention is worth a pound of cure.",
    attribution: "Benjamin Franklin",
    theme: "Prudence",
    difficulty: "easy",
    clueWords: [
      { hint: "A small unit of weight", word: "OUNCE" },
      { hint: "Stopping in advance", word: "PREVENTION" },
      { hint: "Of value", word: "WORTH" },
      { hint: "Larger weight unit", word: "POUND" },
      { hint: "Healing remedy", word: "CURE" },
    ],
  },
  {
    id: "p264",
    quote: "Better the devil you know.",
    attribution: "Proverb",
    theme: "Caution",
    difficulty: "easy",
    clueWords: [
      { hint: "More acceptable", word: "BETTER" },
      { hint: "An evil being", word: "DEVIL" },
      { hint: "Are familiar with", word: "KNOW" },
    ],
  },
  {
    id: "p265",
    quote: "Beauty is only skin deep.",
    attribution: "Proverb",
    theme: "Character",
    difficulty: "easy",
    clueWords: [
      { hint: "Loveliness", word: "BEAUTY" },
      { hint: "Solely, just", word: "ONLY" },
      { hint: "The outer body covering", word: "SKIN" },
      { hint: "Far below the surface", word: "DEEP" },
    ],
  },
  {
    id: "p266",
    quote: "Charity begins at home.",
    attribution: "Proverb",
    theme: "Family",
    difficulty: "easy",
    clueWords: [
      { hint: "Generosity, kindness", word: "CHARITY" },
      { hint: "Starts", word: "BEGINS" },
      { hint: "Place of dwelling", word: "HOME" },
    ],
  },
  {
    id: "p267",
    quote: "Discretion is the better part of valor.",
    attribution: "William Shakespeare",
    theme: "Wisdom",
    difficulty: "easy",
    clueWords: [
      { hint: "Cautious judgment", word: "DISCRETION" },
      { hint: "More desirable", word: "BETTER" },
      { hint: "A portion", word: "PART" },
      { hint: "Bravery", word: "VALOR" },
    ],
  },
  {
    id: "p268",
    quote: "Empty vessels make the most noise.",
    attribution: "Proverb",
    theme: "Wisdom",
    difficulty: "easy",
    clueWords: [
      { hint: "Containing nothing", word: "EMPTY" },
      { hint: "Containers", word: "VESSELS" },
      { hint: "Produce", word: "MAKE" },
      { hint: "Loud sound", word: "NOISE" },
      { hint: "The greatest amount", word: "MOST" },
    ],
  },
  {
    id: "p269",
    quote: "Every dog has its day.",
    attribution: "Proverb",
    theme: "Hope",
    difficulty: "easy",
    clueWords: [
      { hint: "Each one", word: "EVERY" },
      { hint: "A loyal canine pet", word: "DOG" },
      { hint: "Possesses", word: "HAS" },
      { hint: "A 24-hour period", word: "DAY" },
    ],
  },
  {
    id: "p270",
    quote: "If at first you do not succeed, try again.",
    attribution: "Proverb",
    theme: "Persistence",
    difficulty: "easy",
    clueWords: [
      { hint: "Initially", word: "FIRST" },
      { hint: "Achieve", word: "SUCCEED" },
      { hint: "Make an attempt", word: "TRY" },
      { hint: "One more time", word: "AGAIN" },
    ],
  },

  // -------------------- MEDIUM (60) --------------------
  {
    id: "p271",
    quote: "The best way out is always through.",
    attribution: "Robert Frost",
    theme: "Perseverance",
    difficulty: "medium",
    clueWords: [
      { hint: "Top in quality", word: "BEST" },
      { hint: "A method or path", word: "WAY" },
      { hint: "Outside of", word: "OUT" },
      { hint: "Constantly", word: "ALWAYS" },
      { hint: "From end to end", word: "THROUGH" },
    ],
  },
  {
    id: "p272",
    quote: "There is no path to peace; peace is the path.",
    attribution: "Mahatma Gandhi",
    theme: "Peace",
    difficulty: "medium",
    clueWords: [
      { hint: "A walking route", word: "PATH" },
      { hint: "Tranquility", word: "PEACE" },
      { hint: "Negation", word: "NO" },
      { hint: "Exists", word: "IS" },
    ],
  },
  {
    id: "p273",
    quote: "Where flowers bloom, so does hope.",
    attribution: "Lady Bird Johnson",
    theme: "Hope",
    difficulty: "medium",
    clueWords: [
      { hint: "Plants with petals", word: "FLOWERS" },
      { hint: "Open and flourish", word: "BLOOM" },
      { hint: "Optimistic feeling", word: "HOPE" },
      { hint: "At which place", word: "WHERE" },
    ],
  },
  {
    id: "p274",
    quote: "Speak the truth, even if your voice shakes.",
    attribution: "Maggie Kuhn",
    theme: "Honesty",
    difficulty: "medium",
    clueWords: [
      { hint: "Utter aloud", word: "SPEAK" },
      { hint: "Honest reality", word: "TRUTH" },
      { hint: "Sound from your throat", word: "VOICE" },
      { hint: "Trembles", word: "SHAKES" },
      { hint: "On the condition that", word: "IF" },
    ],
  },
  {
    id: "p275",
    quote: "Be kind whenever possible. It is always possible.",
    attribution: "Dalai Lama",
    theme: "Kindness",
    difficulty: "medium",
    clueWords: [
      { hint: "Considerate, caring", word: "KIND" },
      { hint: "At any time that", word: "WHENEVER" },
      { hint: "Capable of being done", word: "POSSIBLE" },
      { hint: "All the time", word: "ALWAYS" },
    ],
  },
  {
    id: "p276",
    quote: "Peace begins with a smile.",
    attribution: "Mother Teresa",
    theme: "Peace",
    difficulty: "medium",
    clueWords: [
      { hint: "Tranquility", word: "PEACE" },
      { hint: "Starts", word: "BEGINS" },
      { hint: "An expression of joy", word: "SMILE" },
      { hint: "Together with", word: "WITH" },
    ],
  },
  {
    id: "p277",
    quote: "If you want others to be happy, practice compassion.",
    attribution: "Dalai Lama",
    theme: "Compassion",
    difficulty: "medium",
    clueWords: [
      { hint: "Desire", word: "WANT" },
      { hint: "Other people", word: "OTHERS" },
      { hint: "Joyful", word: "HAPPY" },
      { hint: "Repeatedly engage in", word: "PRACTICE" },
      { hint: "Sympathetic concern", word: "COMPASSION" },
    ],
  },
  {
    id: "p278",
    quote: "Three things in life are important: to be kind, to be kind, and to be kind.",
    attribution: "Henry James",
    theme: "Kindness",
    difficulty: "medium",
    clueWords: [
      { hint: "Number after two", word: "THREE" },
      { hint: "Items, matters", word: "THINGS" },
      { hint: "Existence", word: "LIFE" },
      { hint: "Significant", word: "IMPORTANT" },
      { hint: "Considerate", word: "KIND" },
    ],
  },
  {
    id: "p279",
    quote: "Faith is taking the first step even when you cannot see the whole staircase.",
    attribution: "Martin Luther King Jr.",
    theme: "Faith",
    difficulty: "medium",
    clueWords: [
      { hint: "Trust or belief", word: "FAITH" },
      { hint: "Initial", word: "FIRST" },
      { hint: "A pace", word: "STEP" },
      { hint: "Perceive with eyes", word: "SEE" },
      { hint: "Entire", word: "WHOLE" },
      { hint: "A flight of steps", word: "STAIRCASE" },
    ],
  },
  {
    id: "p280",
    quote: "Discontent is the first step in progress.",
    attribution: "Oscar Wilde",
    theme: "Growth",
    difficulty: "medium",
    clueWords: [
      { hint: "Dissatisfaction", word: "DISCONTENT" },
      { hint: "Initial", word: "FIRST" },
      { hint: "A pace", word: "STEP" },
      { hint: "Forward motion", word: "PROGRESS" },
    ],
  },
  {
    id: "p281",
    quote: "We become what we think about.",
    attribution: "Earl Nightingale",
    theme: "Mindset",
    difficulty: "medium",
    clueWords: [
      { hint: "Turn into", word: "BECOME" },
      { hint: "Use the mind", word: "THINK" },
      { hint: "First-person plural", word: "WE" },
      { hint: "Concerning", word: "ABOUT" },
    ],
  },
  {
    id: "p282",
    quote: "Anything worth having is worth waiting for.",
    attribution: "Proverb",
    theme: "Patience",
    difficulty: "medium",
    clueWords: [
      { hint: "Any object", word: "ANYTHING" },
      { hint: "Of value", word: "WORTH" },
      { hint: "Possessing", word: "HAVING" },
      { hint: "Staying patiently", word: "WAITING" },
    ],
  },
  {
    id: "p283",
    quote: "What we love we shall grow to resemble.",
    attribution: "Bernard of Clairvaux",
    theme: "Growth",
    difficulty: "medium",
    clueWords: [
      { hint: "Cherish deeply", word: "LOVE" },
      { hint: "Develop, become", word: "GROW" },
      { hint: "Look like", word: "RESEMBLE" },
      { hint: "Will, must", word: "SHALL" },
    ],
  },
  {
    id: "p284",
    quote: "It does not do to dwell on dreams and forget to live.",
    attribution: "J.K. Rowling",
    theme: "Mindfulness",
    difficulty: "medium",
    clueWords: [
      { hint: "Linger over", word: "DWELL" },
      { hint: "Aspirations", word: "DREAMS" },
      { hint: "Lose memory of", word: "FORGET" },
      { hint: "Be alive", word: "LIVE" },
    ],
  },
  {
    id: "p285",
    quote: "We must let go of the life we have planned to accept the one waiting for us.",
    attribution: "Joseph Campbell",
    theme: "Acceptance",
    difficulty: "medium",
    clueWords: [
      { hint: "Release", word: "LET" },
      { hint: "Existence", word: "LIFE" },
      { hint: "Schemed, designed", word: "PLANNED" },
      { hint: "Receive willingly", word: "ACCEPT" },
      { hint: "Staying patiently", word: "WAITING" },
    ],
  },
  {
    id: "p286",
    quote: "Wherever you go, go with all your heart.",
    attribution: "Confucius",
    theme: "Commitment",
    difficulty: "medium",
    clueWords: [
      { hint: "In any place that", word: "WHEREVER" },
      { hint: "Travel, proceed", word: "GO" },
      { hint: "Each, every", word: "ALL" },
      { hint: "Pumping organ", word: "HEART" },
      { hint: "Belonging to you", word: "YOUR" },
    ],
  },
  {
    id: "p287",
    quote: "When you cannot find peace within yourself, it is useless to seek it elsewhere.",
    attribution: "La Rochefoucauld",
    theme: "Inner Peace",
    difficulty: "medium",
    clueWords: [
      { hint: "Discover", word: "FIND" },
      { hint: "Tranquility", word: "PEACE" },
      { hint: "Inside, inside of", word: "WITHIN" },
      { hint: "Of no use", word: "USELESS" },
      { hint: "Search for", word: "SEEK" },
      { hint: "In another place", word: "ELSEWHERE" },
    ],
  },
  {
    id: "p288",
    quote: "Yesterday is gone. Tomorrow has not yet come. We have only today.",
    attribution: "Mother Teresa",
    theme: "Mindfulness",
    difficulty: "medium",
    clueWords: [
      { hint: "The day before", word: "YESTERDAY" },
      { hint: "The day after today", word: "TOMORROW" },
      { hint: "The current day", word: "TODAY" },
      { hint: "Departed", word: "GONE" },
      { hint: "Up to this moment", word: "YET" },
    ],
  },
  {
    id: "p289",
    quote: "Real generosity toward the future lies in giving all to the present.",
    attribution: "Albert Camus",
    theme: "Generosity",
    difficulty: "medium",
    clueWords: [
      { hint: "Genuine", word: "REAL" },
      { hint: "Munificence", word: "GENEROSITY" },
      { hint: "Time yet to come", word: "FUTURE" },
      { hint: "Bestowing", word: "GIVING" },
      { hint: "Current moment", word: "PRESENT" },
    ],
  },
  {
    id: "p290",
    quote: "If we wait until we are ready, we will be waiting for the rest of our lives.",
    attribution: "Lemony Snicket",
    theme: "Initiative",
    difficulty: "medium",
    clueWords: [
      { hint: "Stay in expectation", word: "WAIT" },
      { hint: "Prepared", word: "READY" },
      { hint: "Existences", word: "LIVES" },
      { hint: "Remaining portion", word: "REST" },
    ],
  },
  {
    id: "p291",
    quote: "Beware of the half truth. You may have gotten hold of the wrong half.",
    attribution: "Anonymous",
    theme: "Caution",
    difficulty: "medium",
    clueWords: [
      { hint: "Be cautious of", word: "BEWARE" },
      { hint: "One of two equal parts", word: "HALF" },
      { hint: "Honest reality", word: "TRUTH" },
      { hint: "Grasp, grip", word: "HOLD" },
      { hint: "Incorrect, mistaken", word: "WRONG" },
    ],
  },
  {
    id: "p292",
    quote: "What sunshine is to flowers, smiles are to humanity.",
    attribution: "Joseph Addison",
    theme: "Kindness",
    difficulty: "medium",
    clueWords: [
      { hint: "Light from the sun", word: "SUNSHINE" },
      { hint: "Plants with petals", word: "FLOWERS" },
      { hint: "Friendly facial expressions", word: "SMILES" },
      { hint: "All people", word: "HUMANITY" },
    ],
  },
  {
    id: "p293",
    quote: "An ounce of action is worth a ton of theory.",
    attribution: "Friedrich Engels",
    theme: "Action",
    difficulty: "medium",
    clueWords: [
      { hint: "A small unit of weight", word: "OUNCE" },
      { hint: "A deed", word: "ACTION" },
      { hint: "Of value", word: "WORTH" },
      { hint: "A large weight unit", word: "TON" },
      { hint: "An idea or principle", word: "THEORY" },
    ],
  },
  {
    id: "p294",
    quote: "It is not how much we have, but how much we enjoy that makes happiness.",
    attribution: "Charles Spurgeon",
    theme: "Happiness",
    difficulty: "medium",
    clueWords: [
      { hint: "What quantity", word: "MUCH" },
      { hint: "Possess", word: "HAVE" },
      { hint: "Take pleasure in", word: "ENJOY" },
      { hint: "Causes", word: "MAKES" },
      { hint: "Joyful state", word: "HAPPINESS" },
    ],
  },
  {
    id: "p295",
    quote: "Patience is the companion of wisdom.",
    attribution: "Saint Augustine",
    theme: "Wisdom",
    difficulty: "medium",
    clueWords: [
      { hint: "Calm endurance", word: "PATIENCE" },
      { hint: "An associate", word: "COMPANION" },
      { hint: "Deep insight", word: "WISDOM" },
    ],
  },
  {
    id: "p296",
    quote: "We rise by lifting others.",
    attribution: "Robert Ingersoll",
    theme: "Service",
    difficulty: "medium",
    clueWords: [
      { hint: "Ascend", word: "RISE" },
      { hint: "Raising up", word: "LIFTING" },
      { hint: "Other people", word: "OTHERS" },
    ],
  },
  {
    id: "p297",
    quote: "Begin at the beginning and go on till you come to the end.",
    attribution: "Lewis Carroll",
    theme: "Action",
    difficulty: "medium",
    clueWords: [
      { hint: "Start", word: "BEGIN" },
      { hint: "The starting point", word: "BEGINNING" },
      { hint: "Travel forward", word: "GO" },
      { hint: "Until", word: "TILL" },
      { hint: "The final point", word: "END" },
      { hint: "Arrive", word: "COME" },
    ],
  },
  {
    id: "p298",
    quote: "Truth is mighty and will prevail.",
    attribution: "Sojourner Truth",
    theme: "Truth",
    difficulty: "medium",
    clueWords: [
      { hint: "Honest reality", word: "TRUTH" },
      { hint: "Powerful, strong", word: "MIGHTY" },
      { hint: "Triumph in the end", word: "PREVAIL" },
    ],
  },
  {
    id: "p299",
    quote: "Hold on, when there is nothing in you except the will which says hold on.",
    attribution: "Rudyard Kipling",
    theme: "Resilience",
    difficulty: "medium",
    clueWords: [
      { hint: "Grasp tightly", word: "HOLD" },
      { hint: "Not anything", word: "NOTHING" },
      { hint: "Determination", word: "WILL" },
      { hint: "Utters, states", word: "SAYS" },
      { hint: "Apart from, save", word: "EXCEPT" },
    ],
  },
  {
    id: "p300",
    quote: "Difficulties strengthen the mind, as labor does the body.",
    attribution: "Seneca",
    theme: "Adversity",
    difficulty: "medium",
    clueWords: [
      { hint: "Hardships", word: "DIFFICULTIES" },
      { hint: "Make stronger", word: "STRENGTHEN" },
      { hint: "Thinking faculty", word: "MIND" },
      { hint: "Hard work", word: "LABOR" },
      { hint: "Physical form", word: "BODY" },
    ],
  },
  {
    id: "p301",
    quote: "There is always a way if you are not in a hurry.",
    attribution: "Anonymous",
    theme: "Patience",
    difficulty: "medium",
    clueWords: [
      { hint: "All the time", word: "ALWAYS" },
      { hint: "A path or method", word: "WAY" },
      { hint: "Rushed haste", word: "HURRY" },
      { hint: "On the condition that", word: "IF" },
    ],
  },
  {
    id: "p302",
    quote: "Live in the sunshine. Swim in the sea. Drink the wild air.",
    attribution: "Ralph Waldo Emerson",
    theme: "Nature",
    difficulty: "medium",
    clueWords: [
      { hint: "Be alive", word: "LIVE" },
      { hint: "Light from the sun", word: "SUNSHINE" },
      { hint: "Move through water", word: "SWIM" },
      { hint: "Vast salty water", word: "SEA" },
      { hint: "Take in liquid", word: "DRINK" },
      { hint: "What we breathe", word: "AIR" },
    ],
  },
  {
    id: "p303",
    quote: "There is no progress without struggle.",
    attribution: "Frederick Douglass",
    theme: "Effort",
    difficulty: "medium",
    clueWords: [
      { hint: "Forward motion", word: "PROGRESS" },
      { hint: "Without something", word: "WITHOUT" },
      { hint: "Hard effort, fight", word: "STRUGGLE" },
    ],
  },
  {
    id: "p304",
    quote: "Do not wait for the perfect moment. Take the moment and make it perfect.",
    attribution: "Anonymous",
    theme: "Initiative",
    difficulty: "medium",
    clueWords: [
      { hint: "Stay in expectation", word: "WAIT" },
      { hint: "Without flaw", word: "PERFECT" },
      { hint: "An instant", word: "MOMENT" },
      { hint: "Grab, seize", word: "TAKE" },
      { hint: "Cause", word: "MAKE" },
    ],
  },
  {
    id: "p305",
    quote: "If you cannot stop the wind, learn to sail.",
    attribution: "Anonymous",
    theme: "Adaptability",
    difficulty: "medium",
    clueWords: [
      { hint: "Cease", word: "STOP" },
      { hint: "Moving air", word: "WIND" },
      { hint: "Acquire knowledge", word: "LEARN" },
      { hint: "Travel by boat", word: "SAIL" },
    ],
  },
  {
    id: "p306",
    quote: "Comparison is the thief of joy.",
    attribution: "Theodore Roosevelt",
    theme: "Contentment",
    difficulty: "medium",
    clueWords: [
      { hint: "Measuring against", word: "COMPARISON" },
      { hint: "A robber", word: "THIEF" },
      { hint: "Happiness, delight", word: "JOY" },
    ],
  },
  {
    id: "p307",
    quote: "Yesterday's home runs do not win today's games.",
    attribution: "Babe Ruth",
    theme: "Mindset",
    difficulty: "medium",
    clueWords: [
      { hint: "Place of dwelling", word: "HOME" },
      { hint: "Sprints, jogs", word: "RUNS" },
      { hint: "Be victorious", word: "WIN" },
      { hint: "Sporting contests", word: "GAMES" },
      { hint: "Belonging to today", word: "TODAY" },
    ],
  },
  {
    id: "p308",
    quote: "Trust yourself. You know more than you think you do.",
    attribution: "Benjamin Spock",
    theme: "Confidence",
    difficulty: "medium",
    clueWords: [
      { hint: "Have confidence in", word: "TRUST" },
      { hint: "Your own person", word: "YOURSELF" },
      { hint: "Are aware of", word: "KNOW" },
      { hint: "Use your mind", word: "THINK" },
      { hint: "To a greater extent", word: "MORE" },
    ],
  },
  {
    id: "p309",
    quote: "Sometimes the bad things put us on the path to the best things.",
    attribution: "Anonymous",
    theme: "Hope",
    difficulty: "medium",
    clueWords: [
      { hint: "On occasion", word: "SOMETIMES" },
      { hint: "Of poor quality", word: "BAD" },
      { hint: "A walking route", word: "PATH" },
      { hint: "Top quality", word: "BEST" },
      { hint: "Items, matters", word: "THINGS" },
    ],
  },
  {
    id: "p310",
    quote: "We may have all come on different ships, but we are in the same boat now.",
    attribution: "Martin Luther King Jr.",
    theme: "Unity",
    difficulty: "medium",
    clueWords: [
      { hint: "Possibly", word: "MAY" },
      { hint: "Arrive", word: "COME" },
      { hint: "Not the same", word: "DIFFERENT" },
      { hint: "Large vessels", word: "SHIPS" },
      { hint: "Identical", word: "SAME" },
      { hint: "Small water vessel", word: "BOAT" },
    ],
  },
  {
    id: "p311",
    quote: "Saying nothing sometimes says the most.",
    attribution: "Emily Dickinson",
    theme: "Communication",
    difficulty: "medium",
    clueWords: [
      { hint: "Stating verbally", word: "SAYING" },
      { hint: "Not anything", word: "NOTHING" },
      { hint: "On occasion", word: "SOMETIMES" },
      { hint: "Communicates", word: "SAYS" },
      { hint: "Greatest amount", word: "MOST" },
    ],
  },
  {
    id: "p312",
    quote: "Be a voice, not an echo.",
    attribution: "Albert Einstein",
    theme: "Originality",
    difficulty: "medium",
    clueWords: [
      { hint: "Speaking instrument", word: "VOICE" },
      { hint: "Repeating sound", word: "ECHO" },
      { hint: "Negation", word: "NOT" },
    ],
  },
  {
    id: "p313",
    quote: "Find joy in the journey.",
    attribution: "Anonymous",
    theme: "Joy",
    difficulty: "medium",
    clueWords: [
      { hint: "Discover", word: "FIND" },
      { hint: "Happiness", word: "JOY" },
      { hint: "A long trip", word: "JOURNEY" },
    ],
  },
  {
    id: "p314",
    quote: "Light tomorrow with today.",
    attribution: "Elizabeth Barrett Browning",
    theme: "Action",
    difficulty: "medium",
    clueWords: [
      { hint: "Illuminate, brighten", word: "LIGHT" },
      { hint: "The day after today", word: "TOMORROW" },
      { hint: "The current day", word: "TODAY" },
    ],
  },
  {
    id: "p315",
    quote: "Quietness is the safeguard of wisdom.",
    attribution: "Anonymous",
    theme: "Mindfulness",
    difficulty: "medium",
    clueWords: [
      { hint: "Stillness, hush", word: "QUIETNESS" },
      { hint: "Protection", word: "SAFEGUARD" },
      { hint: "Deep insight", word: "WISDOM" },
    ],
  },
  {
    id: "p316",
    quote: "Live each day as it comes.",
    attribution: "Proverb",
    theme: "Mindfulness",
    difficulty: "medium",
    clueWords: [
      { hint: "Be alive", word: "LIVE" },
      { hint: "Every", word: "EACH" },
      { hint: "A 24-hour period", word: "DAY" },
      { hint: "Arrives", word: "COMES" },
    ],
  },
  {
    id: "p317",
    quote: "The greatest gift of life is friendship.",
    attribution: "Hubert Humphrey",
    theme: "Friendship",
    difficulty: "medium",
    clueWords: [
      { hint: "Best, largest", word: "GREATEST" },
      { hint: "A present", word: "GIFT" },
      { hint: "Existence", word: "LIFE" },
      { hint: "Mutual affection", word: "FRIENDSHIP" },
    ],
  },
  {
    id: "p318",
    quote: "Walk slowly and live with intention.",
    attribution: "Anonymous",
    theme: "Mindfulness",
    difficulty: "medium",
    clueWords: [
      { hint: "Move on foot", word: "WALK" },
      { hint: "Without haste", word: "SLOWLY" },
      { hint: "Be alive", word: "LIVE" },
      { hint: "Purposeful aim", word: "INTENTION" },
    ],
  },
  {
    id: "p319",
    quote: "Begin again, this time as a beginner.",
    attribution: "Anonymous",
    theme: "Renewal",
    difficulty: "medium",
    clueWords: [
      { hint: "Start", word: "BEGIN" },
      { hint: "Once more", word: "AGAIN" },
      { hint: "An occasion", word: "TIME" },
      { hint: "A novice", word: "BEGINNER" },
    ],
  },
  {
    id: "p320",
    quote: "Bad weather always looks worse through a window.",
    attribution: "Tom Lehrer",
    theme: "Perspective",
    difficulty: "medium",
    clueWords: [
      { hint: "Of poor quality", word: "BAD" },
      { hint: "Atmospheric conditions", word: "WEATHER" },
      { hint: "All the time", word: "ALWAYS" },
      { hint: "More unpleasant", word: "WORSE" },
      { hint: "Glass opening", word: "WINDOW" },
    ],
  },
  {
    id: "p321",
    quote: "Small steps in the right direction can turn out to be the biggest step.",
    attribution: "Anonymous",
    theme: "Progress",
    difficulty: "medium",
    clueWords: [
      { hint: "Little, not big", word: "SMALL" },
      { hint: "Paces forward", word: "STEPS" },
      { hint: "Correct", word: "RIGHT" },
      { hint: "Course or heading", word: "DIRECTION" },
      { hint: "Largest", word: "BIGGEST" },
    ],
  },
  {
    id: "p322",
    quote: "Go where you are celebrated, not just tolerated.",
    attribution: "Anonymous",
    theme: "Self-Worth",
    difficulty: "medium",
    clueWords: [
      { hint: "Travel", word: "GO" },
      { hint: "Honored, praised", word: "CELEBRATED" },
      { hint: "Endured, accepted", word: "TOLERATED" },
      { hint: "At which place", word: "WHERE" },
    ],
  },
  {
    id: "p323",
    quote: "Worry is a misuse of imagination.",
    attribution: "Dan Zadra",
    theme: "Mindset",
    difficulty: "medium",
    clueWords: [
      { hint: "Anxious thought", word: "WORRY" },
      { hint: "Wrong use", word: "MISUSE" },
      { hint: "Mental creativity", word: "IMAGINATION" },
    ],
  },
  {
    id: "p324",
    quote: "If you want to lift yourself up, lift up someone else.",
    attribution: "Booker T. Washington",
    theme: "Service",
    difficulty: "medium",
    clueWords: [
      { hint: "Desire", word: "WANT" },
      { hint: "Raise upward", word: "LIFT" },
      { hint: "Your own person", word: "YOURSELF" },
      { hint: "Some person", word: "SOMEONE" },
      { hint: "Apart from", word: "ELSE" },
    ],
  },
  {
    id: "p325",
    quote: "Choose people who lift you up.",
    attribution: "Michelle Obama",
    theme: "Friendship",
    difficulty: "medium",
    clueWords: [
      { hint: "Make a selection", word: "CHOOSE" },
      { hint: "Human beings", word: "PEOPLE" },
      { hint: "Raise upward", word: "LIFT" },
    ],
  },
  {
    id: "p326",
    quote: "Joy comes from using your potential.",
    attribution: "Will Schultz",
    theme: "Joy",
    difficulty: "medium",
    clueWords: [
      { hint: "Happiness", word: "JOY" },
      { hint: "Arrives", word: "COMES" },
      { hint: "Employing", word: "USING" },
      { hint: "Your inner capability", word: "POTENTIAL" },
    ],
  },
  {
    id: "p327",
    quote: "What you do today can improve all your tomorrows.",
    attribution: "Ralph Marston",
    theme: "Action",
    difficulty: "medium",
    clueWords: [
      { hint: "Perform", word: "DO" },
      { hint: "The current day", word: "TODAY" },
      { hint: "Make better", word: "IMPROVE" },
      { hint: "Each, every", word: "ALL" },
      { hint: "Days to come", word: "TOMORROWS" },
    ],
  },
  {
    id: "p328",
    quote: "We grow great by dreams.",
    attribution: "Woodrow Wilson",
    theme: "Aspiration",
    difficulty: "medium",
    clueWords: [
      { hint: "Develop", word: "GROW" },
      { hint: "Outstanding", word: "GREAT" },
      { hint: "Aspirations, hopes", word: "DREAMS" },
      { hint: "First-person plural", word: "WE" },
    ],
  },
  {
    id: "p329",
    quote: "A goal without a plan is just a wish.",
    attribution: "Antoine de Saint-Exupery",
    theme: "Planning",
    difficulty: "medium",
    clueWords: [
      { hint: "An aim or target", word: "GOAL" },
      { hint: "A scheme or design", word: "PLAN" },
      { hint: "A hope or desire", word: "WISH" },
      { hint: "Lacking, devoid of", word: "WITHOUT" },
    ],
  },
  {
    id: "p330",
    quote: "Whatever you can do, or dream you can, begin it.",
    attribution: "Goethe",
    theme: "Initiative",
    difficulty: "medium",
    clueWords: [
      { hint: "Anything that", word: "WHATEVER" },
      { hint: "Are able to", word: "CAN" },
      { hint: "Imagine in sleep", word: "DREAM" },
      { hint: "Start", word: "BEGIN" },
      { hint: "Perform", word: "DO" },
    ],
  },

  // -------------------- HARD (60) --------------------
  {
    id: "p331",
    quote: "I am not what happened to me, I am what I choose to become.",
    attribution: "Carl Jung",
    theme: "Identity",
    difficulty: "hard",
    clueWords: [
      { hint: "Took place", word: "HAPPENED" },
      { hint: "Make a selection", word: "CHOOSE" },
      { hint: "Turn into", word: "BECOME" },
      { hint: "Anything that", word: "WHAT" },
    ],
  },
  {
    id: "p332",
    quote: "Everything that irritates us about others can lead us to understanding ourselves.",
    attribution: "Carl Jung",
    theme: "Self-Knowledge",
    difficulty: "hard",
    clueWords: [
      { hint: "Each thing", word: "EVERYTHING" },
      { hint: "Annoys", word: "IRRITATES" },
      { hint: "Other people", word: "OTHERS" },
      { hint: "Guide", word: "LEAD" },
      { hint: "Comprehending", word: "UNDERSTANDING" },
      { hint: "Our own selves", word: "OURSELVES" },
    ],
  },
  {
    id: "p333",
    quote: "The most terrifying thing is to accept oneself completely.",
    attribution: "Carl Jung",
    theme: "Self-Acceptance",
    difficulty: "hard",
    clueWords: [
      { hint: "Greatest amount", word: "MOST" },
      { hint: "Frightening", word: "TERRIFYING" },
      { hint: "Item or matter", word: "THING" },
      { hint: "Receive willingly", word: "ACCEPT" },
      { hint: "One's own person", word: "ONESELF" },
      { hint: "Wholly, fully", word: "COMPLETELY" },
    ],
  },
  {
    id: "p334",
    quote: "Knowledge is of two kinds; we know a subject, or we know where to find it.",
    attribution: "Samuel Johnson",
    theme: "Learning",
    difficulty: "hard",
    clueWords: [
      { hint: "Information mastered", word: "KNOWLEDGE" },
      { hint: "A pair", word: "TWO" },
      { hint: "Are aware of", word: "KNOW" },
      { hint: "Topic of study", word: "SUBJECT" },
      { hint: "Discover, locate", word: "FIND" },
      { hint: "At which place", word: "WHERE" },
    ],
  },
  {
    id: "p335",
    quote: "Without freedom of thought there can be no such thing as wisdom.",
    attribution: "Benjamin Franklin",
    theme: "Wisdom",
    difficulty: "hard",
    clueWords: [
      { hint: "Lacking", word: "WITHOUT" },
      { hint: "Liberty, independence", word: "FREEDOM" },
      { hint: "Mental ideas", word: "THOUGHT" },
      { hint: "Item or matter", word: "THING" },
      { hint: "Deep insight", word: "WISDOM" },
    ],
  },
  {
    id: "p336",
    quote: "Simplicity is the ultimate sophistication.",
    attribution: "Leonardo da Vinci",
    theme: "Simplicity",
    difficulty: "hard",
    clueWords: [
      { hint: "Plainness, ease", word: "SIMPLICITY" },
      { hint: "Final, supreme", word: "ULTIMATE" },
      { hint: "Refined complexity", word: "SOPHISTICATION" },
    ],
  },
  {
    id: "p337",
    quote: "Love is composed of a single soul inhabiting two bodies.",
    attribution: "Aristotle",
    theme: "Love",
    difficulty: "hard",
    clueWords: [
      { hint: "Deep affection", word: "LOVE" },
      { hint: "Made up of", word: "COMPOSED" },
      { hint: "One alone", word: "SINGLE" },
      { hint: "Inner essence", word: "SOUL" },
      { hint: "Living within", word: "INHABITING" },
      { hint: "Physical forms", word: "BODIES" },
    ],
  },
  {
    id: "p338",
    quote: "What we know is a drop, what we do not know is an ocean.",
    attribution: "Isaac Newton",
    theme: "Humility",
    difficulty: "hard",
    clueWords: [
      { hint: "Are aware of", word: "KNOW" },
      { hint: "A small bead of liquid", word: "DROP" },
      { hint: "Vast body of water", word: "OCEAN" },
      { hint: "Anything that", word: "WHAT" },
    ],
  },
  {
    id: "p339",
    quote: "If I have seen further it is by standing on the shoulders of giants.",
    attribution: "Isaac Newton",
    theme: "Humility",
    difficulty: "hard",
    clueWords: [
      { hint: "Perceived with eyes", word: "SEEN" },
      { hint: "Beyond, additional", word: "FURTHER" },
      { hint: "On feet upright", word: "STANDING" },
      { hint: "Body parts above the arms", word: "SHOULDERS" },
      { hint: "Huge people", word: "GIANTS" },
    ],
  },
  {
    id: "p340",
    quote: "To live is the rarest thing. Most people exist, that is all.",
    attribution: "Oscar Wilde",
    theme: "Mindfulness",
    difficulty: "hard",
    clueWords: [
      { hint: "Be alive", word: "LIVE" },
      { hint: "Most uncommon", word: "RAREST" },
      { hint: "Item or matter", word: "THING" },
      { hint: "Be present", word: "EXIST" },
      { hint: "Greatest amount", word: "MOST" },
      { hint: "Human beings", word: "PEOPLE" },
    ],
  },
  {
    id: "p341",
    quote: "Experience is the name everyone gives to their mistakes.",
    attribution: "Oscar Wilde",
    theme: "Learning",
    difficulty: "hard",
    clueWords: [
      { hint: "Lived events", word: "EXPERIENCE" },
      { hint: "Identifier of a thing", word: "NAME" },
      { hint: "Each person", word: "EVERYONE" },
      { hint: "Provides", word: "GIVES" },
      { hint: "Errors", word: "MISTAKES" },
    ],
  },
  {
    id: "p342",
    quote: "There is only one thing worse than being talked about, and that is not being talked about.",
    attribution: "Oscar Wilde",
    theme: "Reputation",
    difficulty: "hard",
    clueWords: [
      { hint: "Sole, single", word: "ONLY" },
      { hint: "Item or matter", word: "THING" },
      { hint: "More unpleasant", word: "WORSE" },
      { hint: "Spoken about", word: "TALKED" },
      { hint: "Concerning", word: "ABOUT" },
    ],
  },
  {
    id: "p343",
    quote: "I can resist anything except temptation.",
    attribution: "Oscar Wilde",
    theme: "Humor",
    difficulty: "hard",
    clueWords: [
      { hint: "Be able to", word: "CAN" },
      { hint: "Withstand, oppose", word: "RESIST" },
      { hint: "Any item", word: "ANYTHING" },
      { hint: "Apart from, save", word: "EXCEPT" },
      { hint: "Lure or enticement", word: "TEMPTATION" },
    ],
  },
  {
    id: "p344",
    quote: "We have nothing to fear but fear itself.",
    attribution: "Franklin D. Roosevelt",
    theme: "Courage",
    difficulty: "hard",
    clueWords: [
      { hint: "Possess", word: "HAVE" },
      { hint: "Not anything", word: "NOTHING" },
      { hint: "Be afraid of", word: "FEAR" },
      { hint: "Itself, on its own", word: "ITSELF" },
    ],
  },
  {
    id: "p345",
    quote: "It is not in the stars to hold our destiny but in ourselves.",
    attribution: "William Shakespeare",
    theme: "Self-Determination",
    difficulty: "hard",
    clueWords: [
      { hint: "Celestial bodies", word: "STARS" },
      { hint: "Grasp, contain", word: "HOLD" },
      { hint: "Predetermined fate", word: "DESTINY" },
      { hint: "Our own selves", word: "OURSELVES" },
      { hint: "Belonging to us", word: "OUR" },
    ],
  },
  {
    id: "p346",
    quote: "Listen to many, speak to a few.",
    attribution: "William Shakespeare",
    theme: "Wisdom",
    difficulty: "hard",
    clueWords: [
      { hint: "Pay attention to", word: "LISTEN" },
      { hint: "A great number", word: "MANY" },
      { hint: "Utter aloud", word: "SPEAK" },
      { hint: "A small number", word: "FEW" },
    ],
  },
  {
    id: "p347",
    quote: "Anyone who stops learning is old, whether at twenty or eighty.",
    attribution: "Henry Ford",
    theme: "Learning",
    difficulty: "hard",
    clueWords: [
      { hint: "Any person", word: "ANYONE" },
      { hint: "Ceases", word: "STOPS" },
      { hint: "Acquiring knowledge", word: "LEARNING" },
      { hint: "Aged", word: "OLD" },
      { hint: "Two times ten", word: "TWENTY" },
      { hint: "Eight times ten", word: "EIGHTY" },
    ],
  },
  {
    id: "p348",
    quote: "Coming together is a beginning. Keeping together is progress.",
    attribution: "Henry Ford",
    theme: "Teamwork",
    difficulty: "hard",
    clueWords: [
      { hint: "Arriving", word: "COMING" },
      { hint: "Joined as one", word: "TOGETHER" },
      { hint: "The starting point", word: "BEGINNING" },
      { hint: "Maintaining", word: "KEEPING" },
      { hint: "Forward motion", word: "PROGRESS" },
    ],
  },
  {
    id: "p349",
    quote: "Where there is love there is life.",
    attribution: "Mahatma Gandhi",
    theme: "Love",
    difficulty: "hard",
    clueWords: [
      { hint: "At which place", word: "WHERE" },
      { hint: "Deep affection", word: "LOVE" },
      { hint: "Existence", word: "LIFE" },
    ],
  },
  {
    id: "p350",
    quote: "There is more to life than increasing its speed.",
    attribution: "Mahatma Gandhi",
    theme: "Mindfulness",
    difficulty: "hard",
    clueWords: [
      { hint: "Existence", word: "LIFE" },
      { hint: "Making greater", word: "INCREASING" },
      { hint: "Velocity, pace", word: "SPEED" },
      { hint: "To a greater extent", word: "MORE" },
    ],
  },
  {
    id: "p351",
    quote: "The weak can never forgive. Forgiveness is the attribute of the strong.",
    attribution: "Mahatma Gandhi",
    theme: "Forgiveness",
    difficulty: "hard",
    clueWords: [
      { hint: "Lacking strength", word: "WEAK" },
      { hint: "Pardon", word: "FORGIVE" },
      { hint: "Granting pardon", word: "FORGIVENESS" },
      { hint: "A characteristic", word: "ATTRIBUTE" },
      { hint: "Powerful", word: "STRONG" },
    ],
  },
  {
    id: "p352",
    quote: "Strength does not come from physical capacity. It comes from indomitable will.",
    attribution: "Mahatma Gandhi",
    theme: "Strength",
    difficulty: "hard",
    clueWords: [
      { hint: "Power, fortitude", word: "STRENGTH" },
      { hint: "Bodily", word: "PHYSICAL" },
      { hint: "Ability, capability", word: "CAPACITY" },
      { hint: "Unconquerable", word: "INDOMITABLE" },
      { hint: "Resolve, determination", word: "WILL" },
    ],
  },
  {
    id: "p353",
    quote: "The brave man is not he who does not feel afraid, but he who conquers fear.",
    attribution: "Nelson Mandela",
    theme: "Courage",
    difficulty: "hard",
    clueWords: [
      { hint: "Courageous", word: "BRAVE" },
      { hint: "Adult human male", word: "MAN" },
      { hint: "Sense or perceive", word: "FEEL" },
      { hint: "Frightened", word: "AFRAID" },
      { hint: "Defeats, overcomes", word: "CONQUERS" },
      { hint: "Dread", word: "FEAR" },
    ],
  },
  {
    id: "p354",
    quote: "May your choices reflect your hopes, not your fears.",
    attribution: "Nelson Mandela",
    theme: "Choice",
    difficulty: "hard",
    clueWords: [
      { hint: "Selections", word: "CHOICES" },
      { hint: "Mirror, show", word: "REFLECT" },
      { hint: "Aspirations", word: "HOPES" },
      { hint: "Anxieties", word: "FEARS" },
    ],
  },
  {
    id: "p355",
    quote: "Resentment is like drinking poison and hoping it will kill your enemies.",
    attribution: "Nelson Mandela",
    theme: "Forgiveness",
    difficulty: "hard",
    clueWords: [
      { hint: "Bitter ill-will", word: "RESENTMENT" },
      { hint: "Consuming liquid", word: "DRINKING" },
      { hint: "A toxic substance", word: "POISON" },
      { hint: "Wishing", word: "HOPING" },
      { hint: "Adversaries", word: "ENEMIES" },
    ],
  },
  {
    id: "p356",
    quote: "Education is the most powerful weapon to change the world.",
    attribution: "Nelson Mandela",
    theme: "Learning",
    difficulty: "hard",
    clueWords: [
      { hint: "Schooling, instruction", word: "EDUCATION" },
      { hint: "Most strong", word: "POWERFUL" },
      { hint: "An instrument of war", word: "WEAPON" },
      { hint: "Transform", word: "CHANGE" },
      { hint: "The earth", word: "WORLD" },
    ],
  },
  {
    id: "p357",
    quote: "Do not look where you fell, but where you slipped.",
    attribution: "African Proverb",
    theme: "Reflection",
    difficulty: "hard",
    clueWords: [
      { hint: "Use the eyes", word: "LOOK" },
      { hint: "At which place", word: "WHERE" },
      { hint: "Dropped down", word: "FELL" },
      { hint: "Lost footing", word: "SLIPPED" },
    ],
  },
  {
    id: "p358",
    quote: "However long the night, the dawn will break.",
    attribution: "African Proverb",
    theme: "Hope",
    difficulty: "hard",
    clueWords: [
      { hint: "Of great duration", word: "LONG" },
      { hint: "Period after dusk", word: "NIGHT" },
      { hint: "Daybreak", word: "DAWN" },
      { hint: "Burst forth", word: "BREAK" },
      { hint: "No matter how", word: "HOWEVER" },
    ],
  },
  {
    id: "p359",
    quote: "Smooth seas do not make skillful sailors.",
    attribution: "African Proverb",
    theme: "Adversity",
    difficulty: "hard",
    clueWords: [
      { hint: "Calm, even", word: "SMOOTH" },
      { hint: "Bodies of salt water", word: "SEAS" },
      { hint: "Produce, create", word: "MAKE" },
      { hint: "Adept, expert", word: "SKILLFUL" },
      { hint: "Boat-handlers", word: "SAILORS" },
    ],
  },
  {
    id: "p360",
    quote: "He who refuses to obey cannot command.",
    attribution: "Aristotle",
    theme: "Leadership",
    difficulty: "hard",
    clueWords: [
      { hint: "Declines, rejects", word: "REFUSES" },
      { hint: "Comply with orders", word: "OBEY" },
      { hint: "Is not able to", word: "CANNOT" },
      { hint: "Give orders to", word: "COMMAND" },
    ],
  },
  {
    id: "p361",
    quote: "The heart of a fool is in his mouth, but the mouth of a wise man is in his heart.",
    attribution: "Benjamin Franklin",
    theme: "Wisdom",
    difficulty: "hard",
    clueWords: [
      { hint: "Pumping organ", word: "HEART" },
      { hint: "A foolish person", word: "FOOL" },
      { hint: "Speaking organ", word: "MOUTH" },
      { hint: "Sage, learned", word: "WISE" },
      { hint: "Adult human male", word: "MAN" },
    ],
  },
  {
    id: "p362",
    quote: "He who has begun is half done. Dare to be wise; begin.",
    attribution: "Horace",
    theme: "Initiative",
    difficulty: "hard",
    clueWords: [
      { hint: "Started", word: "BEGUN" },
      { hint: "Fifty percent", word: "HALF" },
      { hint: "Completed", word: "DONE" },
      { hint: "Have the courage", word: "DARE" },
      { hint: "Sage, learned", word: "WISE" },
      { hint: "Start", word: "BEGIN" },
    ],
  },
  {
    id: "p363",
    quote: "Sometimes the questions are complicated and the answers are simple.",
    attribution: "Dr. Seuss",
    theme: "Wisdom",
    difficulty: "hard",
    clueWords: [
      { hint: "On occasion", word: "SOMETIMES" },
      { hint: "Inquiries", word: "QUESTIONS" },
      { hint: "Complex, intricate", word: "COMPLICATED" },
      { hint: "Replies, solutions", word: "ANSWERS" },
      { hint: "Easy, plain", word: "SIMPLE" },
    ],
  },
  {
    id: "p364",
    quote: "How vain it is to sit down to write when you have not stood up to live.",
    attribution: "Henry David Thoreau",
    theme: "Action",
    difficulty: "hard",
    clueWords: [
      { hint: "Empty, futile", word: "VAIN" },
      { hint: "Be seated", word: "SIT" },
      { hint: "Compose text", word: "WRITE" },
      { hint: "Risen upright", word: "STOOD" },
      { hint: "Be alive", word: "LIVE" },
    ],
  },
  {
    id: "p365",
    quote: "Heaven is under our feet as well as over our heads.",
    attribution: "Henry David Thoreau",
    theme: "Wonder",
    difficulty: "hard",
    clueWords: [
      { hint: "The sky, paradise", word: "HEAVEN" },
      { hint: "Body parts you stand on", word: "FEET" },
      { hint: "Body parts above the neck", word: "HEADS" },
      { hint: "Beneath", word: "UNDER" },
      { hint: "Above", word: "OVER" },
    ],
  },
  {
    id: "p366",
    quote: "It is not enough to have lived. We should be determined to live for something.",
    attribution: "Winston Churchill",
    theme: "Purpose",
    difficulty: "hard",
    clueWords: [
      { hint: "Sufficient", word: "ENOUGH" },
      { hint: "Existed, been alive", word: "LIVED" },
      { hint: "Resolved", word: "DETERMINED" },
      { hint: "Be alive", word: "LIVE" },
      { hint: "An item or cause", word: "SOMETHING" },
    ],
  },
  {
    id: "p367",
    quote: "If you are going through hell, keep going.",
    attribution: "Winston Churchill",
    theme: "Resilience",
    difficulty: "hard",
    clueWords: [
      { hint: "Traveling", word: "GOING" },
      { hint: "From end to end", word: "THROUGH" },
      { hint: "Place of torment", word: "HELL" },
      { hint: "Maintain", word: "KEEP" },
    ],
  },
  {
    id: "p368",
    quote: "Success is not final, failure is not fatal: it is the courage to continue that counts.",
    attribution: "Winston Churchill",
    theme: "Courage",
    difficulty: "hard",
    clueWords: [
      { hint: "Achievement", word: "SUCCESS" },
      { hint: "Last, ultimate", word: "FINAL" },
      { hint: "Lack of success", word: "FAILURE" },
      { hint: "Causing death", word: "FATAL" },
      { hint: "Bravery", word: "COURAGE" },
      { hint: "Persist", word: "CONTINUE" },
    ],
  },
  {
    id: "p369",
    quote: "Attitude is a little thing that makes a big difference.",
    attribution: "Winston Churchill",
    theme: "Mindset",
    difficulty: "hard",
    clueWords: [
      { hint: "Mental disposition", word: "ATTITUDE" },
      { hint: "Small, slight", word: "LITTLE" },
      { hint: "Item or matter", word: "THING" },
      { hint: "Causes", word: "MAKES" },
      { hint: "Of great size", word: "BIG" },
      { hint: "Distinction", word: "DIFFERENCE" },
    ],
  },
  {
    id: "p370",
    quote: "We make a living by what we get, but we make a life by what we give.",
    attribution: "Winston Churchill",
    theme: "Generosity",
    difficulty: "hard",
    clueWords: [
      { hint: "Construct, earn", word: "MAKE" },
      { hint: "Existing", word: "LIVING" },
      { hint: "Receive, obtain", word: "GET" },
      { hint: "Existence", word: "LIFE" },
      { hint: "Bestow, hand over", word: "GIVE" },
    ],
  },
  {
    id: "p371",
    quote: "A pessimist sees the difficulty in every opportunity; an optimist the opportunity in every difficulty.",
    attribution: "Winston Churchill",
    theme: "Mindset",
    difficulty: "hard",
    clueWords: [
      { hint: "One who expects the worst", word: "PESSIMIST" },
      { hint: "Perceives", word: "SEES" },
      { hint: "A challenge", word: "DIFFICULTY" },
      { hint: "A favorable chance", word: "OPPORTUNITY" },
      { hint: "One who expects the best", word: "OPTIMIST" },
    ],
  },
  {
    id: "p372",
    quote: "Continuous effort, not strength or intelligence, is the key to unlocking potential.",
    attribution: "Winston Churchill",
    theme: "Effort",
    difficulty: "hard",
    clueWords: [
      { hint: "Ongoing, unbroken", word: "CONTINUOUS" },
      { hint: "Hard work", word: "EFFORT" },
      { hint: "Power, force", word: "STRENGTH" },
      { hint: "Mental ability", word: "INTELLIGENCE" },
      { hint: "An opener", word: "KEY" },
      { hint: "Inner capability", word: "POTENTIAL" },
    ],
  },
  {
    id: "p373",
    quote: "Common sense is not so common.",
    attribution: "Voltaire",
    theme: "Wisdom",
    difficulty: "hard",
    clueWords: [
      { hint: "Ordinary, shared", word: "COMMON" },
      { hint: "Practical judgment", word: "SENSE" },
    ],
  },
  {
    id: "p374",
    quote: "Doubt is not a pleasant condition, but certainty is absurd.",
    attribution: "Voltaire",
    theme: "Wisdom",
    difficulty: "hard",
    clueWords: [
      { hint: "Lack of certainty", word: "DOUBT" },
      { hint: "Agreeable", word: "PLEASANT" },
      { hint: "A state of being", word: "CONDITION" },
      { hint: "Total assurance", word: "CERTAINTY" },
      { hint: "Ridiculous", word: "ABSURD" },
    ],
  },
  {
    id: "p375",
    quote: "Judge a man by his questions rather than by his answers.",
    attribution: "Voltaire",
    theme: "Wisdom",
    difficulty: "hard",
    clueWords: [
      { hint: "Form an opinion of", word: "JUDGE" },
      { hint: "Adult human male", word: "MAN" },
      { hint: "Inquiries", word: "QUESTIONS" },
      { hint: "Replies", word: "ANSWERS" },
      { hint: "Instead of", word: "RATHER" },
    ],
  },
  {
    id: "p376",
    quote: "The longer the explanation, the bigger the lie.",
    attribution: "Chinese Proverb",
    theme: "Truth",
    difficulty: "hard",
    clueWords: [
      { hint: "Of greater duration", word: "LONGER" },
      { hint: "A clarification", word: "EXPLANATION" },
      { hint: "Of greater size", word: "BIGGER" },
      { hint: "A falsehood", word: "LIE" },
    ],
  },
  {
    id: "p377",
    quote: "We are made of star stuff.",
    attribution: "Carl Sagan",
    theme: "Wonder",
    difficulty: "hard",
    clueWords: [
      { hint: "Created", word: "MADE" },
      { hint: "Celestial body", word: "STAR" },
      { hint: "Substance, material", word: "STUFF" },
    ],
  },
  {
    id: "p378",
    quote: "Imagination will carry us to worlds that never were. But without it we go nowhere.",
    attribution: "Carl Sagan",
    theme: "Creativity",
    difficulty: "hard",
    clueWords: [
      { hint: "Mental creativity", word: "IMAGINATION" },
      { hint: "Convey, transport", word: "CARRY" },
      { hint: "Realms or planets", word: "WORLDS" },
      { hint: "Lacking, without", word: "WITHOUT" },
      { hint: "No place", word: "NOWHERE" },
    ],
  },
  {
    id: "p379",
    quote: "Somewhere, something incredible is waiting to be known.",
    attribution: "Carl Sagan",
    theme: "Wonder",
    difficulty: "hard",
    clueWords: [
      { hint: "Some place", word: "SOMEWHERE" },
      { hint: "An item", word: "SOMETHING" },
      { hint: "Astonishing", word: "INCREDIBLE" },
      { hint: "Pausing in expectation", word: "WAITING" },
      { hint: "Discovered, learned", word: "KNOWN" },
    ],
  },
  {
    id: "p380",
    quote: "It is not because things are difficult that we do not dare; it is because we do not dare that things are difficult.",
    attribution: "Seneca",
    theme: "Courage",
    difficulty: "hard",
    clueWords: [
      { hint: "Items, matters", word: "THINGS" },
      { hint: "Hard, challenging", word: "DIFFICULT" },
      { hint: "Have courage", word: "DARE" },
      { hint: "For what reason", word: "BECAUSE" },
    ],
  },
  {
    id: "p381",
    quote: "All cruelty springs from weakness.",
    attribution: "Seneca",
    theme: "Compassion",
    difficulty: "hard",
    clueWords: [
      { hint: "Each, every", word: "ALL" },
      { hint: "Inflicting pain", word: "CRUELTY" },
      { hint: "Arises", word: "SPRINGS" },
      { hint: "Lack of strength", word: "WEAKNESS" },
    ],
  },
  {
    id: "p382",
    quote: "Anger, if not restrained, is more hurtful than the injury that provokes it.",
    attribution: "Seneca",
    theme: "Self-Control",
    difficulty: "hard",
    clueWords: [
      { hint: "Strong displeasure", word: "ANGER" },
      { hint: "Held back", word: "RESTRAINED" },
      { hint: "Causing pain", word: "HURTFUL" },
      { hint: "A wound or harm", word: "INJURY" },
      { hint: "Stirs up", word: "PROVOKES" },
    ],
  },
  {
    id: "p383",
    quote: "Begin at once to live, and count each separate day as a separate life.",
    attribution: "Seneca",
    theme: "Mindfulness",
    difficulty: "hard",
    clueWords: [
      { hint: "Start", word: "BEGIN" },
      { hint: "Be alive", word: "LIVE" },
      { hint: "Tally up", word: "COUNT" },
      { hint: "Distinct, individual", word: "SEPARATE" },
      { hint: "A 24-hour period", word: "DAY" },
      { hint: "Existence", word: "LIFE" },
    ],
  },
  {
    id: "p384",
    quote: "Sometimes even to live is an act of courage.",
    attribution: "Seneca",
    theme: "Courage",
    difficulty: "hard",
    clueWords: [
      { hint: "On occasion", word: "SOMETIMES" },
      { hint: "Be alive", word: "LIVE" },
      { hint: "A deed", word: "ACT" },
      { hint: "Bravery", word: "COURAGE" },
      { hint: "Furthermore", word: "EVEN" },
    ],
  },
  {
    id: "p385",
    quote: "Without continual growth, words like improvement and success have no meaning.",
    attribution: "Benjamin Franklin",
    theme: "Growth",
    difficulty: "hard",
    clueWords: [
      { hint: "Lacking", word: "WITHOUT" },
      { hint: "Ongoing", word: "CONTINUAL" },
      { hint: "Development", word: "GROWTH" },
      { hint: "Spoken units", word: "WORDS" },
      { hint: "Achievement", word: "SUCCESS" },
      { hint: "Significance", word: "MEANING" },
    ],
  },
  {
    id: "p386",
    quote: "Stillness reveals the secrets of eternity.",
    attribution: "Lao Tzu",
    theme: "Mindfulness",
    difficulty: "hard",
    clueWords: [
      { hint: "Quietness, calm", word: "STILLNESS" },
      { hint: "Uncovers", word: "REVEALS" },
      { hint: "Hidden truths", word: "SECRETS" },
      { hint: "Endless time", word: "ETERNITY" },
    ],
  },
  {
    id: "p387",
    quote: "From caring comes courage.",
    attribution: "Lao Tzu",
    theme: "Compassion",
    difficulty: "hard",
    clueWords: [
      { hint: "Showing concern", word: "CARING" },
      { hint: "Arrives, originates", word: "COMES" },
      { hint: "Bravery", word: "COURAGE" },
    ],
  },
  {
    id: "p388",
    quote: "When I let go of what I am, I become what I might be.",
    attribution: "Lao Tzu",
    theme: "Growth",
    difficulty: "hard",
    clueWords: [
      { hint: "Allow", word: "LET" },
      { hint: "Release", word: "GO" },
      { hint: "Turn into", word: "BECOME" },
      { hint: "Possibly will", word: "MIGHT" },
    ],
  },
  {
    id: "p389",
    quote: "Care about what other people think and you will always be their prisoner.",
    attribution: "Lao Tzu",
    theme: "Authenticity",
    difficulty: "hard",
    clueWords: [
      { hint: "Be concerned about", word: "CARE" },
      { hint: "Different", word: "OTHER" },
      { hint: "Human beings", word: "PEOPLE" },
      { hint: "Use the mind", word: "THINK" },
      { hint: "One held captive", word: "PRISONER" },
      { hint: "All the time", word: "ALWAYS" },
    ],
  },
  {
    id: "p390",
    quote: "He who knows enough is enough will always have enough.",
    attribution: "Lao Tzu",
    theme: "Contentment",
    difficulty: "hard",
    clueWords: [
      { hint: "Is aware of", word: "KNOWS" },
      { hint: "Sufficient", word: "ENOUGH" },
      { hint: "All the time", word: "ALWAYS" },
      { hint: "Possess", word: "HAVE" },
    ],
  },

  // -------------------- EXPERT (40) --------------------
  {
    id: "p391",
    quote: "The fault, dear Brutus, is not in our stars, but in ourselves.",
    attribution: "William Shakespeare",
    theme: "Self-Determination",
    difficulty: "expert",
    clueWords: [
      { hint: "An error or flaw", word: "FAULT" },
      { hint: "Beloved (form of address)", word: "DEAR" },
      { hint: "Celestial bodies", word: "STARS" },
      { hint: "Our own selves", word: "OURSELVES" },
      { hint: "Belonging to us", word: "OUR" },
    ],
  },
  {
    id: "p392",
    quote: "Better keep yourself clean and bright; you are the window through which you must see the world.",
    attribution: "George Bernard Shaw",
    theme: "Character",
    difficulty: "expert",
    clueWords: [
      { hint: "More desirable", word: "BETTER" },
      { hint: "Maintain", word: "KEEP" },
      { hint: "Free of dirt", word: "CLEAN" },
      { hint: "Shining, vivid", word: "BRIGHT" },
      { hint: "Glass opening", word: "WINDOW" },
      { hint: "Earth, planet", word: "WORLD" },
    ],
  },
  {
    id: "p393",
    quote: "Life is not a problem to be solved, but a reality to be experienced.",
    attribution: "Soren Kierkegaard",
    theme: "Mindfulness",
    difficulty: "expert",
    clueWords: [
      { hint: "Existence", word: "LIFE" },
      { hint: "A puzzle, difficulty", word: "PROBLEM" },
      { hint: "Worked out", word: "SOLVED" },
      { hint: "What is real", word: "REALITY" },
      { hint: "Lived through", word: "EXPERIENCED" },
    ],
  },
  {
    id: "p394",
    quote: "We are not what we know but what we are willing to learn.",
    attribution: "Mary Catherine Bateson",
    theme: "Learning",
    difficulty: "expert",
    clueWords: [
      { hint: "Are aware of", word: "KNOW" },
      { hint: "Ready, prepared", word: "WILLING" },
      { hint: "Acquire knowledge", word: "LEARN" },
      { hint: "First-person plural", word: "WE" },
    ],
  },
  {
    id: "p395",
    quote: "It is not death that a man should fear, but he should fear never beginning to live.",
    attribution: "Marcus Aurelius",
    theme: "Mindfulness",
    difficulty: "expert",
    clueWords: [
      { hint: "End of life", word: "DEATH" },
      { hint: "Adult human male", word: "MAN" },
      { hint: "Be afraid of", word: "FEAR" },
      { hint: "At no time", word: "NEVER" },
      { hint: "Starting", word: "BEGINNING" },
      { hint: "Be alive", word: "LIVE" },
    ],
  },
  {
    id: "p396",
    quote: "Such as your habitual thoughts are, such also will be the character of your mind.",
    attribution: "Marcus Aurelius",
    theme: "Mindset",
    difficulty: "expert",
    clueWords: [
      { hint: "Customary, regular", word: "HABITUAL" },
      { hint: "Mental ideas", word: "THOUGHTS" },
      { hint: "Moral nature", word: "CHARACTER" },
      { hint: "Thinking faculty", word: "MIND" },
      { hint: "Likewise", word: "ALSO" },
    ],
  },
  {
    id: "p397",
    quote: "If it is not right, do not do it. If it is not true, do not say it.",
    attribution: "Marcus Aurelius",
    theme: "Integrity",
    difficulty: "expert",
    clueWords: [
      { hint: "Correct, just", word: "RIGHT" },
      { hint: "Genuine, factual", word: "TRUE" },
      { hint: "Perform", word: "DO" },
      { hint: "Utter aloud", word: "SAY" },
    ],
  },
  {
    id: "p398",
    quote: "How much trouble he avoids who does not look to see what his neighbor says or does.",
    attribution: "Marcus Aurelius",
    theme: "Mindfulness",
    difficulty: "expert",
    clueWords: [
      { hint: "Difficulty, distress", word: "TROUBLE" },
      { hint: "Steers clear of", word: "AVOIDS" },
      { hint: "Use the eyes", word: "LOOK" },
      { hint: "Person living nearby", word: "NEIGHBOR" },
      { hint: "Utters", word: "SAYS" },
      { hint: "Performs", word: "DOES" },
    ],
  },
  {
    id: "p399",
    quote: "Reject your sense of injury and the injury itself disappears.",
    attribution: "Marcus Aurelius",
    theme: "Forgiveness",
    difficulty: "expert",
    clueWords: [
      { hint: "Refuse, dismiss", word: "REJECT" },
      { hint: "Feeling, perception", word: "SENSE" },
      { hint: "Wound, harm", word: "INJURY" },
      { hint: "Vanishes", word: "DISAPPEARS" },
      { hint: "On its own", word: "ITSELF" },
    ],
  },
  {
    id: "p400",
    quote: "Look well into thyself; there is a source of strength which will spring up if thou wilt look there.",
    attribution: "Marcus Aurelius",
    theme: "Self-Knowledge",
    difficulty: "expert",
    clueWords: [
      { hint: "Use the eyes", word: "LOOK" },
      { hint: "Yourself (archaic)", word: "THYSELF" },
      { hint: "An origin or starting place", word: "SOURCE" },
      { hint: "Power, fortitude", word: "STRENGTH" },
      { hint: "Burst forth", word: "SPRING" },
    ],
  },
  {
    id: "p401",
    quote: "The wound is the place where the light enters you.",
    attribution: "Rumi",
    theme: "Healing",
    difficulty: "expert",
    clueWords: [
      { hint: "Injury, hurt", word: "WOUND" },
      { hint: "A location", word: "PLACE" },
      { hint: "At which", word: "WHERE" },
      { hint: "Illumination", word: "LIGHT" },
      { hint: "Goes into", word: "ENTERS" },
    ],
  },
  {
    id: "p402",
    quote: "Yesterday I was clever, so I wanted to change the world. Today I am wise, so I am changing myself.",
    attribution: "Rumi",
    theme: "Wisdom",
    difficulty: "expert",
    clueWords: [
      { hint: "The day before", word: "YESTERDAY" },
      { hint: "Sharp-minded", word: "CLEVER" },
      { hint: "Transform", word: "CHANGE" },
      { hint: "The earth", word: "WORLD" },
      { hint: "The current day", word: "TODAY" },
      { hint: "Sage, learned", word: "WISE" },
    ],
  },
  {
    id: "p403",
    quote: "Stop acting so small. You are the universe in ecstatic motion.",
    attribution: "Rumi",
    theme: "Wonder",
    difficulty: "expert",
    clueWords: [
      { hint: "Cease", word: "STOP" },
      { hint: "Behaving", word: "ACTING" },
      { hint: "Little, slight", word: "SMALL" },
      { hint: "All of existence", word: "UNIVERSE" },
      { hint: "Joyfully overwhelmed", word: "ECSTATIC" },
      { hint: "Movement", word: "MOTION" },
    ],
  },
  {
    id: "p404",
    quote: "Out beyond ideas of wrongdoing and rightdoing, there is a field. I will meet you there.",
    attribution: "Rumi",
    theme: "Forgiveness",
    difficulty: "expert",
    clueWords: [
      { hint: "Past, further than", word: "BEYOND" },
      { hint: "Mental notions", word: "IDEAS" },
      { hint: "An open piece of land", word: "FIELD" },
      { hint: "Encounter", word: "MEET" },
      { hint: "At that place", word: "THERE" },
    ],
  },
  {
    id: "p405",
    quote: "Try not to resist the changes that come your way. Let life live through you.",
    attribution: "Rumi",
    theme: "Acceptance",
    difficulty: "expert",
    clueWords: [
      { hint: "Make an attempt", word: "TRY" },
      { hint: "Withstand", word: "RESIST" },
      { hint: "Alterations", word: "CHANGES" },
      { hint: "A path or route", word: "WAY" },
      { hint: "Allow", word: "LET" },
      { hint: "Existence", word: "LIFE" },
    ],
  },
  {
    id: "p406",
    quote: "Let the beauty of what you love be what you do.",
    attribution: "Rumi",
    theme: "Purpose",
    difficulty: "expert",
    clueWords: [
      { hint: "Allow", word: "LET" },
      { hint: "Loveliness", word: "BEAUTY" },
      { hint: "Cherish deeply", word: "LOVE" },
      { hint: "Perform", word: "DO" },
    ],
  },
  {
    id: "p407",
    quote: "Set your life on fire. Seek those who fan your flames.",
    attribution: "Rumi",
    theme: "Passion",
    difficulty: "expert",
    clueWords: [
      { hint: "Place, put", word: "SET" },
      { hint: "Existence", word: "LIFE" },
      { hint: "Burning combustion", word: "FIRE" },
      { hint: "Search for", word: "SEEK" },
      { hint: "Stir or excite", word: "FAN" },
      { hint: "Burning tongues", word: "FLAMES" },
    ],
  },
  {
    id: "p408",
    quote: "What you seek is seeking you.",
    attribution: "Rumi",
    theme: "Aspiration",
    difficulty: "expert",
    clueWords: [
      { hint: "Search for", word: "SEEK" },
      { hint: "Searching for", word: "SEEKING" },
    ],
  },
  {
    id: "p409",
    quote: "The sage does not hoard. The more he gives to others, the more he has.",
    attribution: "Lao Tzu",
    theme: "Generosity",
    difficulty: "expert",
    clueWords: [
      { hint: "A wise person", word: "SAGE" },
      { hint: "Hide and store", word: "HOARD" },
      { hint: "Hands over", word: "GIVES" },
      { hint: "Other people", word: "OTHERS" },
      { hint: "Possesses", word: "HAS" },
      { hint: "To a greater degree", word: "MORE" },
    ],
  },
  {
    id: "p410",
    quote: "Watch your thoughts, they become your words. Watch your words, they become your actions.",
    attribution: "Lao Tzu",
    theme: "Mindfulness",
    difficulty: "expert",
    clueWords: [
      { hint: "Observe carefully", word: "WATCH" },
      { hint: "Mental ideas", word: "THOUGHTS" },
      { hint: "Spoken units", word: "WORDS" },
      { hint: "Deeds", word: "ACTIONS" },
      { hint: "Turn into", word: "BECOME" },
    ],
  },
  {
    id: "p411",
    quote: "Music in the soul can be heard by the universe.",
    attribution: "Lao Tzu",
    theme: "Wonder",
    difficulty: "expert",
    clueWords: [
      { hint: "Organized sound", word: "MUSIC" },
      { hint: "Inner essence", word: "SOUL" },
      { hint: "Perceived by ear", word: "HEARD" },
      { hint: "All of existence", word: "UNIVERSE" },
    ],
  },
  {
    id: "p412",
    quote: "Time is a created thing. To say I do not have time is to say I do not want to.",
    attribution: "Lao Tzu",
    theme: "Priorities",
    difficulty: "expert",
    clueWords: [
      { hint: "Hours and minutes", word: "TIME" },
      { hint: "Brought into being", word: "CREATED" },
      { hint: "An item or matter", word: "THING" },
      { hint: "Utter aloud", word: "SAY" },
      { hint: "Desire", word: "WANT" },
      { hint: "Possess", word: "HAVE" },
    ],
  },
  {
    id: "p413",
    quote: "If you do not change direction, you may end up where you are heading.",
    attribution: "Lao Tzu",
    theme: "Change",
    difficulty: "expert",
    clueWords: [
      { hint: "Alter, modify", word: "CHANGE" },
      { hint: "Course or heading", word: "DIRECTION" },
      { hint: "The final point", word: "END" },
      { hint: "Going toward", word: "HEADING" },
      { hint: "Possibly", word: "MAY" },
    ],
  },
  {
    id: "p414",
    quote: "Mastering others is strength. Mastering yourself is true power.",
    attribution: "Lao Tzu",
    theme: "Self-Control",
    difficulty: "expert",
    clueWords: [
      { hint: "Gaining control over", word: "MASTERING" },
      { hint: "Other people", word: "OTHERS" },
      { hint: "Force, fortitude", word: "STRENGTH" },
      { hint: "Your own person", word: "YOURSELF" },
      { hint: "Genuine, real", word: "TRUE" },
      { hint: "Authority", word: "POWER" },
    ],
  },
  {
    id: "p415",
    quote: "Cowards die many times before their deaths; the valiant taste of death but once.",
    attribution: "William Shakespeare",
    theme: "Courage",
    difficulty: "expert",
    clueWords: [
      { hint: "Those without courage", word: "COWARDS" },
      { hint: "Cease to live", word: "DIE" },
      { hint: "A great number", word: "MANY" },
      { hint: "Brave individuals", word: "VALIANT" },
      { hint: "Sample, experience", word: "TASTE" },
      { hint: "End of life", word: "DEATH" },
    ],
  },
  {
    id: "p416",
    quote: "We are such stuff as dreams are made on, and our little life is rounded with a sleep.",
    attribution: "William Shakespeare",
    theme: "Life",
    difficulty: "expert",
    clueWords: [
      { hint: "Substance", word: "STUFF" },
      { hint: "Aspirations, visions", word: "DREAMS" },
      { hint: "Constructed", word: "MADE" },
      { hint: "Existence", word: "LIFE" },
      { hint: "Resting unconscious", word: "SLEEP" },
      { hint: "Small, brief", word: "LITTLE" },
    ],
  },
  {
    id: "p417",
    quote: "Better three hours too soon than a minute too late.",
    attribution: "William Shakespeare",
    theme: "Punctuality",
    difficulty: "expert",
    clueWords: [
      { hint: "Preferable", word: "BETTER" },
      { hint: "Number after two", word: "THREE" },
      { hint: "Sixty-minute units", word: "HOURS" },
      { hint: "Excessively", word: "TOO" },
      { hint: "Early", word: "SOON" },
      { hint: "Sixty-second unit", word: "MINUTE" },
    ],
  },
  {
    id: "p418",
    quote: "Have more than you show, speak less than you know.",
    attribution: "William Shakespeare",
    theme: "Wisdom",
    difficulty: "expert",
    clueWords: [
      { hint: "Possess", word: "HAVE" },
      { hint: "To a greater degree", word: "MORE" },
      { hint: "Display", word: "SHOW" },
      { hint: "Utter aloud", word: "SPEAK" },
      { hint: "To a smaller degree", word: "LESS" },
      { hint: "Are aware of", word: "KNOW" },
    ],
  },
  {
    id: "p419",
    quote: "Love all, trust a few, do wrong to none.",
    attribution: "William Shakespeare",
    theme: "Ethics",
    difficulty: "expert",
    clueWords: [
      { hint: "Cherish deeply", word: "LOVE" },
      { hint: "Each, every", word: "ALL" },
      { hint: "Have faith in", word: "TRUST" },
      { hint: "Small number", word: "FEW" },
      { hint: "Incorrect, harmful", word: "WRONG" },
      { hint: "Not anyone", word: "NONE" },
    ],
  },
  {
    id: "p420",
    quote: "The lady doth protest too much, methinks.",
    attribution: "William Shakespeare",
    theme: "Suspicion",
    difficulty: "expert",
    clueWords: [
      { hint: "A noble woman", word: "LADY" },
      { hint: "Object strongly", word: "PROTEST" },
      { hint: "Excessively", word: "TOO" },
      { hint: "A great deal", word: "MUCH" },
      { hint: "I think (archaic)", word: "METHINKS" },
    ],
  },
  {
    id: "p421",
    quote: "The course of true love never did run smooth.",
    attribution: "William Shakespeare",
    theme: "Love",
    difficulty: "expert",
    clueWords: [
      { hint: "A path or progression", word: "COURSE" },
      { hint: "Genuine", word: "TRUE" },
      { hint: "Deep affection", word: "LOVE" },
      { hint: "At no time", word: "NEVER" },
      { hint: "Move quickly", word: "RUN" },
      { hint: "Even, untroubled", word: "SMOOTH" },
    ],
  },
  {
    id: "p422",
    quote: "I have not yet begun to fight.",
    attribution: "John Paul Jones",
    theme: "Resolve",
    difficulty: "expert",
    clueWords: [
      { hint: "Up to now", word: "YET" },
      { hint: "Started", word: "BEGUN" },
      { hint: "Engage in combat", word: "FIGHT" },
    ],
  },
  {
    id: "p423",
    quote: "Whoever has chosen wisdom rather than money as his profession will get the reward.",
    attribution: "Anonymous",
    theme: "Values",
    difficulty: "expert",
    clueWords: [
      { hint: "Any person", word: "WHOEVER" },
      { hint: "Selected", word: "CHOSEN" },
      { hint: "Deep insight", word: "WISDOM" },
      { hint: "Currency", word: "MONEY" },
      { hint: "Career, occupation", word: "PROFESSION" },
      { hint: "Recompense", word: "REWARD" },
    ],
  },
  {
    id: "p424",
    quote: "There is no person so severely punished as those who subject themselves to remorse.",
    attribution: "Seneca",
    theme: "Forgiveness",
    difficulty: "expert",
    clueWords: [
      { hint: "Individual", word: "PERSON" },
      { hint: "Harshly, strictly", word: "SEVERELY" },
      { hint: "Disciplined, penalized", word: "PUNISHED" },
      { hint: "Particular ones", word: "THOSE" },
      { hint: "Their own selves", word: "THEMSELVES" },
      { hint: "Deep regret", word: "REMORSE" },
    ],
  },
  {
    id: "p425",
    quote: "It is impossible to live a pleasant life without living wisely and well and justly.",
    attribution: "Epicurus",
    theme: "Virtue",
    difficulty: "expert",
    clueWords: [
      { hint: "Cannot be done", word: "IMPOSSIBLE" },
      { hint: "Be alive", word: "LIVE" },
      { hint: "Agreeable", word: "PLEASANT" },
      { hint: "Existence", word: "LIFE" },
      { hint: "In a wise way", word: "WISELY" },
      { hint: "Fairly", word: "JUSTLY" },
    ],
  },
  {
    id: "p426",
    quote: "Do not spoil what you have by desiring what you have not.",
    attribution: "Epicurus",
    theme: "Contentment",
    difficulty: "expert",
    clueWords: [
      { hint: "Ruin", word: "SPOIL" },
      { hint: "Possess", word: "HAVE" },
      { hint: "Strongly wishing for", word: "DESIRING" },
      { hint: "Anything that", word: "WHAT" },
    ],
  },
  {
    id: "p427",
    quote: "Not what we have but what we enjoy constitutes our abundance.",
    attribution: "Epicurus",
    theme: "Gratitude",
    difficulty: "expert",
    clueWords: [
      { hint: "Possess", word: "HAVE" },
      { hint: "Take pleasure in", word: "ENJOY" },
      { hint: "Makes up", word: "CONSTITUTES" },
      { hint: "Plenty, riches", word: "ABUNDANCE" },
      { hint: "Belonging to us", word: "OUR" },
    ],
  },
  {
    id: "p428",
    quote: "Vain is the word of a philosopher which does not heal the suffering of man.",
    attribution: "Epicurus",
    theme: "Wisdom",
    difficulty: "expert",
    clueWords: [
      { hint: "Empty, futile", word: "VAIN" },
      { hint: "Lover of wisdom", word: "PHILOSOPHER" },
      { hint: "Cure or mend", word: "HEAL" },
      { hint: "Pain or hardship", word: "SUFFERING" },
      { hint: "Adult human male", word: "MAN" },
    ],
  },
  {
    id: "p429",
    quote: "Vain is the word, who finds no comfort in the truth of his own conscience.",
    attribution: "Anonymous",
    theme: "Integrity",
    difficulty: "expert",
    clueWords: [
      { hint: "Empty, futile", word: "VAIN" },
      { hint: "Discovers", word: "FINDS" },
      { hint: "Solace, ease", word: "COMFORT" },
      { hint: "Honest reality", word: "TRUTH" },
      { hint: "Inner moral guide", word: "CONSCIENCE" },
    ],
  },
  {
    id: "p430",
    quote: "He who is brave is free, and he who is free fears nothing.",
    attribution: "Anonymous",
    theme: "Courage",
    difficulty: "expert",
    clueWords: [
      { hint: "Courageous", word: "BRAVE" },
      { hint: "Not bound", word: "FREE" },
      { hint: "Be afraid of", word: "FEARS" },
      { hint: "Not anything", word: "NOTHING" },
    ],
  },
];
