import type { PuzzleRaw } from "../puzzleData";

/**
 * Batch 3 — 200 new puzzles (IDs p431–p630).
 *  • p431–p470: 40 easy
 *  • p471–p530: 60 medium
 *  • p531–p590: 60 hard
 *  • p591–p630: 40 expert
 */
export const BATCH3: PuzzleRaw[] = [
  // -------------------- EASY (40) --------------------
  {
    id: "p431",
    quote: "A stitch in time saves nine.",
    attribution: "Proverb",
    theme: "Prudence",
    difficulty: "easy",
    clueWords: [
      { hint: "A loop of thread", word: "STITCH" },
      { hint: "Hours and minutes", word: "TIME" },
      { hint: "Spares, prevents", word: "SAVES" },
      { hint: "One less than ten", word: "NINE" },
    ],
  },
  {
    id: "p432",
    quote: "All roads lead to Rome.",
    attribution: "Latin Proverb",
    theme: "Universality",
    difficulty: "easy",
    clueWords: [
      { hint: "Each, every", word: "ALL" },
      { hint: "Travel paths", word: "ROADS" },
      { hint: "Guide, direct", word: "LEAD" },
      { hint: "The Italian capital", word: "ROME" },
    ],
  },
  {
    id: "p433",
    quote: "An idle mind is the devil's workshop.",
    attribution: "Proverb",
    theme: "Industry",
    difficulty: "easy",
    clueWords: [
      { hint: "Doing nothing", word: "IDLE" },
      { hint: "Thinking faculty", word: "MIND" },
      { hint: "An evil being", word: "DEVIL" },
      { hint: "A workplace", word: "WORKSHOP" },
    ],
  },
  {
    id: "p434",
    quote: "April showers bring May flowers.",
    attribution: "Proverb",
    theme: "Patience",
    difficulty: "easy",
    clueWords: [
      { hint: "Spring rains", word: "SHOWERS" },
      { hint: "Carry along", word: "BRING" },
      { hint: "Plants with petals", word: "FLOWERS" },
      { hint: "Fourth month", word: "APRIL" },
      { hint: "Fifth month", word: "MAY" },
    ],
  },
  {
    id: "p435",
    quote: "Barking dogs seldom bite.",
    attribution: "Proverb",
    theme: "Caution",
    difficulty: "easy",
    clueWords: [
      { hint: "Making canine sounds", word: "BARKING" },
      { hint: "Loyal pets", word: "DOGS" },
      { hint: "Rarely", word: "SELDOM" },
      { hint: "Use teeth on", word: "BITE" },
    ],
  },
  {
    id: "p436",
    quote: "Better alone than in bad company.",
    attribution: "Proverb",
    theme: "Friendship",
    difficulty: "easy",
    clueWords: [
      { hint: "Preferable", word: "BETTER" },
      { hint: "By oneself", word: "ALONE" },
      { hint: "Of poor quality", word: "BAD" },
      { hint: "Companionship of others", word: "COMPANY" },
    ],
  },
  {
    id: "p437",
    quote: "Clothes make the man.",
    attribution: "Mark Twain",
    theme: "Appearance",
    difficulty: "easy",
    clueWords: [
      { hint: "What you wear", word: "CLOTHES" },
      { hint: "Cause to be", word: "MAKE" },
      { hint: "Adult human male", word: "MAN" },
    ],
  },
  {
    id: "p438",
    quote: "Dead men tell no tales.",
    attribution: "Proverb",
    theme: "Secrecy",
    difficulty: "easy",
    clueWords: [
      { hint: "No longer alive", word: "DEAD" },
      { hint: "Adult human males", word: "MEN" },
      { hint: "Recount, narrate", word: "TELL" },
      { hint: "Stories, narratives", word: "TALES" },
    ],
  },
  {
    id: "p439",
    quote: "Do not count your chickens before they hatch.",
    attribution: "Proverb",
    theme: "Caution",
    difficulty: "easy",
    clueWords: [
      { hint: "Tally up", word: "COUNT" },
      { hint: "Farmyard birds", word: "CHICKENS" },
      { hint: "Earlier than", word: "BEFORE" },
      { hint: "Emerge from an egg", word: "HATCH" },
    ],
  },
  {
    id: "p440",
    quote: "Do not cross the bridge until you come to it.",
    attribution: "Proverb",
    theme: "Patience",
    difficulty: "easy",
    clueWords: [
      { hint: "Go across", word: "CROSS" },
      { hint: "Span over water", word: "BRIDGE" },
      { hint: "Up to that point", word: "UNTIL" },
      { hint: "Arrive", word: "COME" },
    ],
  },
  {
    id: "p441",
    quote: "Easy does it.",
    attribution: "Proverb",
    theme: "Patience",
    difficulty: "easy",
    clueWords: [
      { hint: "Without difficulty", word: "EASY" },
      { hint: "Performs", word: "DOES" },
    ],
  },
  {
    id: "p442",
    quote: "Eat to live, not live to eat.",
    attribution: "Proverb",
    theme: "Moderation",
    difficulty: "easy",
    clueWords: [
      { hint: "Consume food", word: "EAT" },
      { hint: "Be alive", word: "LIVE" },
    ],
  },
  {
    id: "p443",
    quote: "Every man for himself.",
    attribution: "Proverb",
    theme: "Self-Reliance",
    difficulty: "easy",
    clueWords: [
      { hint: "Each one", word: "EVERY" },
      { hint: "Adult human male", word: "MAN" },
      { hint: "He himself", word: "HIMSELF" },
    ],
  },
  {
    id: "p444",
    quote: "First come, first served.",
    attribution: "Proverb",
    theme: "Initiative",
    difficulty: "easy",
    clueWords: [
      { hint: "Initial, before others", word: "FIRST" },
      { hint: "Arrive", word: "COME" },
      { hint: "Helped or attended to", word: "SERVED" },
    ],
  },
  {
    id: "p445",
    quote: "Good fences make good neighbors.",
    attribution: "Robert Frost",
    theme: "Boundaries",
    difficulty: "easy",
    clueWords: [
      { hint: "Worthy or fine", word: "GOOD" },
      { hint: "Boundary barriers", word: "FENCES" },
      { hint: "Cause, produce", word: "MAKE" },
      { hint: "People living nearby", word: "NEIGHBORS" },
    ],
  },
  {
    id: "p446",
    quote: "He who hesitates is lost.",
    attribution: "Proverb",
    theme: "Initiative",
    difficulty: "easy",
    clueWords: [
      { hint: "Pauses, delays", word: "HESITATES" },
      { hint: "Misplaced, gone astray", word: "LOST" },
    ],
  },
  {
    id: "p447",
    quote: "If you cannot beat them, join them.",
    attribution: "Proverb",
    theme: "Adaptability",
    difficulty: "easy",
    clueWords: [
      { hint: "Are not able to", word: "CANNOT" },
      { hint: "Defeat", word: "BEAT" },
      { hint: "Become a member of", word: "JOIN" },
      { hint: "They, plural", word: "THEM" },
    ],
  },
  {
    id: "p448",
    quote: "If you snooze, you lose.",
    attribution: "Proverb",
    theme: "Initiative",
    difficulty: "easy",
    clueWords: [
      { hint: "Doze briefly", word: "SNOOZE" },
      { hint: "Forfeit", word: "LOSE" },
      { hint: "On the condition that", word: "IF" },
    ],
  },
  {
    id: "p449",
    quote: "Iron sharpens iron.",
    attribution: "Proverb",
    theme: "Friendship",
    difficulty: "easy",
    clueWords: [
      { hint: "A heavy metal", word: "IRON" },
      { hint: "Makes a finer edge", word: "SHARPENS" },
    ],
  },
  {
    id: "p450",
    quote: "Keep your friends close, your enemies closer.",
    attribution: "Proverb",
    theme: "Strategy",
    difficulty: "easy",
    clueWords: [
      { hint: "Hold onto, retain", word: "KEEP" },
      { hint: "Companions", word: "FRIENDS" },
      { hint: "Adversaries", word: "ENEMIES" },
      { hint: "Near", word: "CLOSE" },
      { hint: "More near", word: "CLOSER" },
    ],
  },
  {
    id: "p451",
    quote: "Lightning never strikes twice in the same place.",
    attribution: "Proverb",
    theme: "Fortune",
    difficulty: "easy",
    clueWords: [
      { hint: "Electrical bolt", word: "LIGHTNING" },
      { hint: "At no time", word: "NEVER" },
      { hint: "Hits", word: "STRIKES" },
      { hint: "Two times", word: "TWICE" },
      { hint: "Identical", word: "SAME" },
      { hint: "A location", word: "PLACE" },
    ],
  },
  {
    id: "p452",
    quote: "Live and let live.",
    attribution: "Proverb",
    theme: "Tolerance",
    difficulty: "easy",
    clueWords: [
      { hint: "Be alive", word: "LIVE" },
      { hint: "Allow", word: "LET" },
    ],
  },
  {
    id: "p453",
    quote: "Love conquers all.",
    attribution: "Virgil",
    theme: "Love",
    difficulty: "easy",
    clueWords: [
      { hint: "Deep affection", word: "LOVE" },
      { hint: "Defeats, overcomes", word: "CONQUERS" },
      { hint: "Each, every", word: "ALL" },
    ],
  },
  {
    id: "p454",
    quote: "Money cannot buy happiness.",
    attribution: "Proverb",
    theme: "Values",
    difficulty: "easy",
    clueWords: [
      { hint: "Currency, wealth", word: "MONEY" },
      { hint: "Is not able to", word: "CANNOT" },
      { hint: "Purchase", word: "BUY" },
      { hint: "Joyful well-being", word: "HAPPINESS" },
    ],
  },
  {
    id: "p455",
    quote: "Necessity knows no law.",
    attribution: "Proverb",
    theme: "Survival",
    difficulty: "easy",
    clueWords: [
      { hint: "An essential need", word: "NECESSITY" },
      { hint: "Is aware of", word: "KNOWS" },
      { hint: "A rule of conduct", word: "LAW" },
    ],
  },
  {
    id: "p456",
    quote: "Old soldiers never die.",
    attribution: "Douglas MacArthur",
    theme: "Legacy",
    difficulty: "easy",
    clueWords: [
      { hint: "Aged, longstanding", word: "OLD" },
      { hint: "Military fighters", word: "SOLDIERS" },
      { hint: "At no time", word: "NEVER" },
      { hint: "Cease to live", word: "DIE" },
    ],
  },
  {
    id: "p457",
    quote: "Once bitten, twice shy.",
    attribution: "Proverb",
    theme: "Caution",
    difficulty: "easy",
    clueWords: [
      { hint: "A single occasion", word: "ONCE" },
      { hint: "Was nipped", word: "BITTEN" },
      { hint: "Two times", word: "TWICE" },
      { hint: "Reserved, cautious", word: "SHY" },
    ],
  },
  {
    id: "p458",
    quote: "Penny wise, pound foolish.",
    attribution: "Proverb",
    theme: "Thrift",
    difficulty: "easy",
    clueWords: [
      { hint: "Small coin", word: "PENNY" },
      { hint: "Sensible, prudent", word: "WISE" },
      { hint: "Larger weight unit", word: "POUND" },
      { hint: "Lacking sense", word: "FOOLISH" },
    ],
  },
  {
    id: "p459",
    quote: "Quality over quantity.",
    attribution: "Proverb",
    theme: "Values",
    difficulty: "easy",
    clueWords: [
      { hint: "Standard of excellence", word: "QUALITY" },
      { hint: "A measure of how much", word: "QUANTITY" },
      { hint: "Above, more than", word: "OVER" },
    ],
  },
  {
    id: "p460",
    quote: "Seeing is believing.",
    attribution: "Proverb",
    theme: "Trust",
    difficulty: "easy",
    clueWords: [
      { hint: "Perceiving with eyes", word: "SEEING" },
      { hint: "Trusting, accepting", word: "BELIEVING" },
    ],
  },
  {
    id: "p461",
    quote: "Silence speaks louder than words.",
    attribution: "Proverb",
    theme: "Communication",
    difficulty: "easy",
    clueWords: [
      { hint: "Absence of sound", word: "SILENCE" },
      { hint: "Communicates", word: "SPEAKS" },
      { hint: "More forcefully", word: "LOUDER" },
      { hint: "Spoken units", word: "WORDS" },
    ],
  },
  {
    id: "p462",
    quote: "Sticks and stones may break my bones.",
    attribution: "Proverb",
    theme: "Resilience",
    difficulty: "easy",
    clueWords: [
      { hint: "Wooden rods", word: "STICKS" },
      { hint: "Hard mineral pieces", word: "STONES" },
      { hint: "Possibly", word: "MAY" },
      { hint: "Snap apart", word: "BREAK" },
      { hint: "Skeleton parts", word: "BONES" },
    ],
  },
  {
    id: "p463",
    quote: "Strangers are friends you have not yet met.",
    attribution: "William Butler Yeats",
    theme: "Friendship",
    difficulty: "easy",
    clueWords: [
      { hint: "Unknown people", word: "STRANGERS" },
      { hint: "Companions", word: "FRIENDS" },
      { hint: "Until now", word: "YET" },
      { hint: "Encountered", word: "MET" },
    ],
  },
  {
    id: "p464",
    quote: "The cat is out of the bag.",
    attribution: "Proverb",
    theme: "Truth",
    difficulty: "easy",
    clueWords: [
      { hint: "Whiskered house pet", word: "CAT" },
      { hint: "A sack", word: "BAG" },
      { hint: "Outside of", word: "OUT" },
    ],
  },
  {
    id: "p465",
    quote: "The first step is the hardest.",
    attribution: "Proverb",
    theme: "Beginnings",
    difficulty: "easy",
    clueWords: [
      { hint: "Initial", word: "FIRST" },
      { hint: "A pace", word: "STEP" },
      { hint: "Most difficult", word: "HARDEST" },
    ],
  },
  {
    id: "p466",
    quote: "There is no place like home.",
    attribution: "Proverb",
    theme: "Belonging",
    difficulty: "easy",
    clueWords: [
      { hint: "A location", word: "PLACE" },
      { hint: "Similar to", word: "LIKE" },
      { hint: "Place of dwelling", word: "HOME" },
    ],
  },
  {
    id: "p467",
    quote: "Tomorrow is another day.",
    attribution: "Proverb",
    theme: "Hope",
    difficulty: "easy",
    clueWords: [
      { hint: "The day after today", word: "TOMORROW" },
      { hint: "Different, additional", word: "ANOTHER" },
      { hint: "A 24-hour period", word: "DAY" },
    ],
  },
  {
    id: "p468",
    quote: "What you see is what you get.",
    attribution: "Proverb",
    theme: "Honesty",
    difficulty: "easy",
    clueWords: [
      { hint: "Perceive with the eyes", word: "SEE" },
      { hint: "Receive, obtain", word: "GET" },
      { hint: "Anything that", word: "WHAT" },
    ],
  },
  {
    id: "p469",
    quote: "When pigs fly.",
    attribution: "Proverb",
    theme: "Skepticism",
    difficulty: "easy",
    clueWords: [
      { hint: "Farm animals", word: "PIGS" },
      { hint: "Move through air", word: "FLY" },
      { hint: "At what time", word: "WHEN" },
    ],
  },
  {
    id: "p470",
    quote: "Win some, lose some.",
    attribution: "Proverb",
    theme: "Acceptance",
    difficulty: "easy",
    clueWords: [
      { hint: "Be victorious", word: "WIN" },
      { hint: "Forfeit", word: "LOSE" },
      { hint: "A few, a number", word: "SOME" },
    ],
  },

  // -------------------- MEDIUM (60) --------------------
  {
    id: "p471",
    quote: "The best mirror is an old friend.",
    attribution: "George Herbert",
    theme: "Friendship",
    difficulty: "medium",
    clueWords: [
      { hint: "Top quality", word: "BEST" },
      { hint: "Reflective surface", word: "MIRROR" },
      { hint: "Aged, longstanding", word: "OLD" },
      { hint: "A close companion", word: "FRIEND" },
    ],
  },
  {
    id: "p472",
    quote: "Books are a uniquely portable magic.",
    attribution: "Stephen King",
    theme: "Learning",
    difficulty: "medium",
    clueWords: [
      { hint: "Bound reading material", word: "BOOKS" },
      { hint: "Able to be carried", word: "PORTABLE" },
      { hint: "Mystical wonder", word: "MAGIC" },
      { hint: "In a one-of-a-kind way", word: "UNIQUELY" },
    ],
  },
  {
    id: "p473",
    quote: "Reading is essential for those who seek to rise above the ordinary.",
    attribution: "Jim Rohn",
    theme: "Learning",
    difficulty: "medium",
    clueWords: [
      { hint: "Going through written words", word: "READING" },
      { hint: "Absolutely necessary", word: "ESSENTIAL" },
      { hint: "Search for", word: "SEEK" },
      { hint: "Ascend", word: "RISE" },
      { hint: "Common, normal", word: "ORDINARY" },
    ],
  },
  {
    id: "p474",
    quote: "Travel makes one modest. You see what a tiny place you occupy in the world.",
    attribution: "Gustave Flaubert",
    theme: "Humility",
    difficulty: "medium",
    clueWords: [
      { hint: "Journey to other lands", word: "TRAVEL" },
      { hint: "Cause to be", word: "MAKES" },
      { hint: "Humble, unpretentious", word: "MODEST" },
      { hint: "Very small", word: "TINY" },
      { hint: "A location", word: "PLACE" },
      { hint: "The earth", word: "WORLD" },
    ],
  },
  {
    id: "p475",
    quote: "The world is a book; those who do not travel read only one page.",
    attribution: "Saint Augustine",
    theme: "Adventure",
    difficulty: "medium",
    clueWords: [
      { hint: "The earth", word: "WORLD" },
      { hint: "Bound reading material", word: "BOOK" },
      { hint: "Journey", word: "TRAVEL" },
      { hint: "Go through written words", word: "READ" },
      { hint: "A single sheet", word: "PAGE" },
    ],
  },
  {
    id: "p476",
    quote: "The journey, not the arrival, matters.",
    attribution: "T.S. Eliot",
    theme: "Mindfulness",
    difficulty: "medium",
    clueWords: [
      { hint: "A long trip", word: "JOURNEY" },
      { hint: "The act of arriving", word: "ARRIVAL" },
      { hint: "Is significant", word: "MATTERS" },
    ],
  },
  {
    id: "p477",
    quote: "Take only memories, leave only footprints.",
    attribution: "Chief Seattle",
    theme: "Nature",
    difficulty: "medium",
    clueWords: [
      { hint: "Grasp, carry", word: "TAKE" },
      { hint: "Recollections", word: "MEMORIES" },
      { hint: "Depart from", word: "LEAVE" },
      { hint: "Foot impressions", word: "FOOTPRINTS" },
      { hint: "Solely", word: "ONLY" },
    ],
  },
  {
    id: "p478",
    quote: "I would rather walk with a friend in the dark than alone in the light.",
    attribution: "Helen Keller",
    theme: "Friendship",
    difficulty: "medium",
    clueWords: [
      { hint: "Move on foot", word: "WALK" },
      { hint: "A close companion", word: "FRIEND" },
      { hint: "Without light", word: "DARK" },
      { hint: "By oneself", word: "ALONE" },
      { hint: "Illumination", word: "LIGHT" },
      { hint: "Instead", word: "RATHER" },
    ],
  },
  {
    id: "p479",
    quote: "Keep your face to the sunshine and you cannot see the shadows.",
    attribution: "Helen Keller",
    theme: "Optimism",
    difficulty: "medium",
    clueWords: [
      { hint: "Maintain", word: "KEEP" },
      { hint: "Front of the head", word: "FACE" },
      { hint: "Light from the sun", word: "SUNSHINE" },
      { hint: "Dark areas", word: "SHADOWS" },
      { hint: "Perceive with eyes", word: "SEE" },
    ],
  },
  {
    id: "p480",
    quote: "Life is a great adventure or nothing at all.",
    attribution: "Helen Keller",
    theme: "Adventure",
    difficulty: "medium",
    clueWords: [
      { hint: "Existence", word: "LIFE" },
      { hint: "Outstanding", word: "GREAT" },
      { hint: "An exciting experience", word: "ADVENTURE" },
      { hint: "Not anything", word: "NOTHING" },
    ],
  },
  {
    id: "p481",
    quote: "Although the world is full of suffering, it is also full of overcoming.",
    attribution: "Helen Keller",
    theme: "Hope",
    difficulty: "medium",
    clueWords: [
      { hint: "Even though", word: "ALTHOUGH" },
      { hint: "The earth", word: "WORLD" },
      { hint: "Filled completely", word: "FULL" },
      { hint: "Pain, hardship", word: "SUFFERING" },
      { hint: "Conquering, prevailing", word: "OVERCOMING" },
    ],
  },
  {
    id: "p482",
    quote: "Alone we can do so little; together we can do so much.",
    attribution: "Helen Keller",
    theme: "Teamwork",
    difficulty: "medium",
    clueWords: [
      { hint: "By oneself", word: "ALONE" },
      { hint: "Are able to", word: "CAN" },
      { hint: "A small amount", word: "LITTLE" },
      { hint: "Joined as one", word: "TOGETHER" },
      { hint: "A great amount", word: "MUCH" },
    ],
  },
  {
    id: "p483",
    quote: "The most beautiful things cannot be seen but felt with the heart.",
    attribution: "Helen Keller",
    theme: "Wonder",
    difficulty: "medium",
    clueWords: [
      { hint: "Aesthetically pleasing", word: "BEAUTIFUL" },
      { hint: "Items, matters", word: "THINGS" },
      { hint: "Perceived with eyes", word: "SEEN" },
      { hint: "Sensed with emotion", word: "FELT" },
      { hint: "The pumping organ", word: "HEART" },
    ],
  },
  {
    id: "p484",
    quote: "The future depends on what you do today.",
    attribution: "Mahatma Gandhi",
    theme: "Action",
    difficulty: "medium",
    clueWords: [
      { hint: "Time yet to come", word: "FUTURE" },
      { hint: "Relies on", word: "DEPENDS" },
      { hint: "Perform", word: "DO" },
      { hint: "The current day", word: "TODAY" },
    ],
  },
  {
    id: "p485",
    quote: "Without humility there can be no humanity.",
    attribution: "John Buchan",
    theme: "Humility",
    difficulty: "medium",
    clueWords: [
      { hint: "Lacking", word: "WITHOUT" },
      { hint: "Modesty, lack of pride", word: "HUMILITY" },
      { hint: "All people", word: "HUMANITY" },
      { hint: "Negation", word: "NO" },
    ],
  },
  {
    id: "p486",
    quote: "Today's accomplishments were yesterday's impossibilities.",
    attribution: "Robert Schuller",
    theme: "Possibility",
    difficulty: "medium",
    clueWords: [
      { hint: "The current day", word: "TODAY" },
      { hint: "Achievements", word: "ACCOMPLISHMENTS" },
      { hint: "The day before", word: "YESTERDAY" },
      { hint: "Things that cannot be", word: "IMPOSSIBILITIES" },
    ],
  },
  {
    id: "p487",
    quote: "It is the time you have wasted for your rose that makes your rose so important.",
    attribution: "Antoine de Saint-Exupery",
    theme: "Love",
    difficulty: "medium",
    clueWords: [
      { hint: "Hours and minutes", word: "TIME" },
      { hint: "Squandered", word: "WASTED" },
      { hint: "A thorny flower", word: "ROSE" },
      { hint: "Significant", word: "IMPORTANT" },
      { hint: "Causes", word: "MAKES" },
    ],
  },
  {
    id: "p488",
    quote: "What you do every day matters more than what you do once in a while.",
    attribution: "Gretchen Rubin",
    theme: "Habit",
    difficulty: "medium",
    clueWords: [
      { hint: "Each one", word: "EVERY" },
      { hint: "A 24-hour period", word: "DAY" },
      { hint: "Is significant", word: "MATTERS" },
      { hint: "Performs", word: "DO" },
      { hint: "A single occasion", word: "ONCE" },
    ],
  },
  {
    id: "p489",
    quote: "Vision without action is a daydream. Action without vision is a nightmare.",
    attribution: "Japanese Proverb",
    theme: "Action",
    difficulty: "medium",
    clueWords: [
      { hint: "Mental sight", word: "VISION" },
      { hint: "Lacking", word: "WITHOUT" },
      { hint: "A deed", word: "ACTION" },
      { hint: "Wakeful fantasy", word: "DAYDREAM" },
      { hint: "Bad dream", word: "NIGHTMARE" },
    ],
  },
  {
    id: "p490",
    quote: "Faith is the bird that feels the light when the dawn is still dark.",
    attribution: "Rabindranath Tagore",
    theme: "Faith",
    difficulty: "medium",
    clueWords: [
      { hint: "Trust, belief", word: "FAITH" },
      { hint: "Feathered creature", word: "BIRD" },
      { hint: "Senses, perceives", word: "FEELS" },
      { hint: "Illumination", word: "LIGHT" },
      { hint: "Daybreak", word: "DAWN" },
      { hint: "Without light", word: "DARK" },
    ],
  },
  {
    id: "p491",
    quote: "You cannot cross the sea merely by standing and staring at the water.",
    attribution: "Rabindranath Tagore",
    theme: "Action",
    difficulty: "medium",
    clueWords: [
      { hint: "Are not able to", word: "CANNOT" },
      { hint: "Traverse", word: "CROSS" },
      { hint: "Vast salty water", word: "SEA" },
      { hint: "Solely, simply", word: "MERELY" },
      { hint: "Looking fixedly", word: "STARING" },
      { hint: "The clear liquid", word: "WATER" },
    ],
  },
  {
    id: "p492",
    quote: "Trees are the earth's endless effort to speak to the listening heaven.",
    attribution: "Rabindranath Tagore",
    theme: "Nature",
    difficulty: "medium",
    clueWords: [
      { hint: "Tall woody plants", word: "TREES" },
      { hint: "Our planet", word: "EARTH" },
      { hint: "Without end", word: "ENDLESS" },
      { hint: "Hard work", word: "EFFORT" },
      { hint: "Utter aloud", word: "SPEAK" },
      { hint: "The sky, paradise", word: "HEAVEN" },
    ],
  },
  {
    id: "p493",
    quote: "If you are afraid of being lonely, do not try to be right.",
    attribution: "Jules Renard",
    theme: "Authenticity",
    difficulty: "medium",
    clueWords: [
      { hint: "Frightened", word: "AFRAID" },
      { hint: "Solitary, isolated", word: "LONELY" },
      { hint: "Make an attempt", word: "TRY" },
      { hint: "Correct", word: "RIGHT" },
    ],
  },
  {
    id: "p494",
    quote: "Discontent is the source of trouble, but also of progress.",
    attribution: "Berthold Auerbach",
    theme: "Growth",
    difficulty: "medium",
    clueWords: [
      { hint: "Dissatisfaction", word: "DISCONTENT" },
      { hint: "Origin, root", word: "SOURCE" },
      { hint: "Difficulty, distress", word: "TROUBLE" },
      { hint: "Forward motion", word: "PROGRESS" },
      { hint: "In addition", word: "ALSO" },
    ],
  },
  {
    id: "p495",
    quote: "Gardens are not made by sitting in the shade.",
    attribution: "Rudyard Kipling",
    theme: "Effort",
    difficulty: "medium",
    clueWords: [
      { hint: "Cultivated plots", word: "GARDENS" },
      { hint: "Created", word: "MADE" },
      { hint: "Resting on a seat", word: "SITTING" },
      { hint: "Sheltered area from sun", word: "SHADE" },
    ],
  },
  {
    id: "p496",
    quote: "Words are wind, but blows unsought go to the heart.",
    attribution: "George Herbert",
    theme: "Communication",
    difficulty: "medium",
    clueWords: [
      { hint: "Spoken units", word: "WORDS" },
      { hint: "Moving air", word: "WIND" },
      { hint: "Strikes, hits", word: "BLOWS" },
      { hint: "Pumping organ", word: "HEART" },
    ],
  },
  {
    id: "p497",
    quote: "Pain is inevitable. Suffering is optional.",
    attribution: "Buddhist Saying",
    theme: "Mindset",
    difficulty: "medium",
    clueWords: [
      { hint: "Physical hurt", word: "PAIN" },
      { hint: "Cannot be avoided", word: "INEVITABLE" },
      { hint: "Hardship, anguish", word: "SUFFERING" },
      { hint: "By choice", word: "OPTIONAL" },
    ],
  },
  {
    id: "p498",
    quote: "An ounce of cheerfulness is worth a pound of sadness.",
    attribution: "John Wesley",
    theme: "Joy",
    difficulty: "medium",
    clueWords: [
      { hint: "Small unit of weight", word: "OUNCE" },
      { hint: "Brightness of mood", word: "CHEERFULNESS" },
      { hint: "Of value", word: "WORTH" },
      { hint: "Larger weight unit", word: "POUND" },
      { hint: "Sorrow", word: "SADNESS" },
    ],
  },
  {
    id: "p499",
    quote: "A friend is one who knows you and loves you just the same.",
    attribution: "Elbert Hubbard",
    theme: "Friendship",
    difficulty: "medium",
    clueWords: [
      { hint: "A close companion", word: "FRIEND" },
      { hint: "Is aware of", word: "KNOWS" },
      { hint: "Cherishes", word: "LOVES" },
      { hint: "Identical, equal", word: "SAME" },
    ],
  },
  {
    id: "p500",
    quote: "If you would be loved, love and be lovable.",
    attribution: "Benjamin Franklin",
    theme: "Love",
    difficulty: "medium",
    clueWords: [
      { hint: "Cherished by another", word: "LOVED" },
      { hint: "Show affection", word: "LOVE" },
      { hint: "Worthy of love", word: "LOVABLE" },
      { hint: "Exist as", word: "BE" },
    ],
  },
  {
    id: "p501",
    quote: "There is no medicine like hope, no incentive so great, and no tonic so powerful.",
    attribution: "Orison Swett Marden",
    theme: "Hope",
    difficulty: "medium",
    clueWords: [
      { hint: "A remedy", word: "MEDICINE" },
      { hint: "Optimistic feeling", word: "HOPE" },
      { hint: "A motivator", word: "INCENTIVE" },
      { hint: "Outstanding", word: "GREAT" },
      { hint: "An invigorating drink", word: "TONIC" },
      { hint: "Strong", word: "POWERFUL" },
    ],
  },
  {
    id: "p502",
    quote: "When one door of happiness closes, another opens.",
    attribution: "Helen Keller",
    theme: "Hope",
    difficulty: "medium",
    clueWords: [
      { hint: "An entryway", word: "DOOR" },
      { hint: "Joyful state", word: "HAPPINESS" },
      { hint: "Shuts", word: "CLOSES" },
      { hint: "Different one", word: "ANOTHER" },
      { hint: "Begins to allow access", word: "OPENS" },
    ],
  },
  {
    id: "p503",
    quote: "All that we are is the result of what we have thought.",
    attribution: "Buddha",
    theme: "Mindset",
    difficulty: "medium",
    clueWords: [
      { hint: "Each, every", word: "ALL" },
      { hint: "An outcome", word: "RESULT" },
      { hint: "Considered, pondered", word: "THOUGHT" },
      { hint: "First-person plural", word: "WE" },
    ],
  },
  {
    id: "p504",
    quote: "Hatred does not cease by hatred, but only by love.",
    attribution: "Buddha",
    theme: "Compassion",
    difficulty: "medium",
    clueWords: [
      { hint: "Strong dislike", word: "HATRED" },
      { hint: "Stop, halt", word: "CEASE" },
      { hint: "Solely", word: "ONLY" },
      { hint: "Deep affection", word: "LOVE" },
    ],
  },
  {
    id: "p505",
    quote: "Peace comes from within. Do not seek it without.",
    attribution: "Buddha",
    theme: "Inner Peace",
    difficulty: "medium",
    clueWords: [
      { hint: "Tranquility", word: "PEACE" },
      { hint: "Arrives", word: "COMES" },
      { hint: "Inside", word: "WITHIN" },
      { hint: "Search for", word: "SEEK" },
      { hint: "Outside, lacking", word: "WITHOUT" },
    ],
  },
  {
    id: "p506",
    quote: "Joy is not in things; it is in us.",
    attribution: "Richard Wagner",
    theme: "Joy",
    difficulty: "medium",
    clueWords: [
      { hint: "Happiness", word: "JOY" },
      { hint: "Items, matters", word: "THINGS" },
      { hint: "First-person plural", word: "US" },
    ],
  },
  {
    id: "p507",
    quote: "Honesty without compassion is brutality.",
    attribution: "Anonymous",
    theme: "Kindness",
    difficulty: "medium",
    clueWords: [
      { hint: "Truthfulness", word: "HONESTY" },
      { hint: "Lacking", word: "WITHOUT" },
      { hint: "Sympathetic concern", word: "COMPASSION" },
      { hint: "Cruelty", word: "BRUTALITY" },
    ],
  },
  {
    id: "p508",
    quote: "We cannot solve our problems with the same thinking that created them.",
    attribution: "Albert Einstein",
    theme: "Mindset",
    difficulty: "medium",
    clueWords: [
      { hint: "Are not able to", word: "CANNOT" },
      { hint: "Work out", word: "SOLVE" },
      { hint: "Difficulties", word: "PROBLEMS" },
      { hint: "Identical", word: "SAME" },
      { hint: "Pondering", word: "THINKING" },
      { hint: "Brought into being", word: "CREATED" },
    ],
  },
  {
    id: "p509",
    quote: "Learn from yesterday, live for today, hope for tomorrow.",
    attribution: "Albert Einstein",
    theme: "Mindfulness",
    difficulty: "medium",
    clueWords: [
      { hint: "Acquire knowledge", word: "LEARN" },
      { hint: "The day before", word: "YESTERDAY" },
      { hint: "Be alive", word: "LIVE" },
      { hint: "The current day", word: "TODAY" },
      { hint: "Wish, expect", word: "HOPE" },
      { hint: "The day after today", word: "TOMORROW" },
    ],
  },
  {
    id: "p510",
    quote: "The only source of knowledge is experience.",
    attribution: "Albert Einstein",
    theme: "Learning",
    difficulty: "medium",
    clueWords: [
      { hint: "Sole, single", word: "ONLY" },
      { hint: "An origin", word: "SOURCE" },
      { hint: "Information mastered", word: "KNOWLEDGE" },
      { hint: "Lived events", word: "EXPERIENCE" },
    ],
  },
  {
    id: "p511",
    quote: "Wisdom is not a product of schooling but of the lifelong attempt to acquire it.",
    attribution: "Albert Einstein",
    theme: "Wisdom",
    difficulty: "medium",
    clueWords: [
      { hint: "Deep insight", word: "WISDOM" },
      { hint: "Result, output", word: "PRODUCT" },
      { hint: "Formal education", word: "SCHOOLING" },
      { hint: "Lasting through life", word: "LIFELONG" },
      { hint: "An effort or try", word: "ATTEMPT" },
      { hint: "Obtain", word: "ACQUIRE" },
    ],
  },
  {
    id: "p512",
    quote: "Look deep into nature, and then you will understand everything better.",
    attribution: "Albert Einstein",
    theme: "Nature",
    difficulty: "medium",
    clueWords: [
      { hint: "Use the eyes", word: "LOOK" },
      { hint: "Far below the surface", word: "DEEP" },
      { hint: "The natural world", word: "NATURE" },
      { hint: "Comprehend", word: "UNDERSTAND" },
      { hint: "All things", word: "EVERYTHING" },
      { hint: "Improved", word: "BETTER" },
    ],
  },
  {
    id: "p513",
    quote: "I have decided to stick with love. Hate is too great a burden to bear.",
    attribution: "Martin Luther King Jr.",
    theme: "Love",
    difficulty: "medium",
    clueWords: [
      { hint: "Made a choice", word: "DECIDED" },
      { hint: "Adhere", word: "STICK" },
      { hint: "Deep affection", word: "LOVE" },
      { hint: "Strong dislike", word: "HATE" },
      { hint: "A heavy load", word: "BURDEN" },
      { hint: "Endure, carry", word: "BEAR" },
    ],
  },
  {
    id: "p514",
    quote: "Love is the only force capable of transforming an enemy into a friend.",
    attribution: "Martin Luther King Jr.",
    theme: "Love",
    difficulty: "medium",
    clueWords: [
      { hint: "Deep affection", word: "LOVE" },
      { hint: "Strength, power", word: "FORCE" },
      { hint: "Changing", word: "TRANSFORMING" },
      { hint: "An adversary", word: "ENEMY" },
      { hint: "A close companion", word: "FRIEND" },
    ],
  },
  {
    id: "p515",
    quote: "True peace is not the absence of tension; it is the presence of justice.",
    attribution: "Martin Luther King Jr.",
    theme: "Peace",
    difficulty: "medium",
    clueWords: [
      { hint: "Genuine, real", word: "TRUE" },
      { hint: "Tranquility", word: "PEACE" },
      { hint: "Lack of being there", word: "ABSENCE" },
      { hint: "Mental strain", word: "TENSION" },
      { hint: "Being there", word: "PRESENCE" },
      { hint: "Fairness", word: "JUSTICE" },
    ],
  },
  {
    id: "p516",
    quote: "Our lives begin to end the day we become silent about things that matter.",
    attribution: "Martin Luther King Jr.",
    theme: "Conviction",
    difficulty: "medium",
    clueWords: [
      { hint: "Existences", word: "LIVES" },
      { hint: "Start", word: "BEGIN" },
      { hint: "Without sound", word: "SILENT" },
      { hint: "Items, issues", word: "THINGS" },
      { hint: "Are significant", word: "MATTER" },
      { hint: "Belonging to us", word: "OUR" },
    ],
  },
  {
    id: "p517",
    quote: "If I cannot do great things, I can do small things in a great way.",
    attribution: "Martin Luther King Jr.",
    theme: "Excellence",
    difficulty: "medium",
    clueWords: [
      { hint: "Are not able to", word: "CANNOT" },
      { hint: "Outstanding", word: "GREAT" },
      { hint: "Items", word: "THINGS" },
      { hint: "Little, slight", word: "SMALL" },
      { hint: "A method", word: "WAY" },
    ],
  },
  {
    id: "p518",
    quote: "We must learn to live together as brothers or perish together as fools.",
    attribution: "Martin Luther King Jr.",
    theme: "Unity",
    difficulty: "medium",
    clueWords: [
      { hint: "Acquire knowledge", word: "LEARN" },
      { hint: "Be alive", word: "LIVE" },
      { hint: "Joined as one", word: "TOGETHER" },
      { hint: "Male siblings", word: "BROTHERS" },
      { hint: "Die, be destroyed", word: "PERISH" },
      { hint: "Foolish people", word: "FOOLS" },
    ],
  },
  {
    id: "p519",
    quote: "Justice is what love looks like in public.",
    attribution: "Cornel West",
    theme: "Justice",
    difficulty: "medium",
    clueWords: [
      { hint: "Fairness, equity", word: "JUSTICE" },
      { hint: "Deep affection", word: "LOVE" },
      { hint: "Appears", word: "LOOKS" },
      { hint: "Out in the open", word: "PUBLIC" },
    ],
  },
  {
    id: "p520",
    quote: "I have learned to keep my eyes on the prize.",
    attribution: "Anonymous",
    theme: "Focus",
    difficulty: "medium",
    clueWords: [
      { hint: "Acquired knowledge", word: "LEARNED" },
      { hint: "Maintain", word: "KEEP" },
      { hint: "Organs of sight", word: "EYES" },
      { hint: "A reward", word: "PRIZE" },
    ],
  },
  {
    id: "p521",
    quote: "There is nothing more difficult than to initiate a new order of things.",
    attribution: "Niccolo Machiavelli",
    theme: "Change",
    difficulty: "medium",
    clueWords: [
      { hint: "Not anything", word: "NOTHING" },
      { hint: "Hard, challenging", word: "DIFFICULT" },
      { hint: "Begin", word: "INITIATE" },
      { hint: "Recently created", word: "NEW" },
      { hint: "An arrangement", word: "ORDER" },
      { hint: "Items, matters", word: "THINGS" },
    ],
  },
  {
    id: "p522",
    quote: "Difficulties are just things to overcome.",
    attribution: "Ernest Shackleton",
    theme: "Adversity",
    difficulty: "medium",
    clueWords: [
      { hint: "Hardships", word: "DIFFICULTIES" },
      { hint: "Items, matters", word: "THINGS" },
      { hint: "Conquer", word: "OVERCOME" },
      { hint: "Solely, simply", word: "JUST" },
    ],
  },
  {
    id: "p523",
    quote: "Do not go gentle into that good night.",
    attribution: "Dylan Thomas",
    theme: "Resolve",
    difficulty: "medium",
    clueWords: [
      { hint: "Travel", word: "GO" },
      { hint: "Mild, soft", word: "GENTLE" },
      { hint: "Worthy, fine", word: "GOOD" },
      { hint: "Period of darkness", word: "NIGHT" },
    ],
  },
  {
    id: "p524",
    quote: "Hope is the thing with feathers that perches in the soul.",
    attribution: "Emily Dickinson",
    theme: "Hope",
    difficulty: "medium",
    clueWords: [
      { hint: "Optimistic feeling", word: "HOPE" },
      { hint: "An item or matter", word: "THING" },
      { hint: "Bird coverings", word: "FEATHERS" },
      { hint: "Settles like a bird", word: "PERCHES" },
      { hint: "Inner essence", word: "SOUL" },
    ],
  },
  {
    id: "p525",
    quote: "In the depth of winter, I finally learned that within me there lay an invincible summer.",
    attribution: "Albert Camus",
    theme: "Resilience",
    difficulty: "medium",
    clueWords: [
      { hint: "Far below the surface", word: "DEPTH" },
      { hint: "Cold season", word: "WINTER" },
      { hint: "At last", word: "FINALLY" },
      { hint: "Acquired knowledge", word: "LEARNED" },
      { hint: "Cannot be conquered", word: "INVINCIBLE" },
      { hint: "Warm season", word: "SUMMER" },
    ],
  },
  {
    id: "p526",
    quote: "Do not pray for an easy life. Pray for the strength to endure a difficult one.",
    attribution: "Bruce Lee",
    theme: "Strength",
    difficulty: "medium",
    clueWords: [
      { hint: "Speak to a higher being", word: "PRAY" },
      { hint: "Without difficulty", word: "EASY" },
      { hint: "Existence", word: "LIFE" },
      { hint: "Power, fortitude", word: "STRENGTH" },
      { hint: "Persist through", word: "ENDURE" },
      { hint: "Hard, challenging", word: "DIFFICULT" },
    ],
  },
  {
    id: "p527",
    quote: "Nothing is impossible. The word itself says I am possible.",
    attribution: "Audrey Hepburn",
    theme: "Possibility",
    difficulty: "medium",
    clueWords: [
      { hint: "Not anything", word: "NOTHING" },
      { hint: "Cannot be done", word: "IMPOSSIBLE" },
      { hint: "Spoken unit", word: "WORD" },
      { hint: "Can be done", word: "POSSIBLE" },
      { hint: "On its own", word: "ITSELF" },
      { hint: "Utters, states", word: "SAYS" },
    ],
  },
  {
    id: "p528",
    quote: "We do not remember days, we remember moments.",
    attribution: "Cesare Pavese",
    theme: "Memory",
    difficulty: "medium",
    clueWords: [
      { hint: "Recall to mind", word: "REMEMBER" },
      { hint: "24-hour periods", word: "DAYS" },
      { hint: "Brief instants", word: "MOMENTS" },
      { hint: "First-person plural", word: "WE" },
    ],
  },
  {
    id: "p529",
    quote: "Be the reason someone smiles today.",
    attribution: "Anonymous",
    theme: "Kindness",
    difficulty: "medium",
    clueWords: [
      { hint: "A motive or cause", word: "REASON" },
      { hint: "Some person", word: "SOMEONE" },
      { hint: "Shows joyful expression", word: "SMILES" },
      { hint: "The current day", word: "TODAY" },
    ],
  },
  {
    id: "p530",
    quote: "Stars cannot shine without darkness.",
    attribution: "D.H. Sidebottom",
    theme: "Adversity",
    difficulty: "medium",
    clueWords: [
      { hint: "Celestial bodies", word: "STARS" },
      { hint: "Are not able to", word: "CANNOT" },
      { hint: "Glow brightly", word: "SHINE" },
      { hint: "Lacking", word: "WITHOUT" },
      { hint: "Absence of light", word: "DARKNESS" },
    ],
  },

  // -------------------- HARD (60) --------------------
  {
    id: "p531",
    quote: "Pain demands to be felt.",
    attribution: "John Green",
    theme: "Healing",
    difficulty: "hard",
    clueWords: [
      { hint: "Physical hurt", word: "PAIN" },
      { hint: "Insists, requires", word: "DEMANDS" },
      { hint: "Sensed", word: "FELT" },
    ],
  },
  {
    id: "p532",
    quote: "Faith consists in believing when it is beyond the power of reason to believe.",
    attribution: "Voltaire",
    theme: "Faith",
    difficulty: "hard",
    clueWords: [
      { hint: "Trust, conviction", word: "FAITH" },
      { hint: "Is composed of", word: "CONSISTS" },
      { hint: "Trusting deeply", word: "BELIEVING" },
      { hint: "Past, further than", word: "BEYOND" },
      { hint: "Force, capability", word: "POWER" },
      { hint: "Logic, sense", word: "REASON" },
    ],
  },
  {
    id: "p533",
    quote: "The heart has its reasons of which reason knows nothing.",
    attribution: "Blaise Pascal",
    theme: "Love",
    difficulty: "hard",
    clueWords: [
      { hint: "Pumping organ", word: "HEART" },
      { hint: "Possesses", word: "HAS" },
      { hint: "Causes, motives", word: "REASONS" },
      { hint: "Logic, sense", word: "REASON" },
      { hint: "Is aware of", word: "KNOWS" },
      { hint: "Not anything", word: "NOTHING" },
    ],
  },
  {
    id: "p534",
    quote: "All of humanity's problems stem from the inability to sit quietly in a room alone.",
    attribution: "Blaise Pascal",
    theme: "Solitude",
    difficulty: "hard",
    clueWords: [
      { hint: "Each, every", word: "ALL" },
      { hint: "All people", word: "HUMANITY" },
      { hint: "Difficulties", word: "PROBLEMS" },
      { hint: "Be seated", word: "SIT" },
      { hint: "Calmly, hushed", word: "QUIETLY" },
      { hint: "By oneself", word: "ALONE" },
    ],
  },
  {
    id: "p535",
    quote: "He who fears he shall suffer, already suffers what he fears.",
    attribution: "Michel de Montaigne",
    theme: "Mindset",
    difficulty: "hard",
    clueWords: [
      { hint: "Is afraid of", word: "FEARS" },
      { hint: "Is to, will", word: "SHALL" },
      { hint: "Endures pain", word: "SUFFER" },
      { hint: "Endures pain (third person)", word: "SUFFERS" },
      { hint: "By this time", word: "ALREADY" },
    ],
  },
  {
    id: "p536",
    quote: "The greatest thing is to know how to belong to oneself.",
    attribution: "Michel de Montaigne",
    theme: "Authenticity",
    difficulty: "hard",
    clueWords: [
      { hint: "Largest, finest", word: "GREATEST" },
      { hint: "An item or matter", word: "THING" },
      { hint: "Be aware of", word: "KNOW" },
      { hint: "Be a member of", word: "BELONG" },
      { hint: "One's own person", word: "ONESELF" },
    ],
  },
  {
    id: "p537",
    quote: "I quote others only the better to express myself.",
    attribution: "Michel de Montaigne",
    theme: "Communication",
    difficulty: "hard",
    clueWords: [
      { hint: "Repeat words of", word: "QUOTE" },
      { hint: "Other people", word: "OTHERS" },
      { hint: "Solely", word: "ONLY" },
      { hint: "Convey, communicate", word: "EXPRESS" },
      { hint: "My own self", word: "MYSELF" },
    ],
  },
  {
    id: "p538",
    quote: "I am the master of my fate, I am the captain of my soul.",
    attribution: "William Ernest Henley",
    theme: "Self-Determination",
    difficulty: "hard",
    clueWords: [
      { hint: "Controller, expert", word: "MASTER" },
      { hint: "Predetermined destiny", word: "FATE" },
      { hint: "A leader", word: "CAPTAIN" },
      { hint: "Inner essence", word: "SOUL" },
    ],
  },
  {
    id: "p539",
    quote: "What does not destroy me makes me stronger.",
    attribution: "Friedrich Nietzsche",
    theme: "Resilience",
    difficulty: "hard",
    clueWords: [
      { hint: "Wreck, ruin", word: "DESTROY" },
      { hint: "Causes me to be", word: "MAKES" },
      { hint: "Of greater fortitude", word: "STRONGER" },
    ],
  },
  {
    id: "p540",
    quote: "Those who were dancing were thought insane by those who could not hear the music.",
    attribution: "Friedrich Nietzsche",
    theme: "Originality",
    difficulty: "hard",
    clueWords: [
      { hint: "Particular ones", word: "THOSE" },
      { hint: "Moving rhythmically", word: "DANCING" },
      { hint: "Considered, believed", word: "THOUGHT" },
      { hint: "Mad, crazy", word: "INSANE" },
      { hint: "Receive sound", word: "HEAR" },
      { hint: "Organized sound", word: "MUSIC" },
    ],
  },
  {
    id: "p541",
    quote: "It is not a lack of love but a lack of friendship that makes unhappy marriages.",
    attribution: "Friedrich Nietzsche",
    theme: "Friendship",
    difficulty: "hard",
    clueWords: [
      { hint: "An absence", word: "LACK" },
      { hint: "Deep affection", word: "LOVE" },
      { hint: "Mutual companionship", word: "FRIENDSHIP" },
      { hint: "Cause to be", word: "MAKES" },
      { hint: "Not joyful", word: "UNHAPPY" },
      { hint: "Wedded unions", word: "MARRIAGES" },
    ],
  },
  {
    id: "p542",
    quote: "There are no facts, only interpretations.",
    attribution: "Friedrich Nietzsche",
    theme: "Perspective",
    difficulty: "hard",
    clueWords: [
      { hint: "True statements", word: "FACTS" },
      { hint: "Solely", word: "ONLY" },
      { hint: "Personal readings", word: "INTERPRETATIONS" },
    ],
  },
  {
    id: "p543",
    quote: "What is now proved was once only imagined.",
    attribution: "William Blake",
    theme: "Possibility",
    difficulty: "hard",
    clueWords: [
      { hint: "At this moment", word: "NOW" },
      { hint: "Demonstrated", word: "PROVED" },
      { hint: "A single occasion", word: "ONCE" },
      { hint: "Solely", word: "ONLY" },
      { hint: "Conceived in mind", word: "IMAGINED" },
    ],
  },
  {
    id: "p544",
    quote: "The road of excess leads to the palace of wisdom.",
    attribution: "William Blake",
    theme: "Experience",
    difficulty: "hard",
    clueWords: [
      { hint: "A travel route", word: "ROAD" },
      { hint: "Going beyond limits", word: "EXCESS" },
      { hint: "Guides, conducts", word: "LEADS" },
      { hint: "A grand residence", word: "PALACE" },
      { hint: "Deep insight", word: "WISDOM" },
    ],
  },
  {
    id: "p545",
    quote: "To see a world in a grain of sand and a heaven in a wild flower.",
    attribution: "William Blake",
    theme: "Wonder",
    difficulty: "hard",
    clueWords: [
      { hint: "Perceive with eyes", word: "SEE" },
      { hint: "The earth, realm", word: "WORLD" },
      { hint: "A small particle", word: "GRAIN" },
      { hint: "Beach material", word: "SAND" },
      { hint: "The sky, paradise", word: "HEAVEN" },
      { hint: "Plant blossom", word: "FLOWER" },
    ],
  },
  {
    id: "p546",
    quote: "Better to remain silent and be thought a fool than to speak and remove all doubt.",
    attribution: "Mark Twain",
    theme: "Wisdom",
    difficulty: "hard",
    clueWords: [
      { hint: "Preferable", word: "BETTER" },
      { hint: "Stay", word: "REMAIN" },
      { hint: "Without sound", word: "SILENT" },
      { hint: "Considered, supposed", word: "THOUGHT" },
      { hint: "A foolish person", word: "FOOL" },
      { hint: "Utter aloud", word: "SPEAK" },
    ],
  },
  {
    id: "p547",
    quote: "Whenever you find yourself on the side of the majority, it is time to pause and reflect.",
    attribution: "Mark Twain",
    theme: "Independence",
    difficulty: "hard",
    clueWords: [
      { hint: "Discover", word: "FIND" },
      { hint: "Your own person", word: "YOURSELF" },
      { hint: "An edge or position", word: "SIDE" },
      { hint: "Larger group", word: "MAJORITY" },
      { hint: "Brief stop", word: "PAUSE" },
      { hint: "Ponder", word: "REFLECT" },
    ],
  },
  {
    id: "p548",
    quote: "Twenty years from now you will be more disappointed by what you did not do than what you did.",
    attribution: "Mark Twain",
    theme: "Regret",
    difficulty: "hard",
    clueWords: [
      { hint: "Two times ten", word: "TWENTY" },
      { hint: "Calendar units", word: "YEARS" },
      { hint: "Frustrated by unmet hopes", word: "DISAPPOINTED" },
      { hint: "Performed", word: "DID" },
      { hint: "Perform", word: "DO" },
      { hint: "To a greater degree", word: "MORE" },
    ],
  },
  {
    id: "p549",
    quote: "The two most important days in your life are the day you are born and the day you find out why.",
    attribution: "Mark Twain",
    theme: "Purpose",
    difficulty: "hard",
    clueWords: [
      { hint: "A pair", word: "TWO" },
      { hint: "Greatest in degree", word: "MOST" },
      { hint: "Significant", word: "IMPORTANT" },
      { hint: "24-hour periods", word: "DAYS" },
      { hint: "Brought into life", word: "BORN" },
      { hint: "Discover", word: "FIND" },
    ],
  },
  {
    id: "p550",
    quote: "Outside of a dog, a book is a person's best friend.",
    attribution: "Groucho Marx",
    theme: "Learning",
    difficulty: "hard",
    clueWords: [
      { hint: "Beyond, except", word: "OUTSIDE" },
      { hint: "Loyal canine pet", word: "DOG" },
      { hint: "Bound reading material", word: "BOOK" },
      { hint: "An individual", word: "PERSON" },
      { hint: "Top quality", word: "BEST" },
      { hint: "A close companion", word: "FRIEND" },
    ],
  },
  {
    id: "p551",
    quote: "We learn from history that we do not learn from history.",
    attribution: "Georg Wilhelm Friedrich Hegel",
    theme: "Learning",
    difficulty: "hard",
    clueWords: [
      { hint: "Acquire knowledge", word: "LEARN" },
      { hint: "Past events", word: "HISTORY" },
      { hint: "First-person plural", word: "WE" },
    ],
  },
  {
    id: "p552",
    quote: "The only thing necessary for the triumph of evil is for good people to do nothing.",
    attribution: "Edmund Burke",
    theme: "Action",
    difficulty: "hard",
    clueWords: [
      { hint: "Sole, single", word: "ONLY" },
      { hint: "Required", word: "NECESSARY" },
      { hint: "Victory", word: "TRIUMPH" },
      { hint: "Wickedness", word: "EVIL" },
      { hint: "Worthy", word: "GOOD" },
      { hint: "Not anything", word: "NOTHING" },
    ],
  },
  {
    id: "p553",
    quote: "Those who do not move, do not notice their chains.",
    attribution: "Rosa Luxemburg",
    theme: "Liberty",
    difficulty: "hard",
    clueWords: [
      { hint: "Particular ones", word: "THOSE" },
      { hint: "Travel, shift", word: "MOVE" },
      { hint: "Become aware of", word: "NOTICE" },
      { hint: "Linked iron rings", word: "CHAINS" },
      { hint: "Belonging to them", word: "THEIR" },
    ],
  },
  {
    id: "p554",
    quote: "Time is the wisest counselor of all.",
    attribution: "Pericles",
    theme: "Wisdom",
    difficulty: "hard",
    clueWords: [
      { hint: "Hours and minutes", word: "TIME" },
      { hint: "Most sage", word: "WISEST" },
      { hint: "An advisor", word: "COUNSELOR" },
      { hint: "Each, every", word: "ALL" },
    ],
  },
  {
    id: "p555",
    quote: "What you leave behind is woven into the lives of others.",
    attribution: "Pericles",
    theme: "Legacy",
    difficulty: "hard",
    clueWords: [
      { hint: "Depart from", word: "LEAVE" },
      { hint: "In the rear", word: "BEHIND" },
      { hint: "Interlaced", word: "WOVEN" },
      { hint: "Existences", word: "LIVES" },
      { hint: "Other people", word: "OTHERS" },
    ],
  },
  {
    id: "p556",
    quote: "He who moves not forward, goes backward.",
    attribution: "Johann Wolfgang von Goethe",
    theme: "Growth",
    difficulty: "hard",
    clueWords: [
      { hint: "Travels", word: "MOVES" },
      { hint: "Toward the front", word: "FORWARD" },
      { hint: "Travels", word: "GOES" },
      { hint: "Toward the rear", word: "BACKWARD" },
    ],
  },
  {
    id: "p557",
    quote: "By seeking and blundering we learn.",
    attribution: "Johann Wolfgang von Goethe",
    theme: "Learning",
    difficulty: "hard",
    clueWords: [
      { hint: "Searching for", word: "SEEKING" },
      { hint: "Making errors", word: "BLUNDERING" },
      { hint: "Acquire knowledge", word: "LEARN" },
      { hint: "First-person plural", word: "WE" },
    ],
  },
  {
    id: "p558",
    quote: "Knowing is not enough; we must apply. Willing is not enough; we must do.",
    attribution: "Johann Wolfgang von Goethe",
    theme: "Action",
    difficulty: "hard",
    clueWords: [
      { hint: "Being aware of", word: "KNOWING" },
      { hint: "Sufficient", word: "ENOUGH" },
      { hint: "Put into use", word: "APPLY" },
      { hint: "Ready, prepared", word: "WILLING" },
      { hint: "Perform", word: "DO" },
    ],
  },
  {
    id: "p559",
    quote: "Do not look back. You are not going that way.",
    attribution: "Mary Engelbreit",
    theme: "Mindfulness",
    difficulty: "hard",
    clueWords: [
      { hint: "Use the eyes", word: "LOOK" },
      { hint: "Toward the rear", word: "BACK" },
      { hint: "Traveling", word: "GOING" },
      { hint: "A path or route", word: "WAY" },
    ],
  },
  {
    id: "p560",
    quote: "There are far better things ahead than any we leave behind.",
    attribution: "C.S. Lewis",
    theme: "Hope",
    difficulty: "hard",
    clueWords: [
      { hint: "To a great distance", word: "FAR" },
      { hint: "More desirable", word: "BETTER" },
      { hint: "Items, matters", word: "THINGS" },
      { hint: "In front", word: "AHEAD" },
      { hint: "Depart from", word: "LEAVE" },
      { hint: "In the rear", word: "BEHIND" },
    ],
  },
  {
    id: "p561",
    quote: "Worry never robs tomorrow of its sorrow, it only saps today of its joy.",
    attribution: "Leo Buscaglia",
    theme: "Mindfulness",
    difficulty: "hard",
    clueWords: [
      { hint: "Anxiety", word: "WORRY" },
      { hint: "At no time", word: "NEVER" },
      { hint: "Steals from", word: "ROBS" },
      { hint: "The day after today", word: "TOMORROW" },
      { hint: "Sadness", word: "SORROW" },
      { hint: "Happiness", word: "JOY" },
    ],
  },
  {
    id: "p562",
    quote: "There is more wisdom in your body than in your deepest philosophy.",
    attribution: "Friedrich Nietzsche",
    theme: "Body",
    difficulty: "hard",
    clueWords: [
      { hint: "Deep insight", word: "WISDOM" },
      { hint: "Physical form", word: "BODY" },
      { hint: "Most profound", word: "DEEPEST" },
      { hint: "Study of fundamental questions", word: "PHILOSOPHY" },
      { hint: "Belonging to you", word: "YOUR" },
    ],
  },
  {
    id: "p563",
    quote: "The privilege of a lifetime is to become who you truly are.",
    attribution: "Carl Jung",
    theme: "Authenticity",
    difficulty: "hard",
    clueWords: [
      { hint: "Special advantage", word: "PRIVILEGE" },
      { hint: "Span of one's life", word: "LIFETIME" },
      { hint: "Turn into", word: "BECOME" },
      { hint: "In a true way", word: "TRULY" },
    ],
  },
  {
    id: "p564",
    quote: "Until you make the unconscious conscious, it will direct your life and you will call it fate.",
    attribution: "Carl Jung",
    theme: "Self-Knowledge",
    difficulty: "hard",
    clueWords: [
      { hint: "Up to the moment that", word: "UNTIL" },
      { hint: "Hidden mind", word: "UNCONSCIOUS" },
      { hint: "Aware mind", word: "CONSCIOUS" },
      { hint: "Guide, lead", word: "DIRECT" },
      { hint: "Existence", word: "LIFE" },
      { hint: "Predetermined destiny", word: "FATE" },
    ],
  },
  {
    id: "p565",
    quote: "Loneliness comes from being unable to communicate things that seem important.",
    attribution: "Carl Jung",
    theme: "Connection",
    difficulty: "hard",
    clueWords: [
      { hint: "Solitude, isolation", word: "LONELINESS" },
      { hint: "Arrives", word: "COMES" },
      { hint: "Not capable", word: "UNABLE" },
      { hint: "Convey, share", word: "COMMUNICATE" },
      { hint: "Items, matters", word: "THINGS" },
      { hint: "Significant", word: "IMPORTANT" },
    ],
  },
  {
    id: "p566",
    quote: "Be silent, or let thy words be worth more than silence.",
    attribution: "Pythagoras",
    theme: "Communication",
    difficulty: "hard",
    clueWords: [
      { hint: "Without sound", word: "SILENT" },
      { hint: "Allow", word: "LET" },
      { hint: "Your (archaic)", word: "THY" },
      { hint: "Spoken units", word: "WORDS" },
      { hint: "Of value", word: "WORTH" },
      { hint: "Absence of sound", word: "SILENCE" },
    ],
  },
  {
    id: "p567",
    quote: "Choose rather to be strong of soul than strong of body.",
    attribution: "Pythagoras",
    theme: "Character",
    difficulty: "hard",
    clueWords: [
      { hint: "Make a selection", word: "CHOOSE" },
      { hint: "Instead", word: "RATHER" },
      { hint: "Powerful", word: "STRONG" },
      { hint: "Inner essence", word: "SOUL" },
      { hint: "Physical form", word: "BODY" },
    ],
  },
  {
    id: "p568",
    quote: "Educate the children and it will not be necessary to punish the men.",
    attribution: "Pythagoras",
    theme: "Learning",
    difficulty: "hard",
    clueWords: [
      { hint: "Provide schooling", word: "EDUCATE" },
      { hint: "Young persons", word: "CHILDREN" },
      { hint: "Required", word: "NECESSARY" },
      { hint: "Discipline, penalize", word: "PUNISH" },
      { hint: "Adult human males", word: "MEN" },
    ],
  },
  {
    id: "p569",
    quote: "Friends are companions on a journey who help each other to persevere.",
    attribution: "Pythagoras",
    theme: "Friendship",
    difficulty: "hard",
    clueWords: [
      { hint: "Close associates", word: "FRIENDS" },
      { hint: "Travel partners", word: "COMPANIONS" },
      { hint: "A long trip", word: "JOURNEY" },
      { hint: "Aid, assist", word: "HELP" },
      { hint: "Persist through", word: "PERSEVERE" },
    ],
  },
  {
    id: "p570",
    quote: "Above all things, reverence yourself.",
    attribution: "Pythagoras",
    theme: "Self-Respect",
    difficulty: "hard",
    clueWords: [
      { hint: "Higher than", word: "ABOVE" },
      { hint: "Each, every", word: "ALL" },
      { hint: "Items, matters", word: "THINGS" },
      { hint: "Deep respect", word: "REVERENCE" },
      { hint: "Your own person", word: "YOURSELF" },
    ],
  },
  {
    id: "p571",
    quote: "Force has no place where there is need of skill.",
    attribution: "Herodotus",
    theme: "Wisdom",
    difficulty: "hard",
    clueWords: [
      { hint: "Strength applied", word: "FORCE" },
      { hint: "A location", word: "PLACE" },
      { hint: "Requirement", word: "NEED" },
      { hint: "Trained ability", word: "SKILL" },
      { hint: "At which point", word: "WHERE" },
    ],
  },
  {
    id: "p572",
    quote: "Men trust their ears less than their eyes.",
    attribution: "Herodotus",
    theme: "Perception",
    difficulty: "hard",
    clueWords: [
      { hint: "Adult human males", word: "MEN" },
      { hint: "Have faith in", word: "TRUST" },
      { hint: "Hearing organs", word: "EARS" },
      { hint: "Sight organs", word: "EYES" },
      { hint: "To a smaller extent", word: "LESS" },
    ],
  },
  {
    id: "p573",
    quote: "Bravery is the capacity to perform properly even when scared half to death.",
    attribution: "Omar Bradley",
    theme: "Courage",
    difficulty: "hard",
    clueWords: [
      { hint: "Courage", word: "BRAVERY" },
      { hint: "Ability", word: "CAPACITY" },
      { hint: "Carry out", word: "PERFORM" },
      { hint: "Correctly", word: "PROPERLY" },
      { hint: "Frightened", word: "SCARED" },
      { hint: "End of life", word: "DEATH" },
    ],
  },
  {
    id: "p574",
    quote: "Courage is grace under pressure.",
    attribution: "Ernest Hemingway",
    theme: "Courage",
    difficulty: "hard",
    clueWords: [
      { hint: "Bravery", word: "COURAGE" },
      { hint: "Elegance, poise", word: "GRACE" },
      { hint: "Stress, force", word: "PRESSURE" },
      { hint: "Beneath", word: "UNDER" },
    ],
  },
  {
    id: "p575",
    quote: "True nobility is being superior to your former self.",
    attribution: "Ernest Hemingway",
    theme: "Growth",
    difficulty: "hard",
    clueWords: [
      { hint: "Genuine, real", word: "TRUE" },
      { hint: "High character", word: "NOBILITY" },
      { hint: "Better than", word: "SUPERIOR" },
      { hint: "Earlier, previous", word: "FORMER" },
      { hint: "Your own person", word: "SELF" },
    ],
  },
  {
    id: "p576",
    quote: "The world breaks everyone, and afterward, many are strong at the broken places.",
    attribution: "Ernest Hemingway",
    theme: "Resilience",
    difficulty: "hard",
    clueWords: [
      { hint: "The earth", word: "WORLD" },
      { hint: "Snaps apart", word: "BREAKS" },
      { hint: "Each person", word: "EVERYONE" },
      { hint: "A great number", word: "MANY" },
      { hint: "Strong, firm", word: "STRONG" },
      { hint: "Fractured", word: "BROKEN" },
    ],
  },
  {
    id: "p577",
    quote: "A man can be destroyed but not defeated.",
    attribution: "Ernest Hemingway",
    theme: "Resilience",
    difficulty: "hard",
    clueWords: [
      { hint: "Adult human male", word: "MAN" },
      { hint: "Be able to", word: "CAN" },
      { hint: "Wrecked, ruined", word: "DESTROYED" },
      { hint: "Beaten, conquered", word: "DEFEATED" },
    ],
  },
  {
    id: "p578",
    quote: "When people talk, listen completely.",
    attribution: "Ernest Hemingway",
    theme: "Listening",
    difficulty: "hard",
    clueWords: [
      { hint: "Human beings", word: "PEOPLE" },
      { hint: "Speak", word: "TALK" },
      { hint: "Pay attention", word: "LISTEN" },
      { hint: "Wholly, fully", word: "COMPLETELY" },
    ],
  },
  {
    id: "p579",
    quote: "There is no friend as loyal as a book.",
    attribution: "Ernest Hemingway",
    theme: "Learning",
    difficulty: "hard",
    clueWords: [
      { hint: "A close companion", word: "FRIEND" },
      { hint: "Faithful", word: "LOYAL" },
      { hint: "Bound reading material", word: "BOOK" },
    ],
  },
  {
    id: "p580",
    quote: "It takes courage to grow up and become who you really are.",
    attribution: "E.E. Cummings",
    theme: "Authenticity",
    difficulty: "hard",
    clueWords: [
      { hint: "Requires", word: "TAKES" },
      { hint: "Bravery", word: "COURAGE" },
      { hint: "Mature", word: "GROW" },
      { hint: "Turn into", word: "BECOME" },
      { hint: "Truly, in fact", word: "REALLY" },
    ],
  },
  {
    id: "p581",
    quote: "Once we believe in ourselves, we can risk curiosity, wonder, spontaneous delight.",
    attribution: "E.E. Cummings",
    theme: "Confidence",
    difficulty: "hard",
    clueWords: [
      { hint: "A single occasion", word: "ONCE" },
      { hint: "Have faith", word: "BELIEVE" },
      { hint: "Our own selves", word: "OURSELVES" },
      { hint: "Hazard, dare", word: "RISK" },
      { hint: "Eagerness to know", word: "CURIOSITY" },
      { hint: "Awe, amazement", word: "WONDER" },
    ],
  },
  {
    id: "p582",
    quote: "When the power of love overcomes the love of power, the world will know peace.",
    attribution: "Jimi Hendrix",
    theme: "Peace",
    difficulty: "hard",
    clueWords: [
      { hint: "Strength, force", word: "POWER" },
      { hint: "Deep affection", word: "LOVE" },
      { hint: "Conquers", word: "OVERCOMES" },
      { hint: "The earth", word: "WORLD" },
      { hint: "Be aware of", word: "KNOW" },
      { hint: "Tranquility", word: "PEACE" },
    ],
  },
  {
    id: "p583",
    quote: "Music is a higher revelation than all wisdom and philosophy.",
    attribution: "Ludwig van Beethoven",
    theme: "Wonder",
    difficulty: "hard",
    clueWords: [
      { hint: "Organized sound", word: "MUSIC" },
      { hint: "Of greater elevation", word: "HIGHER" },
      { hint: "Disclosure of truth", word: "REVELATION" },
      { hint: "Deep insight", word: "WISDOM" },
      { hint: "Study of fundamental questions", word: "PHILOSOPHY" },
    ],
  },
  {
    id: "p584",
    quote: "Friends show their love in times of trouble, not in happiness.",
    attribution: "Euripides",
    theme: "Friendship",
    difficulty: "hard",
    clueWords: [
      { hint: "Close companions", word: "FRIENDS" },
      { hint: "Display, demonstrate", word: "SHOW" },
      { hint: "Deep affection", word: "LOVE" },
      { hint: "Periods, occasions", word: "TIMES" },
      { hint: "Distress", word: "TROUBLE" },
      { hint: "Joyful state", word: "HAPPINESS" },
    ],
  },
  {
    id: "p585",
    quote: "When good men die their goodness does not perish, but lives though they are gone.",
    attribution: "Euripides",
    theme: "Legacy",
    difficulty: "hard",
    clueWords: [
      { hint: "Worthy", word: "GOOD" },
      { hint: "Adult human males", word: "MEN" },
      { hint: "Cease to live", word: "DIE" },
      { hint: "Quality of being good", word: "GOODNESS" },
      { hint: "Be destroyed", word: "PERISH" },
      { hint: "Continues to exist", word: "LIVES" },
    ],
  },
  {
    id: "p586",
    quote: "Question everything. Learn something. Answer nothing.",
    attribution: "Euripides",
    theme: "Wisdom",
    difficulty: "hard",
    clueWords: [
      { hint: "Inquire about", word: "QUESTION" },
      { hint: "All things", word: "EVERYTHING" },
      { hint: "Acquire knowledge", word: "LEARN" },
      { hint: "An item or matter", word: "SOMETHING" },
      { hint: "Reply", word: "ANSWER" },
      { hint: "Not anything", word: "NOTHING" },
    ],
  },
  {
    id: "p587",
    quote: "Things are not always what they seem; the first appearance deceives many.",
    attribution: "Phaedrus",
    theme: "Perception",
    difficulty: "hard",
    clueWords: [
      { hint: "Items, matters", word: "THINGS" },
      { hint: "All the time", word: "ALWAYS" },
      { hint: "Look like", word: "SEEM" },
      { hint: "Initial", word: "FIRST" },
      { hint: "How something looks", word: "APPEARANCE" },
      { hint: "Misleads", word: "DECEIVES" },
    ],
  },
  {
    id: "p588",
    quote: "Better to ask twice than to lose your way once.",
    attribution: "Danish Proverb",
    theme: "Humility",
    difficulty: "hard",
    clueWords: [
      { hint: "Preferable", word: "BETTER" },
      { hint: "Inquire", word: "ASK" },
      { hint: "Two times", word: "TWICE" },
      { hint: "Forfeit, misplace", word: "LOSE" },
      { hint: "A path", word: "WAY" },
      { hint: "A single occasion", word: "ONCE" },
    ],
  },
  {
    id: "p589",
    quote: "After the verb to love, to help is the most beautiful verb in the world.",
    attribution: "Bertha von Suttner",
    theme: "Service",
    difficulty: "hard",
    clueWords: [
      { hint: "An action word", word: "VERB" },
      { hint: "Show affection", word: "LOVE" },
      { hint: "Aid, assist", word: "HELP" },
      { hint: "Aesthetically pleasing", word: "BEAUTIFUL" },
      { hint: "The earth", word: "WORLD" },
    ],
  },
  {
    id: "p590",
    quote: "We are most alive when we are in love.",
    attribution: "John Updike",
    theme: "Love",
    difficulty: "hard",
    clueWords: [
      { hint: "Greatest extent", word: "MOST" },
      { hint: "Living", word: "ALIVE" },
      { hint: "Deep affection", word: "LOVE" },
      { hint: "First-person plural", word: "WE" },
    ],
  },

  // -------------------- EXPERT (40) --------------------
  {
    id: "p591",
    quote: "I think therefore I am.",
    attribution: "Rene Descartes",
    theme: "Existence",
    difficulty: "expert",
    clueWords: [
      { hint: "Use the mind", word: "THINK" },
      { hint: "For that reason", word: "THEREFORE" },
    ],
  },
  {
    id: "p592",
    quote: "The greatest minds are capable of the greatest vices as well as virtues.",
    attribution: "Rene Descartes",
    theme: "Character",
    difficulty: "expert",
    clueWords: [
      { hint: "Most outstanding", word: "GREATEST" },
      { hint: "Thinking faculties", word: "MINDS" },
      { hint: "Able", word: "CAPABLE" },
      { hint: "Moral faults", word: "VICES" },
      { hint: "Moral excellences", word: "VIRTUES" },
    ],
  },
  {
    id: "p593",
    quote: "It is not enough to have a good mind; the main thing is to use it well.",
    attribution: "Rene Descartes",
    theme: "Wisdom",
    difficulty: "expert",
    clueWords: [
      { hint: "Sufficient", word: "ENOUGH" },
      { hint: "Possess", word: "HAVE" },
      { hint: "Worthy", word: "GOOD" },
      { hint: "Thinking faculty", word: "MIND" },
      { hint: "Most important", word: "MAIN" },
      { hint: "Properly", word: "WELL" },
    ],
  },
  {
    id: "p594",
    quote: "If you would be a real seeker after truth, doubt all things at least once.",
    attribution: "Rene Descartes",
    theme: "Truth",
    difficulty: "expert",
    clueWords: [
      { hint: "Genuine", word: "REAL" },
      { hint: "One who searches", word: "SEEKER" },
      { hint: "Honest reality", word: "TRUTH" },
      { hint: "Question, distrust", word: "DOUBT" },
      { hint: "A single occasion", word: "ONCE" },
      { hint: "Items, matters", word: "THINGS" },
    ],
  },
  {
    id: "p595",
    quote: "Conquer yourself rather than the world.",
    attribution: "Rene Descartes",
    theme: "Self-Control",
    difficulty: "expert",
    clueWords: [
      { hint: "Defeat, overcome", word: "CONQUER" },
      { hint: "Your own person", word: "YOURSELF" },
      { hint: "Instead", word: "RATHER" },
      { hint: "The earth", word: "WORLD" },
    ],
  },
  {
    id: "p596",
    quote: "Half of the troubles of life can be traced to saying yes too quickly.",
    attribution: "Josh Billings",
    theme: "Discernment",
    difficulty: "expert",
    clueWords: [
      { hint: "Fifty percent", word: "HALF" },
      { hint: "Difficulties", word: "TROUBLES" },
      { hint: "Existence", word: "LIFE" },
      { hint: "Followed back", word: "TRACED" },
      { hint: "Affirmative reply", word: "YES" },
      { hint: "Rapidly", word: "QUICKLY" },
    ],
  },
  {
    id: "p597",
    quote: "I am only one, but still I am one. I cannot do everything, but I can do something.",
    attribution: "Edward Everett Hale",
    theme: "Initiative",
    difficulty: "expert",
    clueWords: [
      { hint: "Sole, single", word: "ONLY" },
      { hint: "A single unit", word: "ONE" },
      { hint: "Yet, even", word: "STILL" },
      { hint: "Are not able to", word: "CANNOT" },
      { hint: "All things", word: "EVERYTHING" },
      { hint: "An item or task", word: "SOMETHING" },
    ],
  },
  {
    id: "p598",
    quote: "I am a slow walker, but I never walk back.",
    attribution: "Abraham Lincoln",
    theme: "Persistence",
    difficulty: "expert",
    clueWords: [
      { hint: "Not fast", word: "SLOW" },
      { hint: "One who travels on foot", word: "WALKER" },
      { hint: "At no time", word: "NEVER" },
      { hint: "Move on foot", word: "WALK" },
      { hint: "Toward the rear", word: "BACK" },
    ],
  },
  {
    id: "p599",
    quote: "Most folks are about as happy as they make up their minds to be.",
    attribution: "Abraham Lincoln",
    theme: "Happiness",
    difficulty: "expert",
    clueWords: [
      { hint: "Greatest amount", word: "MOST" },
      { hint: "Common people", word: "FOLKS" },
      { hint: "Joyful", word: "HAPPY" },
      { hint: "Cause to be", word: "MAKE" },
      { hint: "Thinking faculties", word: "MINDS" },
      { hint: "Concerning", word: "ABOUT" },
    ],
  },
  {
    id: "p600",
    quote: "Things may come to those who wait, but only the things left by those who hustle.",
    attribution: "Abraham Lincoln",
    theme: "Initiative",
    difficulty: "expert",
    clueWords: [
      { hint: "Items, matters", word: "THINGS" },
      { hint: "Possibly", word: "MAY" },
      { hint: "Arrive", word: "COME" },
      { hint: "Particular ones", word: "THOSE" },
      { hint: "Stay in expectation", word: "WAIT" },
      { hint: "Move with energy", word: "HUSTLE" },
    ],
  },
  {
    id: "p601",
    quote: "Nearly all people can stand adversity, but if you want to test character, give power.",
    attribution: "Abraham Lincoln",
    theme: "Character",
    difficulty: "expert",
    clueWords: [
      { hint: "Almost", word: "NEARLY" },
      { hint: "Endure", word: "STAND" },
      { hint: "Hardship", word: "ADVERSITY" },
      { hint: "Examine", word: "TEST" },
      { hint: "Moral nature", word: "CHARACTER" },
      { hint: "Authority", word: "POWER" },
    ],
  },
  {
    id: "p602",
    quote: "Always do sober what you said you would do.",
    attribution: "Ernest Hemingway",
    theme: "Integrity",
    difficulty: "expert",
    clueWords: [
      { hint: "All the time", word: "ALWAYS" },
      { hint: "Perform", word: "DO" },
      { hint: "Not intoxicated", word: "SOBER" },
      { hint: "Stated, expressed", word: "SAID" },
    ],
  },
  {
    id: "p603",
    quote: "Friendship is born at the moment when one person says: What! You too?",
    attribution: "C.S. Lewis",
    theme: "Friendship",
    difficulty: "expert",
    clueWords: [
      { hint: "Mutual companionship", word: "FRIENDSHIP" },
      { hint: "Brought into being", word: "BORN" },
      { hint: "An instant", word: "MOMENT" },
      { hint: "An individual", word: "PERSON" },
      { hint: "Utters, states", word: "SAYS" },
    ],
  },
  {
    id: "p604",
    quote: "There is no greater wealth in this world than peace of mind.",
    attribution: "Anonymous",
    theme: "Peace",
    difficulty: "expert",
    clueWords: [
      { hint: "Larger, more", word: "GREATER" },
      { hint: "Riches", word: "WEALTH" },
      { hint: "The earth", word: "WORLD" },
      { hint: "Tranquility", word: "PEACE" },
      { hint: "Thinking faculty", word: "MIND" },
    ],
  },
  {
    id: "p605",
    quote: "If you cannot fly then run, if you cannot run then walk, but keep moving forward.",
    attribution: "Martin Luther King Jr.",
    theme: "Persistence",
    difficulty: "expert",
    clueWords: [
      { hint: "Move through air", word: "FLY" },
      { hint: "Move quickly on foot", word: "RUN" },
      { hint: "Move slowly on foot", word: "WALK" },
      { hint: "Maintain", word: "KEEP" },
      { hint: "Toward the front", word: "FORWARD" },
      { hint: "In motion", word: "MOVING" },
    ],
  },
  {
    id: "p606",
    quote: "I have spent most of my life worrying about things that have never happened.",
    attribution: "Mark Twain",
    theme: "Mindfulness",
    difficulty: "expert",
    clueWords: [
      { hint: "Used up time", word: "SPENT" },
      { hint: "Greatest amount", word: "MOST" },
      { hint: "Existence", word: "LIFE" },
      { hint: "Fretting", word: "WORRYING" },
      { hint: "At no time", word: "NEVER" },
      { hint: "Took place", word: "HAPPENED" },
    ],
  },
  {
    id: "p607",
    quote: "Music in the soul can be heard by the universe.",
    attribution: "Lao Tzu",
    theme: "Wonder",
    difficulty: "expert",
    clueWords: [
      { hint: "Organized sound", word: "MUSIC" },
      { hint: "Inner essence", word: "SOUL" },
      { hint: "Perceived by ear", word: "HEARD" },
      { hint: "All of existence", word: "UNIVERSE" },
    ],
  },
  {
    id: "p608",
    quote: "When I let go of what I am, I become what I might be.",
    attribution: "Lao Tzu",
    theme: "Transformation",
    difficulty: "expert",
    clueWords: [
      { hint: "Allow", word: "LET" },
      { hint: "Release", word: "GO" },
      { hint: "Turn into", word: "BECOME" },
      { hint: "Possibly will", word: "MIGHT" },
    ],
  },
  {
    id: "p609",
    quote: "It is your reaction to adversity that determines your story.",
    attribution: "Marcus Aurelius",
    theme: "Mindset",
    difficulty: "expert",
    clueWords: [
      { hint: "A response", word: "REACTION" },
      { hint: "Hardship", word: "ADVERSITY" },
      { hint: "Decides, fixes", word: "DETERMINES" },
      { hint: "A narrative", word: "STORY" },
      { hint: "Belonging to you", word: "YOUR" },
    ],
  },
  {
    id: "p610",
    quote: "We are not human beings having a spiritual experience; we are spiritual beings having a human experience.",
    attribution: "Pierre Teilhard de Chardin",
    theme: "Spirituality",
    difficulty: "expert",
    clueWords: [
      { hint: "Of people", word: "HUMAN" },
      { hint: "Living entities", word: "BEINGS" },
      { hint: "Possessing", word: "HAVING" },
      { hint: "Of the spirit", word: "SPIRITUAL" },
      { hint: "Lived event", word: "EXPERIENCE" },
    ],
  },
  {
    id: "p611",
    quote: "Words can be like rays if used properly. They will go through anything.",
    attribution: "Aldous Huxley",
    theme: "Communication",
    difficulty: "expert",
    clueWords: [
      { hint: "Spoken units", word: "WORDS" },
      { hint: "Beams of light", word: "RAYS" },
      { hint: "Correctly", word: "PROPERLY" },
      { hint: "From end to end", word: "THROUGH" },
      { hint: "Any item", word: "ANYTHING" },
    ],
  },
  {
    id: "p612",
    quote: "Whoever has chosen wisdom rather than money will get the reward.",
    attribution: "Anonymous",
    theme: "Values",
    difficulty: "expert",
    clueWords: [
      { hint: "Any person", word: "WHOEVER" },
      { hint: "Selected", word: "CHOSEN" },
      { hint: "Deep insight", word: "WISDOM" },
      { hint: "Currency", word: "MONEY" },
      { hint: "Recompense", word: "REWARD" },
      { hint: "Instead", word: "RATHER" },
    ],
  },
  {
    id: "p613",
    quote: "There is no person so severely punished as those subject to remorse.",
    attribution: "Seneca",
    theme: "Forgiveness",
    difficulty: "expert",
    clueWords: [
      { hint: "Individual", word: "PERSON" },
      { hint: "Harshly", word: "SEVERELY" },
      { hint: "Disciplined", word: "PUNISHED" },
      { hint: "Particular ones", word: "THOSE" },
      { hint: "Subjected to", word: "SUBJECT" },
      { hint: "Deep regret", word: "REMORSE" },
    ],
  },
  {
    id: "p614",
    quote: "The only way to deal with this life is to find that something larger than yourself.",
    attribution: "Anonymous",
    theme: "Purpose",
    difficulty: "expert",
    clueWords: [
      { hint: "Sole, single", word: "ONLY" },
      { hint: "A path or method", word: "WAY" },
      { hint: "Manage, handle", word: "DEAL" },
      { hint: "Existence", word: "LIFE" },
      { hint: "Discover", word: "FIND" },
      { hint: "Bigger", word: "LARGER" },
    ],
  },
  {
    id: "p615",
    quote: "We forge the chains we wear in life.",
    attribution: "Charles Dickens",
    theme: "Self-Determination",
    difficulty: "expert",
    clueWords: [
      { hint: "Shape with effort", word: "FORGE" },
      { hint: "Linked iron rings", word: "CHAINS" },
      { hint: "Have on, carry", word: "WEAR" },
      { hint: "Existence", word: "LIFE" },
    ],
  },
  {
    id: "p616",
    quote: "No one can make you feel inferior without your consent.",
    attribution: "Eleanor Roosevelt",
    theme: "Self-Worth",
    difficulty: "expert",
    clueWords: [
      { hint: "Cause to be", word: "MAKE" },
      { hint: "Sense", word: "FEEL" },
      { hint: "Lower in rank", word: "INFERIOR" },
      { hint: "Lacking, devoid of", word: "WITHOUT" },
      { hint: "Permission", word: "CONSENT" },
    ],
  },
  {
    id: "p617",
    quote: "The future belongs to those who prepare for it today.",
    attribution: "Malcolm X",
    theme: "Action",
    difficulty: "expert",
    clueWords: [
      { hint: "Time yet to come", word: "FUTURE" },
      { hint: "Is owned by", word: "BELONGS" },
      { hint: "Particular ones", word: "THOSE" },
      { hint: "Get ready", word: "PREPARE" },
      { hint: "The current day", word: "TODAY" },
    ],
  },
  {
    id: "p618",
    quote: "A person who never made a mistake never tried anything new.",
    attribution: "Albert Einstein",
    theme: "Risk",
    difficulty: "expert",
    clueWords: [
      { hint: "Human individual", word: "PERSON" },
      { hint: "An error", word: "MISTAKE" },
      { hint: "Made an attempt", word: "TRIED" },
      { hint: "Recently created", word: "NEW" },
      { hint: "At no time", word: "NEVER" },
    ],
  },
  {
    id: "p619",
    quote: "Three may keep a secret if two of them are dead.",
    attribution: "Benjamin Franklin",
    theme: "Secrecy",
    difficulty: "expert",
    clueWords: [
      { hint: "Number after two", word: "THREE" },
      { hint: "Possibly", word: "MAY" },
      { hint: "Hold or guard", word: "KEEP" },
      { hint: "Hidden information", word: "SECRET" },
      { hint: "One pair", word: "TWO" },
      { hint: "Without life", word: "DEAD" },
    ],
  },
  {
    id: "p620",
    quote: "He who has a why to live can bear almost any how.",
    attribution: "Friedrich Nietzsche",
    theme: "Purpose",
    difficulty: "expert",
    clueWords: [
      { hint: "Reason or cause", word: "WHY" },
      { hint: "To exist", word: "LIVE" },
      { hint: "Endure or carry", word: "BEAR" },
      { hint: "Nearly", word: "ALMOST" },
      { hint: "In what manner", word: "HOW" },
    ],
  },
  {
    id: "p621",
    quote: "Whatever you do in life, do it with all your heart.",
    attribution: "Confucius",
    theme: "Commitment",
    difficulty: "expert",
    clueWords: [
      { hint: "Anything that", word: "WHATEVER" },
      { hint: "Existence", word: "LIFE" },
      { hint: "Each, every", word: "ALL" },
      { hint: "Pumping organ", word: "HEART" },
      { hint: "Belonging to you", word: "YOUR" },
    ],
  },
  {
    id: "p622",
    quote: "A journey of self-discovery never ends.",
    attribution: "Anonymous",
    theme: "Growth",
    difficulty: "expert",
    clueWords: [
      { hint: "A long trip", word: "JOURNEY" },
      { hint: "One's own person", word: "SELF" },
      { hint: "Finding out", word: "DISCOVERY" },
      { hint: "At no time", word: "NEVER" },
      { hint: "Concludes", word: "ENDS" },
    ],
  },
  {
    id: "p623",
    quote: "It is not how much we have but how much we enjoy that makes happiness.",
    attribution: "Charles Spurgeon",
    theme: "Gratitude",
    difficulty: "expert",
    clueWords: [
      { hint: "What quantity", word: "MUCH" },
      { hint: "Possess", word: "HAVE" },
      { hint: "Take pleasure in", word: "ENJOY" },
      { hint: "Causes", word: "MAKES" },
      { hint: "Joyful state", word: "HAPPINESS" },
    ],
  },
  {
    id: "p624",
    quote: "The shoe that fits one person pinches another; there is no recipe for living that fits all.",
    attribution: "Carl Jung",
    theme: "Individuality",
    difficulty: "expert",
    clueWords: [
      { hint: "Foot covering", word: "SHOE" },
      { hint: "Suits, is right size", word: "FITS" },
      { hint: "An individual", word: "PERSON" },
      { hint: "Squeezes painfully", word: "PINCHES" },
      { hint: "A formula", word: "RECIPE" },
      { hint: "Existing", word: "LIVING" },
    ],
  },
  {
    id: "p625",
    quote: "Do not look back, you are not heading that way.",
    attribution: "Anonymous",
    theme: "Mindfulness",
    difficulty: "expert",
    clueWords: [
      { hint: "Use the eyes", word: "LOOK" },
      { hint: "Toward the rear", word: "BACK" },
      { hint: "Going toward", word: "HEADING" },
      { hint: "A path or route", word: "WAY" },
    ],
  },
  {
    id: "p626",
    quote: "Each problem solved becomes a rule that helps to solve other problems.",
    attribution: "Rene Descartes",
    theme: "Learning",
    difficulty: "expert",
    clueWords: [
      { hint: "Every", word: "EACH" },
      { hint: "A challenge", word: "PROBLEM" },
      { hint: "Worked out", word: "SOLVED" },
      { hint: "Becomes", word: "BECOMES" },
      { hint: "A guideline", word: "RULE" },
      { hint: "Other people", word: "OTHER" },
    ],
  },
  {
    id: "p627",
    quote: "The only true wisdom is in knowing you know nothing.",
    attribution: "Socrates",
    theme: "Humility",
    difficulty: "expert",
    clueWords: [
      { hint: "Sole, single", word: "ONLY" },
      { hint: "Genuine", word: "TRUE" },
      { hint: "Deep insight", word: "WISDOM" },
      { hint: "Being aware of", word: "KNOWING" },
      { hint: "Are aware of", word: "KNOW" },
      { hint: "Not anything", word: "NOTHING" },
    ],
  },
  {
    id: "p628",
    quote: "Strong reasons make strong actions.",
    attribution: "William Shakespeare",
    theme: "Conviction",
    difficulty: "expert",
    clueWords: [
      { hint: "Powerful, firm", word: "STRONG" },
      { hint: "Causes, motives", word: "REASONS" },
      { hint: "Cause", word: "MAKE" },
      { hint: "Deeds", word: "ACTIONS" },
    ],
  },
  {
    id: "p629",
    quote: "How far that little candle throws his beams! So shines a good deed in a weary world.",
    attribution: "William Shakespeare",
    theme: "Kindness",
    difficulty: "expert",
    clueWords: [
      { hint: "To what extent", word: "FAR" },
      { hint: "Small, slight", word: "LITTLE" },
      { hint: "Wax light source", word: "CANDLE" },
      { hint: "Casts forth", word: "THROWS" },
      { hint: "Shines, glows", word: "SHINES" },
      { hint: "A worthy act", word: "DEED" },
    ],
  },
  {
    id: "p630",
    quote: "What is past is prologue.",
    attribution: "William Shakespeare",
    theme: "Time",
    difficulty: "expert",
    clueWords: [
      { hint: "Earlier time", word: "PAST" },
      { hint: "An introduction", word: "PROLOGUE" },
    ],
  },
];
