import type { PuzzleRaw } from "../puzzleData";

/**
 * Batch 5 (final) — 170 new puzzles (IDs p831–p1000).
 *  • p831–p858: 28 easy
 *  • p859–p907: 49 medium
 *  • p908–p962: 55 hard
 *  • p963–p1000: 38 expert
 *
 * After Batch 5 the full PUZZLES list lands at exactly 1000 puzzles
 * with a 200 easy / 300 medium / 300 hard / 200 expert distribution.
 */
export const BATCH5: PuzzleRaw[] = [
  // -------------------- EASY (28) --------------------
  {
    id: "p831",
    quote: "All is well that ends well.",
    attribution: "Proverb",
    theme: "Acceptance",
    difficulty: "easy",
    clueWords: [
      { hint: "Each one", word: "ALL" },
      { hint: "Good, fine", word: "WELL" },
      { hint: "Concludes", word: "ENDS" },
    ],
  },
  {
    id: "p832",
    quote: "Better the head of a dog than the tail of a lion.",
    attribution: "Proverb",
    theme: "Status",
    difficulty: "easy",
    clueWords: [
      { hint: "More desirable", word: "BETTER" },
      { hint: "Top of the body", word: "HEAD" },
      { hint: "Loyal canine pet", word: "DOG" },
      { hint: "Rear appendage", word: "TAIL" },
      { hint: "Large wild cat", word: "LION" },
    ],
  },
  {
    id: "p833",
    quote: "Diligence is the mother of good fortune.",
    attribution: "Proverb",
    theme: "Effort",
    difficulty: "easy",
    clueWords: [
      { hint: "Steady effort", word: "DILIGENCE" },
      { hint: "Female parent", word: "MOTHER" },
      { hint: "Worthy, fine", word: "GOOD" },
      { hint: "Luck", word: "FORTUNE" },
    ],
  },
  {
    id: "p834",
    quote: "Eagles do not catch flies.",
    attribution: "Latin Proverb",
    theme: "Focus",
    difficulty: "easy",
    clueWords: [
      { hint: "Large soaring birds", word: "EAGLES" },
      { hint: "Grab, capture", word: "CATCH" },
      { hint: "Tiny winged insects", word: "FLIES" },
    ],
  },
  {
    id: "p835",
    quote: "East or west, home is best.",
    attribution: "Proverb",
    theme: "Belonging",
    difficulty: "easy",
    clueWords: [
      { hint: "Direction of sunrise", word: "EAST" },
      { hint: "Direction of sunset", word: "WEST" },
      { hint: "Place of dwelling", word: "HOME" },
      { hint: "Top quality", word: "BEST" },
    ],
  },
  {
    id: "p836",
    quote: "Even a broken clock is right twice a day.",
    attribution: "Proverb",
    theme: "Perspective",
    difficulty: "easy",
    clueWords: [
      { hint: "Furthermore", word: "EVEN" },
      { hint: "Damaged", word: "BROKEN" },
      { hint: "Time-keeping device", word: "CLOCK" },
      { hint: "Correct", word: "RIGHT" },
      { hint: "Two times", word: "TWICE" },
      { hint: "A 24-hour period", word: "DAY" },
    ],
  },
  {
    id: "p837",
    quote: "Fools rush in where angels fear to tread.",
    attribution: "Alexander Pope",
    theme: "Caution",
    difficulty: "easy",
    clueWords: [
      { hint: "Foolish people", word: "FOOLS" },
      { hint: "Move hastily", word: "RUSH" },
      { hint: "Heavenly beings", word: "ANGELS" },
      { hint: "Be afraid of", word: "FEAR" },
      { hint: "Step", word: "TREAD" },
    ],
  },
  {
    id: "p838",
    quote: "If you cannot stand the heat, get out of the kitchen.",
    attribution: "Harry Truman",
    theme: "Resilience",
    difficulty: "easy",
    clueWords: [
      { hint: "Are not able to", word: "CANNOT" },
      { hint: "Endure", word: "STAND" },
      { hint: "Warmth", word: "HEAT" },
      { hint: "Leave, exit", word: "GET" },
      { hint: "Cooking room", word: "KITCHEN" },
    ],
  },
  {
    id: "p839",
    quote: "Live by the sword, die by the sword.",
    attribution: "Proverb",
    theme: "Consequences",
    difficulty: "easy",
    clueWords: [
      { hint: "Be alive", word: "LIVE" },
      { hint: "A bladed weapon", word: "SWORD" },
      { hint: "Cease to live", word: "DIE" },
    ],
  },
  {
    id: "p840",
    quote: "Loose lips sink ships.",
    attribution: "Proverb",
    theme: "Discretion",
    difficulty: "easy",
    clueWords: [
      { hint: "Not tight", word: "LOOSE" },
      { hint: "Mouth edges", word: "LIPS" },
      { hint: "Cause to go under", word: "SINK" },
      { hint: "Sea vessels", word: "SHIPS" },
    ],
  },
  {
    id: "p841",
    quote: "Make a long story short.",
    attribution: "Proverb",
    theme: "Brevity",
    difficulty: "easy",
    clueWords: [
      { hint: "Cause to be", word: "MAKE" },
      { hint: "Of great length", word: "LONG" },
      { hint: "A narrative", word: "STORY" },
      { hint: "Brief", word: "SHORT" },
    ],
  },
  {
    id: "p842",
    quote: "Misery loves company.",
    attribution: "Proverb",
    theme: "Connection",
    difficulty: "easy",
    clueWords: [
      { hint: "Suffering", word: "MISERY" },
      { hint: "Cherishes", word: "LOVES" },
      { hint: "Companionship", word: "COMPANY" },
    ],
  },
  {
    id: "p843",
    quote: "Never say never.",
    attribution: "Proverb",
    theme: "Possibility",
    difficulty: "easy",
    clueWords: [
      { hint: "At no time", word: "NEVER" },
      { hint: "Express verbally", word: "SAY" },
    ],
  },
  {
    id: "p844",
    quote: "One swallow does not make a summer.",
    attribution: "Aristotle",
    theme: "Patience",
    difficulty: "easy",
    clueWords: [
      { hint: "A single unit", word: "ONE" },
      { hint: "A small bird", word: "SWALLOW" },
      { hint: "Cause", word: "MAKE" },
      { hint: "Warm season", word: "SUMMER" },
    ],
  },
  {
    id: "p845",
    quote: "Out of the frying pan, into the fire.",
    attribution: "Proverb",
    theme: "Misfortune",
    difficulty: "easy",
    clueWords: [
      { hint: "Cooking implement", word: "PAN" },
      { hint: "Used for cooking", word: "FRYING" },
      { hint: "Burning combustion", word: "FIRE" },
      { hint: "Outside of", word: "OUT" },
    ],
  },
  {
    id: "p846",
    quote: "People in glass houses should not throw stones.",
    attribution: "Proverb",
    theme: "Humility",
    difficulty: "easy",
    clueWords: [
      { hint: "Human beings", word: "PEOPLE" },
      { hint: "Transparent material", word: "GLASS" },
      { hint: "Dwellings", word: "HOUSES" },
      { hint: "Cast forth", word: "THROW" },
      { hint: "Rock pieces", word: "STONES" },
    ],
  },
  {
    id: "p847",
    quote: "Sleep on it.",
    attribution: "Proverb",
    theme: "Patience",
    difficulty: "easy",
    clueWords: [
      { hint: "Rest unconscious", word: "SLEEP" },
      { hint: "Onto, upon", word: "ON" },
    ],
  },
  {
    id: "p848",
    quote: "Speak softly and carry a big stick.",
    attribution: "Theodore Roosevelt",
    theme: "Diplomacy",
    difficulty: "easy",
    clueWords: [
      { hint: "Utter aloud", word: "SPEAK" },
      { hint: "Quietly, gently", word: "SOFTLY" },
      { hint: "Bear, transport", word: "CARRY" },
      { hint: "Of large size", word: "BIG" },
      { hint: "A wooden rod", word: "STICK" },
    ],
  },
  {
    id: "p849",
    quote: "Time and tide wait for no man.",
    attribution: "Proverb",
    theme: "Time",
    difficulty: "easy",
    clueWords: [
      { hint: "Hours and minutes", word: "TIME" },
      { hint: "Ocean's rise and fall", word: "TIDE" },
      { hint: "Stay in expectation", word: "WAIT" },
      { hint: "Negation", word: "NO" },
      { hint: "Adult human male", word: "MAN" },
    ],
  },
  {
    id: "p850",
    quote: "Truth will out.",
    attribution: "Proverb",
    theme: "Truth",
    difficulty: "easy",
    clueWords: [
      { hint: "Honest reality", word: "TRUTH" },
      { hint: "Future tense helper", word: "WILL" },
      { hint: "Outside, revealed", word: "OUT" },
    ],
  },
  {
    id: "p851",
    quote: "United we stand, divided we fall.",
    attribution: "Aesop",
    theme: "Unity",
    difficulty: "easy",
    clueWords: [
      { hint: "Joined together", word: "UNITED" },
      { hint: "Take a position", word: "STAND" },
      { hint: "Separated", word: "DIVIDED" },
      { hint: "Drop down", word: "FALL" },
    ],
  },
  {
    id: "p852",
    quote: "Walk before you run.",
    attribution: "Proverb",
    theme: "Progress",
    difficulty: "easy",
    clueWords: [
      { hint: "Move on foot slowly", word: "WALK" },
      { hint: "Earlier than", word: "BEFORE" },
      { hint: "Move on foot quickly", word: "RUN" },
    ],
  },
  {
    id: "p853",
    quote: "Waste not, want not.",
    attribution: "Proverb",
    theme: "Thrift",
    difficulty: "easy",
    clueWords: [
      { hint: "Squander", word: "WASTE" },
      { hint: "Desire", word: "WANT" },
      { hint: "Negation", word: "NOT" },
    ],
  },
  {
    id: "p854",
    quote: "When the cat is away, the mice will play.",
    attribution: "Proverb",
    theme: "Freedom",
    difficulty: "easy",
    clueWords: [
      { hint: "Whiskered house pet", word: "CAT" },
      { hint: "Not present", word: "AWAY" },
      { hint: "Small rodents", word: "MICE" },
      { hint: "Engage in fun", word: "PLAY" },
    ],
  },
  {
    id: "p855",
    quote: "You are never too old to learn.",
    attribution: "Proverb",
    theme: "Learning",
    difficulty: "easy",
    clueWords: [
      { hint: "At no time", word: "NEVER" },
      { hint: "Excessively", word: "TOO" },
      { hint: "Aged", word: "OLD" },
      { hint: "Acquire knowledge", word: "LEARN" },
    ],
  },
  {
    id: "p856",
    quote: "You can lead a horse to water.",
    attribution: "Proverb",
    theme: "Limits",
    difficulty: "easy",
    clueWords: [
      { hint: "Are able to", word: "CAN" },
      { hint: "Guide, direct", word: "LEAD" },
      { hint: "A riding animal", word: "HORSE" },
      { hint: "Clear drinking liquid", word: "WATER" },
    ],
  },
  {
    id: "p857",
    quote: "You cannot have your cake and eat it too.",
    attribution: "Proverb",
    theme: "Choice",
    difficulty: "easy",
    clueWords: [
      { hint: "Are not able to", word: "CANNOT" },
      { hint: "Possess", word: "HAVE" },
      { hint: "Sweet baked dessert", word: "CAKE" },
      { hint: "Consume food", word: "EAT" },
      { hint: "Also, as well", word: "TOO" },
    ],
  },
  {
    id: "p858",
    quote: "Where there is muck, there is brass.",
    attribution: "English Proverb",
    theme: "Opportunity",
    difficulty: "easy",
    clueWords: [
      { hint: "At which place", word: "WHERE" },
      { hint: "Dirt, filth", word: "MUCK" },
      { hint: "A copper-zinc metal", word: "BRASS" },
    ],
  },

  // -------------------- MEDIUM (49) --------------------
  {
    id: "p859",
    quote: "Everyone thinks of changing the world, but no one thinks of changing himself.",
    attribution: "Leo Tolstoy",
    theme: "Self-Knowledge",
    difficulty: "medium",
    clueWords: [
      { hint: "Each person", word: "EVERYONE" },
      { hint: "Uses the mind", word: "THINKS" },
      { hint: "Altering", word: "CHANGING" },
      { hint: "The earth", word: "WORLD" },
      { hint: "He himself", word: "HIMSELF" },
    ],
  },
  {
    id: "p860",
    quote: "The two most powerful warriors are patience and time.",
    attribution: "Leo Tolstoy",
    theme: "Patience",
    difficulty: "medium",
    clueWords: [
      { hint: "A pair", word: "TWO" },
      { hint: "Greatest in might", word: "POWERFUL" },
      { hint: "Skilled fighters", word: "WARRIORS" },
      { hint: "Calm endurance", word: "PATIENCE" },
      { hint: "Hours and days", word: "TIME" },
    ],
  },
  {
    id: "p861",
    quote: "Wrong does not cease to be wrong because the majority share in it.",
    attribution: "Leo Tolstoy",
    theme: "Conscience",
    difficulty: "medium",
    clueWords: [
      { hint: "Incorrect, harmful", word: "WRONG" },
      { hint: "Stop, halt", word: "CEASE" },
      { hint: "For what reason", word: "BECAUSE" },
      { hint: "The larger group", word: "MAJORITY" },
      { hint: "Take part", word: "SHARE" },
    ],
  },
  {
    id: "p862",
    quote: "The mystery of life is finding something to live for.",
    attribution: "Fyodor Dostoevsky",
    theme: "Purpose",
    difficulty: "medium",
    clueWords: [
      { hint: "An unknown thing", word: "MYSTERY" },
      { hint: "Existence", word: "LIFE" },
      { hint: "Discovering", word: "FINDING" },
      { hint: "An item or cause", word: "SOMETHING" },
      { hint: "Be alive", word: "LIVE" },
    ],
  },
  {
    id: "p863",
    quote: "Above all, do not lie to yourself.",
    attribution: "Fyodor Dostoevsky",
    theme: "Honesty",
    difficulty: "medium",
    clueWords: [
      { hint: "Higher than", word: "ABOVE" },
      { hint: "Each, every", word: "ALL" },
      { hint: "Speak untruth", word: "LIE" },
      { hint: "Your own person", word: "YOURSELF" },
    ],
  },
  {
    id: "p864",
    quote: "There is nothing like staying at home for real comfort.",
    attribution: "Jane Austen",
    theme: "Belonging",
    difficulty: "medium",
    clueWords: [
      { hint: "Not anything", word: "NOTHING" },
      { hint: "Remaining", word: "STAYING" },
      { hint: "Place of dwelling", word: "HOME" },
      { hint: "Genuine", word: "REAL" },
      { hint: "Ease, solace", word: "COMFORT" },
    ],
  },
  {
    id: "p865",
    quote: "There is no enjoyment like reading.",
    attribution: "Jane Austen",
    theme: "Learning",
    difficulty: "medium",
    clueWords: [
      { hint: "Pleasure, delight", word: "ENJOYMENT" },
      { hint: "Similar to", word: "LIKE" },
      { hint: "Going through text", word: "READING" },
      { hint: "Negation", word: "NO" },
    ],
  },
  {
    id: "p866",
    quote: "If you do not tell the truth about yourself, you cannot tell it about others.",
    attribution: "Virginia Woolf",
    theme: "Honesty",
    difficulty: "medium",
    clueWords: [
      { hint: "State, inform", word: "TELL" },
      { hint: "Honest reality", word: "TRUTH" },
      { hint: "Your own person", word: "YOURSELF" },
      { hint: "Other people", word: "OTHERS" },
      { hint: "Are not able to", word: "CANNOT" },
    ],
  },
  {
    id: "p867",
    quote: "Have a heart that never hardens, a temper that never tires.",
    attribution: "Charles Dickens",
    theme: "Compassion",
    difficulty: "medium",
    clueWords: [
      { hint: "Possess", word: "HAVE" },
      { hint: "Pumping organ", word: "HEART" },
      { hint: "At no time", word: "NEVER" },
      { hint: "Becomes firm", word: "HARDENS" },
      { hint: "A mood or disposition", word: "TEMPER" },
      { hint: "Grows weary", word: "TIRES" },
    ],
  },
  {
    id: "p868",
    quote: "There is nothing as irresistibly contagious as laughter and good humor.",
    attribution: "Charles Dickens",
    theme: "Joy",
    difficulty: "medium",
    clueWords: [
      { hint: "Not anything", word: "NOTHING" },
      { hint: "Cannot be resisted", word: "IRRESISTIBLY" },
      { hint: "Easily spread", word: "CONTAGIOUS" },
      { hint: "Sounds of joy", word: "LAUGHTER" },
      { hint: "Worthy, fine", word: "GOOD" },
      { hint: "Comic mood", word: "HUMOR" },
    ],
  },
  {
    id: "p869",
    quote: "He who has a thousand friends has not a friend to spare.",
    attribution: "Thomas Carlyle",
    theme: "Friendship",
    difficulty: "medium",
    clueWords: [
      { hint: "Ten hundred", word: "THOUSAND" },
      { hint: "Companions", word: "FRIENDS" },
      { hint: "A close companion", word: "FRIEND" },
      { hint: "Give up, lose", word: "SPARE" },
      { hint: "Possesses", word: "HAS" },
    ],
  },
  {
    id: "p870",
    quote: "The good life is one inspired by love and guided by knowledge.",
    attribution: "Bertrand Russell",
    theme: "Purpose",
    difficulty: "medium",
    clueWords: [
      { hint: "Worthy", word: "GOOD" },
      { hint: "Existence", word: "LIFE" },
      { hint: "Stirred to act", word: "INSPIRED" },
      { hint: "Deep affection", word: "LOVE" },
      { hint: "Led, directed", word: "GUIDED" },
      { hint: "Information mastered", word: "KNOWLEDGE" },
    ],
  },
  {
    id: "p871",
    quote: "A thing of beauty is a joy forever.",
    attribution: "John Keats",
    theme: "Wonder",
    difficulty: "medium",
    clueWords: [
      { hint: "An item or matter", word: "THING" },
      { hint: "Loveliness", word: "BEAUTY" },
      { hint: "Happiness", word: "JOY" },
      { hint: "Eternally", word: "FOREVER" },
    ],
  },
  {
    id: "p872",
    quote: "I exist as I am, that is enough.",
    attribution: "Walt Whitman",
    theme: "Identity",
    difficulty: "medium",
    clueWords: [
      { hint: "Be present", word: "EXIST" },
      { hint: "Sufficient", word: "ENOUGH" },
    ],
  },
  {
    id: "p873",
    quote: "I celebrate myself, and sing myself.",
    attribution: "Walt Whitman",
    theme: "Self-Love",
    difficulty: "medium",
    clueWords: [
      { hint: "Honor, rejoice over", word: "CELEBRATE" },
      { hint: "My own person", word: "MYSELF" },
      { hint: "Vocalize melodically", word: "SING" },
    ],
  },
  {
    id: "p874",
    quote: "Resist much, obey little.",
    attribution: "Walt Whitman",
    theme: "Independence",
    difficulty: "medium",
    clueWords: [
      { hint: "Push back against", word: "RESIST" },
      { hint: "A great deal", word: "MUCH" },
      { hint: "Comply with orders", word: "OBEY" },
      { hint: "A small amount", word: "LITTLE" },
    ],
  },
  {
    id: "p875",
    quote: "Henceforth I ask not good fortune; I myself am good fortune.",
    attribution: "Walt Whitman",
    theme: "Confidence",
    difficulty: "medium",
    clueWords: [
      { hint: "From now on", word: "HENCEFORTH" },
      { hint: "Inquire", word: "ASK" },
      { hint: "Worthy", word: "GOOD" },
      { hint: "Luck, destiny", word: "FORTUNE" },
      { hint: "My own person", word: "MYSELF" },
    ],
  },
  {
    id: "p876",
    quote: "Arise! Awake! and stop not till the goal is reached.",
    attribution: "Swami Vivekananda",
    theme: "Determination",
    difficulty: "medium",
    clueWords: [
      { hint: "Get up", word: "ARISE" },
      { hint: "Become conscious", word: "AWAKE" },
      { hint: "Cease", word: "STOP" },
      { hint: "Until", word: "TILL" },
      { hint: "An aim", word: "GOAL" },
      { hint: "Attained", word: "REACHED" },
    ],
  },
  {
    id: "p877",
    quote: "All power is within you; you can do anything and everything.",
    attribution: "Swami Vivekananda",
    theme: "Confidence",
    difficulty: "medium",
    clueWords: [
      { hint: "Each, every", word: "ALL" },
      { hint: "Strength, ability", word: "POWER" },
      { hint: "Inside", word: "WITHIN" },
      { hint: "Are able to", word: "CAN" },
      { hint: "Any item", word: "ANYTHING" },
      { hint: "All things", word: "EVERYTHING" },
    ],
  },
  {
    id: "p878",
    quote: "Take risks in your life. If you win, you can lead. If you lose, you can guide.",
    attribution: "Swami Vivekananda",
    theme: "Risk",
    difficulty: "medium",
    clueWords: [
      { hint: "Accept, grasp", word: "TAKE" },
      { hint: "Hazards", word: "RISKS" },
      { hint: "Existence", word: "LIFE" },
      { hint: "Be victorious", word: "WIN" },
      { hint: "Forfeit", word: "LOSE" },
      { hint: "Direct", word: "GUIDE" },
    ],
  },
  {
    id: "p879",
    quote: "The greatest religion is to be true to your own nature.",
    attribution: "Swami Vivekananda",
    theme: "Authenticity",
    difficulty: "medium",
    clueWords: [
      { hint: "Largest, finest", word: "GREATEST" },
      { hint: "A system of belief", word: "RELIGION" },
      { hint: "Genuine, faithful", word: "TRUE" },
      { hint: "Belonging to oneself", word: "OWN" },
      { hint: "Essence, character", word: "NATURE" },
    ],
  },
  {
    id: "p880",
    quote: "Strength is life, weakness is death.",
    attribution: "Swami Vivekananda",
    theme: "Strength",
    difficulty: "medium",
    clueWords: [
      { hint: "Power, fortitude", word: "STRENGTH" },
      { hint: "Existence", word: "LIFE" },
      { hint: "Lack of strength", word: "WEAKNESS" },
      { hint: "End of life", word: "DEATH" },
    ],
  },
  {
    id: "p881",
    quote: "Anything that makes you weak, reject it.",
    attribution: "Swami Vivekananda",
    theme: "Self-Care",
    difficulty: "medium",
    clueWords: [
      { hint: "Any item", word: "ANYTHING" },
      { hint: "Causes", word: "MAKES" },
      { hint: "Lacking strength", word: "WEAK" },
      { hint: "Refuse, dismiss", word: "REJECT" },
    ],
  },
  {
    id: "p882",
    quote: "Listen to the wind, it talks. Listen to the silence, it speaks.",
    attribution: "Native American Proverb",
    theme: "Listening",
    difficulty: "medium",
    clueWords: [
      { hint: "Pay attention to", word: "LISTEN" },
      { hint: "Moving air", word: "WIND" },
      { hint: "Communicates", word: "TALKS" },
      { hint: "Absence of sound", word: "SILENCE" },
      { hint: "Utters", word: "SPEAKS" },
    ],
  },
  {
    id: "p883",
    quote: "When the legends die, the dreams end.",
    attribution: "Native American Proverb",
    theme: "Legacy",
    difficulty: "medium",
    clueWords: [
      { hint: "Stories of heroes", word: "LEGENDS" },
      { hint: "Cease to live", word: "DIE" },
      { hint: "Aspirations", word: "DREAMS" },
      { hint: "Conclude", word: "END" },
    ],
  },
  {
    id: "p884",
    quote: "Take your time. Hurry is the parent of failure.",
    attribution: "Greek Proverb",
    theme: "Patience",
    difficulty: "medium",
    clueWords: [
      { hint: "Receive, use", word: "TAKE" },
      { hint: "Hours and minutes", word: "TIME" },
      { hint: "Rushed action", word: "HURRY" },
      { hint: "A creator", word: "PARENT" },
      { hint: "Lack of success", word: "FAILURE" },
    ],
  },
  {
    id: "p885",
    quote: "Better a diamond with a flaw than a pebble without.",
    attribution: "Confucius",
    theme: "Authenticity",
    difficulty: "medium",
    clueWords: [
      { hint: "Preferable", word: "BETTER" },
      { hint: "Precious gem", word: "DIAMOND" },
      { hint: "An imperfection", word: "FLAW" },
      { hint: "A small stone", word: "PEBBLE" },
      { hint: "Lacking", word: "WITHOUT" },
    ],
  },
  {
    id: "p886",
    quote: "When anger rises, think of the consequences.",
    attribution: "Confucius",
    theme: "Self-Control",
    difficulty: "medium",
    clueWords: [
      { hint: "Strong displeasure", word: "ANGER" },
      { hint: "Goes up", word: "RISES" },
      { hint: "Use the mind", word: "THINK" },
      { hint: "Outcomes", word: "CONSEQUENCES" },
    ],
  },
  {
    id: "p887",
    quote: "Real knowledge is to know the extent of one's ignorance.",
    attribution: "Confucius",
    theme: "Humility",
    difficulty: "medium",
    clueWords: [
      { hint: "Genuine", word: "REAL" },
      { hint: "Information mastered", word: "KNOWLEDGE" },
      { hint: "Be aware of", word: "KNOW" },
      { hint: "The size or scope", word: "EXTENT" },
      { hint: "Lack of knowledge", word: "IGNORANCE" },
    ],
  },
  {
    id: "p888",
    quote: "The person who moves a mountain begins by carrying small stones.",
    attribution: "Confucius",
    theme: "Persistence",
    difficulty: "medium",
    clueWords: [
      { hint: "An individual", word: "PERSON" },
      { hint: "Shifts, transports", word: "MOVES" },
      { hint: "A high landform", word: "MOUNTAIN" },
      { hint: "Starts", word: "BEGINS" },
      { hint: "Conveying", word: "CARRYING" },
      { hint: "Pieces of rock", word: "STONES" },
    ],
  },
  {
    id: "p889",
    quote: "Study the past if you would define the future.",
    attribution: "Confucius",
    theme: "Wisdom",
    difficulty: "medium",
    clueWords: [
      { hint: "Examine carefully", word: "STUDY" },
      { hint: "Earlier time", word: "PAST" },
      { hint: "Determine, shape", word: "DEFINE" },
      { hint: "Time yet to come", word: "FUTURE" },
    ],
  },
  {
    id: "p890",
    quote: "Choose a job you love, and you will never have to work a day in your life.",
    attribution: "Confucius",
    theme: "Purpose",
    difficulty: "medium",
    clueWords: [
      { hint: "Make a selection", word: "CHOOSE" },
      { hint: "An occupation", word: "JOB" },
      { hint: "Cherish deeply", word: "LOVE" },
      { hint: "At no time", word: "NEVER" },
      { hint: "Effort, labor", word: "WORK" },
      { hint: "Existence", word: "LIFE" },
    ],
  },
  {
    id: "p891",
    quote: "If you make a mistake and do not correct it, this is called a mistake.",
    attribution: "Confucius",
    theme: "Honesty",
    difficulty: "medium",
    clueWords: [
      { hint: "Cause", word: "MAKE" },
      { hint: "An error", word: "MISTAKE" },
      { hint: "Fix, set right", word: "CORRECT" },
      { hint: "Named, termed", word: "CALLED" },
    ],
  },
  {
    id: "p892",
    quote: "Our greatest glory is not in never falling, but in rising every time we fall.",
    attribution: "Confucius",
    theme: "Resilience",
    difficulty: "medium",
    clueWords: [
      { hint: "Largest, finest", word: "GREATEST" },
      { hint: "Honor, splendor", word: "GLORY" },
      { hint: "At no time", word: "NEVER" },
      { hint: "Dropping down", word: "FALLING" },
      { hint: "Getting up", word: "RISING" },
      { hint: "Each one", word: "EVERY" },
    ],
  },
  {
    id: "p893",
    quote: "What the superior person seeks is in himself; what the small person seeks is in others.",
    attribution: "Confucius",
    theme: "Character",
    difficulty: "medium",
    clueWords: [
      { hint: "Higher quality", word: "SUPERIOR" },
      { hint: "An individual", word: "PERSON" },
      { hint: "Searches for", word: "SEEKS" },
      { hint: "He himself", word: "HIMSELF" },
      { hint: "Of slight rank", word: "SMALL" },
      { hint: "Other people", word: "OTHERS" },
    ],
  },
  {
    id: "p894",
    quote: "Hold faithfulness and sincerity as first principles.",
    attribution: "Confucius",
    theme: "Integrity",
    difficulty: "medium",
    clueWords: [
      { hint: "Maintain", word: "HOLD" },
      { hint: "Loyalty", word: "FAITHFULNESS" },
      { hint: "Genuine honesty", word: "SINCERITY" },
      { hint: "Initial, foremost", word: "FIRST" },
      { hint: "Fundamental rules", word: "PRINCIPLES" },
    ],
  },
  {
    id: "p895",
    quote: "When goals cannot be reached, adjust the action steps, not the goals.",
    attribution: "Confucius",
    theme: "Adaptability",
    difficulty: "medium",
    clueWords: [
      { hint: "Aims, targets", word: "GOALS" },
      { hint: "Are not able to", word: "CANNOT" },
      { hint: "Attained", word: "REACHED" },
      { hint: "Modify", word: "ADJUST" },
      { hint: "A deed", word: "ACTION" },
      { hint: "Paces", word: "STEPS" },
    ],
  },
  {
    id: "p896",
    quote: "Stray birds of summer come to my window to sing and fly away.",
    attribution: "Rabindranath Tagore",
    theme: "Wonder",
    difficulty: "medium",
    clueWords: [
      { hint: "Wandering", word: "STRAY" },
      { hint: "Feathered creatures", word: "BIRDS" },
      { hint: "Warm season", word: "SUMMER" },
      { hint: "Glass opening", word: "WINDOW" },
      { hint: "Vocalize melodically", word: "SING" },
      { hint: "Travel through air", word: "FLY" },
    ],
  },
  {
    id: "p897",
    quote: "Roots below the earth claim no rewards for making the branches fruitful.",
    attribution: "Rabindranath Tagore",
    theme: "Humility",
    difficulty: "medium",
    clueWords: [
      { hint: "Plant parts in soil", word: "ROOTS" },
      { hint: "Underneath", word: "BELOW" },
      { hint: "Our planet", word: "EARTH" },
      { hint: "Demand", word: "CLAIM" },
      { hint: "Recompenses", word: "REWARDS" },
      { hint: "Tree limbs", word: "BRANCHES" },
    ],
  },
  {
    id: "p898",
    quote: "The roots of education are bitter, but the fruit is sweet.",
    attribution: "Aristotle",
    theme: "Learning",
    difficulty: "medium",
    clueWords: [
      { hint: "Plant parts in soil", word: "ROOTS" },
      { hint: "Schooling, instruction", word: "EDUCATION" },
      { hint: "Sharp, harsh", word: "BITTER" },
      { hint: "Plant reward", word: "FRUIT" },
      { hint: "Sugary, pleasant", word: "SWEET" },
    ],
  },
  {
    id: "p899",
    quote: "Whosoever loves much, does much.",
    attribution: "Thomas a Kempis",
    theme: "Love",
    difficulty: "medium",
    clueWords: [
      { hint: "Any person", word: "WHOSOEVER" },
      { hint: "Cherishes", word: "LOVES" },
      { hint: "A great deal", word: "MUCH" },
      { hint: "Performs", word: "DOES" },
    ],
  },
  {
    id: "p900",
    quote: "Light is the symbol of truth.",
    attribution: "James Russell Lowell",
    theme: "Truth",
    difficulty: "medium",
    clueWords: [
      { hint: "Illumination", word: "LIGHT" },
      { hint: "A representation", word: "SYMBOL" },
      { hint: "Honest reality", word: "TRUTH" },
    ],
  },
  {
    id: "p901",
    quote: "Music is the universal language of mankind.",
    attribution: "Henry Wadsworth Longfellow",
    theme: "Wonder",
    difficulty: "medium",
    clueWords: [
      { hint: "Organized sound", word: "MUSIC" },
      { hint: "Applicable to all", word: "UNIVERSAL" },
      { hint: "System of communication", word: "LANGUAGE" },
      { hint: "All people", word: "MANKIND" },
    ],
  },
  {
    id: "p902",
    quote: "The shortest answer is doing.",
    attribution: "Lord Herbert",
    theme: "Action",
    difficulty: "medium",
    clueWords: [
      { hint: "Most brief", word: "SHORTEST" },
      { hint: "A reply", word: "ANSWER" },
      { hint: "Performing", word: "DOING" },
    ],
  },
  {
    id: "p903",
    quote: "Action conquers fear.",
    attribution: "Peter Zarlenga",
    theme: "Courage",
    difficulty: "medium",
    clueWords: [
      { hint: "A deed", word: "ACTION" },
      { hint: "Defeats, overcomes", word: "CONQUERS" },
      { hint: "Dread, terror", word: "FEAR" },
    ],
  },
  {
    id: "p904",
    quote: "Wealth comes as a by-product of providing useful service.",
    attribution: "Henry Ford",
    theme: "Service",
    difficulty: "medium",
    clueWords: [
      { hint: "Riches", word: "WEALTH" },
      { hint: "Arrives", word: "COMES" },
      { hint: "Supplying", word: "PROVIDING" },
      { hint: "Helpful, beneficial", word: "USEFUL" },
      { hint: "Helpful labor", word: "SERVICE" },
    ],
  },
  {
    id: "p905",
    quote: "There are no shortcuts to any place worth going.",
    attribution: "Beverly Sills",
    theme: "Effort",
    difficulty: "medium",
    clueWords: [
      { hint: "Quick alternative paths", word: "SHORTCUTS" },
      { hint: "Any location", word: "PLACE" },
      { hint: "Of value", word: "WORTH" },
      { hint: "Traveling", word: "GOING" },
    ],
  },
  {
    id: "p906",
    quote: "Excellence is to do a common thing in an uncommon way.",
    attribution: "Booker T. Washington",
    theme: "Excellence",
    difficulty: "medium",
    clueWords: [
      { hint: "Outstanding quality", word: "EXCELLENCE" },
      { hint: "Perform", word: "DO" },
      { hint: "Ordinary, shared", word: "COMMON" },
      { hint: "An item or matter", word: "THING" },
      { hint: "Unusual", word: "UNCOMMON" },
      { hint: "A method", word: "WAY" },
    ],
  },
  {
    id: "p907",
    quote: "Character is doing the right thing when nobody is looking.",
    attribution: "J.C. Watts",
    theme: "Integrity",
    difficulty: "medium",
    clueWords: [
      { hint: "Moral nature", word: "CHARACTER" },
      { hint: "Performing", word: "DOING" },
      { hint: "Correct", word: "RIGHT" },
      { hint: "An item or matter", word: "THING" },
      { hint: "Not a person", word: "NOBODY" },
      { hint: "Using the eyes", word: "LOOKING" },
    ],
  },

  // -------------------- HARD (55) --------------------
  {
    id: "p908",
    quote: "If you want to be happy, be.",
    attribution: "Leo Tolstoy",
    theme: "Happiness",
    difficulty: "hard",
    clueWords: [
      { hint: "Desire", word: "WANT" },
      { hint: "Joyful", word: "HAPPY" },
      { hint: "Exist as", word: "BE" },
    ],
  },
  {
    id: "p909",
    quote: "There is no greatness where there is no simplicity, goodness, and truth.",
    attribution: "Leo Tolstoy",
    theme: "Values",
    difficulty: "hard",
    clueWords: [
      { hint: "Quality of being great", word: "GREATNESS" },
      { hint: "Plainness", word: "SIMPLICITY" },
      { hint: "Worthy nature", word: "GOODNESS" },
      { hint: "Honest reality", word: "TRUTH" },
      { hint: "At which place", word: "WHERE" },
    ],
  },
  {
    id: "p910",
    quote: "If you look for perfection, you will never be content.",
    attribution: "Leo Tolstoy",
    theme: "Contentment",
    difficulty: "hard",
    clueWords: [
      { hint: "Use the eyes", word: "LOOK" },
      { hint: "Without flaw", word: "PERFECTION" },
      { hint: "At no time", word: "NEVER" },
      { hint: "Satisfied", word: "CONTENT" },
    ],
  },
  {
    id: "p911",
    quote: "To live without hope is to cease to live.",
    attribution: "Fyodor Dostoevsky",
    theme: "Hope",
    difficulty: "hard",
    clueWords: [
      { hint: "Be alive", word: "LIVE" },
      { hint: "Lacking", word: "WITHOUT" },
      { hint: "Optimistic feeling", word: "HOPE" },
      { hint: "Stop, halt", word: "CEASE" },
    ],
  },
  {
    id: "p912",
    quote: "Pain and suffering are always inevitable for a large intelligence and a deep heart.",
    attribution: "Fyodor Dostoevsky",
    theme: "Adversity",
    difficulty: "hard",
    clueWords: [
      { hint: "Physical hurt", word: "PAIN" },
      { hint: "Anguish", word: "SUFFERING" },
      { hint: "All the time", word: "ALWAYS" },
      { hint: "Cannot be avoided", word: "INEVITABLE" },
      { hint: "Mental capability", word: "INTELLIGENCE" },
      { hint: "Pumping organ", word: "HEART" },
    ],
  },
  {
    id: "p913",
    quote: "Beauty will save the world.",
    attribution: "Fyodor Dostoevsky",
    theme: "Wonder",
    difficulty: "hard",
    clueWords: [
      { hint: "Loveliness", word: "BEAUTY" },
      { hint: "Rescue", word: "SAVE" },
      { hint: "The earth", word: "WORLD" },
    ],
  },
  {
    id: "p914",
    quote: "He who opens a school door, closes a prison.",
    attribution: "Victor Hugo",
    theme: "Learning",
    difficulty: "hard",
    clueWords: [
      { hint: "Unfastens, begins", word: "OPENS" },
      { hint: "A place of learning", word: "SCHOOL" },
      { hint: "An entryway", word: "DOOR" },
      { hint: "Shuts", word: "CLOSES" },
      { hint: "A place of confinement", word: "PRISON" },
    ],
  },
  {
    id: "p915",
    quote: "The trouble with the world is that fools are certain and the wise are full of doubt.",
    attribution: "Bertrand Russell",
    theme: "Humility",
    difficulty: "hard",
    clueWords: [
      { hint: "Difficulty", word: "TROUBLE" },
      { hint: "The earth", word: "WORLD" },
      { hint: "Foolish people", word: "FOOLS" },
      { hint: "Sure, confident", word: "CERTAIN" },
      { hint: "Sage, learned", word: "WISE" },
      { hint: "Lack of certainty", word: "DOUBT" },
    ],
  },
  {
    id: "p916",
    quote: "I would never die for my beliefs because I might be wrong.",
    attribution: "Bertrand Russell",
    theme: "Humility",
    difficulty: "hard",
    clueWords: [
      { hint: "At no time", word: "NEVER" },
      { hint: "Cease to live", word: "DIE" },
      { hint: "Convictions", word: "BELIEFS" },
      { hint: "For what reason", word: "BECAUSE" },
      { hint: "Possibly will", word: "MIGHT" },
      { hint: "Incorrect", word: "WRONG" },
    ],
  },
  {
    id: "p917",
    quote: "To be happy, you must be your own sunshine.",
    attribution: "Bertrand Russell",
    theme: "Happiness",
    difficulty: "hard",
    clueWords: [
      { hint: "Joyful", word: "HAPPY" },
      { hint: "Have to", word: "MUST" },
      { hint: "Belonging to oneself", word: "OWN" },
      { hint: "Light from the sun", word: "SUNSHINE" },
    ],
  },
  {
    id: "p918",
    quote: "While there is life, there is hope.",
    attribution: "Cicero",
    theme: "Hope",
    difficulty: "hard",
    clueWords: [
      { hint: "Existence", word: "LIFE" },
      { hint: "Optimistic feeling", word: "HOPE" },
      { hint: "During the time that", word: "WHILE" },
    ],
  },
  {
    id: "p919",
    quote: "The more laws, the less justice.",
    attribution: "Cicero",
    theme: "Justice",
    difficulty: "hard",
    clueWords: [
      { hint: "To a greater extent", word: "MORE" },
      { hint: "Rules of conduct", word: "LAWS" },
      { hint: "To a smaller extent", word: "LESS" },
      { hint: "Fairness", word: "JUSTICE" },
    ],
  },
  {
    id: "p920",
    quote: "Friendship improves happiness and abates misery.",
    attribution: "Cicero",
    theme: "Friendship",
    difficulty: "hard",
    clueWords: [
      { hint: "Mutual companionship", word: "FRIENDSHIP" },
      { hint: "Makes better", word: "IMPROVES" },
      { hint: "Joyful state", word: "HAPPINESS" },
      { hint: "Reduces", word: "ABATES" },
      { hint: "Suffering", word: "MISERY" },
    ],
  },
  {
    id: "p921",
    quote: "The mind is not a vessel to be filled but a fire to be kindled.",
    attribution: "Plutarch",
    theme: "Learning",
    difficulty: "hard",
    clueWords: [
      { hint: "Thinking faculty", word: "MIND" },
      { hint: "A container", word: "VESSEL" },
      { hint: "Made full", word: "FILLED" },
      { hint: "Burning combustion", word: "FIRE" },
      { hint: "Set ablaze", word: "KINDLED" },
    ],
  },
  {
    id: "p922",
    quote: "Character is simply habit long continued.",
    attribution: "Plutarch",
    theme: "Character",
    difficulty: "hard",
    clueWords: [
      { hint: "Moral nature", word: "CHARACTER" },
      { hint: "Merely, plainly", word: "SIMPLY" },
      { hint: "A repeated behavior", word: "HABIT" },
      { hint: "Of great duration", word: "LONG" },
      { hint: "Persisted", word: "CONTINUED" },
    ],
  },
  {
    id: "p923",
    quote: "The measure of a person is the way they bear up under misfortune.",
    attribution: "Plutarch",
    theme: "Resilience",
    difficulty: "hard",
    clueWords: [
      { hint: "An assessment", word: "MEASURE" },
      { hint: "An individual", word: "PERSON" },
      { hint: "A method", word: "WAY" },
      { hint: "Endure, carry", word: "BEAR" },
      { hint: "Beneath", word: "UNDER" },
      { hint: "Bad luck", word: "MISFORTUNE" },
    ],
  },
  {
    id: "p924",
    quote: "Adversity has the effect of eliciting talents.",
    attribution: "Horace",
    theme: "Adversity",
    difficulty: "hard",
    clueWords: [
      { hint: "Hardship", word: "ADVERSITY" },
      { hint: "Possesses", word: "HAS" },
      { hint: "An influence", word: "EFFECT" },
      { hint: "Drawing out", word: "ELICITING" },
      { hint: "Natural abilities", word: "TALENTS" },
    ],
  },
  {
    id: "p925",
    quote: "Seize the day, put very little trust in tomorrow.",
    attribution: "Horace",
    theme: "Mindfulness",
    difficulty: "hard",
    clueWords: [
      { hint: "Grab firmly", word: "SEIZE" },
      { hint: "A 24-hour period", word: "DAY" },
      { hint: "Place into", word: "PUT" },
      { hint: "A small amount", word: "LITTLE" },
      { hint: "Reliance", word: "TRUST" },
      { hint: "The day after today", word: "TOMORROW" },
    ],
  },
  {
    id: "p926",
    quote: "The pen is the language of the soul.",
    attribution: "Miguel de Cervantes",
    theme: "Communication",
    difficulty: "hard",
    clueWords: [
      { hint: "Writing tool", word: "PEN" },
      { hint: "System of communication", word: "LANGUAGE" },
      { hint: "Inner essence", word: "SOUL" },
    ],
  },
  {
    id: "p927",
    quote: "Learning never exhausts the mind.",
    attribution: "Leonardo da Vinci",
    theme: "Learning",
    difficulty: "hard",
    clueWords: [
      { hint: "Acquiring knowledge", word: "LEARNING" },
      { hint: "At no time", word: "NEVER" },
      { hint: "Wears out", word: "EXHAUSTS" },
      { hint: "Thinking faculty", word: "MIND" },
    ],
  },
  {
    id: "p928",
    quote: "Art is never finished, only abandoned.",
    attribution: "Leonardo da Vinci",
    theme: "Creativity",
    difficulty: "hard",
    clueWords: [
      { hint: "Creative work", word: "ART" },
      { hint: "At no time", word: "NEVER" },
      { hint: "Completed", word: "FINISHED" },
      { hint: "Solely", word: "ONLY" },
      { hint: "Left behind", word: "ABANDONED" },
    ],
  },
  {
    id: "p929",
    quote: "He who thinks little, errs much.",
    attribution: "Leonardo da Vinci",
    theme: "Wisdom",
    difficulty: "hard",
    clueWords: [
      { hint: "Uses the mind", word: "THINKS" },
      { hint: "A small amount", word: "LITTLE" },
      { hint: "Makes mistakes", word: "ERRS" },
      { hint: "A great deal", word: "MUCH" },
    ],
  },
  {
    id: "p930",
    quote: "The noblest pleasure is the joy of understanding.",
    attribution: "Leonardo da Vinci",
    theme: "Joy",
    difficulty: "hard",
    clueWords: [
      { hint: "Most virtuous", word: "NOBLEST" },
      { hint: "Enjoyment", word: "PLEASURE" },
      { hint: "Happiness", word: "JOY" },
      { hint: "Comprehending", word: "UNDERSTANDING" },
    ],
  },
  {
    id: "p931",
    quote: "The greater danger is not aiming too high but aiming too low.",
    attribution: "Michelangelo",
    theme: "Ambition",
    difficulty: "hard",
    clueWords: [
      { hint: "Larger, more", word: "GREATER" },
      { hint: "Risk, peril", word: "DANGER" },
      { hint: "Targeting", word: "AIMING" },
      { hint: "Excessively", word: "TOO" },
      { hint: "Elevated", word: "HIGH" },
      { hint: "Not high", word: "LOW" },
    ],
  },
  {
    id: "p932",
    quote: "I am still learning.",
    attribution: "Michelangelo",
    theme: "Humility",
    difficulty: "hard",
    clueWords: [
      { hint: "Yet, even now", word: "STILL" },
      { hint: "Acquiring knowledge", word: "LEARNING" },
    ],
  },
  {
    id: "p933",
    quote: "Walking is the best medicine.",
    attribution: "Hippocrates",
    theme: "Health",
    difficulty: "hard",
    clueWords: [
      { hint: "Moving on foot", word: "WALKING" },
      { hint: "Top quality", word: "BEST" },
      { hint: "A remedy", word: "MEDICINE" },
    ],
  },
  {
    id: "p934",
    quote: "Healing is a matter of time, but sometimes also of opportunity.",
    attribution: "Hippocrates",
    theme: "Healing",
    difficulty: "hard",
    clueWords: [
      { hint: "Recovering", word: "HEALING" },
      { hint: "An issue", word: "MATTER" },
      { hint: "Hours and days", word: "TIME" },
      { hint: "On occasion", word: "SOMETIMES" },
      { hint: "A favorable chance", word: "OPPORTUNITY" },
    ],
  },
  {
    id: "p935",
    quote: "Be kind, for everyone you meet is fighting a hard battle.",
    attribution: "Plato",
    theme: "Compassion",
    difficulty: "hard",
    clueWords: [
      { hint: "Considerate", word: "KIND" },
      { hint: "Each person", word: "EVERYONE" },
      { hint: "Encounter", word: "MEET" },
      { hint: "Combating", word: "FIGHTING" },
      { hint: "Difficult", word: "HARD" },
      { hint: "A struggle", word: "BATTLE" },
    ],
  },
  {
    id: "p936",
    quote: "Wise people speak because they have something to say.",
    attribution: "Plato",
    theme: "Wisdom",
    difficulty: "hard",
    clueWords: [
      { hint: "Sage, learned", word: "WISE" },
      { hint: "Human beings", word: "PEOPLE" },
      { hint: "Utter aloud", word: "SPEAK" },
      { hint: "An item", word: "SOMETHING" },
      { hint: "Express verbally", word: "SAY" },
    ],
  },
  {
    id: "p937",
    quote: "Knowledge becomes evil if the aim be not virtuous.",
    attribution: "Plato",
    theme: "Ethics",
    difficulty: "hard",
    clueWords: [
      { hint: "Information mastered", word: "KNOWLEDGE" },
      { hint: "Turns into", word: "BECOMES" },
      { hint: "Wickedness", word: "EVIL" },
      { hint: "An intention", word: "AIM" },
      { hint: "Morally good", word: "VIRTUOUS" },
    ],
  },
  {
    id: "p938",
    quote: "Better than a thousand days of diligent study is one day with a great teacher.",
    attribution: "Japanese Proverb",
    theme: "Teaching",
    difficulty: "hard",
    clueWords: [
      { hint: "Preferable", word: "BETTER" },
      { hint: "Ten hundred", word: "THOUSAND" },
      { hint: "24-hour periods", word: "DAYS" },
      { hint: "Hardworking", word: "DILIGENT" },
      { hint: "Outstanding", word: "GREAT" },
      { hint: "An instructor", word: "TEACHER" },
    ],
  },
  {
    id: "p939",
    quote: "A wise person learns more from enemies than a fool from friends.",
    attribution: "Baltasar Gracian",
    theme: "Wisdom",
    difficulty: "hard",
    clueWords: [
      { hint: "Sage, learned", word: "WISE" },
      { hint: "An individual", word: "PERSON" },
      { hint: "Acquires knowledge", word: "LEARNS" },
      { hint: "Adversaries", word: "ENEMIES" },
      { hint: "A foolish person", word: "FOOL" },
      { hint: "Companions", word: "FRIENDS" },
    ],
  },
  {
    id: "p940",
    quote: "Beauty surrounds us, but we must walk in order to see it.",
    attribution: "Native American Proverb",
    theme: "Wonder",
    difficulty: "hard",
    clueWords: [
      { hint: "Loveliness", word: "BEAUTY" },
      { hint: "Encircles", word: "SURROUNDS" },
      { hint: "Move on foot", word: "WALK" },
      { hint: "An arrangement", word: "ORDER" },
      { hint: "Perceive with eyes", word: "SEE" },
    ],
  },
  {
    id: "p941",
    quote: "Cherish youth, but trust old age.",
    attribution: "Persian Proverb",
    theme: "Wisdom",
    difficulty: "hard",
    clueWords: [
      { hint: "Treasure deeply", word: "CHERISH" },
      { hint: "The state of being young", word: "YOUTH" },
      { hint: "Have faith in", word: "TRUST" },
      { hint: "Aged", word: "OLD" },
      { hint: "How long one has lived", word: "AGE" },
    ],
  },
  {
    id: "p942",
    quote: "Patience is a tree whose root is bitter but its fruit is very sweet.",
    attribution: "Persian Proverb",
    theme: "Patience",
    difficulty: "hard",
    clueWords: [
      { hint: "Calm endurance", word: "PATIENCE" },
      { hint: "Tall woody plant", word: "TREE" },
      { hint: "Plant part in soil", word: "ROOT" },
      { hint: "Sharp, harsh", word: "BITTER" },
      { hint: "Plant reward", word: "FRUIT" },
      { hint: "Sugary, pleasant", word: "SWEET" },
    ],
  },
  {
    id: "p943",
    quote: "Doubt grows with knowledge.",
    attribution: "Johann Wolfgang von Goethe",
    theme: "Wisdom",
    difficulty: "hard",
    clueWords: [
      { hint: "Lack of certainty", word: "DOUBT" },
      { hint: "Increases", word: "GROWS" },
      { hint: "Information mastered", word: "KNOWLEDGE" },
    ],
  },
  {
    id: "p944",
    quote: "We are shaped and fashioned by what we love.",
    attribution: "Johann Wolfgang von Goethe",
    theme: "Love",
    difficulty: "hard",
    clueWords: [
      { hint: "Formed", word: "SHAPED" },
      { hint: "Crafted", word: "FASHIONED" },
      { hint: "Cherish deeply", word: "LOVE" },
      { hint: "First-person plural", word: "WE" },
    ],
  },
  {
    id: "p945",
    quote: "Daring ideas are like chessmen moved forward; they may be beaten, but they may start a winning game.",
    attribution: "Johann Wolfgang von Goethe",
    theme: "Courage",
    difficulty: "hard",
    clueWords: [
      { hint: "Bold", word: "DARING" },
      { hint: "Thoughts, concepts", word: "IDEAS" },
      { hint: "Board game pieces", word: "CHESSMEN" },
      { hint: "Shifted", word: "MOVED" },
      { hint: "Toward the front", word: "FORWARD" },
      { hint: "Victorious", word: "WINNING" },
    ],
  },
  {
    id: "p946",
    quote: "You have your way. I have my way. The right way does not exist.",
    attribution: "Friedrich Nietzsche",
    theme: "Individuality",
    difficulty: "hard",
    clueWords: [
      { hint: "Possess", word: "HAVE" },
      { hint: "A method", word: "WAY" },
      { hint: "Correct", word: "RIGHT" },
      { hint: "Be present", word: "EXIST" },
    ],
  },
  {
    id: "p947",
    quote: "There is always some madness in love, and some reason in madness.",
    attribution: "Friedrich Nietzsche",
    theme: "Love",
    difficulty: "hard",
    clueWords: [
      { hint: "All the time", word: "ALWAYS" },
      { hint: "A few", word: "SOME" },
      { hint: "Insanity", word: "MADNESS" },
      { hint: "Deep affection", word: "LOVE" },
      { hint: "Logic, sense", word: "REASON" },
    ],
  },
  {
    id: "p948",
    quote: "One must have chaos in oneself to give birth to a dancing star.",
    attribution: "Friedrich Nietzsche",
    theme: "Creativity",
    difficulty: "hard",
    clueWords: [
      { hint: "A single unit", word: "ONE" },
      { hint: "Have to", word: "MUST" },
      { hint: "Disorder", word: "CHAOS" },
      { hint: "One's own person", word: "ONESELF" },
      { hint: "Provide, bestow", word: "GIVE" },
      { hint: "Celestial body", word: "STAR" },
    ],
  },
  {
    id: "p949",
    quote: "To live defeated is to die every day.",
    attribution: "Napoleon Bonaparte",
    theme: "Resilience",
    difficulty: "hard",
    clueWords: [
      { hint: "Be alive", word: "LIVE" },
      { hint: "Beaten, conquered", word: "DEFEATED" },
      { hint: "Cease to live", word: "DIE" },
      { hint: "Each one", word: "EVERY" },
      { hint: "A 24-hour period", word: "DAY" },
    ],
  },
  {
    id: "p950",
    quote: "Victory belongs to the most persevering.",
    attribution: "Napoleon Bonaparte",
    theme: "Persistence",
    difficulty: "hard",
    clueWords: [
      { hint: "A triumph", word: "VICTORY" },
      { hint: "Is owned by", word: "BELONGS" },
      { hint: "Greatest extent", word: "MOST" },
      { hint: "Persisting through", word: "PERSEVERING" },
    ],
  },
  {
    id: "p951",
    quote: "Glory is fleeting, but obscurity is forever.",
    attribution: "Napoleon Bonaparte",
    theme: "Humility",
    difficulty: "hard",
    clueWords: [
      { hint: "Honor, fame", word: "GLORY" },
      { hint: "Passing quickly", word: "FLEETING" },
      { hint: "Being unknown", word: "OBSCURITY" },
      { hint: "Eternally", word: "FOREVER" },
    ],
  },
  {
    id: "p952",
    quote: "Impossible is a word found only in the dictionary of fools.",
    attribution: "Napoleon Bonaparte",
    theme: "Possibility",
    difficulty: "hard",
    clueWords: [
      { hint: "Cannot be done", word: "IMPOSSIBLE" },
      { hint: "A spoken unit", word: "WORD" },
      { hint: "Discovered", word: "FOUND" },
      { hint: "Word reference book", word: "DICTIONARY" },
      { hint: "Foolish people", word: "FOOLS" },
    ],
  },
  {
    id: "p953",
    quote: "Talent hits a target no one else can hit. Genius hits a target no one else can see.",
    attribution: "Arthur Schopenhauer",
    theme: "Genius",
    difficulty: "hard",
    clueWords: [
      { hint: "Natural ability", word: "TALENT" },
      { hint: "Strikes", word: "HITS" },
      { hint: "An aim", word: "TARGET" },
      { hint: "Are able to", word: "CAN" },
      { hint: "Exceptional ability", word: "GENIUS" },
      { hint: "Perceive with eyes", word: "SEE" },
    ],
  },
  {
    id: "p954",
    quote: "The two enemies of human happiness are pain and boredom.",
    attribution: "Arthur Schopenhauer",
    theme: "Happiness",
    difficulty: "hard",
    clueWords: [
      { hint: "A pair", word: "TWO" },
      { hint: "Adversaries", word: "ENEMIES" },
      { hint: "Of people", word: "HUMAN" },
      { hint: "Joyful state", word: "HAPPINESS" },
      { hint: "Hurt", word: "PAIN" },
      { hint: "Lack of interest", word: "BOREDOM" },
    ],
  },
  {
    id: "p955",
    quote: "It is difficult to find happiness within oneself, but impossible to find it anywhere else.",
    attribution: "Arthur Schopenhauer",
    theme: "Inner Peace",
    difficulty: "hard",
    clueWords: [
      { hint: "Hard, challenging", word: "DIFFICULT" },
      { hint: "Discover", word: "FIND" },
      { hint: "Joyful state", word: "HAPPINESS" },
      { hint: "Inside", word: "WITHIN" },
      { hint: "Cannot be done", word: "IMPOSSIBLE" },
      { hint: "Some place", word: "ANYWHERE" },
    ],
  },
  {
    id: "p956",
    quote: "Compassion is the basis of morality.",
    attribution: "Arthur Schopenhauer",
    theme: "Ethics",
    difficulty: "hard",
    clueWords: [
      { hint: "Sympathetic concern", word: "COMPASSION" },
      { hint: "A foundation", word: "BASIS" },
      { hint: "Ethical conduct", word: "MORALITY" },
    ],
  },
  {
    id: "p957",
    quote: "A person can do what they want, but not want what they want.",
    attribution: "Arthur Schopenhauer",
    theme: "Free Will",
    difficulty: "hard",
    clueWords: [
      { hint: "An individual", word: "PERSON" },
      { hint: "Are able to", word: "CAN" },
      { hint: "Perform", word: "DO" },
      { hint: "Desire", word: "WANT" },
    ],
  },
  {
    id: "p958",
    quote: "He who walks in another's tracks leaves no footprints.",
    attribution: "Anonymous",
    theme: "Originality",
    difficulty: "hard",
    clueWords: [
      { hint: "Moves on foot", word: "WALKS" },
      { hint: "A different person", word: "ANOTHER" },
      { hint: "Marks left by movement", word: "TRACKS" },
      { hint: "Departs from", word: "LEAVES" },
      { hint: "Foot impressions", word: "FOOTPRINTS" },
    ],
  },
  {
    id: "p959",
    quote: "Hope smiles from the threshold of the year to come.",
    attribution: "Alfred Lord Tennyson",
    theme: "Hope",
    difficulty: "hard",
    clueWords: [
      { hint: "Optimistic feeling", word: "HOPE" },
      { hint: "Shows a happy face", word: "SMILES" },
      { hint: "A doorway entrance", word: "THRESHOLD" },
      { hint: "Twelve months", word: "YEAR" },
      { hint: "Arrive", word: "COME" },
    ],
  },
  {
    id: "p960",
    quote: "Better to have loved and lost than never to have loved at all.",
    attribution: "Alfred Lord Tennyson",
    theme: "Love",
    difficulty: "hard",
    clueWords: [
      { hint: "Preferable", word: "BETTER" },
      { hint: "Cherished", word: "LOVED" },
      { hint: "Forfeited", word: "LOST" },
      { hint: "At no time", word: "NEVER" },
      { hint: "Each, every", word: "ALL" },
    ],
  },
  {
    id: "p961",
    quote: "To strive, to seek, to find, and not to yield.",
    attribution: "Alfred Lord Tennyson",
    theme: "Persistence",
    difficulty: "hard",
    clueWords: [
      { hint: "Make great effort", word: "STRIVE" },
      { hint: "Search for", word: "SEEK" },
      { hint: "Discover", word: "FIND" },
      { hint: "Surrender", word: "YIELD" },
    ],
  },
  {
    id: "p962",
    quote: "Knowledge comes, but wisdom lingers.",
    attribution: "Alfred Lord Tennyson",
    theme: "Wisdom",
    difficulty: "hard",
    clueWords: [
      { hint: "Information mastered", word: "KNOWLEDGE" },
      { hint: "Arrives", word: "COMES" },
      { hint: "Deep insight", word: "WISDOM" },
      { hint: "Stays, remains", word: "LINGERS" },
    ],
  },

  // -------------------- EXPERT (38) --------------------
  {
    id: "p963",
    quote: "It was the best of times, it was the worst of times.",
    attribution: "Charles Dickens",
    theme: "Contradiction",
    difficulty: "expert",
    clueWords: [
      { hint: "Top quality", word: "BEST" },
      { hint: "Periods, occasions", word: "TIMES" },
      { hint: "Poorest quality", word: "WORST" },
    ],
  },
  {
    id: "p964",
    quote: "No one is useless in this world who lightens the burdens of others.",
    attribution: "Charles Dickens",
    theme: "Service",
    difficulty: "expert",
    clueWords: [
      { hint: "Of no use", word: "USELESS" },
      { hint: "The earth", word: "WORLD" },
      { hint: "Eases, brightens", word: "LIGHTENS" },
      { hint: "Heavy loads", word: "BURDENS" },
      { hint: "Other people", word: "OTHERS" },
    ],
  },
  {
    id: "p965",
    quote: "It is a far better thing that I do than I have ever done.",
    attribution: "Charles Dickens",
    theme: "Sacrifice",
    difficulty: "expert",
    clueWords: [
      { hint: "By a great distance", word: "FAR" },
      { hint: "More desirable", word: "BETTER" },
      { hint: "An item or matter", word: "THING" },
      { hint: "Perform", word: "DO" },
      { hint: "At any time", word: "EVER" },
      { hint: "Completed", word: "DONE" },
    ],
  },
  {
    id: "p966",
    quote: "Happy families are all alike; every unhappy family is unhappy in its own way.",
    attribution: "Leo Tolstoy",
    theme: "Family",
    difficulty: "expert",
    clueWords: [
      { hint: "Joyful", word: "HAPPY" },
      { hint: "Related groups", word: "FAMILIES" },
      { hint: "Similarly", word: "ALIKE" },
      { hint: "Each one", word: "EVERY" },
      { hint: "Not joyful", word: "UNHAPPY" },
      { hint: "A method", word: "WAY" },
    ],
  },
  {
    id: "p967",
    quote: "I have always been delighted at the prospect of a new day, a fresh try, one more start.",
    attribution: "J.B. Priestley",
    theme: "Renewal",
    difficulty: "expert",
    clueWords: [
      { hint: "All the time", word: "ALWAYS" },
      { hint: "Greatly pleased", word: "DELIGHTED" },
      { hint: "An anticipation", word: "PROSPECT" },
      { hint: "Recently created", word: "NEW" },
      { hint: "A 24-hour period", word: "DAY" },
      { hint: "Newly made", word: "FRESH" },
    ],
  },
  {
    id: "p968",
    quote: "We sometimes encounter strangers who begin to interest us at first sight.",
    attribution: "Fyodor Dostoevsky",
    theme: "Friendship",
    difficulty: "expert",
    clueWords: [
      { hint: "On occasion", word: "SOMETIMES" },
      { hint: "Meet by chance", word: "ENCOUNTER" },
      { hint: "Unknown people", word: "STRANGERS" },
      { hint: "Start", word: "BEGIN" },
      { hint: "Engage attention", word: "INTEREST" },
      { hint: "Vision, view", word: "SIGHT" },
    ],
  },
  {
    id: "p969",
    quote: "Better to be slapped with the truth than kissed with a lie.",
    attribution: "Russian Proverb",
    theme: "Honesty",
    difficulty: "expert",
    clueWords: [
      { hint: "Preferable", word: "BETTER" },
      { hint: "Struck with palm", word: "SLAPPED" },
      { hint: "Honest reality", word: "TRUTH" },
      { hint: "Touched with lips", word: "KISSED" },
      { hint: "A falsehood", word: "LIE" },
    ],
  },
  {
    id: "p970",
    quote: "The fool wonders, the wise person asks.",
    attribution: "Benjamin Disraeli",
    theme: "Curiosity",
    difficulty: "expert",
    clueWords: [
      { hint: "A foolish individual", word: "FOOL" },
      { hint: "Marvels, ponders", word: "WONDERS" },
      { hint: "Sage, learned", word: "WISE" },
      { hint: "An individual", word: "PERSON" },
      { hint: "Inquires", word: "ASKS" },
    ],
  },
  {
    id: "p971",
    quote: "Never apologize for showing feeling. When you do so, you apologize for the truth.",
    attribution: "Benjamin Disraeli",
    theme: "Authenticity",
    difficulty: "expert",
    clueWords: [
      { hint: "At no time", word: "NEVER" },
      { hint: "Say sorry", word: "APOLOGIZE" },
      { hint: "Displaying", word: "SHOWING" },
      { hint: "Emotion", word: "FEELING" },
      { hint: "Honest reality", word: "TRUTH" },
    ],
  },
  {
    id: "p972",
    quote: "Read no history: nothing but biography, for that is life without theory.",
    attribution: "Benjamin Disraeli",
    theme: "Learning",
    difficulty: "expert",
    clueWords: [
      { hint: "Go through written text", word: "READ" },
      { hint: "Past events recorded", word: "HISTORY" },
      { hint: "Not anything", word: "NOTHING" },
      { hint: "A life story", word: "BIOGRAPHY" },
      { hint: "Existence", word: "LIFE" },
      { hint: "A speculative idea", word: "THEORY" },
    ],
  },
  {
    id: "p973",
    quote: "He who has love in his heart has spurs in his sides.",
    attribution: "Benjamin Disraeli",
    theme: "Passion",
    difficulty: "expert",
    clueWords: [
      { hint: "Deep affection", word: "LOVE" },
      { hint: "Pumping organ", word: "HEART" },
      { hint: "Pointed riding tools", word: "SPURS" },
      { hint: "Body edges", word: "SIDES" },
      { hint: "Possesses", word: "HAS" },
    ],
  },
  {
    id: "p974",
    quote: "Never complain and never explain.",
    attribution: "Benjamin Disraeli",
    theme: "Stoicism",
    difficulty: "expert",
    clueWords: [
      { hint: "At no time", word: "NEVER" },
      { hint: "Voice dissatisfaction", word: "COMPLAIN" },
      { hint: "Clarify", word: "EXPLAIN" },
    ],
  },
  {
    id: "p975",
    quote: "Action may not always bring happiness, but there is no happiness without action.",
    attribution: "Benjamin Disraeli",
    theme: "Action",
    difficulty: "expert",
    clueWords: [
      { hint: "A deed", word: "ACTION" },
      { hint: "Possibly", word: "MAY" },
      { hint: "All the time", word: "ALWAYS" },
      { hint: "Convey, deliver", word: "BRING" },
      { hint: "Joyful state", word: "HAPPINESS" },
      { hint: "Lacking", word: "WITHOUT" },
    ],
  },
  {
    id: "p976",
    quote: "Without forgetting it is quite impossible to live at all.",
    attribution: "Friedrich Nietzsche",
    theme: "Acceptance",
    difficulty: "expert",
    clueWords: [
      { hint: "Lacking", word: "WITHOUT" },
      { hint: "Losing from memory", word: "FORGETTING" },
      { hint: "Entirely", word: "QUITE" },
      { hint: "Cannot be done", word: "IMPOSSIBLE" },
      { hint: "Be alive", word: "LIVE" },
    ],
  },
  {
    id: "p977",
    quote: "The advantage of a bad memory is enjoying the same good things for the first time again.",
    attribution: "Friedrich Nietzsche",
    theme: "Humor",
    difficulty: "expert",
    clueWords: [
      { hint: "A benefit", word: "ADVANTAGE" },
      { hint: "Of poor quality", word: "BAD" },
      { hint: "Recollection", word: "MEMORY" },
      { hint: "Taking pleasure in", word: "ENJOYING" },
      { hint: "Identical", word: "SAME" },
      { hint: "An occasion", word: "TIME" },
    ],
  },
  {
    id: "p978",
    quote: "We have art in order not to die of the truth.",
    attribution: "Friedrich Nietzsche",
    theme: "Art",
    difficulty: "expert",
    clueWords: [
      { hint: "Possess", word: "HAVE" },
      { hint: "Creative work", word: "ART" },
      { hint: "An arrangement", word: "ORDER" },
      { hint: "Cease to live", word: "DIE" },
      { hint: "Honest reality", word: "TRUTH" },
    ],
  },
  {
    id: "p979",
    quote: "Become who you are.",
    attribution: "Friedrich Nietzsche",
    theme: "Authenticity",
    difficulty: "expert",
    clueWords: [
      { hint: "Turn into", word: "BECOME" },
    ],
  },
  {
    id: "p980",
    quote: "The future affects the present just as much as the past.",
    attribution: "Friedrich Nietzsche",
    theme: "Time",
    difficulty: "expert",
    clueWords: [
      { hint: "Time yet to come", word: "FUTURE" },
      { hint: "Influences", word: "AFFECTS" },
      { hint: "Current time", word: "PRESENT" },
      { hint: "A great deal", word: "MUCH" },
      { hint: "Earlier time", word: "PAST" },
    ],
  },
  {
    id: "p981",
    quote: "It is never too late to be wise.",
    attribution: "Daniel Defoe",
    theme: "Learning",
    difficulty: "expert",
    clueWords: [
      { hint: "At no time", word: "NEVER" },
      { hint: "Excessively", word: "TOO" },
      { hint: "After the proper time", word: "LATE" },
      { hint: "Sage, learned", word: "WISE" },
    ],
  },
  {
    id: "p982",
    quote: "Today is the tomorrow we worried about yesterday.",
    attribution: "Anonymous",
    theme: "Mindfulness",
    difficulty: "expert",
    clueWords: [
      { hint: "The current day", word: "TODAY" },
      { hint: "The day after today", word: "TOMORROW" },
      { hint: "Fretted", word: "WORRIED" },
      { hint: "The day before", word: "YESTERDAY" },
    ],
  },
  {
    id: "p983",
    quote: "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    attribution: "Nelson Mandela",
    theme: "Resilience",
    difficulty: "expert",
    clueWords: [
      { hint: "Largest, finest", word: "GREATEST" },
      { hint: "Honor, splendor", word: "GLORY" },
      { hint: "Being alive", word: "LIVING" },
      { hint: "At no time", word: "NEVER" },
      { hint: "Dropping down", word: "FALLING" },
      { hint: "Getting up", word: "RISING" },
    ],
  },
  {
    id: "p984",
    quote: "People will never forget how you made them feel.",
    attribution: "Maya Angelou",
    theme: "Kindness",
    difficulty: "expert",
    clueWords: [
      { hint: "Human beings", word: "PEOPLE" },
      { hint: "At no time", word: "NEVER" },
      { hint: "Lose memory of", word: "FORGET" },
      { hint: "Caused to be", word: "MADE" },
      { hint: "Sense", word: "FEEL" },
    ],
  },
  {
    id: "p985",
    quote: "I am not afraid of storms, for I am learning how to sail my ship.",
    attribution: "Louisa May Alcott",
    theme: "Courage",
    difficulty: "expert",
    clueWords: [
      { hint: "Frightened", word: "AFRAID" },
      { hint: "Severe weather", word: "STORMS" },
      { hint: "Acquiring knowledge", word: "LEARNING" },
      { hint: "Travel by boat", word: "SAIL" },
      { hint: "Sea vessel", word: "SHIP" },
    ],
  },
  {
    id: "p986",
    quote: "Far away there in the sunshine are my highest aspirations.",
    attribution: "Louisa May Alcott",
    theme: "Aspiration",
    difficulty: "expert",
    clueWords: [
      { hint: "To a great distance", word: "FAR" },
      { hint: "Not present", word: "AWAY" },
      { hint: "Light from the sun", word: "SUNSHINE" },
      { hint: "Greatest elevation", word: "HIGHEST" },
      { hint: "Strong hopes", word: "ASPIRATIONS" },
    ],
  },
  {
    id: "p987",
    quote: "Have regular hours for work and play; make each day both useful and pleasant.",
    attribution: "Louisa May Alcott",
    theme: "Balance",
    difficulty: "expert",
    clueWords: [
      { hint: "Possess", word: "HAVE" },
      { hint: "Recurring at intervals", word: "REGULAR" },
      { hint: "Time units of sixty minutes", word: "HOURS" },
      { hint: "Labor", word: "WORK" },
      { hint: "Recreation", word: "PLAY" },
      { hint: "Beneficial", word: "USEFUL" },
    ],
  },
  {
    id: "p988",
    quote: "Without going outside, you may know the whole world.",
    attribution: "Lao Tzu",
    theme: "Inner Knowledge",
    difficulty: "expert",
    clueWords: [
      { hint: "Lacking", word: "WITHOUT" },
      { hint: "Traveling", word: "GOING" },
      { hint: "Beyond", word: "OUTSIDE" },
      { hint: "Be aware of", word: "KNOW" },
      { hint: "Entire", word: "WHOLE" },
      { hint: "The earth", word: "WORLD" },
    ],
  },
  {
    id: "p989",
    quote: "Nature does not hurry, yet everything is accomplished.",
    attribution: "Lao Tzu",
    theme: "Patience",
    difficulty: "expert",
    clueWords: [
      { hint: "The natural world", word: "NATURE" },
      { hint: "Rush, hasten", word: "HURRY" },
      { hint: "All things", word: "EVERYTHING" },
      { hint: "Completed", word: "ACCOMPLISHED" },
    ],
  },
  {
    id: "p990",
    quote: "Silence is a source of great strength.",
    attribution: "Lao Tzu",
    theme: "Mindfulness",
    difficulty: "expert",
    clueWords: [
      { hint: "Absence of sound", word: "SILENCE" },
      { hint: "An origin", word: "SOURCE" },
      { hint: "Outstanding", word: "GREAT" },
      { hint: "Power, fortitude", word: "STRENGTH" },
    ],
  },
  {
    id: "p991",
    quote: "The greatest virtue is like water, which benefits all things.",
    attribution: "Lao Tzu",
    theme: "Virtue",
    difficulty: "expert",
    clueWords: [
      { hint: "Largest, finest", word: "GREATEST" },
      { hint: "Moral excellence", word: "VIRTUE" },
      { hint: "Similar to", word: "LIKE" },
      { hint: "Clear drinking liquid", word: "WATER" },
      { hint: "Helps", word: "BENEFITS" },
      { hint: "Items, matters", word: "THINGS" },
    ],
  },
  {
    id: "p992",
    quote: "Manifest plainness, embrace simplicity, reduce selfishness, have few desires.",
    attribution: "Lao Tzu",
    theme: "Simplicity",
    difficulty: "expert",
    clueWords: [
      { hint: "Display openly", word: "MANIFEST" },
      { hint: "Hold close", word: "EMBRACE" },
      { hint: "Plainness", word: "SIMPLICITY" },
      { hint: "Lessen", word: "REDUCE" },
      { hint: "Strong wants", word: "DESIRES" },
      { hint: "Small number", word: "FEW" },
    ],
  },
  {
    id: "p993",
    quote: "Music gives a soul to the universe, wings to the mind, flight to the imagination.",
    attribution: "Plato",
    theme: "Wonder",
    difficulty: "expert",
    clueWords: [
      { hint: "Organized sound", word: "MUSIC" },
      { hint: "Inner essence", word: "SOUL" },
      { hint: "All of existence", word: "UNIVERSE" },
      { hint: "Bird flying parts", word: "WINGS" },
      { hint: "Thinking faculty", word: "MIND" },
      { hint: "Mental creativity", word: "IMAGINATION" },
    ],
  },
  {
    id: "p994",
    quote: "The price good people pay for indifference is to be ruled by evil people.",
    attribution: "Plato",
    theme: "Civic Duty",
    difficulty: "expert",
    clueWords: [
      { hint: "Cost", word: "PRICE" },
      { hint: "Worthy", word: "GOOD" },
      { hint: "Human beings", word: "PEOPLE" },
      { hint: "Lack of care", word: "INDIFFERENCE" },
      { hint: "Governed", word: "RULED" },
      { hint: "Wickedness", word: "EVIL" },
    ],
  },
  {
    id: "p995",
    quote: "There are three classes: lovers of wisdom, lovers of honor, and lovers of gain.",
    attribution: "Plato",
    theme: "Values",
    difficulty: "expert",
    clueWords: [
      { hint: "Number after two", word: "THREE" },
      { hint: "Categories", word: "CLASSES" },
      { hint: "Those who cherish", word: "LOVERS" },
      { hint: "Deep insight", word: "WISDOM" },
      { hint: "Respect, glory", word: "HONOR" },
      { hint: "Profit, increase", word: "GAIN" },
    ],
  },
  {
    id: "p996",
    quote: "Courage is knowing what not to fear.",
    attribution: "Plato",
    theme: "Courage",
    difficulty: "expert",
    clueWords: [
      { hint: "Bravery", word: "COURAGE" },
      { hint: "Being aware of", word: "KNOWING" },
      { hint: "Be afraid of", word: "FEAR" },
    ],
  },
  {
    id: "p997",
    quote: "At the touch of love everyone becomes a poet.",
    attribution: "Plato",
    theme: "Love",
    difficulty: "expert",
    clueWords: [
      { hint: "Make contact with", word: "TOUCH" },
      { hint: "Deep affection", word: "LOVE" },
      { hint: "Each person", word: "EVERYONE" },
      { hint: "Turns into", word: "BECOMES" },
      { hint: "A verse writer", word: "POET" },
    ],
  },
  {
    id: "p998",
    quote: "Ignorance is the root and stem of all evil.",
    attribution: "Plato",
    theme: "Wisdom",
    difficulty: "expert",
    clueWords: [
      { hint: "Lack of knowledge", word: "IGNORANCE" },
      { hint: "Plant part in soil", word: "ROOT" },
      { hint: "Plant body part", word: "STEM" },
      { hint: "Each, every", word: "ALL" },
      { hint: "Wickedness", word: "EVIL" },
    ],
  },
  {
    id: "p999",
    quote: "When the mind is at peace, the world too is at peace.",
    attribution: "Zen Saying",
    theme: "Inner Peace",
    difficulty: "expert",
    clueWords: [
      { hint: "Thinking faculty", word: "MIND" },
      { hint: "Tranquility", word: "PEACE" },
      { hint: "The earth", word: "WORLD" },
      { hint: "Also", word: "TOO" },
    ],
  },
  {
    id: "p1000",
    quote: "End the day with gratitude and begin it with hope.",
    attribution: "Anonymous",
    theme: "Gratitude",
    difficulty: "expert",
    clueWords: [
      { hint: "Conclude", word: "END" },
      { hint: "A 24-hour period", word: "DAY" },
      { hint: "Thankfulness", word: "GRATITUDE" },
      { hint: "Start", word: "BEGIN" },
      { hint: "Optimistic feeling", word: "HOPE" },
    ],
  },
];
